import type { Locale } from '../../shared/locale';
import { formatPublicStatus } from '../../shared/public-labels';

export const backtestDetailsCopy = {
  en: {
    sweep: {
      kicker: 'Parameter sweep',
      title: 'Bounded parameter sweep',
      subtitle:
        'Test a small typed grid for the selected strategy. Rankings are research evidence and still require OOS, after-cost, risk, and manual review.',
      candidateLabel: (label: string) => `${label} candidates`,
      rankBy: 'Rank by',
      rankTotalReturn: 'Total return',
      rankSharpe: 'Sharpe',
      rankMaxDrawdown: 'Max drawdown',
      gridHint: (count: number) => `${count} combinations before validation`,
      run: 'Run parameter sweep',
      running: 'Running sweep',
      resultsKicker: 'Sweep review',
      resultsTitle: 'Sweep rankings',
      tested: (count: number) => `${count} tested`,
      rank: 'Rank',
      result: 'Result',
      resultId: (id: number) => `Result #${id}`,
      params: 'Params',
      score: 'Score',
      sharpe: 'Sharpe',
      cost: 'Cost',
    },
    compare: {
      kicker: 'Strategy comparison',
      title: 'Same-dataset comparison',
      subtitle:
        'Compare explicit parameter sets for the selected strategy. Results are saved only after every run is verified against the same frozen data snapshot.',
      parameterSets: 'Comparison parameter sets',
      setsHint: (count: number, example: string) =>
        `${count} parameter sets parsed; use one set per line${
          example ? `, for example ${example}` : ''
        }.`,
      invalidSets:
        'Enter at least two valid parameter sets using known parameter keys.',
      run: 'Run comparison',
      running: 'Running comparison',
      resultsKicker: 'Comparison review',
      resultsTitle: 'Comparison results',
      compared: (count: number) => `${count} compared`,
      result: 'Result',
      resultId: (id: number) => `Result #${id}`,
      params: 'Params',
      totalReturn: 'Total return',
      drawdown: 'Drawdown',
      sharpe: 'Sharpe',
      cost: 'Cost',
    },
    selection: {
      kicker: 'Backtest history',
      title: 'Report selection',
      ariaLabel: 'Select backtest report',
      loading: 'Loading backtest results.',
      loadFailed: 'Failed to load backtest history.',
      empty:
        'No backtest reports have been saved yet. Run a backtest first to inspect metrics, costs, equity curve, and fills.',
      selectedLoading: 'Loading selected report.',
      selectedFailed: 'Failed to load selected backtest report.',
    },
    summary: {
      return: 'Summary return',
      sharpe: 'Summary Sharpe',
      maxDrawdown: 'Summary max drawdown',
    },
    metrics: {
      totalReturn: 'Total return',
      sharpe: 'Sharpe',
      sortino: 'Sortino',
      maxDrawdown: 'Max drawdown',
      calmar: 'Calmar',
      winRate: 'Win rate',
      durationDays: (days: number) => `${days} trading days`,
      volatility: 'Volatility',
      annualReturn: 'Annual return',
      grossTurnover: 'Gross turnover',
      fills: (count: number) => `${count} fills`,
      totalCommission: 'Total commission',
      commissionDetail: 'Brokerage and exchange fees',
      totalSlippage: 'Total slippage',
      slippageDetail: 'Execution drift from reference price',
    },
    datasetSnapshot: {
      kicker: 'Data audit',
      title: 'Dataset snapshot',
      subtitle:
        'Frozen input scope for this research result. Use it to compare runs without silently changing inputs.',
      snapshotId: 'Snapshot id',
      dataSource: 'Data source',
      dateRange: 'Date range',
      rows: 'Rows',
      rowsValue: (count: number) => `${count} rows`,
      quality: 'Quality',
      qualityValue: (status: string) =>
        status === 'ok' ? 'OK' : formatPublicStatus(status, 'en'),
      cacheStore: 'Cache store',
      cacheMetadata: 'Cache metadata',
      adjustmentMode: 'Adjustment',
      symbol: 'Symbol',
      assetClass: 'Asset class',
      frequency: 'Frequency',
      dataStatus: 'Data status',
      providerName: 'Provider',
      coverage: 'Coverage',
      unconfirmedDataNotice:
        'Dataset contains unconfirmed market data. Treat after-cost metrics as research evidence until data is refreshed or replayed from confirmed bars.',
      yes: 'Yes',
      no: 'No',
      unknown: 'Unknown',
      notAvailable: 'N/A',
    },
    strategySnapshot: {
      kicker: 'Strategy audit',
      title: 'Strategy snapshot',
      subtitle:
        'The strategy definition, normalized parameters, and validation requirements saved with this report.',
      strategy: 'Strategy',
      strategyId: 'Strategy id',
      internalStrategyId: 'Strategy audit id',
      displayName: 'Display name',
      benchmarkRole: 'Benchmark role',
      universe: 'Asset universe',
      frequencies: 'Frequencies',
      frequencyDaily: 'Daily bars',
      frequencyMinute: 'Minute bars',
      frequencyTick: 'Tick data',
      validation: 'Validation',
      runParams: 'Run params',
      parameterSchema: 'Parameter schema',
      parameter: 'Parameter',
      type: 'Type',
      defaultValue: (value: string) => `default ${value}`,
      bounds: 'Bounds',
      description: 'Description',
      validationNotes: 'Validation notes',
      oosRequired: 'OOS required',
      afterCostRequired: 'After-cost required',
      unknown: 'Unknown',
      notDeclared: 'Not declared',
      noBounds: 'No bounds',
      apiField: (name: string) => `API field: ${name}`,
      minMax: (min: string, max: string) => `${min} to ${max}`,
    },
    validationEvidence: {
      kicker: 'Research evidence',
      title: 'Validation evidence',
      subtitle:
        'After-cost and out-of-sample evidence for this run. Use it for research review, not as an execution approval.',
      afterCostTitle: 'After-cost evidence',
      oosTitle: 'Out-of-sample split',
      netReturn: 'Net return',
      grossReturn: 'Gross before costs',
      totalCost: 'Total cost',
      costDrag: 'Cost drag',
      fills: 'Fills',
      turnover: 'Turnover',
      strategy: 'Strategy',
      strategyAuditId: 'Audit id',
      benchmarkRole: 'Benchmark role',
      split: 'Split',
      status: 'Status',
      oosReturn: 'OOS return',
      excessReturn: 'Excess return',
      benchmarkReturn: 'Benchmark return',
      oosFills: 'OOS fills',
      costAssumptions: 'Cost assumptions',
      slippageAssumptions: 'Slippage assumptions',
      assumptions: 'Assumptions',
      limitations: 'Limitations',
      unknown: 'Unknown',
      fillCount: (count: number) => `${count} fills`,
      statusValue: (status?: string, passed?: boolean | null) => {
        if (status === 'benchmark_passed' || passed === true) {
          return 'Benchmark passed';
        }
        if (status === 'benchmark_failed' || passed === false) {
          return 'Benchmark failed';
        }
        if (status === 'benchmark_not_supplied') {
          return 'Benchmark not supplied';
        }
        return formatPublicStatus(status, 'en');
      },
    },
    chart: {
      kicker: 'Backtest curve',
      title: 'Equity and drawdown',
      empty: 'No equity curve is available for this backtest result.',
      points: (count: number) => `${count} points`,
      drawdown: 'Drawdown',
      markersKicker: 'Trade markers',
      markersTitle: 'Buy / sell points',
      markersCount: (count: number) => `${count} markers`,
      markerQuantity: 'Qty',
    },
    fills: {
      kicker: 'Execution ledger',
      title: 'Fills',
      rows: (count: number) => `${count} rows`,
      empty:
        'No fill details are available for this saved result. New runs expose per-fill cost records when the backtest engine returns them.',
      time: 'Time',
      symbol: 'Symbol',
      side: 'Side',
      fillPrice: 'Fill price',
      quantity: 'Quantity',
      commission: 'Commission',
      slippage: 'Slippage',
    },
  },
  zh: {
    sweep: {
      kicker: '参数扫描',
      title: '有界参数扫描',
      subtitle:
        '对当前策略运行小规模参数网格。排名只作为研究证据，仍需样本外、扣除成本后、风控和人工复核。',
      candidateLabel: (label: string) => `${label}候选值`,
      rankBy: '排序指标',
      rankTotalReturn: '总收益',
      rankSharpe: 'Sharpe',
      rankMaxDrawdown: '最大回撤',
      gridHint: (count: number) => `校验前 ${count} 组组合`,
      run: '运行参数扫描',
      running: '正在扫描',
      resultsKicker: '扫描复核',
      resultsTitle: '扫描排名',
      tested: (count: number) => `${count} 组已测试`,
      rank: '排名',
      result: '结果',
      resultId: (id: number) => `结果 #${id}`,
      params: '参数',
      score: '分数',
      sharpe: 'Sharpe',
      cost: '成本',
    },
    compare: {
      kicker: '策略对比',
      title: '同数据快照对比',
      subtitle:
        '对比当前策略的多组明确参数；仅当所有运行使用同一份冻结数据快照并通过一致性校验时，结果才会保存。',
      parameterSets: '对比参数集',
      setsHint: (count: number, example: string) =>
        `已解析 ${count} 组参数；每行一组${
          example ? `，例如 ${example}` : ''
        }。`,
      invalidSets: '请至少输入两组有效参数，并使用已知参数名或 API 键。',
      run: '运行对比',
      running: '正在对比',
      resultsKicker: '对比复核',
      resultsTitle: '对比结果',
      compared: (count: number) => `${count} 组已对比`,
      result: '结果',
      resultId: (id: number) => `结果 #${id}`,
      params: '参数',
      totalReturn: '总收益率',
      drawdown: '回撤',
      sharpe: 'Sharpe',
      cost: '成本',
    },
    selection: {
      kicker: '回测历史',
      title: '报告选择',
      ariaLabel: '选择回测报告',
      loading: '正在加载回测结果。',
      loadFailed: '回测历史加载失败。',
      empty:
        '还没有保存的回测报告。先运行一次回测，再查看指标、成本、净值曲线和成交流水。',
      selectedLoading: '正在加载所选报告。',
      selectedFailed: '所选回测报告加载失败。',
    },
    summary: {
      return: '摘要收益',
      sharpe: '摘要夏普',
      maxDrawdown: '摘要最大回撤',
    },
    metrics: {
      totalReturn: '总收益率',
      sharpe: '夏普',
      sortino: '索提诺',
      maxDrawdown: '最大回撤',
      calmar: 'Calmar',
      winRate: '胜率',
      durationDays: (days: number) => `${days} 个交易日`,
      volatility: '波动率',
      annualReturn: '年化收益',
      grossTurnover: '总成交额',
      fills: (count: number) => `${count} 笔成交`,
      totalCommission: '总手续费',
      commissionDetail: '券商与交易所费用',
      totalSlippage: '总滑点',
      slippageDetail: '成交相对参考价的偏移成本',
    },
    datasetSnapshot: {
      kicker: '数据审计',
      title: '数据快照',
      subtitle:
        '本次研究结果固定使用的数据范围；用于比较不同运行，避免静默更换输入。',
      snapshotId: '快照 ID',
      dataSource: '数据源',
      dateRange: '日期范围',
      rows: '行数',
      rowsValue: (count: number) => `${count} 行`,
      quality: '质量',
      qualityValue: (status: string) =>
        status === 'ok' ? '正常' : formatPublicStatus(status, 'zh'),
      cacheStore: '缓存存储',
      cacheMetadata: '缓存元数据',
      adjustmentMode: '复权',
      symbol: '标的',
      assetClass: '资产类别',
      frequency: '频率',
      dataStatus: '数据状态',
      providerName: '来源',
      coverage: '覆盖范围',
      unconfirmedDataNotice:
        '数据快照包含未确认行情。请在数据刷新或用确认 K 线回放前，将扣除成本后的指标视为研究证据。',
      yes: '是',
      no: '否',
      unknown: '未知',
      notAvailable: '不可用',
    },
    strategySnapshot: {
      kicker: '策略审计',
      title: '策略快照',
      subtitle:
        '本次报告保存的策略定义、归一化参数和验证要求，用于复盘历史结果。',
      strategy: '策略',
      strategyId: '策略 ID',
      internalStrategyId: '策略审计标识',
      displayName: '策略名称',
      benchmarkRole: '基准角色',
      universe: '适用资产',
      frequencies: '支持频率',
      frequencyDaily: '日线',
      frequencyMinute: '分钟线',
      frequencyTick: 'Tick 数据',
      validation: '验证要求',
      runParams: '运行参数',
      parameterSchema: '参数定义',
      parameter: '参数',
      type: '类型',
      defaultValue: (value: string) => `默认值 ${value}`,
      bounds: '范围',
      description: '说明',
      validationNotes: '验证备注',
      oosRequired: '需要样本外验证',
      afterCostRequired: '需要扣除成本后报告',
      unknown: '未知',
      notDeclared: '未声明',
      noBounds: '无范围限制',
      apiField: (name: string) => `参数键：${name}`,
      minMax: (min: string, max: string) => `${min} 至 ${max}`,
    },
    validationEvidence: {
      kicker: '研究证据',
      title: '验证证据',
      subtitle:
        '本次运行的扣除成本后与样本外证据。用于研究复核，不代表执行审批。',
      afterCostTitle: '扣除成本后证据',
      oosTitle: '样本外切分',
      netReturn: '净收益率',
      grossReturn: '扣成本前收益',
      totalCost: '总成本',
      costDrag: '成本拖累',
      fills: '成交',
      turnover: '成交额',
      strategy: '策略',
      strategyAuditId: '审计 ID',
      benchmarkRole: '基准角色',
      split: '切分点',
      status: '状态',
      oosReturn: '样本外收益',
      excessReturn: '超额收益',
      benchmarkReturn: '基准收益',
      oosFills: '样本外成交',
      costAssumptions: '成本假设',
      slippageAssumptions: '滑点假设',
      assumptions: '假设',
      limitations: '限制',
      unknown: '未知',
      fillCount: (count: number) => `${count} 笔成交`,
      statusValue: (status?: string, passed?: boolean | null) => {
        if (status === 'benchmark_passed' || passed === true) {
          return '基准通过';
        }
        if (status === 'benchmark_failed' || passed === false) {
          return '基准未通过';
        }
        if (status === 'benchmark_not_supplied') {
          return '未提供基准';
        }
        return formatPublicStatus(status, 'zh');
      },
    },
    chart: {
      kicker: '回测曲线',
      title: '净值与回撤',
      empty: '当前回测结果没有可用的净值曲线。',
      points: (count: number) => `${count} 个点`,
      drawdown: '回撤',
      markersKicker: '交易点位',
      markersTitle: '买卖点',
      markersCount: (count: number) => `${count} 个点位`,
      markerQuantity: '数量',
    },
    fills: {
      kicker: '执行流水',
      title: '成交明细',
      rows: (count: number) => `${count} 行`,
      empty:
        '当前保存结果没有成交明细。新的回测运行会在引擎返回成本流水后展示逐笔记录。',
      time: '时间',
      symbol: '标的',
      side: '方向',
      fillPrice: '成交价',
      quantity: '数量',
      commission: '手续费',
      slippage: '滑点',
    },
  },
} satisfies Record<Locale, Record<string, unknown>>;
