export const backtestPageZh = {
  kicker: '回测实验室',
  title: '策略回放',
  subtitle: '运行受控历史模拟，并查看风险、成本、净值路径与成交覆盖。',
  formKicker: '运行设置',
  formTitle: '回测配置',
  formDetail: '可明确填写资产列表；留空时使用已保存的研究资产池。',
  decisionHandoffKicker: '决策交接',
  decisionHandoffTitle: '来自决策候选动作',
  decisionHandoffDetail:
    '此表单已从候选动作带入标的、资产类别和策略。运行回测后，再查看数据快照、扣费后结果、信号预览、风控预览和模拟证据，之后才进入人工步骤。',
  decisionHandoffResearchOnly: '仅研究；不会创建券商订单',
  holdingHandoffKicker: '持仓研究交接',
  holdingHandoffTitle: '来自持仓详情',
  holdingHandoffDetail:
    '此表单已从持仓详情页带入标的和资产类别。运行该标的回测后，再查看数据快照、扣费后结果、信号预览、风控预览和模拟证据，之后才进入人工步骤。',
  runContextKicker: '运行上下文',
  runContextTitle: '单标的研究上下文',
  runContextDetail:
    '这条上下文会跟随本次运行进入数据、信号、风控、模拟复核和归因复核链路。',
  runContextSource: '来源',
  runContextSourcePortfolio: '来自持仓详情',
  runContextSourceDecision: '来自决策候选动作',
  runContextSourceManual: '手动回测配置',
  runContextInstrument: '标的',
  runContextAssetClass: '资产类别',
  runContextStrategy: '策略',
  runContextReviewHolding: '查看持仓详情',
  startDate: '开始日期',
  endDate: '结束日期',
  initialCash: '初始现金',
  strategy: '策略',
  strategyNames: {
    dual_ma: '双均线策略',
    monthly_rebalance: '月度再平衡',
    bollinger: '布林带均值回归',
    rsi: 'RSI 动量/反转',
    time_series_momentum: '时间序列动量',
    donchian_breakout: 'Donchian 通道突破',
    volatility_target_trend: '波动率目标趋势',
    pairs_ratio_mean_reversion: '配对比值均值回归',
  },
  strategyDescriptions: {
    dual_ma: '用短期均线与长期均线的交叉关系判断趋势方向的基准策略。',
    monthly_rebalance: '按固定周期把组合调回目标权重的再平衡基准策略。',
    bollinger: '基于布林带上下轨偏离程度观察均值回归机会的基准策略。',
    rsi: '基于 RSI 强弱变化观察动量或反转机会的基准策略。',
    time_series_momentum: '基于过去一段收益延续性的论文型趋势基准策略。',
    donchian_breakout: '基于前高/前低通道突破的经典趋势跟踪基准策略。',
    volatility_target_trend:
      '先判断趋势，再按已实现波动率缩放长仓暴露的风险控制型趋势策略。',
    pairs_ratio_mean_reversion:
      '用两只标的 A/B 比值 z-score 做长仓轮动的相对价值策略。',
  },
  benchmarkRoleNames: {
    trend_following: '趋势跟踪基准',
    etf_rotation_trend_following: 'ETF 趋势跟踪基准',
    allocation_rebalance: '配置再平衡基准',
    a_share_or_etf_mean_reversion: 'A 股 / ETF 均值回归基准',
    custom_momentum_research: '自定义动量研究基准',
    time_series_momentum: '时间序列动量基准',
    channel_breakout_trend_following: '通道突破趋势基准',
    volatility_target_trend_following: '波动率目标趋势基准',
    pair_relative_value_mean_reversion: '配对相对价值均值回归基准',
  },
  validationNotes: {
    'Requires after-cost, out-of-sample ETF trend-following validation before promotion.':
      '进入复核前需要完成扣除成本后与样本外 ETF 趋势跟踪验证。',
    'Requires after-cost, out-of-sample validation across equity ETF, bond, gold, and cash proxy allocations.':
      '进入复核前需要覆盖股票 ETF、债券、黄金和现金代理配置的扣除成本后与样本外验证。',
    'Requires after-cost, out-of-sample mean-reversion validation on A-share or ETF fixtures before promotion.':
      '进入复核前需要在 A 股或 ETF 样本上完成扣除成本后与样本外均值回归验证。',
    'Inspired by time-series momentum literature; requires after-cost, out-of-sample validation before promotion.':
      '参考时间序列动量研究；进入复核前需要完成扣除成本后与样本外验证。',
    'Long-only implementation exits to cash instead of using leverage or short futures exposure.':
      '当前实现是长仓版本，信号失效时退回现金，不使用杠杆或期货做空暴露。',
    'Common channel-breakout trend-following baseline; requires turnover, whipsaw, and after-cost review.':
      '经典通道突破趋势基准；需要重点复核换手、震荡假突破和扣费后表现。',
    'Uses prior high/low channels only and does not approve execution without risk gates.':
      '仅使用历史前高/前低通道；没有风控闸门时不能进入执行。',
    'Trend-following baseline with realized-volatility sizing; requires volatility-regime and turnover review.':
      '带已实现波动率仓位缩放的趋势基准；需要复核波动率阶段和换手成本。',
    'Long-only volatility targeting caps weight at 1.0 and never implies leverage.':
      '当前波动率目标是长仓上限 1.0 的版本，不隐含杠杆。',
    'Inspired by pairs-trading literature but constrained to long-only target weights.':
      '参考配对交易研究，但受 Karkinos 目标权重约束，当前是长仓轮动版本。',
    'Requires pair-selection, liquidity, co-movement, and transaction-cost review before promotion.':
      '进入复核前需要检查配对选择、流动性、共同运动关系和交易成本。',
  },
  parameterLabels: {
    short_period: '短期均线周期',
    long_period: '长期均线周期',
    bb_period: '布林带回看周期',
    num_std: '标准差倍数',
    rsi_period: 'RSI 平滑周期',
    oversold: '超卖阈值',
    overbought: '超买阈值',
    lookback_period: '回看窗口',
    min_return: '入场收益阈值',
    exit_return: '退出收益阈值',
    target_weight: '目标权重',
    entry_window: '突破入场窗口',
    exit_window: '突破退出窗口',
    volatility_window: '波动率窗口',
    target_annual_volatility: '目标年化波动率',
    max_weight: '最大权重',
    min_momentum: '最小动量',
    rebalance_threshold: '再平衡阈值',
    symbol_a: '配对标的 A',
    symbol_b: '配对标的 B',
    entry_z: '入场 z-score',
    exit_z: '退出 z-score',
    pair_weight: '配对单腿权重',
    neutral_weight: '中性单腿权重',
  },
  parameterDescriptions: {
    short_period:
      '用于计算短期移动平均线的 K 线/交易周期数，例如 5 表示最近 5 根日线或分钟线。',
    long_period: '用于计算长期移动平均线的 K 线/交易周期数，必须大于短期周期。',
    bb_period: '用于计算布林带上下轨的回看窗口。',
    num_std: '上下轨距离均线的标准差倍数。',
    rsi_period: 'Wilder 平滑 RSI 使用的回看窗口。',
    oversold: 'RSI 从下方上穿该水平时发出长仓目标。',
    overbought: 'RSI 从上方下穿该水平时发出退出目标。',
    lookback_period: '用于衡量收益、趋势或价差状态的历史窗口。',
    min_return: '入场前要求达到的最小历史收益。',
    exit_return: '历史收益低于或等于该阈值时退回现金。',
    target_weight: '策略发出的长仓目标权重。',
    entry_window: '用于判断向上突破的历史前高通道窗口。',
    exit_window: '用于判断向下退出的历史前低通道窗口。',
    volatility_window: '估计已实现波动率的滚动收益窗口。',
    target_annual_volatility: '用于缩放仓位的目标年化波动率。',
    max_weight: '长仓最大目标权重；当前不使用杠杆。',
    min_momentum: '继续持有风险暴露所需的最小历史收益。',
    rebalance_threshold: '目标权重变化超过该阈值时才发出信号。',
    symbol_a: '第一只配对标的；留空时使用本次运行的第一个标的。',
    symbol_b: '第二只配对标的；留空时使用本次运行的第二个标的。',
    entry_z: 'A/B 比值偏离到该 z-score 时轮动到其中一腿。',
    exit_z: 'A/B 比值回到该 z-score 内时恢复中性权重。',
    pair_weight: '配对偏离时分配给便宜一腿的目标权重。',
    neutral_weight: '比值回归后每一腿恢复到的目标权重。',
  },
  parameterCode: (name: string) => `参数键：${name}`,
  strategyMetadata: '策略元数据',
  assetUniverse: '适用资产',
  supportedFrequencies: '支持频率',
  benchmarkRole: '基准角色',
  validationRequirements: '验证要求',
  oosRequired: '需要样本外验证',
  afterCostRequired: '需要扣除成本后报告',
  notDeclared: '未声明',
  strategyRegistryLoading: '正在加载策略注册表。',
  strategyRegistryFailed: '策略注册表不可用；暂用默认基准策略。',
  strategyCatalogKicker: '策略库',
  strategyCatalogTitle: '可用回测策略',
  strategyCatalogDetail:
    '先选择研究策略，再指定标的运行回测并查看扣除成本后证据。',
  strategySourceBuiltin: '内置策略',
  strategySourceExtension: '本地扩展',
  selectStrategy: (name: string) => `选择${name}`,
  selectedStrategy: '已选',
  runReadinessTitle: '运行前摘要',
  runReadinessDetail: '运行扣费后回测并冻结数据前，先核对本次研究输入。',
  runReadinessStrategy: '策略',
  runReadinessStrategySource: '策略来源',
  runReadinessInstrument: '标的',
  runReadinessAssetClass: '资产类别',
  runReadinessParams: '参数',
  runReadinessDataset: '数据快照',
  runReadinessDatasetPending: '运行回测时会冻结本次数据快照。',
  runReadinessParameterCount: (count: number) => `${count} 个已配置参数`,
  promotionRequirementsCount: (count: number) => `${count} 个闸门待满足`,
  promotionEvidenceUnavailable: '该策略暂无推广证据',
  advancedToolsTitle: '高级实验工具',
  advancedToolsDetail: '参数扫描与同快照对比属于次级研究工具。',
  researchGovernanceTitle: '研究治理',
  researchGovernanceDetail:
    '账户/标的策略绑定与已复盘学习保持独立，不授予执行权限。',
  promotionEvidenceTitle: '推广证据',
  promotionEvidenceDetail:
    '复核扣费后、样本外、风控、模拟、账户事实与归因闸门。',
  researchArchiveTitle: 'AI 研究与已保存报告',
  researchArchiveDetail:
    'AI 任务只会在你明确发起后运行；已保存的实验仍仅作为研究证据。',
  accountStrategyKicker: '账户策略',
  accountStrategyTitle: '当前账户策略',
  accountStrategyDetail:
    '记录当前账户用于研究和人工复核上下文的策略；不会授权券商下单。',
  accountStrategyLoading: '正在加载账户策略绑定。',
  accountStrategyUnavailable:
    '账户策略绑定暂不可用；回测仍可作为研究证据运行。',
  accountStrategyStatus: {
    research_only: '仅研究',
    paper_review: '模拟复核',
    shadow_review: '模拟复核',
    manual_confirm: '人工确认',
    disabled: '已停用',
  },
  accountStrategyAttribution: {
    not_started: '尚未开始归因',
    assignment_only: '仅完成绑定',
    signal_chain_pending: '信号链路待补齐',
    orders_linked_no_fills: '已有订单，缺少成交',
    evidence_linked_pnl_pending: '证据已串联，收益待确认',
    partial: '部分归因',
    blocked: '归因已阻断',
    failed: '归因失败',
    complete: '已归因',
    attributed: '已归因',
  },
  accountStrategyScope: {
    account: '全账户',
    symbol: '单一标的',
    asset_class: '资产类别',
  },
  accountStrategyAutoTradeOff: '自动交易关闭',
  accountStrategyPnlPending:
    '当前账户策略暂无完整收益归因证据链；需要可追溯的信号、复核、订单与成交引用后再展示策略收益。',
  accountStrategyPnlAttributionStatus: '收益归因状态',
  accountStrategyPnlAttributionTier: {
    not_started: '尚未开始归因',
    partial: '部分归因',
    stale: '归因数据陈旧',
    blocked: '归因已阻断',
    complete: '归因完整',
  },
  accountStrategyPnlAttributionTierDetail: {
    not_started: '当前还没有可归属到策略的信号、复核、订单或成交引用。',
    partial: '已有部分证据，但当前策略收益归因证据链仍缺少必要引用。',
    stale: '已有归因证据，但估值数据陈旧或缺失。',
    blocked: '归因被阻断，需要先复核缺失或无效证据。',
    complete: '策略证据链足够完整，可以展示贡献。',
  },
  accountStrategyAttributionSourceStatus: '来源状态',
  accountStrategyContributionSourceStatus: '贡献状态',
  accountStrategyValuationStale: '估值陈旧 / 缺失',
  accountStrategySelectedHint: (name: string) =>
    `当前选中的回测策略：${name}。绑定只会改变研究上下文。`,
  accountStrategyAssignSelected: '设为账户研究策略',
  accountStrategyAssignSelectedSymbol: '设为当前标的策略',
  accountStrategyAssigning: '正在保存绑定',
  accountStrategyAssigned: '已绑定',
  accountStrategySymbolAssigned: '当前标的已绑定',
  accountStrategySymbolNeedsInput: '先填写标的',
  accountStrategyAssignFailed: '账户策略绑定保存失败。',
  accountStrategyScopedAssignFailed: '标的策略绑定保存失败。',
  accountStrategyScopedAssignmentsTitle: '标的策略绑定',
  accountStrategyScopedAssignmentsEmpty: '还没有单标的策略绑定。',
  accountStrategyScopedAssignmentsLoading: '正在加载标的策略绑定。',
  accountStrategyScopedAssignmentsUnavailable: '标的策略绑定暂不可用。',
  accountStrategyAttributionEvidence: '归因证据',
  accountStrategyAttributionLoading: '正在加载归因证据。',
  accountStrategyAttributionUnavailable: '归因证据暂不可用。',
  accountStrategySignalActionRisk: '信号 / 动作 / 风控',
  accountStrategyOrdersFills: '订单 / 成交',
  accountStrategyPnlStatus: '收益归因状态',
  accountStrategyContributionReport: '策略贡献报告',
  accountStrategyContributionPublicTitle: '策略贡献',
  accountStrategyContributionLoading: '正在加载策略贡献报告。',
  accountStrategyContributionUnavailable: '策略贡献报告暂不可用。',
  accountStrategyContributionExplanation:
    '只有已记入生产账本并绑定同一持久化估值快照的策略成交才会展示贡献；手工交易和现金流会单独列出。',
  accountStrategyEvidenceLinked: '证据链已连接',
  accountStrategyEvidenceRequired: '需要补齐证据',
  accountStrategyEvidenceNotApplicable: '暂未产生应归因成交',
  accountStrategyContributionHiddenUntilEvidence:
    '在所列账本与估值证据完整前，策略贡献会保持隐藏。',
  accountStrategyEvidenceRefs: '证据引用',
  accountStrategyAuditId: '审计 ID',
  accountStrategyContributionStatus: '贡献状态',
  accountStrategyEvidenceBinding: '证据绑定',
  accountStrategyLedgerPostedFills: '已入账 / 已关联成交',
  accountStrategyValuationSnapshot: '估值快照',
  accountStrategyLedgerCutoff: '账本截止点',
  accountStrategyNextManualAction: '下一步人工操作',
  accountStrategyBlockers: '阻断证据',
  accountStrategyHealthStatus: '策略健康',
  accountStrategyHealthStatusMap: {
    healthy: '健康',
    degraded: '降级',
    stale: '证据陈旧',
    paused: '已暂停',
    needs_review: '需要复核',
    not_applicable: '暂不适用',
  },
  accountStrategyEvidenceBindingStatusMap: {
    bound: '已绑定且可重放',
    blocked: '已阻断',
    not_applicable: '暂不适用',
  },
  accountStrategyContributionStatusMap: {
    no_linked_fills: '暂无可归属成交',
    valuation_missing: '缺少估值',
    evidence_bound_from_posted_fills: '账本与估值证据已绑定',
    ledger_posting_pending: '成交尚未记入生产账本',
    ledger_evidence_drift: '成交与账本记录不一致',
    valuation_snapshot_missing: '缺少持久化估值快照',
    valuation_snapshot_invalid: '持久化估值快照无效',
    valuation_identity_drift: '估值范围已变化',
    inventory_lineage_incomplete: '策略持仓来源不完整',
  },
  accountStrategyNextActionMap: {
    no_action_until_strategy_linked_fill_exists:
      '策略尚未产生关联成交，当前无需处理。',
    review_unattributed_strategy_fill_lineage:
      '复核声明属于该策略、但缺少完整信号与订单链路的成交。',
    complete_execution_reconciliation_and_explicit_ledger_posting:
      '完成执行对账，并将成交明确记入生产账本。',
    review_strategy_fill_and_ledger_identity:
      '逐项核对成交与生产账本记录，解决记录不一致。',
    publish_or_repair_persisted_valuation_snapshot:
      '核对持久化行情或净值事实后，发布或修复估值快照。',
    publish_persisted_valuation_snapshot:
      '确认行情或净值证据后，发布持久化估值快照。',
    repair_persisted_valuation_snapshot:
      '先修复无效的持久化估值快照，再重试归因。',
    review_strategy_inventory_lineage: '复核策略自有买卖持仓来源链路。',
    sync_confirmed_market_or_nav_evidence:
      '显式采集并确认行情或净值证据，再发布新快照。',
    review_evidence_bound_strategy_contribution:
      '复核当前可重放的策略贡献证据。',
  },
  accountStrategyGrossRealizedPnl: '毛已实现收益',
  accountStrategyGrossUnrealizedPnl: '毛未实现收益',
  accountStrategyCommissionSlippage: '佣金 / 滑点',
  accountStrategyTax: '税费',
  accountStrategyManualCashFlowMovement: '手工 / 现金流变动',
  accountStrategyTaxExcludedMovement: '税费 / 排除变动',
  accountStrategyNetContribution: '净贡献',
  accountStrategyMissingValuation: (symbols: string) =>
    `缺少本地估值：${symbols}。`,
  shortPeriod: '短周期',
  longPeriod: '长周期',
  symbol: '标的代码',
  symbolPlaceholder: '600002',
  assetClass: '资产类别',
  singleSymbolHint:
    '标的代码留空时，将使用已保存的研究资产池；单标的回测仅作为研究证据。',
  assets: '资产',
  assetsPlaceholder: '标的代码 股票\n标的代码 基金',
  assetsHint:
    '每行一个资产：标的代码 + 资产类别，例如股票、ETF、基金、黄金或债券。',
  run: '运行回测',
  running: '回测运行中',
  currentKicker: '当前运行',
  currentTitle: '运行结果',
  resultsWorkspaceTab: '结果与证据',
  emptyCurrent: '运行一次回测后可查看当前结果；已保存报告仍在下方可选。',
  signalPreviewKicker: '策略信号',
  signalPreviewTitle: '策略信号预览',
  signalPreviewDetail:
    '使用当前策略和同一条服务端行情数据路径，为本次单标的回测预览最新研究信号。',
  signalPreviewResearchOnly: '仅研究',
  signalPreviewSkipped: '运行单标的回测后可预览策略信号。',
  signalPreviewLoading: '正在加载策略信号预览。',
  signalPreviewUnavailable:
    '策略信号预览暂不可用；回测结果仍可作为研究证据查看。',
  signalPreviewPending: '运行单标的回测后可预览最新策略信号。',
  signalPreviewAction: '候选动作',
  signalPreviewActions: {
    buy: '买入候选',
    sell: '卖出候选',
    rebalance: '再平衡候选',
    no_action: '不操作',
  },
  signalPreviewReason: '原因',
  signalPreviewReasons: {
    buy: '策略基于本次回测数据生成了买入候选。',
    sell: '策略基于本次回测数据生成了卖出候选。',
    rebalance: '策略基于本次回测数据生成了再平衡候选。',
    no_action: '策略基于本次回测数据没有生成候选动作。',
  },
  signalPreviewDataQualityLabel: '数据质量',
  signalPreviewDataQuality: (status: string) => `数据质量：${status}`,
  signalPreviewBars: 'K 线数量',
  signalPreviewBarCount: (count: number) => `${count} 根`,
  signalPreviewReferencePriceLabel: '参考价格',
  signalPreviewReferencePrice: (price: string) => `参考价格 ${price}`,
  signalPreviewDataBasis: '信号数据依据',
  signalPreviewDataset: '数据快照',
  signalPreviewReviewGates: '复核闸门',
  signalPreviewRiskQuantity: '风控预检数量',
  signalPreviewRiskPreviewButton: '预检风控',
  signalPreviewRiskPreviewLoading: '正在预检风控',
  signalPreviewRiskPreviewUnavailable: '风控预检暂不可用；未创建订单。',
  signalPreviewRiskPreviewTitle: '风控预检',
  signalPreviewRiskPassed: '风控通过',
  signalPreviewRiskBlocked: '风控阻断',
  signalPreviewRiskNoOrder: '未创建订单',
  signalPreviewRiskPending: '输入数量后可运行只读的交易前风控预检。',
  signalPreviewRiskReasonLabels: {
    approved: '可进入人工复核',
    killSwitch: '已开启交易熔断',
    dataQuality: '行情数据需要复核',
    cashReserve: '会触碰现金保留要求',
    orderNotional: '订单金额超过策略限制',
    positionWeight: '持仓集中度超过策略限制',
  },
  signalPreviewPaperShadowTitle: '模拟复核预览',
  signalPreviewPaperShadowNextStep: '模拟复核下一步',
  signalPreviewPaperShadowReady:
    '风控预检已通过。先运行模拟复核，再进入任何人工步骤。',
  signalPreviewPaperShadowBlocked: '模拟复核预览需要等待风控预检通过。',
  signalPreviewPaperShadowButton: '预览模拟复核',
  signalPreviewPaperShadowLoading: '正在运行模拟复核',
  signalPreviewPaperShadowUnavailable: '模拟复核预览暂不可用；未创建账本记录。',
  signalPreviewPaperShadowResultTitle: '模拟复核预览',
  signalPreviewPaperShadowSimulatedFill: '模拟成交',
  signalPreviewPaperShadowBlockedResult: '等待风控通过',
  signalPreviewPaperShadowNoLedgerMutation: '不改真实账本',
  signalPreviewPaperShadowFill: '模拟执行',
  signalPreviewPaperShadowFillSummary: (quantity: string, price: string) =>
    `成交 ${quantity} @ ${price}`,
  signalPreviewPaperShadowFee: '预估成本',
  signalPreviewPaperShadowEstimatedFee: (fee: string) => `预估费用 ${fee}`,
  signalPreviewAttributionTitle: '归因证据预览',
  signalPreviewAttributionLoading: '正在检查归因证据',
  signalPreviewAttributionUnavailable: '归因预览暂不可用；未归因任何收益。',
  signalPreviewAttributionReady: '可进入复核关联',
  signalPreviewAttributionIncomplete: '证据仍不完整',
  signalPreviewAttributionNoPnl: '仅预览，不归因收益',
  signalPreviewAttributionEvidence: '证据边界',
  signalPreviewAttributionEvidenceSummary: (
    previewEvidence: number,
    productionFacts: number,
  ) => `预览证据 ${previewEvidence} / 真实事实 ${productionFacts}`,
  signalPreviewAttributionBoundary: '归因边界',
  signalPreviewAttributionPreviewOnly:
    '该预览只说明当前证据状态；只有真实信号、复核、订单和成交事实全部关联后，才允许归因策略收益。',
  signalPreviewAttributionNoLinkedFillsTitle: '没有关联真实成交',
  signalPreviewAttributionNoLinkedFillsDetail:
    '当前还没有可追溯的真实成交引用；缺少信号、复核、订单或成交证据时，不展示策略收益归因。',
  signalPreviewEvidenceChainTitle: '证据链',
  signalPreviewEvidenceChainDetail:
    '本次预览的可读审计步骤。原始证据引用不会直接暴露在操作界面。',
  signalPreviewEvidenceChainPresent: '已关联',
  signalPreviewEvidenceChainMissing: '缺失',
  signalPreviewEvidenceChainSignal: '策略信号',
  signalPreviewEvidenceChainDataset: '数据快照',
  signalPreviewEvidenceChainRisk: '风控闸门预览',
  signalPreviewEvidenceChainPaperOrder: '模拟复核订单',
  signalPreviewEvidenceChainPaperFill: '模拟复核成交',
  signalPreviewReviewLinkageTitle: '复核关联候选',
  signalPreviewReviewLinkageManual: '需要人工复核',
  signalPreviewReviewLinkageNoWrite: '不写订单或账本',
  signalPreviewReviewLinkageDetail:
    '信号、风控和模拟复核证据可以人工复核并关联。',
  signalPreviewReviewHoldingAttribution: '查看持仓归因复核',
  signalPreviewHoldingAttributionReadiness: '持仓归因准备度',
  signalPreviewGateLabels: {
    dataReady: '数据可用',
    dataNeedsReview: '数据需复核',
    dataBlocked: '数据阻断',
    accountTruthRequired: '账户事实待复核',
    riskRequired: '风控闸门待执行',
    paperShadowWaiting: '模拟复核待前置闸门',
    manualReviewRequired: '人工复核必需',
    notRequired: '无需执行',
    unknown: '需要复核',
  },
  signalPreviewGateRequired:
    '需要先经过风控、账户事实、模拟复核和人工复核，才能进入任何类实时流程。',
  signalPreviewNoGateRequired: '未生成候选动作；不需要进入交易闸门。',
  signalPreviewExecutionBoundary:
    '该预览不会创建信号、动作任务、订单、成交、账本记录或券商提交。',
  singleInstrumentLoopKicker: '单标的证据闭环',
  singleInstrumentLoopTitle: '单标的策略闭环就绪度',
  singleInstrumentLoopDetail:
    '查看冻结数据、策略、信号、风控、模拟复核和归因边界当前缺少哪些证据引用。',
  singleInstrumentLoopReady: '可进入人工复核',
  singleInstrumentLoopWaiting: '等待证据',
  singleInstrumentLoopBlocked: '被复核闸门阻断',
  singleInstrumentLoopNextStep: '下一步复核',
  singleInstrumentLoopNextBacktest: '先查看扣费后回测证据，再生成今日信号。',
  singleInstrumentLoopNextSignal: '等待这个单标的回测生成策略信号预览。',
  singleInstrumentLoopNextRisk: '先运行风控预览，再进入模拟复核。',
  singleInstrumentLoopNextBlocked: '风控预览已阻断；先复核阻断原因再模拟。',
  singleInstrumentLoopNextPaper: '风控预览通过后，运行模拟复核。',
  singleInstrumentLoopNextAttribution:
    '复核归因边界；当前缺少信号、复核、订单或成交引用时，不展示策略收益。',
  singleInstrumentLoopNextComplete:
    '研究证据已就绪，可进入人工复核；这里不会创建券商订单。',
  singleInstrumentLoopAuditCoverage: '验收审计覆盖',
  singleInstrumentLoopAuditVerified: '项已验证',
  singleInstrumentLoopAuditLoading: '正在读取验收审计覆盖',
  singleInstrumentLoopAuditUnavailable: '验收审计覆盖暂不可用',
  singleInstrumentLoopAuditFallbackKey: '验收审计',
  singleInstrumentLoopAuditBoundary:
    '仅代表产品就绪证据；不会启用券商执行，也不构成投资建议。',
  singleInstrumentLoopEvidenceCta: '查看证据',
  singleInstrumentLoopDatasetEvidence: '查看数据快照证据',
  singleInstrumentLoopStrategyEvidence: '查看策略注册证据',
  singleInstrumentLoopBacktestEvidence: '查看扣费后回测证据',
  singleInstrumentLoopSignalEvidence: '查看今日信号证据',
  singleInstrumentLoopRiskEvidence: '查看风控闸门证据',
  singleInstrumentLoopPaperEvidence: '查看模拟复核证据',
  singleInstrumentLoopAttributionEvidence: '查看归因边界证据',
  singleInstrumentLoopDatasetReady: '数据快照已就绪',
  singleInstrumentLoopDatasetWaiting: '等待数据快照',
  singleInstrumentLoopStrategyReady: '策略注册已就绪',
  singleInstrumentLoopStrategyWaiting: '等待策略注册',
  singleInstrumentLoopBacktestReady: '扣费后回测已就绪',
  singleInstrumentLoopBacktestWaiting: '等待扣费后回测',
  singleInstrumentLoopSignalReady: '今日信号已就绪',
  singleInstrumentLoopSignalWaiting: '等待今日信号',
  singleInstrumentLoopRiskPassed: '风控闸门已通过',
  singleInstrumentLoopRiskBlocked: '风控闸门已阻断',
  singleInstrumentLoopRiskWaiting: '等待风控闸门',
  singleInstrumentLoopPaperReady: '模拟复核已就绪',
  singleInstrumentLoopPaperWaiting: '等待模拟复核',
  singleInstrumentLoopAttributionReady: '归因边界已就绪',
  singleInstrumentLoopAttributionWaiting: '等待归因边界',
  totalReturn: '总收益率',
  maxDrawdown: '最大回撤',
  totalCost: '总成本',
  fillsCount: '成交数',
  evidenceGate: '研究门槛',
  evidenceGateTitle: '策略验证与复核状态',
  evidenceGateDetail:
    '查看扣除成本后、样本外、风控、模拟复核与账户事实证据，判断策略是否具备进入人工复核流程的条件；不会自动上线或下单。',
  evidenceGateLoading: '正在加载策略证据门槛。',
  evidenceGateFailed: '策略证据门槛暂不可用。',
  validationMatrix: '验证覆盖',
  promotionReadiness: '复核状态',
  accountTruthGate: '账户事实闸门',
  accountTruthEvidencePresent: '已有证据',
  accountTruthEvidenceMissing: '缺少证据',
  strategyAttributionGate: '策略归因闸门',
  strategyAttributionReady: '归因可用',
  strategyAttributionPending: '归因待补齐',
  missingRequirements: '缺失要求',
  complete: '已完成',
  incomplete: '未完成',
  noEvidenceRows: '当前还没有策略证据行。',
  none: '无',
};
