export const backtestCostCopy = {
  en: {
    settings: 'Trading cost assumptions',
    mode: 'Cost model',
    default: 'Built-in model',
    custom: 'Custom research assumptions',
    defaultDetail:
      'Built-in fees and zero slippage. Each new report saves the effective assumptions used.',
    shared:
      'These settings apply to the backtest, parameter sweep, and comparison.',
    blank:
      'Leave a field blank to keep the built-in value. One basis point (bp) is 0.01%.',
    fields: {
      stock_commission_rate: 'Stock commission (bps)',
      stock_min_commission: 'Stock minimum commission (CNY)',
      etf_commission_rate: 'ETF commission (bps)',
      etf_min_commission: 'ETF minimum commission (CNY)',
      slippage_bps: 'Slippage per fill (bps)',
    },
    inherited: 'Use built-in value',
    invalid:
      'Costs must be finite and non-negative; commissions cannot exceed 10,000 bps and slippage must be below 10,000 bps.',
    boundary:
      'Tax and transfer fees follow the built-in model. Fixed slippage does not model market impact or partial fills.',
    report: 'Recorded costs and liquidity',
    recorded: 'Effective assumptions saved with this report',
    missingCosts:
      'This report did not save its effective cost assumptions. Current defaults cannot reconstruct them.',
    unsupportedCosts:
      'This report uses an unsupported cost model. Its assumptions are not reconstructed here.',
    asset: 'Asset',
    stock: 'Stock',
    etf: 'ETF',
    bond: 'Exchange bond',
    gold: 'Gold',
    commission: 'Commission (bps)',
    minimum: 'Minimum (CNY)',
    stamp: 'Sell stamp tax (bps)',
    transfer: 'Transfer fee (bps)',
    other: 'Other fee (bps)',
    slippage: 'Slippage per fill',
    bps: 'bps',
    rules: 'Recorded fee rules',
    capacity: 'Recorded daily-bar liquidity check',
    passed: 'Within recorded limits',
    blocked: 'Limits exceeded or evidence incomplete',
    missingCapacity: 'No capacity check was saved with this report.',
    unsupportedCapacity:
      'The saved capacity model is not supported by this view.',
    legacyCapacity:
      'This older check measured each fill separately; it did not aggregate same-bar fills.',
    capital: 'Largest fill / initial capital',
    liquidity: 'Peak participation / configured limit',
    ceiling: 'Daily volume participation limit',
    observations: 'Fills with volume evidence',
    capacityDetail:
      'The current check adds absolute buy and sell quantities per symbol and execution bar. Daily volume does not establish executable depth or maximum strategy capital.',
    recordedNotes: 'Recorded assumptions and limitations',
    issues: 'Missing or conflicting evidence',
  },
  zh: {
    settings: '交易成本假设',
    mode: '成本模型',
    default: '内置模型',
    custom: '自定义研究假设',
    defaultDetail: '使用内置费用和零滑点；新报告会保存本次实际采用的假设。',
    shared: '这些设置同时用于单次回测、参数扫描和参数对比。',
    blank: '留空沿用内置值。1 个基点（bp）等于 0.01%。',
    fields: {
      stock_commission_rate: '股票佣金（基点）',
      stock_min_commission: '股票最低佣金（元）',
      etf_commission_rate: 'ETF 佣金（基点）',
      etf_min_commission: 'ETF 最低佣金（元）',
      slippage_bps: '每笔成交滑点（基点）',
    },
    inherited: '沿用内置值',
    invalid:
      '成本须为有限非负数；佣金不可超过 10,000 基点，滑点须小于 10,000 基点。',
    boundary: '印花税与过户费沿用内置模型；固定滑点不模拟市场冲击或部分成交。',
    report: '报告成本与流动性',
    recorded: '本报告保存的实际成本假设',
    missingCosts: '本报告未保存实际成本假设，不能用当前默认值还原。',
    unsupportedCosts:
      '本报告采用的成本模型尚不受此视图支持，此处不补造其假设。',
    asset: '资产',
    stock: '股票',
    etf: 'ETF',
    bond: '场内债券',
    gold: '黄金',
    commission: '佣金（基点）',
    minimum: '最低佣金（元）',
    stamp: '卖出印花税（基点）',
    transfer: '过户费（基点）',
    other: '其他费用（基点）',
    slippage: '每笔成交滑点',
    bps: '基点',
    rules: '保存的费用规则',
    capacity: '报告日线流动性检查',
    passed: '在已记录的限制内',
    blocked: '超出限制或证据不完整',
    missingCapacity: '本报告未保存容量检查。',
    unsupportedCapacity: '此视图尚不支持报告的容量模型。',
    legacyCapacity: '此旧版检查按单笔成交计算，未聚合同一根行情的多笔成交。',
    capital: '最大单笔成交额 / 初始资金',
    liquidity: '峰值参与率 / 配置上限',
    ceiling: '日成交量参与率上限',
    observations: '有成交量证据的成交笔数',
    capacityDetail:
      '当前检查按标的和成交行情汇总买卖绝对数量。日成交量不能证明可成交深度或策略最大资金容量。',
    recordedNotes: '报告保存的假设与限制',
    issues: '缺失或冲突证据',
  },
};
