export const observationHealthCopy = {
  en: {
    enable: 'Configure a forward health rule',
    mode: 'When the rule is breached',
    observe_only: 'Record the result only',
    pause_on_breach: 'Pause new publications in this observation',
    window: 'Window of matured intervals',
    minimum: 'Minimum eligible intervals',
    threshold: 'Minimum mean relative price response (decimal)',
    units:
      'Enter a decimal: 0.01 means +1 percentage point. No threshold is preselected.',
    invalid:
      'Enter positive whole numbers for the window and minimum, with minimum no greater than window, and a finite decimal threshold.',
    frozen:
      'The rule is frozen when this observation starts. It is evaluated when you publish or measure. A configured pause affects only this observation and never resumes it automatically.',
    title: 'Forward health rule',
    not_configured: 'Health rule not configured',
    notEvaluated: 'Awaiting saved health evaluation',
    waiting: 'Waiting for intervals to mature',
    insufficient_evidence: 'Too few eligible intervals',
    within_rule: 'Within configured rule',
    threshold_breached: 'Configured threshold breached',
    unavailable: 'Health evidence unavailable',
    metric:
      'Each interval compares target-weighted raw price change with a 100% equal-weight allocation to the frozen universe. Cash and lower gross exposure affect this difference; it is not risk-adjusted alpha. The rule checks the arithmetic mean of these differences against a strictly lower-than threshold.',
    selection:
      'The window uses chronological, non-overlapping intervals selected before exclusions. Missing, zero-exposure and excluded intervals retain their places.',
    boundary:
      'Raw prices exclude fees, distributions and fills; this is not NAV or proof of alpha decay. Provider-reported corporate actions may be incomplete, including ETF distributions. Known ex-date distortions are excluded; missing evidence is never treated as zero or a loss.',
    evaluated: 'Saved evaluation time',
    marketAsOf: 'Market evidence through',
    mean: 'Mean relative price response (decimal)',
    comparisonThreshold: 'Saved threshold (decimal)',
    noValue: 'Unavailable',
    scheduled_matured: 'Matured window intervals',
    pending: 'Pending intervals',
    missing_matured: 'Missing matured outcomes',
    zero_exposure: 'Zero-exposure intervals',
    corporate_action_excluded: 'Corporate-action exclusions',
    unresolved: 'Unresolved intervals',
    eligible: 'Eligible intervals',
    paused:
      'The saved rule paused new publications in this observation. Existing publications can still be measured.',
    pauseDecision: 'Saved action: pause new publications in this observation.',
    recordOnly: 'Saved action: no lifecycle change.',
    unavailableDetail:
      'Repair the missing or conflicting evidence, then measure again. This result does not establish strategy deterioration.',
    insufficientDetail:
      'More eligible matured intervals are needed before the configured comparison can be evaluated.',
    provenance: 'Saved health evidence details',
    publications: 'Selected publication identities',
    inputs: 'Input fingerprint',
    source: 'Source fingerprint',
    code: 'Code fingerprint',
    policy: 'Policy fingerprint',
    blockers: 'Saved evidence blockers',
    limitations: 'Saved measurement limitations',
  },
  zh: {
    enable: '配置前向健康规则',
    mode: '规则触发后的动作',
    observe_only: '仅记录结果',
    pause_on_breach: '暂停本观察的新增发布',
    window: '已到期区间窗口数',
    minimum: '最少有效区间数',
    threshold: '最低平均相对价格响应（小数）',
    units: '使用小数：0.01 表示高出 1 个百分点。阈值无预设值。',
    invalid:
      '窗口数和最少有效区间数须为正整数，最少有效数不得超过窗口数；阈值须为有限小数。',
    frozen:
      '规则在开始观察时冻结，仅在发布或评估时检查。配置的暂停仅影响本观察，且不会自动恢复发布。',
    title: '前向健康规则',
    not_configured: '未配置健康规则',
    notEvaluated: '等待已保存的健康评估',
    waiting: '等待观察区间到期',
    insufficient_evidence: '有效区间不足',
    within_rule: '未触发配置的规则',
    threshold_breached: '已触发配置的阈值',
    unavailable: '健康评估证据不可用',
    metric:
      '每个区间比较目标权重加权的不复权价格变化与冻结股票池 100% 等权配置的价格变化。现金和较低总敞口会影响差值，这不是风险调整后的 Alpha。规则检查这些差值的算术均值是否严格低于阈值。',
    selection:
      '窗口按时间选取互不重叠的区间，再判断是否排除；缺失、零敞口和被排除区间仍占用原位置。',
    boundary:
      '价格响应未计费用、分红送转或成交，不是净值，也不能证明 Alpha 衰退。供应商公司行动证据可能不完整，包括 ETF 分配。已知除权除息影响的区间会被排除；缺失证据不按零或亏损处理。',
    evaluated: '已保存评估时间',
    marketAsOf: '行情证据截至',
    mean: '平均相对价格响应（小数）',
    comparisonThreshold: '已保存阈值（小数）',
    noValue: '不可用',
    scheduled_matured: '窗口内已到期区间',
    pending: '等待到期区间',
    missing_matured: '缺失到期结果',
    zero_exposure: '零敞口区间',
    corporate_action_excluded: '公司行动排除区间',
    unresolved: '证据未解决区间',
    eligible: '有效区间',
    paused: '已保存的规则暂停了本观察的新增发布，已有发布仍可继续评估。',
    pauseDecision: '已保存动作：暂停本观察的新增发布。',
    recordOnly: '已保存动作：不改变发布状态。',
    unavailableDetail:
      '请修复缺失或冲突证据后重新评估。此状态不代表策略表现恶化。',
    insufficientDetail: '需要更多有效且已到期的区间，才能执行配置的阈值比较。',
    provenance: '已保存健康证据详情',
    publications: '选中的发布身份',
    inputs: '输入指纹',
    source: '来源指纹',
    code: '代码指纹',
    policy: '规则指纹',
    blockers: '已保存证据阻断原因',
    limitations: '已保存测量限制',
  },
};
