import type { Locale } from '../../shared/locale';

export const marketCopy = {
  en: {
    kicker: 'Market',
    title: 'Market research',
    subtitle:
      'Track coverage, quote health, price structure, and research records for each symbol.',
    loading: 'Loading research board.',
    error: 'Failed to load research board.',
    watchlist: 'Research board',
    health: 'Data health',
    chart: 'Price structure',
    priceRangeKline: 'Price range / K-line',
    addSymbol: 'Add symbol',
    symbolPlaceholder: 'Symbol',
    assetClass: 'Asset class',
    add: 'Add',
    remove: 'Remove',
    marketOpen: 'Market open',
    marketClosed: 'Market closed',
    refreshPolicy: 'Refresh policy',
    evidenceMode: 'Evidence mode',
    sourceHealth: 'Source health',
    provider: 'Provider',
    providerStatus: 'Provider status',
    providerConfigured: 'Provider configured',
    providerSupportsFunds: 'Fund support',
    providerTimeout: 'Provider timeout',
    providerNextAction: 'Next action',
    providerFundCoverageScope: 'Portfolio-wide fund coverage',
    metadataConfiguredCount: 'Configured metadata',
    latestQuote: 'Latest quote timestamp',
    cacheAge: 'Cache age',
    staleSymbols: 'quotes need review',
    lastRefreshAttempt: 'Last refresh attempt',
    lastRefreshError: 'Last refresh error',
    quoteSource: 'Quote source',
    staleReason: 'Stale reason',
    quoteAge: 'Quote age',
    configured: 'Configured',
    notConfigured: 'Not configured',
    fundSupported: 'Fund-capable',
    fundUnsupported: 'Not fund-capable',
    unknown: 'Unknown',
    refreshQuotes: 'Refresh quotes',
    refreshingQuotes: 'Refreshing quotes',
    quoteRefreshComplete: 'Quote refresh completed',
    quoteRefreshPartial: 'Partial quote refresh completed',
    quoteRefreshStale: 'Quote source returned cached quotes',
    quoteRefreshFailed: 'Quote refresh failed',
    refreshResult: 'Refresh result',
    refreshConfirmedFundNav: 'Sync confirmed NAV',
    refreshingConfirmedFundNav: 'Syncing confirmed NAV',
    confirmedFundNavRefreshComplete: (count: number) =>
      `${count} confirmed fund NAV${count === 1 ? '' : 's'} recorded`,
    confirmedFundNavRefreshPartial: (refreshed: number, failed: number) =>
      `${refreshed} confirmed, ${failed} still need review`,
    confirmedFundNavRefreshUnavailable:
      'No same-day confirmed NAV was published; the review items remain.',
    confirmedFundNavRefreshInProgress:
      'The same audited ingestion run is still in progress.',
    confirmedFundNavIdempotentReplay:
      'Repeated request: reused the existing audited refresh without contacting the data source again.',
    confirmedFundNavRefreshFailed: 'Confirmed NAV ingestion failed',
    confirmedFundNavAuditRun: 'Audit run',
    holdingEvidenceReview: 'Current holding evidence review',
    holdingEvidenceReviewDetail:
      'Only current non-zero holdings from the account record are included. A review clears only after newer confirmed quote or NAV evidence is recorded.',
    holdingEvidenceReviewComplete:
      'All current holdings have confirmed market evidence.',
    holdingEvidenceReviewEmpty: 'There are no current holdings to review.',
    holdingEvidenceReviewUnavailable:
      'The canonical current-holding evidence report is unavailable.',
    holdingEvidenceReviewBlocked:
      'The valuation basis is incomplete. Restore the snapshot binding before reviewing market evidence.',
    holdingEvidenceReviewCount: (count: number) =>
      `${count} current holding${count === 1 ? ' needs' : 's need'} review`,
    holdingEvidenceConfirmedCount: (count: number) =>
      `${count} confirmed holding${count === 1 ? '' : 's'}`,
    holdingEvidenceMetricsLabel: 'Current holding evidence metrics',
    holdingEvidenceMetricReviewRequired: 'Review required',
    holdingEvidenceMetricConfirmed: 'Confirmed',
    holdingEvidenceExceptionListLabel:
      'Holdings requiring market evidence review',
    holdingEvidenceReasonLabel: 'Evidence gap',
    holdingEvidenceClearingConditionLabel: 'Clearing condition',
    holdingEvidenceSafeNextStepLabel: 'Safe next step',
    holdingEvidenceEvidenceLabel: 'Recorded evidence',
    holdingEvidenceClearingCondition:
      'A newer confirmed quote or NAV must replace this record.',
    holdingEvidenceBlocksAuthoritativeDecisions:
      'Authoritative decisions remain blocked for this holding.',
    holdingEvidenceIdentityBlockedStatus: 'Valuation basis incomplete',
    holdingEvidenceIdentityTitle: 'Valuation basis',
    holdingEvidenceIdentityReason:
      'The saved snapshot is missing a required valuation, ledger, or quote-set reference.',
    holdingEvidenceIdentityClearingCondition:
      'Save and validate a complete snapshot binding before reviewing quote evidence.',
    holdingEvidenceIdentityNextAction:
      'Restore the missing snapshot reference in Account Truth.',
    holdingEvidenceIdentityEvidence: (count: number) =>
      `${count} required reference field${count === 1 ? ' is' : 's are'} missing`,
    holdingEvidenceReasons: {
      confirmed_nav_missing:
        'Confirmed NAV has not been published or recorded.',
      estimated_quote_not_authoritative:
        'The estimated quote is not authoritative market evidence.',
      quote_stale_or_cached:
        'The recorded quote is stale or bound to cached evidence.',
      quote_missing_or_error: 'No usable recorded quote is available.',
      quote_status_not_confirmed:
        'The recorded quote status is not recognized as confirmed.',
    },
    holdingEvidenceExplicitRefresh:
      'This button performs an explicit ingestion run. It may contact the configured market-data source, records the batch, and does not change ledger, OMS, risk, or authority.',
    holdingEvidenceConfirmedNavRefresh:
      'Fund NAV uses a separate confirmation-only ingestion run. Estimates and previous-day NAV cannot clear review; every attempt is audited and cannot change trading authority.',
    holdingEvidenceSnapshot: 'Valuation snapshot',
    holdingEvidenceLedgerCutoff: 'Ledger cutoff',
    holdingEvidenceFingerprint: 'Review fingerprint',
    holdingEvidenceActions: {
      wait_for_confirmed_nav_then_run_explicit_refresh:
        'Wait for confirmed NAV, then run explicit refresh',
      wait_for_confirmed_data_then_run_explicit_refresh:
        'Wait for confirmed data, then run explicit refresh',
      run_explicit_quote_refresh: 'Run explicit quote refresh',
      inspect_data_source_then_run_explicit_refresh:
        'Inspect data source, then run explicit refresh',
      review_unknown_quote_status_before_refresh:
        'Review the unknown quote state before refresh',
    },
    providerActions: {
      configure_data_source_token: 'Configure data source token',
      switch_to_fund_supported_provider: 'Switch to a fund-capable source',
      check_provider_network_or_use_cache:
        'Check provider network or continue with cached quotes',
      check_data_source_settings: 'Check data source settings',
      refresh_quotes_or_check_source: 'Refresh quotes or check source',
      configure_real_provider: 'Configure a real market data provider',
      configure_asset_metadata: 'Configure asset metadata',
      use_cached_data: 'Continue with local cached market data',
      run_first_sync: 'Configure a data source or run the first sync',
    },
    selectedSymbol: 'Selected symbol',
    symbolLabel: 'Symbol',
    priceLabel: 'Price',
    klineRanges: {
      oneMonth: '1M',
      threeMonths: '3M',
      sixMonths: '6M',
      oneYear: '1Y',
      all: 'All',
    },
    klineAxes: {
      price: 'Price axis',
      date: 'Date axis',
      volume: 'Volume',
    },
    showKlineRange: (label: string) => `Show ${label} K-line range`,
    snapshotLabel: 'Snapshot time',
    holdingsContext: 'Holding context',
    personalUniverse: 'Personal universe',
    scopeBoundary:
      'Watchlist and current-holding research only; this is not a broad-market dashboard or a portfolio-contribution view.',
    noSelection: 'Select or add a symbol to start research.',
    noChart: 'No price structure available for the selected symbol.',
    klineLoading: 'Loading persisted price structure',
    klineLoadingDetail:
      'Waiting for the selected symbol’s saved bars; absence has not been determined yet.',
    klineError: 'Price structure could not be loaded',
    klineErrorDetail:
      'The saved bar request failed. No provider refresh was attempted.',
    promptsTitle: 'Research checklist',
    notesTitle: 'Research notes',
    notesEmpty:
      'No notes yet. Capture the current thesis before the market moves.',
    noteType: 'Record type',
    noteTitle: 'Title',
    noteContent: 'Content',
    notePriority: 'Priority',
    noteDate: 'Catalyst date',
    noteDateFrom: 'From date',
    noteDateTo: 'To date',
    editNote: 'Edit note',
    noteUpdatedAt: 'Updated',
    showFullNote: 'View full record',
    hideFullNote: 'Hide full record',
    updateNote: 'Update note',
    saveNote: 'Save note',
    savingNote: 'Saving...',
    noteSaved: 'Research note saved',
    noteFailed: 'Failed to save research note',
    noteDeleted: 'Research note removed',
    noteDeleteFailed: 'Failed to remove research note',
    noteTitlePlaceholder: 'What changed or needs to be watched?',
    noteContentPlaceholder:
      'Capture the thesis, risk, or trigger in a reusable way.',
    note: 'Note',
    thesis: 'Thesis',
    catalyst: 'Catalyst',
    highPriority: 'High',
    normalPriority: 'Normal',
    lowPriority: 'Low',
    researchCount: 'Research records',
    lastResearch: 'Last updated',
    allTypes: 'All types',
    allPriorities: 'All priorities',
    prompts: [
      'Review price structure against the current cost basis.',
      'Confirm whether position size still fits conviction and cash buffer.',
      'Check whether the symbol adds opportunity or concentration risk.',
    ],
    dataOperations: 'Data operations',
    dataOperationsDetail:
      'Inspect recent quote fetch runs and manually backfill metadata or daily bars when local cache coverage is incomplete.',
    metadataBackfill: 'Backfill metadata',
    barsBackfill: 'Backfill daily bars',
    backfilling: 'Backfilling',
    metadataBackfillComplete: 'Metadata backfill completed',
    metadataBackfillFailed: 'Metadata backfill failed',
    barsBackfillComplete: 'Daily bars backfill completed',
    barsBackfillFailed: 'Daily bars backfill failed',
    backfillResult: (updated: number, failed: number) =>
      `${updated} updated, ${failed} failed`,
    quoteFetchRunsFailed: 'Quote fetch runs are unavailable.',
    noQuoteFetchRuns: 'No quote fetch runs have been recorded yet.',
    successCount: 'Success',
    failedCount: 'Failed',
    cacheHitCount: 'Cache hits',
  },
  zh: {
    kicker: '市场',
    title: '市场研究',
    subtitle: '围绕关注列表、行情健康度、价格结构与研究记录组织研究输入。',
    loading: '正在加载市场研究。',
    error: '市场研究加载失败。',
    watchlist: '研究看板',
    health: '数据健康度',
    chart: '价格结构',
    priceRangeKline: '区间波动 / K 线',
    klineRanges: {
      oneMonth: '1月',
      threeMonths: '3月',
      sixMonths: '6月',
      oneYear: '1年',
      all: '全部',
    },
    klineAxes: {
      price: '价格轴',
      date: '日期轴',
      volume: '成交量',
    },
    showKlineRange: (label: string) => `显示 ${label} K 线区间`,
    addSymbol: '新增标的',
    symbolPlaceholder: '代码',
    assetClass: '资产类别',
    add: '添加',
    remove: '移除',
    marketOpen: '市场开盘',
    marketClosed: '市场收盘',
    refreshPolicy: '刷新策略',
    evidenceMode: '证据模式',
    sourceHealth: '来源健康度',
    provider: '行情源',
    providerStatus: '行情源状态',
    providerConfigured: '配置状态',
    providerSupportsFunds: '基金支持',
    providerTimeout: '超时保护',
    providerNextAction: '下一步',
    providerFundCoverageScope: '组合级基金覆盖',
    metadataConfiguredCount: '已配置元数据',
    latestQuote: '最近行情时间',
    cacheAge: '缓存年龄',
    staleSymbols: '条行情需确认',
    lastRefreshAttempt: '最近刷新尝试',
    lastRefreshError: '最近刷新错误',
    quoteSource: '行情来源',
    staleReason: '缓存原因',
    quoteAge: '行情年龄',
    configured: '已配置',
    notConfigured: '未配置',
    fundSupported: '支持基金',
    fundUnsupported: '不支持基金',
    unknown: '未知',
    refreshQuotes: '刷新行情',
    refreshingQuotes: '刷新中',
    quoteRefreshComplete: '行情刷新完成',
    quoteRefreshPartial: '部分行情刷新完成',
    quoteRefreshStale: '行情源返回缓存行情',
    quoteRefreshFailed: '行情刷新失败',
    refreshResult: '刷新结果',
    refreshConfirmedFundNav: '同步确认净值',
    refreshingConfirmedFundNav: '正在同步确认净值',
    confirmedFundNavRefreshComplete: (count: number) =>
      `${count} 个基金确认净值已记录`,
    confirmedFundNavRefreshPartial: (refreshed: number, failed: number) =>
      `${refreshed} 个已确认，${failed} 个仍需复核`,
    confirmedFundNavRefreshUnavailable:
      '暂未取得当日确认净值，复核项继续保留。',
    confirmedFundNavRefreshInProgress: '同一审计采集批次仍在运行中。',
    confirmedFundNavIdempotentReplay:
      '重复请求已复用原审计批次，未再次联系数据源。',
    confirmedFundNavRefreshFailed: '确认净值采集失败',
    confirmedFundNavAuditRun: '审计批次',
    holdingEvidenceReview: '当前持仓证据复核',
    holdingEvidenceReviewDetail:
      '仅纳入账户记录中的非零当前持仓；只有更新且已确认的行情或净值证据才能解除复核。',
    holdingEvidenceReviewComplete: '所有当前持仓均已有确认行情证据。',
    holdingEvidenceReviewEmpty: '当前没有需要复核的持仓。',
    holdingEvidenceReviewUnavailable: '当前持仓权威证据报告暂不可用。',
    holdingEvidenceReviewBlocked:
      '估值依据不完整；需要先恢复快照绑定，不能把该报告当作完整证据。',
    holdingEvidenceReviewCount: (count: number) =>
      `${count} 个当前持仓需要复核`,
    holdingEvidenceConfirmedCount: (count: number) =>
      `${count} 个当前持仓已确认`,
    holdingEvidenceMetricsLabel: '当前持仓证据指标',
    holdingEvidenceMetricReviewRequired: '待复核',
    holdingEvidenceMetricConfirmed: '已确认',
    holdingEvidenceExceptionListLabel: '需要行情证据复核的当前持仓',
    holdingEvidenceReasonLabel: '证据缺口',
    holdingEvidenceClearingConditionLabel: '解除条件',
    holdingEvidenceSafeNextStepLabel: '安全下一步',
    holdingEvidenceEvidenceLabel: '已记录证据',
    holdingEvidenceClearingCondition:
      '必须由更新且已确认的行情或净值证据替代。',
    holdingEvidenceBlocksAuthoritativeDecisions: '该持仓仍不能用于权威决策。',
    holdingEvidenceIdentityBlockedStatus: '估值依据不完整',
    holdingEvidenceIdentityTitle: '估值依据',
    holdingEvidenceIdentityReason:
      '已保存快照缺少必需的估值、账本或行情集标识。',
    holdingEvidenceIdentityClearingCondition:
      '必须先保存并验证完整的快照绑定，才能继续复核行情证据。',
    holdingEvidenceIdentityNextAction: '前往账户事实页恢复缺失的快照标识。',
    holdingEvidenceIdentityEvidence: (count: number) =>
      `${count} 个必需标识字段缺失`,
    holdingEvidenceReasons: {
      confirmed_nav_missing: '确认净值尚未发布或记录。',
      estimated_quote_not_authoritative: '估算行情不属于权威行情证据。',
      quote_stale_or_cached: '已记录行情已过期或仍受缓存证据约束。',
      quote_missing_or_error: '当前没有可用的已记录行情。',
      quote_status_not_confirmed: '已记录行情状态尚未被识别为已确认。',
    },
    holdingEvidenceExplicitRefresh:
      '该按钮会显式采集行情：可能联系已配置的行情源并记录批次，但不会修改账本、订单状态、风控或任何权限。',
    holdingEvidenceConfirmedNavRefresh:
      '基金净值使用独立的仅确认采集批次；估值与前一日净值不能清除复核，每次尝试均留存审计且不会改变交易权限。',
    holdingEvidenceSnapshot: '估值快照',
    holdingEvidenceLedgerCutoff: '账本截止',
    holdingEvidenceFingerprint: '复核指纹',
    holdingEvidenceActions: {
      wait_for_confirmed_nav_then_run_explicit_refresh:
        '等待确认净值发布后，再显式刷新',
      wait_for_confirmed_data_then_run_explicit_refresh:
        '等待确认数据后，再显式刷新',
      run_explicit_quote_refresh: '显式刷新该行情',
      inspect_data_source_then_run_explicit_refresh: '先检查数据源，再显式刷新',
      review_unknown_quote_status_before_refresh: '刷新前先复核未知行情状态',
    },
    providerActions: {
      configure_data_source_token: '配置数据源凭证',
      switch_to_fund_supported_provider: '切换到支持基金的数据源',
      check_provider_network_or_use_cache: '检查行情源网络，或继续使用缓存行情',
      check_data_source_settings: '检查数据源设置',
      refresh_quotes_or_check_source: '刷新行情或检查数据源',
      configure_real_provider: '配置真实行情源',
      configure_asset_metadata: '配置资产元数据',
      use_cached_data: '继续使用本地缓存行情',
      run_first_sync: '配置数据源或执行首次同步',
    },
    selectedSymbol: '当前标的',
    symbolLabel: '代码',
    priceLabel: '价格',
    snapshotLabel: '快照时间',
    holdingsContext: '持仓上下文',
    personalUniverse: '个人研究域',
    scopeBoundary:
      '这里只展示关注列表与当前持仓研究，不代表大盘表现，也不等同于个人组合贡献。',
    noSelection: '先选择或新增一个标的，再开始研究。',
    noChart: '当前标的没有可用的价格结构数据。',
    klineLoading: '正在读取已保存价格历史',
    klineLoadingDetail: '正在等待当前标的的已保存 K 线，尚不能判定为数据缺失。',
    klineError: '价格结构加载失败',
    klineErrorDetail: '读取已保存 K 线失败；本次查看没有触发行情源刷新。',
    promptsTitle: '研究清单',
    notesTitle: '研究记录',
    notesEmpty: '还没有研究记录，先把当前逻辑或催化剂写下来。',
    noteType: '记录类型',
    noteTitle: '标题',
    noteContent: '内容',
    notePriority: '优先级',
    noteDate: '催化日期',
    noteDateFrom: '开始日期',
    noteDateTo: '结束日期',
    editNote: '编辑记录',
    noteUpdatedAt: '更新时间',
    showFullNote: '查看完整记录',
    hideFullNote: '收起完整记录',
    updateNote: '更新记录',
    saveNote: '保存记录',
    savingNote: '保存中...',
    noteSaved: '研究记录已保存',
    noteFailed: '研究记录保存失败',
    noteDeleted: '研究记录已删除',
    noteDeleteFailed: '研究记录删除失败',
    noteTitlePlaceholder: '这次变化是什么，接下来要盯什么？',
    noteContentPlaceholder: '把逻辑、风险点和催化条件写成可复用记录。',
    note: '笔记',
    thesis: '逻辑',
    catalyst: '催化剂',
    highPriority: '高',
    normalPriority: '中',
    lowPriority: '低',
    researchCount: '研究条目',
    lastResearch: '最近更新',
    allTypes: '全部类型',
    allPriorities: '全部优先级',
    prompts: [
      '检查当前价格结构相对持仓成本的变化。',
      '确认当前仓位是否仍匹配判断与现金缓冲。',
      '判断该标的是新增机会还是集中度来源。',
    ],
    dataOperations: '数据运维',
    dataOperationsDetail:
      '查看最近行情抓取批次；当本地缓存覆盖不足时，可手动补齐元数据或日线数据。',
    metadataBackfill: '补齐元数据',
    barsBackfill: '补齐日线',
    backfilling: '补齐中',
    metadataBackfillComplete: '元数据补齐完成',
    metadataBackfillFailed: '元数据补齐失败',
    barsBackfillComplete: '日线补齐完成',
    barsBackfillFailed: '日线补齐失败',
    backfillResult: (updated: number, failed: number) =>
      `${updated} 条更新，${failed} 条失败`,
    quoteFetchRunsFailed: '行情抓取批次暂不可用。',
    noQuoteFetchRuns: '当前还没有记录行情抓取批次。',
    successCount: '成功',
    failedCount: '失败',
    cacheHitCount: '缓存命中',
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type MarketCopy = (typeof marketCopy)[Locale];

declare module '../../shared/i18n/context' {
  interface ApplicationCopy {
    market: MarketCopy;
  }
}
