export const accountTruthReviewLabelsZh = {
  kicker: '账户事实',
  title: '账户事实复核中心',
  subtitle: '在依赖账户事实前，复核券商证据、对账差异和人工处理状态。',
  loading: '正在加载账户事实证据。',
  error: '账户事实证据加载失败。',
  score: '对账分数',
  scorePending: '待导入',
  gate: '对账门禁',
  unresolved: '未解决差异',
  resolved: '已复核',
  freshness: '新鲜度',
  components: '组件原因',
  blockingReasons: '阻断原因',
  requiredActions: '下一步动作',
  imports: '导入批次',
  reports: '对账报告',
  reviewWorkspace: '当前对账复核',
  reviewWorkspaceDetail:
    '优先查看未解决差异与已失效复核；匹配明细默认保持安静。',
  reconciliationLanes: '分资产对账通道',
  reconciliationLanesDetail:
    '股票与基金证据分别呈现，现金由两类资产共享；执行仍只服从一个账户总门禁。',
  reconciliationStockLane: '股票通道',
  reconciliationStockLaneDetail: '股票对账可独立通过，不被基金差异混淆。',
  reconciliationFundLane: '基金通道',
  reconciliationFundLaneDetail:
    '基金差异保持可见，不会抹去股票通道的通过状态。',
  reconciliationCashLane: '共享现金通道',
  reconciliationCashLaneDetail: '现金由股票和基金持仓共同使用。',
  reconciliationAccountLane: '账户总门禁',
  reconciliationAccountBlockedDetail:
    '所有必需通道通过前，账户总执行门禁继续阻断。',
  reconciliationAccountPassDetail: '账户总门禁已通过，但这本身不授予执行权限。',
  reconciliationLaneUnresolved: (count: number) => `${count} 条未解决明细`,
  detail: '报告明细',
  reportHistory: '历史对账报告',
  reportHistoryCount: (count: number) => `${count} 份较早报告`,
  reportListLabel: '选择对账报告',
  currentReport: '当前报告',
  reconciliationItems: '对账明细',
  attentionItems: '待复核明细',
  matchedItems: '已匹配明细',
  matchedItemsQuiet: (count: number) =>
    `${count} 条明细未发现当前阻断，默认收起。`,
  showMatchedItems: (count: number) => `查看 ${count} 条已匹配明细`,
  hideMatchedItems: '收起已匹配明细',
  itemListLabel: '选择对账明细',
  selectItem: '查看明细',
  itemCount: (count: number) => `${count} 条明细`,
  rows: '行数',
  duplicates: '重复',
  cashDifference: '现金差异',
  feeDifference: '费用差异',
  taxDifference: '税费差异',
  validation: '校验',
  source: '来源',
  created: '创建时间',
  limitations: '限制',
  noImports: '还没有暂存的券商证据。',
  noReports: '当前筛选下没有对账报告。',
  noItems: '该报告没有对账差异。',
  notReadyTitle: '账户事实尚未建立',
  notReadyBody:
    '还没有暂存券商交割单、持仓快照或现金快照，暂时无法计算账户事实分。',
  workflowTitle: '这个页面怎么用',
  workflowSteps: [
    '先导入券商证据',
    '把券商证据与 Karkinos 账本和持仓做对账',
    '回到这里逐条复核差异',
  ],
  importWizardKicker: '券商 CSV',
  importWizardTitle: '上传券商流水',
  importWizardBody:
    '上传或粘贴标准券商流水 CSV。预览只校验文件，不会暂存证据。',
  importToolsTitle: '暂存新的券商证据',
  importToolsDetail: '显式导入会写入可审计证据批次，但不会把数据写入生产账本。',
  importHistoryTitle: '导入历史',
  importHistoryDetail: (count: number) => `${count} 个持久化导入批次`,
  scoreEvidenceTitle: '账户事实闸门证据',
  scoreEvidenceDetail: '查看分数组件、阻断原因和所需人工动作。',
  readinessTitle: '证据就绪清单',
  readinessDetail:
    '用同一个只读持久事实清单说明哪些证据已审查、还缺什么，以及账户事实门禁为何通过或继续阻断。',
  readinessRequirements: '证据要求',
  readinessKnownSources: '持久化待补证来源',
  readinessClear: '持久证据已通过',
  readinessNextAction: '下一步安全动作',
  readinessPriorityBlockedTitle: '账户证据尚未就绪',
  readinessPriorityReadyTitle: '已复核账户证据已就绪',
  readinessPriorityBlockedDetail:
    '只要账户绑定、覆盖时段、资产范围或对账证据仍有缺失，整体证据门禁就会继续阻断。',
  readinessPriorityLocalPassDetail: '局部对账分数通过，不能清除这些证据缺失。',
  readinessPriorityReadyDetail:
    '持久化证据清单已完整；这不会授予执行或资本权限。',
  readinessPriorityAction: '查看证据要求',
  readinessItemEvidence: '支持证据',
  readinessItemSafeAction: '安全下一步',
  readinessItemNoEvidence: '暂无持久化证据',
  readinessScopeTitle: '可证明的证据范围',
  readinessScopeDetail:
    '已观察到的记录只能说明文件里有什么，不能证明它完整覆盖了整个账户或完整时段。',
  readinessAccountBinding: '已复核账户绑定',
  readinessDeclaredWindow: '已复核覆盖时段',
  readinessObservedWindow: '观察到的事件跨度',
  readinessObservedRows: (count: number) => `持久化记录 ${count} 条`,
  readinessObservedAssets: '观察到的资产类别',
  readinessSnapshotDates: '最新快照日期',
  readinessNoObservedAssets: '未观察到经过校验的资产类别',
  readinessCashSnapshotShort: '资金',
  readinessPositionSnapshotShort: '持仓',
  scopeReviewTitle: '复核并绑定这份证据范围',
  scopeReviewDetail:
    '把当前精确导入绑定到私有账户引用、已复核时段和完整资产范围。',
  scopeReviewProvider: '券商提供方代码',
  scopeReviewAccountAlias: '本地账户别名',
  scopeReviewAccountIdentifier: '券商账户标识',
  scopeReviewAccountIdentifierHelp:
    '账户标识只在当前浏览器中计算哈希，原值不会发送给 API，也不会持久化。',
  scopeReviewStartDate: '覆盖开始日期',
  scopeReviewEndDate: '覆盖结束日期',
  scopeReviewAssets: '已复核资产类别',
  scopeReviewAttestation:
    '我已复核这份精确导出，并确认它完整覆盖该时段内的整个账户及上述资产类别。',
  scopeReviewSubmit: '记录范围复核',
  scopeReviewRecording: '正在记录复核…',
  scopeReviewRecorded: '范围复核已记录',
  scopeReviewFailed: '范围复核已失败关闭',
  scopeReviewRevoke: '撤销范围复核',
  scopeReviewRevoking: '正在撤销复核…',
  scopeReviewRevoked: '范围复核已撤销',
  scopeReviewBoundary:
    '该显式动作只写入追加式范围复核记录；不会修改券商证据、执行对账、改写账本、联系券商，也不会授予执行或资本权限。',
  scopeReviewComplete: '已复核范围已绑定到当前精确持久化导入。',
  assetClassStock: '股票',
  assetClassEtf: 'ETF',
  assetClassFund: '基金',
  assetClassGold: '黄金',
  assetClassBond: '债券',
  assetClassCash: '现金',
  readinessBoundary:
    '该清单严格只读，不导入证据、不联系券商、不执行对账，也不授予执行或资本权限。',
  sourceName: '来源名称',
  chooseFile: '选择 CSV 文件',
  csvContent: 'CSV 内容',
  previewImport: '预览',
  confirmImport: '暂存证据并对账',
  previewReady: '预览完成',
  importReady: '证据已暂存',
  importFailed: '导入失败',
  noFileContent: '请先选择 CSV 文件或粘贴 CSV 内容。',
  validRows: '有效行',
  invalidRows: '无效行',
  duplicateRows: '重复行',
  eventPreview: '事件预览',
  importBoundary:
    '这里只暂存券商证据；不会修改生产账本、持仓、现金，也不会提交券商订单。',
  citicPreviewKicker: '中信旧版 XLS',
  citicPreviewTitle: '按月检查中信历史成交',
  citicPreviewBody:
    '一次选择最多 24 份已导出的 .xls 文件；系统只在内存中逐份检查，响应不会返回账户和成交明细。',
  citicChooseFile: '选择中信历史成交 XLS 文件',
  citicPreviewAction: '预览所选中信 XLS 文件',
  citicDirectoryTitle: '已配置的本地导出目录',
  citicDirectoryBody:
    '仅在人工触发时，按数量和字节上限读取目录直属且稳定的 XLS 文件；API 不返回配置路径或来源文件名。',
  citicDirectoryScanAction: '扫描已配置目录',
  citicDirectoryDisabled:
    '启动配置尚未启用本地目录扫描；仍可继续使用浏览器选择文件。',
  citicDirectoryUnavailable: '暂时无法读取目录扫描配置状态。',
  citicDirectoryEmpty: '目录中没有可读取的中信 .xls 文件。',
  citicDirectoryScanFailed: '目录扫描已安全阻断。',
  citicDirectoryPartial: (count: number) =>
    `${count} 个本地来源已被安全跳过；其余可读取来源仍然只是阻断预览。`,
  citicDirectorySummary: (
    candidates: number,
    previews: number,
    duplicates: number,
  ) => `候选 ${candidates} · 唯一预览 ${previews} · 重复 ${duplicates}`,
  citicBatchAssessmentTitle: '批次完整性与覆盖边界',
  citicBatchIntegrityClear: '文件集合完整性无冲突；覆盖范围尚未证明',
  citicBatchIntegrityBlocked: '文件集合完整性已阻断',
  citicBatchObservedMonths: (months: string) =>
    `观察到事件的月份：${months || '无'}`,
  citicBatchIntegritySummary: (
    uniqueEvents: number,
    crossFileDuplicates: number,
    identityConflicts: number,
    sourcesWithoutEvents: number,
  ) =>
    `唯一事件 ${uniqueEvents} · 跨文件重复 ${crossFileDuplicates} · 事件身份冲突 ${identityConflicts} · 无资金事件来源 ${sourcesWithoutEvents}`,
  citicBatchQueryWindowProgress: (reviewed: number, total: number) =>
    `当前来源查询区间已显式复核 ${reviewed} / ${total}`,
  citicQueryWindowBatchTitle: '声明查询区间完整性',
  citicQueryWindowBatchUnavailable: '尚无已复核查询区间',
  citicQueryWindowBatchPartial: '查询区间复核尚未完成',
  citicQueryWindowBatchClear: '声明日期连续且无重叠',
  citicQueryWindowBatchBlocked: '声明日期需要修正',
  citicQueryWindowBatchSummary: (
    startDate: string | null,
    endDate: string | null,
    coveredDays: number,
    gapDays: number,
    overlapDays: number,
  ) =>
    startDate && endDate
      ? `声明区间 ${startDate} — ${endDate} · 覆盖 ${coveredDays} 个自然日 · 缺口 ${gapDays} 天 · 重叠 ${overlapDays} 天`
      : '当前来源尚未记录显式复核的查询区间。',
  citicQueryWindowBatchBoundary:
    '这里只检查 owner 声明的导出日期。日期连续不能证明账户或资产范围完整，也不能补足逐项结算、当前资金或当前持仓。',
  citicSourceScopeBatchTitle: '声明来源范围完整性',
  citicSourceScopeBatchUnavailable: '尚无已复核来源范围',
  citicSourceScopeBatchPartial: '来源范围复核尚未完成',
  citicSourceScopeBatchClear: '声明来源范围一致',
  citicSourceScopeBatchBlocked: '声明来源范围存在冲突',
  citicSourceScopeBatchSummary: (
    reviewed: number,
    total: number,
    accountConsistent: boolean,
    scopeConsistent: boolean,
  ) =>
    `来源范围已复核 ${reviewed} / ${total} · 账户绑定${accountConsistent ? '一致' : '未证明或冲突'} · 声明范围${scopeConsistent ? '一致' : '未证明或冲突'}`,
  citicSourceScopeBatchDeclared: (
    accountType: string | null,
    markets: string,
    assets: string,
    accountValueBand: string | null,
    businesses: string,
  ) =>
    `账户类型 ${accountType || '未证明'} · 市场 ${markets || '未证明'} · 资产 ${assets || '未证明'} · 账户规模区间 ${accountValueBand || '未证明'} · 业务类型 ${businesses || '未证明'}`,
  citicSourceScopeBatchBoundary:
    '这是与精确文件和查询区间指纹绑定的 owner 声明；不能证明账户覆盖完整，也不能补足逐项结算、当前资金、当前持仓或交易授权。',
  citicBatchCoverageBoundary:
    '观察到事件的月份不能证明导出查询区间或月份覆盖完整。仍需逐份复核查询区间、逐项结算或资金流水、当前资金与持仓快照，以及账户绑定。',
  citicCanonicalLineageTitle: 'Canonical 来源链',
  citicCanonicalLineageExact: '事件身份已精确保留',
  citicCanonicalLineagePartial: '来源链不完整；需要复核',
  citicCanonicalLineageUnavailable: '来源链暂不可用',
  citicCanonicalLineageSummary: (
    matched: number,
    source: number,
    exactIdentity: number,
    brokerIdentity: number,
    sourceBrokerIdentity: number,
    canonicalUnmatched: number,
  ) =>
    `来源事件语义匹配 ${matched} / ${source} · 精确保留事件身份 ${exactIdentity} · 保留券商委托身份 ${brokerIdentity} / ${sourceBrokerIdentity} · 此批次之外的可比 canonical 事件 ${canonicalUnmatched}`,
  citicCanonicalLineageObservedTypes: (
    sourceTypes: string,
    canonicalTypes: string,
  ) => `来源事件类型：${sourceTypes} · Canonical 事件类型：${canonicalTypes}`,
  citicCanonicalLineageMismatchTypes: (
    matchedTypes: string,
    sourceUnmatchedTypes: string,
    canonicalUnmatchedTypes: string,
  ) =>
    `已匹配类型：${matchedTypes} · 来源未匹配类型：${sourceUnmatchedTypes} · 此批次之外的 canonical 类型：${canonicalUnmatchedTypes}`,
  citicCanonicalLineageIdentityPresence: (
    sourceIdentityCount: number,
    canonicalIdentityCount: number,
  ) =>
    `含券商委托身份：来源 ${sourceIdentityCount} · canonical ${canonicalIdentityCount}`,
  citicCanonicalLineageBoundary:
    '仅做只读运行时比对。财务语义相似但事件身份未保留，不构成 canonical 来源证明，也不能把这批 XLS 提升为 Account Truth。',
  citicConfiguredSource: (index: number) => `已配置来源 ${index}`,
  citicLocalNameMonthHint: (month: string) => `本地文件名月份提示：${month}`,
  citicLocalNameMonthHintBoundary:
    '仅用于辨认来源；不会自动填写，也不能证明券商查询区间。',
  citicConfiguredSourceUnidentified:
    '这一目录来源没有唯一的 YYYYMM 文件名标记。记录或拒绝前，请在浏览器中重新选择这份精确文件。',
  citicNoFile: '请先选择一份或多份中信 .xls 文件。',
  citicWrongFile: '请选择从中信“历史成交”导出的旧版 .xls 文件。',
  citicFileTooLarge: '所选文件超过 10 MB 预览上限。',
  citicTooManyFiles: '每个预检批次最多选择 24 个文件。',
  citicReadFailed: '无法读取所选本地文件。',
  citicPreviewFailed: '中信 XLS 预览失败',
  citicPreviewComplete: '只读批量预览完成',
  citicSelectedFiles: (count: number) => `已选择 ${count} 个文件`,
  citicPreviewProgress: (completed: number, total: number) =>
    `正在检查第 ${Math.min(completed + 1, total)} / ${total} 个文件`,
  citicFiles: '文件',
  citicFailedFileCount: (count: number) => `${count} 个文件预检失败`,
  citicDuplicateFile: '重复文件——不计入汇总',
  citicFilePreviewComplete: '已检查',
  citicFilePreviewFailed: '预检失败',
  citicRecognizedEvents: '识别事件',
  citicRecognizedNonFinancialActivities: '非资金活动',
  citicNonFinancialActivityNotice: (count: number) =>
    `已识别并隔离 ${count} 条指定交易类非资金活动，未生成券商事件。`,
  citicPrivacyBoundary:
    '仅做预览：不持久化证据、不联系券商，不修改账本、券商提交能力或资本授权。',
  citicPrivacyResponse:
    '响应只包含计数、校验问题和文件指纹；不包含账户、证券、金额和本地路径明细。',
  citicReviewFollowUp: '复核并记录待补证',
  citicRejectSource: '复核并拒绝',
  citicConfirmReview: '确认来源复核',
  citicConfirmFollowUpBody:
    '只记录文件指纹、校验摘要和缺失证据清单；解析事件仍不会进入账户事实。',
  citicQueryWindowStart: '券商查询起始日期',
  citicQueryWindowEnd: '券商查询结束日期',
  citicQueryWindowAttestation:
    '我已亲自核对：这一精确文件确实是使用上述起止日期从券商查询并导出的。',
  citicQueryWindowBoundary:
    '日期默认留空，系统不会从文件名或观察到的事件月份推断。该复核只证明这一来源的查询区间，不能证明账户覆盖完整。',
  citicSourceScopeAccountAlias: '本地账户别名',
  citicSourceScopeAccountIdentifier: '券商账户标识',
  citicSourceScopeAccountIdentifierBoundary:
    '仅在当前浏览器内散列；原始标识不会发送或保存。',
  citicSourceScopeAccountType: '账户类型代码',
  citicSourceScopeMarkets: '市场范围（逗号分隔代码）',
  citicSourceScopeAssets: '资产类别（逗号分隔代码）',
  citicSourceScopeAccountValueBand: '账户规模区间代码（例如 cny_0_20000）',
  citicSourceScopeAccountValueBandBoundary:
    '仅为查询范围元数据；不是当前余额、订单额度或资本授权。',
  citicSourceScopeBusinessTypes: '业务类型（逗号分隔代码）',
  citicSourceScopeNoOtherFiltersAttestation:
    '我确认这一精确导出没有使用其他券商查询筛选条件。',
  citicSourceScopeCompleteResultsAttestation:
    '我确认该文件包含上述券商查询返回的全部记录。',
  citicSourceScopeAttestation:
    '我确认上述账户、账户类型、市场、资产、账户规模区间和业务范围适用于这一精确导出。',
  citicSourceScopeBoundary:
    '该来源范围复核仍是证据不完整的旧版来源；不会创建账户事实、对账放行、执行权限或资本授权。',
  citicQueryWindowRequired:
    '请填写券商查询的起止日期，并明确勾选查询区间证明。',
  citicSourceScopeRequired:
    '请完整填写查询区间、账户绑定和声明范围，并勾选全部精确证明。',
  citicQueryWindowFailed: '来源已记录，但查询区间未能记录',
  citicSourceScopeFailed: '来源及查询区间已记录，但来源范围未能记录',
  citicQueryWindowSaved: '来源查询区间已记录',
  citicQueryWindowStillBlocked:
    '仅证明来源查询区间；账户事实与对账仍保持阻断。',
  citicSourceScopeSaved: '来源范围已记录',
  citicSourceScopeLabel: '已复核来源范围',
  citicSourceScopeRevokeFailed: '来源范围撤销已安全失败。',
  citicReviewQueryWindow: '复核来源查询区间',
  citicReviewSourceScope: '复核来源查询与范围',
  citicIntakeStillSaved: '脱敏来源复核仍已保存；请重新执行显式查询区间复核。',
  citicQueryWindowLabel: '已复核券商查询区间',
  citicQueryWindowActive: '来源复核有效',
  citicQueryWindowRevoked: '已撤销',
  citicQueryWindowRevoke: '撤销查询区间复核',
  citicQueryWindowRevokeConfirm: '确认撤销查询区间复核',
  citicQueryWindowRevokeBody:
    '为这一精确复核追加撤销记录。来源仍留在待补证队列，查询区间会重新变为未复核。',
  citicQueryWindowRevokeConfirmAction: '确认撤销',
  citicQueryWindowRevoking: '正在撤销…',
  citicQueryWindowRevokeFailed: '查询区间撤销已安全失败。',
  citicConfirmRejectBody:
    '拒绝这一精确文件指纹。拒绝为终态；内容变化后必须作为新证据重新预览。',
  citicConfirmAction: '确认复核',
  citicCancelAction: '取消',
  citicIntakeSaved: '已记录待补证来源',
  citicRejectionSaved: '已拒绝该来源',
  citicIntakeFailed: '来源复核未能记录',
  citicClearBatch: '清除本地批次',
  citicRetainedFileBoundary:
    '浏览器只在你记录、拒绝或清除该批次前保留原始 File 引用；每次请求结束都会清除 base64 内容。',
  citicDirectoryRetainedBoundary:
    '浏览器不保留 File 或路径；最终复核会重新扫描已配置目录，并且必须匹配同一完整 SHA-256 指纹。',
  citicIntakeHistory: '已持久化来源复核队列',
  citicNoIntakes: '还没有持久化的中信来源复核。',
  citicEvidenceBlocked: '证据仍不完整',
  citicEvidenceBlockedBody:
    '“历史成交”没有逐项列出全部结算费用，也不能证明当前现金和持仓；这些记录目前不能进入账户事实。',
  citicSoakBlocked: '不能计入券商只读 soak',
  citicSoakBlockedBody:
    '“历史成交”只是待补全的账户事实来源，不是版本化券商连接器快照；它不能启动或计入 20 个交易日只读 soak。',
  citicSoakRequiredEvidence: '进入 soak 前仍需的来源证据',
  citicSoakProhibited:
    '该评估不会注册连接器、记录 soak 证据、联系券商，也不会授予执行或资本权限。',
  citicInvalidRows: (count: number) =>
    `仍有 ${count} 个文件或行级问题；受影响记录没有被转换为证据。`,
  citicNextSteps: [
    '导出覆盖同一期间、逐项列出费用的交割单或资金流水。',
    '导出当前资金和持仓快照，用于对账。',
  ],
  citicNextStepTitle: '下一份安全证据',
  collectorTitle: '本地自动读取',
  collectorLoading: '正在检查本地 collector。',
  collectorUnavailable: '暂时无法读取 collector 状态。',
  collectorPath: '文件',
  collectorRun: '导入批次',
  collectorFallback: '手工上传仍作为 fallback；自动读取永远不会自动入账。',
  broker: '券商',
  karkinos: 'Karkinos',
  difference: '差异',
  suggestedAction: '建议动作',
  evidence: '证据',
  evidenceDetail: '证据详情',
  openEvidence: '查看证据详情',
  closeEvidence: '关闭证据详情',
  copyEvidence: (field: string) => `复制${field}`,
  copiedEvidence: (field: string) => `已复制${field}`,
  importRunIdentity: '导入批次',
  itemIdentity: '明细标识',
  evidenceReference: (index: number) => `证据引用 ${index}`,
  auditDecision: '记录审计处理',
  auditDecisionDetail:
    '这里只追加复核标签；物质性差异仍需新的持久化证据才能解除。',
  showAuditActions: '显示审计复核动作',
  latestReview: '最近复核',
  currentReview: '已绑定当前事实',
  staleReview: '复核已失效：对账事实已变化',
  reviewSaved: '复核已保存',
  reviewFailed: '复核保存失败',
  safety:
    '人工复核只是审计标签，不能清除仍存在的物质性差异，不会修改生产账本，也不会提交券商订单。',
  componentLabels: {
    cash: '现金',
    position: '持仓',
    fee: '费用',
    costBasis: '成本价',
  },
} as const;
