export const RESEARCH_TASK_COPY = {
  en: {
    kicker: 'Research boundary',
    title: 'Research tasks',
    detail:
      'Review saved evidence, then explicitly run a local deterministic analysis. Nothing starts in the background.',
    closedDetail:
      'This workspace stays idle until you open it. Nothing starts in the background.',
    open: 'Open research tasks',
    close: 'Collapse research workspace',
    openCompact: 'Open tasks',
    closeCompact: 'Collapse',
    queueKicker: 'Review queue',
    queueTitle: 'Research task queue',
    queueDetail:
      'Every task keeps its saved evidence and citations attached for review.',
    taskCount: (count: number) => `${count} task${count === 1 ? '' : 's'}`,
    newTask: 'Draft research task',
    closeDraft: 'Close task draft',
    formKicker: 'Human capture',
    formTitle: 'Record a research task',
    formDetail:
      'Define the question and choose which saved evidence to attach. Recording the task does not start an analysis.',
    loadingTitle: 'Loading frozen task evidence',
    loadErrorTitle: 'Research task evidence unavailable',
    emptyTitle: 'No frozen research task',
    emptyWorkflowLabel: 'Research review sequence',
    emptyWorkflow: [
      {
        title: 'Freeze context',
        detail: 'Bind only saved account and backtest facts.',
      },
      {
        title: 'Record the question',
        detail: 'A human drafts the task; no analysis starts.',
      },
      {
        title: 'Run explicitly',
        detail: 'Local deterministic analysis runs only on request.',
      },
      {
        title: 'Review the outcome',
        detail: 'A human decides whether the result may be recalled.',
      },
    ],
    successTitle: 'Research task recorded',
    noModel: 'No background AI',
    noAuthority: 'Advisory only',
    operator: 'Human operator',
    account: 'Account alias',
    taskTitle: 'Task title',
    question: 'Research question',
    includeBacktest: 'Bind saved backtest evidence',
    includeContribution: 'Bind current strategy outcome evidence',
    noContribution:
      'No exact current strategy is available for contribution capture.',
    noBacktest:
      'Run and save a backtest first to bind exact research evidence.',
    submit: 'Capture evidence and record task',
    submitting: 'Recording…',
    success: 'The task was recorded without starting model execution.',
    loading: 'Loading saved research tasks…',
    loadError: 'Saved research tasks could not be loaded.',
    empty: 'No human research task has been recorded yet.',
    evidence: 'Evidence',
    authoritative: 'Authoritative',
    blocked: 'Blocked',
    snapshot: 'Valuation snapshot',
    cutoff: 'Ledger cutoff',
    reviewNote: 'Human review note',
    accept: 'Accept context',
    revise: 'Request revision',
    closeWithout: 'Close without analysis',
    reviewing: 'Recording review…',
    acceptBlocked: 'Acceptance requires complete authoritative evidence.',
    persistedOnly: 'Saved facts only',
    analysisLoading: 'Loading saved local analyses…',
    analysisLoadError: 'Local analysis records could not be loaded.',
    runFixture: 'Run local deterministic analysis',
    runningFixture: 'Running local analysis…',
    fixtureOnly: 'Local deterministic analysis',
    noNetwork: 'No network or external model',
    analysisStatus: 'Analysis workflow',
    bindingStatus: 'Evidence binding',
    memoryStatus: 'Memory draft',
    auditValid: 'Audit replay valid',
    auditInvalid: 'Audit replay blocked',
    bindingValid: 'Exact context valid',
    bindingDrift: 'Evidence drift — output invalidated',
    memoryPending: 'Human review required; exact context only',
    memoryInvalid: 'Invalidated by evidence drift',
    report: 'Analysis report',
    artifacts: 'Artifacts',
    analysisReview: 'Human analysis review',
    analysisReviewBoundary:
      'This decision only controls research-memory recall. It cannot enter Decision or grant trading authority.',
    reviewer: 'Reviewer',
    analysisReviewNote: 'Analysis review note',
    acceptMemory: 'Accept as reviewed memory',
    requestAnalysisRevision: 'Request analysis revision',
    rejectAnalysis: 'Reject analysis output',
    recordingAnalysisReview: 'Recording analysis review…',
    analysisReviewLoadError: 'Analysis review could not be loaded.',
    analysisReviewRequired: 'A reviewer and note are required.',
    acceptAnalysisBlocked:
      'Acceptance requires a completed, exact, replay-valid analysis and memory artifact.',
    memoryRecallEligible: 'Eligible for reviewed research recall',
    memoryRecallIneligible: 'Not eligible for research recall',
    analysisReviewStatuses: {
      reviewed_memory: 'Reviewed memory',
      revision_requested: 'Revision requested',
      rejected: 'Rejected',
      invalidated_by_evidence_drift: 'Invalidated by evidence drift',
    },
    statuses: {
      awaiting_human_review: 'Awaiting human review',
      blocked_by_evidence: 'Blocked by evidence',
      context_accepted: 'Context accepted',
      context_revision_requested: 'Revision requested',
      closed_without_analysis: 'Closed without analysis',
    },
  },
  zh: {
    kicker: '研究边界',
    title: '研究任务',
    detail:
      '先复核已保存证据，再由人显式运行本地确定性分析；后台不会自行启动。',
    closedDetail: '显式打开前保持空闲；后台不会自行启动任何分析。',
    open: '打开研究任务',
    close: '收起研究工作区',
    openCompact: '打开任务',
    closeCompact: '收起',
    queueKicker: '复核队列',
    queueTitle: '研究任务队列',
    queueDetail: '每项任务都保留已保存证据与引用，供人工复核。',
    taskCount: (count: number) => `${count} 个任务`,
    newTask: '起草研究任务',
    closeDraft: '关闭任务草稿',
    formKicker: '人工采集',
    formTitle: '记录研究任务',
    formDetail: '定义问题，并选择需要附带的已保存证据；记录任务不会启动分析。',
    loadingTitle: '正在读取已冻结任务证据',
    loadErrorTitle: '研究任务证据不可用',
    emptyTitle: '暂无已冻结研究任务',
    emptyWorkflowLabel: '研究复核顺序',
    emptyWorkflow: [
      {
        title: '冻结上下文',
        detail: '仅绑定已保存的账户与回测事实。',
      },
      {
        title: '记录问题',
        detail: '由人起草任务，不会启动分析。',
      },
      {
        title: '显式运行',
        detail: '本地确定性分析只在人工请求后运行。',
      },
      {
        title: '人工复核',
        detail: '由人决定结果能否进入研究记忆。',
      },
    ],
    successTitle: '研究任务已记录',
    noModel: '无后台 AI',
    noAuthority: '仅供研究',
    operator: '人工操作人',
    account: '账户别名',
    taskTitle: '任务标题',
    question: '研究问题',
    includeBacktest: '绑定已保存回测证据',
    includeContribution: '绑定当前策略结果证据',
    noContribution: '当前没有可供精确选择的策略贡献证据。',
    noBacktest: '请先运行并保存回测，才能绑定对应研究证据。',
    submit: '冻结证据并记录任务',
    submitting: '记录中…',
    success: '任务已记录，未启动任何模型执行。',
    loading: '正在读取已保存研究任务…',
    loadError: '无法读取已保存研究任务。',
    empty: '尚未记录人工研究任务。',
    evidence: '证据',
    authoritative: '权威完整',
    blocked: '阻断',
    snapshot: '估值快照',
    cutoff: '账本截止',
    reviewNote: '人工复核备注',
    accept: '接受上下文',
    revise: '要求修订',
    closeWithout: '不分析并关闭',
    reviewing: '正在记录复核…',
    acceptBlocked: '只有完整、权威的证据上下文才可接受。',
    persistedOnly: '仅已保存事实',
    analysisLoading: '正在读取已保存的本地分析…',
    analysisLoadError: '无法读取本地分析记录。',
    runFixture: '运行本地确定性分析',
    runningFixture: '本地分析运行中…',
    fixtureOnly: '本地确定性分析',
    noNetwork: '无网络、无外部模型',
    analysisStatus: '分析流程',
    bindingStatus: '证据绑定',
    memoryStatus: '记忆草稿',
    auditValid: '审计回放有效',
    auditInvalid: '审计回放阻断',
    bindingValid: '精确上下文有效',
    bindingDrift: '证据漂移——产物已失效',
    memoryPending: '等待人工复核；仅对精确上下文有效',
    memoryInvalid: '已因证据漂移失效',
    report: '分析报告',
    artifacts: '产物',
    analysisReview: '人工分析复核',
    analysisReviewBoundary:
      '该决定只控制研究记忆的回忆资格，不能进入 Decision，也不授予任何交易权限。',
    reviewer: '复核人',
    analysisReviewNote: '分析复核备注',
    acceptMemory: '接受为已复核研究记忆',
    requestAnalysisRevision: '要求修订分析',
    rejectAnalysis: '驳回分析产物',
    recordingAnalysisReview: '正在记录分析复核…',
    analysisReviewLoadError: '无法读取分析复核记录。',
    analysisReviewRequired: '必须填写复核人和备注。',
    acceptAnalysisBlocked:
      '只有已完成、精确绑定、回放有效且包含 memory 的分析才能接受。',
    memoryRecallEligible: '可用于已复核研究回忆',
    memoryRecallIneligible: '不可用于研究回忆',
    analysisReviewStatuses: {
      reviewed_memory: '已复核研究记忆',
      revision_requested: '已要求修订',
      rejected: '已驳回',
      invalidated_by_evidence_drift: '已因证据漂移失效',
    },
    statuses: {
      awaiting_human_review: '等待人工复核',
      blocked_by_evidence: '证据阻断',
      context_accepted: '上下文已接受',
      context_revision_requested: '已要求修订',
      closed_without_analysis: '已关闭且未分析',
    },
  },
} as const;

export type ResearchTaskPanelCopy =
  (typeof RESEARCH_TASK_COPY)[keyof typeof RESEARCH_TASK_COPY];
