export const STRATEGY_HYPOTHESIS_COPY = {
  en: {
    kicker: 'AI strategy research',
    title: 'Evidence-bound hypothesis lab',
    detail:
      'A configured provider may propose and critique formulas. Karkinos validates the DSL and the canonical engine alone calculates after-cost results.',
    open: 'Open AI strategy research',
    close: 'Close',
    noAuthority: 'No trading authority',
    humanGated: 'Three human gates',
    savedBacktest: 'Saved backtest',
    dataset: 'Dataset snapshot',
    window: 'Frozen window',
    universe: 'Frozen universe',
    cost: 'Canonical cost model',
    accountBinding: 'Account facts',
    notApplicable: 'Not applicable — strategy-only research',
    question: 'Research question',
    operator: 'Human operator',
    account: 'Research account alias',
    exportConfirm:
      'I authorize sending only the displayed sanitized research evidence and frozen identifiers to the configured external model.',
    generate: 'Generate hypothesis drafts',
    generating: 'Calling configured model…',
    missingReport: 'Run and save a backtest first.',
    missingSnapshot:
      'The saved result has no complete dataset snapshot; hypothesis export is blocked.',
    missingReviewedCosts:
      'The saved result is not bound to a currently reviewed real-account fee and tax schedule.',
    missingAccount:
      'A complete current account snapshot matching this research capital is required.',
    drafts: 'Candidate hypotheses',
    valid: 'Locally validated',
    blocked: 'Blocked by Formula DSL',
    formula: 'Formula AST',
    parameters: 'Parameters',
    risk: 'Risk impact',
    limitations: 'Limitations',
    tests: 'Proposed deterministic tests',
    backtestConfirm:
      'I select this validated draft and authorize one local canonical research backtest.',
    runBacktest: 'Run canonical research backtest',
    runningBacktest: 'Running deterministic backtest…',
    result: 'Canonical after-cost result',
    totalReturn: 'Total return',
    drawdown: 'Max drawdown',
    commission: 'Commission',
    trades: 'Trades',
    critiqueConfirm:
      'I authorize sending this normalized draft and canonical backtest evidence for one external critique.',
    critique: 'Request evidence critique',
    critiquing: 'Calling configured model…',
    critiqueTitle: 'AI evidence critique',
    supported: 'Supported claims',
    contradicted: 'Contradicted claims',
    gaps: 'Evidence gaps',
    robustness: 'Recommended robustness tests',
    uncertainty: 'Uncertainty',
    finalReview: 'Human final review',
    reviewNote: 'Review note',
    accept: 'Keep for more research',
    revise: 'Needs revision',
    reject: 'Reject hypothesis',
    recordReview: 'Record human review',
    recordingReview: 'Recording…',
    reviewRecorded:
      'Human review recorded; no Decision or execution input was created.',
    externalError:
      'The research stage failed closed. No automatic retry was started; use a new human request to retry.',
    validationErrors: 'Validation blockers',
    identity: 'Evidence reference',
    providerEvidence: 'Model provenance',
    invalidated:
      'This historical research binding is no longer current. Evidence or audit drift blocks backtest and critique.',
    incomplete: 'The research stage is not complete',
  },
  zh: {
    kicker: 'AI 策略研究',
    title: '证据绑定的策略假设实验室',
    detail:
      '已配置模型只负责提出和批判公式；Formula DSL 由本地严格验证，成本后结果只由权威回测引擎计算。',
    open: '打开 AI 策略研究',
    close: '收起',
    noAuthority: '无交易权限',
    humanGated: '三次人工门禁',
    savedBacktest: '已保存回测',
    dataset: '数据集快照',
    window: '冻结区间',
    universe: '冻结股票池',
    cost: '权威成本模型',
    accountBinding: '账户事实',
    notApplicable: '不适用——仅策略研究',
    question: '研究问题',
    operator: '人工操作人',
    account: '研究账户别名',
    exportConfirm:
      '我授权仅将上方展示的脱敏研究证据与冻结标识发送给已配置外部模型。',
    generate: '生成策略假设草案',
    generating: '正在调用已配置模型…',
    missingReport: '请先运行并保存一条回测。',
    missingSnapshot:
      '已保存结果缺少完整 dataset snapshot，禁止外发和生成草案。',
    missingReviewedCosts: '已保存结果未绑定当前复核通过的真实账户费税规则。',
    missingAccount: '必须提供完整的当前账户快照，且研究本金不得超过账户权益。',
    drafts: '候选策略假设',
    valid: '本地验证通过',
    blocked: 'Formula DSL 已阻断',
    formula: '公式 AST',
    parameters: '参数',
    risk: '风险影响',
    limitations: '限制',
    tests: '建议的确定性测试',
    backtestConfirm: '我选择这条已验证草案，并授权运行一次本地权威研究回测。',
    runBacktest: '运行权威研究回测',
    runningBacktest: '正在运行确定性回测…',
    result: '权威成本后结果',
    totalReturn: '总收益',
    drawdown: '最大回撤',
    commission: '佣金',
    trades: '成交数',
    critiqueConfirm:
      '我授权将该规范化草案与权威回测证据发送给外部模型进行一次批判。',
    critique: '请求证据批判',
    critiquing: '正在调用已配置模型…',
    critiqueTitle: 'AI 证据批判',
    supported: '得到支持的主张',
    contradicted: '被证据反驳的主张',
    gaps: '证据缺口',
    robustness: '建议的稳健性测试',
    uncertainty: '不确定性',
    finalReview: '最终人工复核',
    reviewNote: '复核备注',
    accept: '保留并继续研究',
    revise: '需要修订',
    reject: '驳回假设',
    recordReview: '记录人工复核',
    recordingReview: '正在记录…',
    reviewRecorded: '人工复核已记录；未生成 Decision 或执行输入。',
    externalError:
      '研究阶段已 fail closed，系统不会自动重试；如需重试，请发起新的人工请求。',
    validationErrors: '验证阻断原因',
    identity: '证据标识',
    providerEvidence: '模型来源证据',
    invalidated: '该历史研究绑定已不再有效；证据或审计漂移已阻断回测与批判。',
    incomplete: '研究阶段尚未完整完成',
  },
} as const;

export type StrategyHypothesisCopy =
  (typeof STRATEGY_HYPOTHESIS_COPY)[keyof typeof STRATEGY_HYPOTHESIS_COPY];
