export type CiticBrokerSoakCandidate = {
  schema_version: 'karkinos.account_truth.citic_broker_soak_candidate.v1';
  status: 'blocked';
  assessment_fingerprint: string;
  source_contract_valid: boolean;
  recognized_event_count: number;
  blockers: string[];
  required_source_evidence: string[];
  operational_prerequisites: string[];
  eligible_for_broker_soak: false;
  connector_registered: false;
  provider_contacted: false;
  database_writes_performed: false;
  does_not_register_connector: true;
  does_not_record_soak_evidence: true;
  does_not_submit_broker_order: true;
  does_not_cancel_broker_order: true;
  authorizes_execution: false;
  changes_capital_authority: false;
};

export type CiticHistoryXlsPreview = {
  schema_version: string;
  source_type: 'citic_history_xls_preview';
  generated_at: string;
  file_fingerprint: string;
  row_count: number;
  valid_row_count: number;
  invalid_row_count: number;
  recognized_non_financial_activity_count: number;
  duplicate_row_count: number;
  validation_status: 'blocked';
  limitations: string[];
  errors: Array<{
    row_number: number | null;
    code: string;
    message: string;
  }>;
  total_event_count: number;
  source_preview_fingerprint: string;
  recordable_for_follow_up: boolean;
  required_evidence: string[];
  broker_soak_candidate: CiticBrokerSoakCandidate;
  events_included: false;
  evidence_persisted: false;
  does_not_mutate_production_ledger: true;
  does_not_contact_provider: true;
  does_not_enable_broker_submission: true;
  does_not_change_capital_authority: true;
};

export type CiticSourceReviewStatus = 'follow_up_required' | 'rejected';

export type CiticSourceQueryWindowReview = {
  review_id: string;
  schema_version: 'karkinos.account_truth.citic_source_query_window_review.v1';
  intake_id: string;
  file_fingerprint: string;
  source_preview_fingerprint: string;
  query_start_date: string;
  query_end_date: string;
  query_window_attested: true;
  decision: 'accepted' | 'revoked';
  effective_status: 'active' | 'revoked' | 'source_closed';
  supersedes_review_id: string | null;
  reviewer: string;
  review_fingerprint: string;
  created_at: string;
  reused: boolean;
  review_persisted: true;
  events_included: false;
  transaction_details_included: false;
  source_name_included: false;
  source_path_included: false;
  eligible_for_account_truth: false;
  eligible_for_reconciliation: false;
  does_not_mutate_broker_evidence: true;
  does_not_mutate_production_ledger: true;
  does_not_contact_provider: true;
  does_not_enable_broker_submission: true;
  does_not_change_capital_authority: true;
};

export type CiticSourceQueryWindowReviewCommand = {
  schema_version: 'karkinos.account_truth.citic_source_query_window_review_command.v1';
  status: 'recorded' | 'revoked';
  review: CiticSourceQueryWindowReview;
  query_window_review_write_performed: boolean;
  writes_only_query_window_review_store: true;
  events_persisted: false;
  does_not_mutate_source_intake: true;
  does_not_mutate_broker_evidence: true;
  does_not_mutate_production_ledger: true;
  does_not_reconcile_account: true;
  does_not_contact_provider: true;
  does_not_enable_broker_submission: true;
  does_not_change_capital_authority: true;
};

export type CiticSourceScopeReview = {
  review_id: string;
  schema_version:
    | 'karkinos.account_truth.citic_source_scope_review.v1'
    | 'karkinos.account_truth.citic_source_scope_review.v2';
  intake_id: string;
  file_fingerprint: string;
  source_preview_fingerprint: string;
  query_window_review_id: string;
  query_window_review_fingerprint: string;
  account_alias: string;
  account_reference_hash: string;
  account_type: string;
  market_scopes: string[];
  asset_classes: string[];
  account_value_band: string | null;
  business_types: string[];
  no_other_filters_attested: true;
  complete_returned_results_attested: true;
  source_scope_attested: true;
  decision: 'accepted' | 'revoked';
  effective_status:
    'active' | 'revoked' | 'source_closed' | 'query_window_superseded';
  supersedes_review_id: string | null;
  reviewer: string;
  review_fingerprint: string;
  created_at: string;
  reused: boolean;
  review_persisted: true;
  raw_account_identifier_included: false;
  events_included: false;
  transaction_details_included: false;
  source_name_included: false;
  source_path_included: false;
  eligible_for_account_truth: false;
  eligible_for_reconciliation: false;
  does_not_mutate_broker_evidence: true;
  does_not_mutate_production_ledger: true;
  does_not_contact_provider: true;
  does_not_enable_broker_submission: true;
  does_not_change_capital_authority: true;
  account_value_band_is_capital_authority: false;
};

export type CiticSourceScopeReviewCommand = {
  schema_version: 'karkinos.account_truth.citic_source_scope_review_command.v2';
  status: 'recorded' | 'revoked';
  review: CiticSourceScopeReview;
  source_scope_review_write_performed: boolean;
  writes_only_source_scope_review_store: true;
  raw_account_identifier_persisted: false;
  events_persisted: false;
  does_not_mutate_source_intake: true;
  does_not_mutate_query_window_review: true;
  does_not_mutate_broker_evidence: true;
  does_not_mutate_production_ledger: true;
  does_not_reconcile_account: true;
  does_not_contact_provider: true;
  does_not_enable_broker_submission: true;
  does_not_change_capital_authority: true;
  account_value_band_is_capital_authority: false;
};

export type CiticSourceIntake = {
  intake_id: string;
  schema_version: string;
  source_type: 'citic_history_xls_preview';
  file_fingerprint: string;
  source_preview_fingerprint: string;
  validation_status: 'blocked';
  row_count: number;
  valid_row_count: number;
  invalid_row_count: number;
  duplicate_row_count: number;
  recognized_event_count: number;
  recognized_non_financial_activity_count: number;
  error_codes: string[];
  required_evidence: string[];
  limitations: string[];
  recordable_for_follow_up: boolean;
  review_id: string;
  review_status: CiticSourceReviewStatus;
  reviewer: string;
  created_at: string;
  reviewed_at: string;
  reused: boolean;
  query_window_review: CiticSourceQueryWindowReview | null;
  source_scope_review: CiticSourceScopeReview | null;
  source_intake_persisted: true;
  events_persisted: false;
  eligible_for_account_truth: false;
  eligible_for_reconciliation: false;
  does_not_mutate_production_ledger: true;
  does_not_contact_provider: true;
  does_not_enable_broker_submission: true;
  does_not_change_capital_authority: true;
};

export type CiticHistoryXlsDirectoryStatus = {
  schema_version: 'karkinos.account_truth.citic_history_xls_directory.v1';
  enabled: boolean;
  state: 'configured' | 'disabled';
  max_files: number;
  max_file_bytes: number;
  max_total_bytes: number;
  configured_path_included: false;
  source_names_included: false;
  scan_requires_explicit_command: true;
  scan_persisted: false;
  events_persisted: false;
  eligible_for_account_truth: false;
  eligible_for_reconciliation: false;
  does_not_mutate_production_ledger: true;
  does_not_contact_provider: true;
  does_not_enable_broker_submission: true;
  does_not_change_capital_authority: true;
};

export type CiticHistoryEventTypeCount = {
  event_type: string;
  count: number;
};

export type CiticQueryWindowBatchAssessment = {
  schema_version: 'karkinos.account_truth.citic_query_window_batch_assessment.v1';
  status: 'blocked';
  integrity_status: 'not_available' | 'partial' | 'clear' | 'blocked';
  source_count: number;
  reviewed_source_count: number;
  unreviewed_source_count: number;
  invalid_review_count: number;
  all_current_sources_reviewed: boolean;
  declared_window_start_date: string | null;
  declared_window_end_date: string | null;
  covered_calendar_day_count: number;
  gap_calendar_day_count: number;
  overlap_calendar_day_count: number;
  declared_windows_contiguous: boolean;
  declared_windows_non_overlapping: boolean;
  blockers: string[];
  required_evidence: string[];
  complete_account_coverage_proven: false;
  account_scope_bound: false;
  settlement_components_complete: false;
  current_account_snapshots_present: false;
  reviewed_query_windows_included: boolean;
  events_included: false;
  transaction_details_included: false;
  private_fields_included: false;
  source_names_included: false;
  paths_included: false;
  assessment_persisted: false;
  database_writes_performed: false;
  provider_contacted: false;
  eligible_for_account_truth: false;
  eligible_for_reconciliation: false;
  authorizes_execution: false;
  changes_capital_authority: false;
  limitations: string[];
  assessment_fingerprint: string;
};

export type CiticSourceScopeBatchAssessment = {
  schema_version: 'karkinos.account_truth.citic_source_scope_batch_assessment.v2';
  status: 'blocked';
  integrity_status: 'not_available' | 'partial' | 'clear' | 'blocked';
  source_count: number;
  reviewed_source_count: number;
  unreviewed_source_count: number;
  invalid_query_window_review_count: number;
  invalid_scope_review_count: number;
  all_current_sources_reviewed: boolean;
  account_binding_consistent: boolean;
  declared_scope_consistent: boolean;
  account_scope_bound: boolean;
  declared_source_scope_complete: boolean;
  no_other_filters_attested: boolean;
  complete_returned_results_attested: boolean;
  declared_account_type: string | null;
  declared_market_scopes: string[];
  declared_asset_classes: string[];
  declared_account_value_band: string | null;
  declared_business_types: string[];
  blockers: string[];
  required_evidence: string[];
  complete_account_coverage_proven: false;
  settlement_components_complete: false;
  current_account_snapshots_present: false;
  account_reference_hashes_included: false;
  source_names_included: false;
  paths_included: false;
  events_included: false;
  transaction_details_included: false;
  assessment_persisted: false;
  database_writes_performed: false;
  provider_contacted: false;
  eligible_for_account_truth: false;
  eligible_for_reconciliation: false;
  authorizes_execution: false;
  changes_capital_authority: false;
  limitations: string[];
  assessment_fingerprint: string;
};

export type CiticHistoryXlsDirectoryScan = {
  schema_version: 'karkinos.account_truth.citic_history_xls_directory.v1';
  enabled: boolean;
  state: 'disabled' | 'empty' | 'ready' | 'partial' | 'blocked';
  candidate_file_count: number;
  preview_count: number;
  duplicate_file_count: number;
  unreadable_file_count: number;
  recognized_event_count: number;
  valid_row_count: number;
  invalid_row_count: number;
  scan_fingerprint: string;
  error_codes: string[];
  batch_assessment: {
    schema_version: 'karkinos.account_truth.citic_history_xls_batch_assessment.v1';
    status: 'blocked';
    integrity_status: 'not_available' | 'clear' | 'blocked';
    source_count: number;
    structurally_recordable_source_count: number;
    source_with_financial_events_count: number;
    source_without_financial_events_count: number;
    observed_event_count: number;
    unique_event_count: number;
    within_file_duplicate_row_count: number;
    cross_file_duplicate_event_count: number;
    conflicting_event_identity_count: number;
    invalid_row_count: number;
    invalid_event_time_count: number;
    recognized_non_financial_activity_count: number;
    observed_event_months: string[];
    observed_event_month_counts: Array<{
      month: string;
      event_count: number;
    }>;
    batch_fingerprint: string;
    blockers: string[];
    required_evidence: string[];
    limitations: string[];
    query_windows_reviewed: false;
    complete_coverage_proven: false;
    settlement_components_complete: false;
    current_account_snapshots_present: false;
    account_scope_bound: false;
    events_included: false;
    private_fields_included: false;
    source_names_included: false;
    paths_included: false;
    evidence_persisted: false;
    eligible_for_account_truth: false;
    eligible_for_reconciliation: false;
    does_not_mutate_production_ledger: true;
    does_not_contact_provider: true;
    does_not_enable_broker_submission: true;
    does_not_change_capital_authority: true;
  };
  canonical_lineage_assessment: {
    schema_version: 'karkinos.account_truth.citic_history_canonical_lineage_assessment.v1';
    status: 'blocked';
    event_lineage_status: 'not_available' | 'partial' | 'exact';
    match_contract_version: 'citic_history_financial_semantics.v1';
    source_batch_fingerprint: string;
    canonical_import_reference: string | null;
    canonical_import_file_fingerprint: string | null;
    source_supported_event_count: number;
    canonical_supported_event_count: number;
    semantically_matched_event_count: number;
    source_unmatched_event_count: number;
    canonical_unmatched_event_count: number;
    source_event_type_counts: CiticHistoryEventTypeCount[];
    canonical_event_type_counts: CiticHistoryEventTypeCount[];
    semantically_matched_event_type_counts: CiticHistoryEventTypeCount[];
    source_unmatched_event_type_counts: CiticHistoryEventTypeCount[];
    canonical_unmatched_event_type_counts: CiticHistoryEventTypeCount[];
    source_events_with_broker_order_identity_count: number;
    canonical_events_with_broker_order_identity_count: number;
    broker_order_identity_matched_event_count: number;
    exact_event_identity_matched_event_count: number;
    semantic_match_dimensions: string[];
    blockers: string[];
    required_evidence: string[];
    complete_account_coverage_proven: false;
    events_included: false;
    transaction_details_included: false;
    private_fields_included: false;
    source_names_included: false;
    paths_included: false;
    assessment_persisted: false;
    database_writes_performed: false;
    provider_contacted: false;
    eligible_for_account_truth: false;
    eligible_for_reconciliation: false;
    authorizes_execution: false;
    changes_capital_authority: false;
    limitations: string[];
    assessment_fingerprint: string;
  };
  query_window_review_summary: {
    reviewed_source_count: number;
    unreviewed_source_count: number;
    all_current_sources_reviewed: boolean;
    complete_coverage_proven: false;
    eligible_for_account_truth: false;
    eligible_for_reconciliation: false;
  };
  query_window_batch_assessment: CiticQueryWindowBatchAssessment;
  source_scope_review_summary: {
    reviewed_source_count: number;
    unreviewed_source_count: number;
    all_current_sources_reviewed: boolean;
    same_account_binding_proven: boolean;
    declared_scope_consistent: boolean;
    complete_account_coverage_proven: false;
    eligible_for_account_truth: false;
    eligible_for_reconciliation: false;
  };
  source_scope_batch_assessment: CiticSourceScopeBatchAssessment;
  items: Array<
    CiticHistoryXlsPreview & {
      local_name_month_hint: string | null;
      local_name_month_hint_is_evidence: false;
      query_window_inferred: false;
      source_intake: CiticSourceIntake | null;
    }
  >;
  max_files: number;
  max_file_bytes: number;
  max_total_bytes: number;
  configured_path_included: false;
  source_names_included: false;
  source_name_month_hints_included: boolean;
  source_name_month_hints_are_evidence: false;
  scan_persisted: false;
  events_persisted: false;
  eligible_for_account_truth: false;
  eligible_for_reconciliation: false;
  does_not_mutate_production_ledger: true;
  does_not_contact_provider: true;
  does_not_enable_broker_submission: true;
  does_not_change_capital_authority: true;
};

export type BrokerStatementCollectorStatus = {
  schema_version: string;
  enabled: boolean;
  state:
    | 'disabled'
    | 'waiting_for_file'
    | 'pending_stability'
    | 'imported'
    | 'unchanged'
    | 'blocked'
    | 'error';
  configured_path: string;
  source_name: string;
  file_present: boolean;
  poll_interval_seconds: number;
  stability_delay_seconds: number;
  max_file_bytes: number;
  last_observed_at: string | null;
  last_processed_at: string | null;
  last_success_at: string | null;
  file_fingerprint: string | null;
  import_run_id: string | null;
  validation_status: string | null;
  row_count: number | null;
  valid_row_count: number | null;
  invalid_row_count: number | null;
  duplicate_row_count: number | null;
  error_code: string | null;
  message: string;
  source_kind: 'local_file_readonly';
  does_not_mutate_production_ledger: true;
  does_not_contact_provider: true;
  does_not_change_execution_authority: true;
};
