import type { Locale } from '../../shared/locale';

export const settingsCopy = {
  en: {
    kicker: 'Settings',
    title: 'Control center',
    subtitle:
      'Manage saved defaults, review service status, and verify safety boundaries without changing trading authority.',
    dataStatus: 'Data status',
    dataStatusDetail:
      'Portfolio valuations follow the recorded quote state and refresh policy.',
    refreshActionDetail:
      'Starts a controlled quote refresh and records the result. It does not write ledger entries or submit orders.',
    refreshActionEvidence: 'Controlled refresh · recorded quote cache',
    reviewRefreshControls: 'Review controlled refresh',
    liveServices: 'Live services',
    liveServicesDetail:
      'Shows scheduled quote updates and service readiness; it does not change trading authority.',
    preferences: 'Preferences',
    preferencesDetail:
      'Theme and language are local browser preferences for this platform.',
    notifications: 'Notifications',
    notificationsDetail:
      'Notification readiness is shown here. Delivery credentials are managed by the runtime environment and cannot be edited on this page.',
    dataSafety: 'Data safety',
    dataSafetyDetail:
      'Trading authority, evidence requirements, and private-data ownership remain explicit.',
    loading: 'Loading settings state.',
    error: 'Failed to load settings state.',
    retry: 'Retry status',
    marketState: 'Market state',
    quoteState: 'Quote state',
    refreshPolicy: 'Refresh policy',
    valuationTime: 'Valuation time',
    noValuationTime: 'No valuation timestamp',
    cacheOnly: 'Cache only',
    cacheOnlyDetail:
      'Market refresh policy is cache-only. Valuation may use stored quotes.',
    cachedQuotes: 'Cached quotes',
    cachedQuotesDetail: 'Current valuation is based on cached market data.',
    valuationRequiresReview: 'Valuation requires review',
    valuationRequiresReviewDetail: (status: string) =>
      `Quote state is ${status}. Treat valuation and returns as unconfirmed until data is refreshed or reconciled.`,
    dataSource: 'Data source',
    dataSourceStatus: 'Data source status',
    currentProvider: 'Current provider',
    providerConfigured: 'Provider configured',
    providerSupportsFunds: 'Fund support',
    providerRequiresToken: 'Token required',
    metadataConfigured: 'Asset metadata',
    persistentCache: 'Local quote cache',
    lastSuccessfulSync: 'Last successful sync',
    providerNextAction: 'Next action',
    providerAkshare: 'AKShare',
    providerTushare: 'Tushare',
    selectDataSource: 'Select data source',
    providerTimeoutNotice: 'The configured quote source is timing out.',
    operationsRegister: 'Operations register',
    registerProvider: 'Quote source',
    registerPollInterval: 'Poll interval',
    registerTrackedAssets: 'Tracked assets',
    registerStrategy: 'Strategy',
    providerConfiguration: 'Quote source configuration',
    providerConfigurationDetail:
      'Data-source changes take effect only after you save them and do not alter execution behavior.',
    configurationEditor: 'Edit account and data settings',
    configurationEditorDetail:
      'Open only when changing account cost defaults or the saved quote source.',
    metadataReadiness: 'Metadata readiness',
    metadataReadinessDetail:
      'Asset names and quote symbols must have traceable identities before display.',
    dataSourceOperations: 'Data source operations',
    dataSourceOperationsDetail:
      'Review source capabilities, permission gaps, backup quote paths, and manual TuShare tasks.',
    providerCapabilityMatrix: 'Provider capability matrix',
    capabilityStockRealtime: 'Stock realtime',
    capabilityStockDaily: 'Stock daily',
    capabilityFundEstimate: 'Sina intraday fund estimate',
    capabilityPersistentCache: 'Local quote cache',
    tusharePermissions: 'TuShare permissions',
    fundFallback: 'Fund backup quote',
    eastmoneyFundEstimate: 'Sina intraday fund estimate',
    latestFallbackQuote: 'Latest backup quote',
    manualDailyTaskChecklist: 'Manual daily task checklist',
    taskTushareSignIn: 'TuShare sign-in',
    taskGuessMarketDirection: 'Guess market direction',
    taskCheckPoints: 'Check points and permissions',
    openExternal: 'Open',
    permissionBlocked: 'Permission blocked',
    permissionUnknown: 'Permission unknown',
    available: 'Available',
    assetMetadataMissing: 'Asset metadata is not configured',
    assetMetadataMissingDetail:
      'Complete missing asset names and quote symbols in locally saved metadata. Keep private runtime configuration local.',
    assetMetadataDetail:
      'Asset names and quote symbols come from saved metadata rather than temporary runtime state.',
    assetMetadataMissingCount: 'Missing metadata',
    assetMetadataSource: 'Metadata source',
    assetMetadataSourcePersisted: 'Saved register and watchlist',
    assetMetadataSourceLocal: 'Local saved configuration',
    assetMetadataSourceProvided: 'System-provided metadata',
    assetMetadataMissingSymbols: 'Assets missing metadata',
    assetMetadataSnippet: 'Suggested config snippet',
    assetMetadataSnippetDetail:
      'Use this payload as a reference for metadata backfill or manual metadata repair. Do not commit private runtime config.',
    assetMetadataComplete: 'Asset metadata configured',
    assetMetadataCompleteDetail:
      'Current holdings have traceable names and quote symbols.',
    requiresRestart: 'Restart required',
    hotSwitchAvailable:
      'Quote refresh uses the selected source immediately. Broader data-manager tasks may still use startup configuration.',
    yes: 'Yes',
    no: 'No',
    pollInterval: 'Poll interval',
    pollIntervalUnit: 'seconds',
    token: 'TuShare credential',
    credentialConfigured: 'Configured in the runtime environment',
    credentialMissing:
      'Missing; configure the runtime credential before switching',
    credentialNotRequired: 'Not required by the selected quote source',
    credentialEnvironmentDetail:
      'This page never accepts or displays credentials. Configure the runtime environment and restart Karkinos.',
    accountCostProfile: 'Account cost profile',
    accountCostProfileDetail:
      'Used only to prefill manual stock/ETF trade fees. It does not change backtest assumptions or submit orders.',
    stockCommissionRate: 'Stock commission rate',
    minimumCommission: 'Minimum commission',
    accountCostPreview: (rate: number, minimum: number) =>
      `Manual trade default: ${Number(rate * 10000).toFixed(2)} bp, minimum ¥${Number(
        minimum,
      ).toFixed(2)}`,
    saveAccountCosts: 'Save account costs',
    savingAccountCosts: 'Saving account costs',
    accountCostsSaved: 'Account costs saved',
    accountCostsSavedDetail:
      'New manual trades will prefill fees from this account profile.',
    accountCostsFailed: 'Failed to save account costs',
    saveDataSource: 'Save data settings',
    savingDataSource: 'Saving data settings',
    dataSourceSaved: 'Data settings saved',
    dataSourceFailed: 'Failed to save data settings',
    scheduler: 'Scheduler',
    schedulerRunning: 'Scheduler running',
    schedulerUnavailable: 'Scheduler unavailable',
    brokerInterface: 'Broker interface',
    brokerReady: 'Interface status available',
    brokerDegraded: 'Interface not running',
    runtimeBoundary: 'Runtime boundary',
    executionDefault: 'Execution default',
    manualConfirmation: 'Manual confirmation',
    manualConfirmationRequired: 'Manual confirmation required',
    noAutoTrading: 'No automatic trading',
    safetyRegister: 'Safety register',
    marketDataBoundary: 'Market data',
    timestampRequired: 'Timestamp required',
    adviceBoundary: 'Advice boundary',
    analysisOnly: 'Analysis only',
    privateDataBoundary: 'Private data',
    keepPrivate: 'Keep private',
    safetyManualConfirmation:
      'Any workflow approaching live execution remains manually confirmed by default.',
    backendSettings: 'Saved configuration',
    persistedSettingsDetail:
      'Non-secret account and data defaults are saved here. Credentials remain in the local runtime environment.',
    assetsTracked: (count: number) => `${count} tracked assets`,
    initialCash: 'Initial cash',
    strategy: 'Strategy',
    themeMocha: 'Mocha',
    themeLatte: 'Latte',
    themeSystem: 'System',
    languageZh: '中文',
    languageEn: 'English',
    localOnly: 'Local preference',
    notificationType: 'Notification type',
    notificationUnavailable: 'No notification channel configured',
    notificationStatus: 'Notification readiness',
    notificationConfigured: 'Configured through the runtime environment',
    notificationMissingCredential: 'Required environment values are missing',
    testNotification: 'Send test notification',
    testingNotification: 'Testing notification',
    notificationOk: 'Notification test sent',
    notificationFailed: 'Notification test failed',
    safetyCachedQuotes:
      'Cached quote labels mean the latest known price is stored locally and may not match the current market.',
    safetyNoAdvice:
      'Karkinos is a personal quant research and trading platform, not investment advice or execution guarantee.',
    safetyPrivateData:
      'Keep broker tokens, account exports, and real statements out of public repositories.',
    deferred: 'Deferred',
    deferredDetail:
      'AI research services, evidence collection rules, broker credentials, and notification delivery remain managed outside this page until reviewed controls are available.',
  },
  zh: {
    kicker: '设置',
    title: '控制中心',
    subtitle:
      '管理已保存的默认配置、检查服务状态并复核安全边界，不改变交易权限。',
    dataStatus: '数据状态',
    dataStatusDetail: '组合估值以已记录的行情状态和刷新策略为准。',
    refreshActionDetail:
      '主动刷新行情并记录结果；不会写入账本，也不会提交订单。',
    refreshActionEvidence: '受控刷新 · 已记录行情缓存',
    reviewRefreshControls: '查看受控刷新入口',
    liveServices: '服务状态',
    liveServicesDetail: '展示定时行情更新与服务就绪状态；不会改变交易权限。',
    preferences: '偏好设置',
    preferencesDetail: '主题和语言是当前浏览器的本地偏好。',
    notifications: '通知',
    notificationsDetail:
      '这里展示通知是否就绪；投递凭证由运行环境管理，不能在本页编辑。',
    dataSafety: '数据安全',
    dataSafetyDetail: '交易权限、证据要求和私有数据归属保持显式。',
    loading: '正在加载设置状态。',
    error: '设置状态加载失败。',
    retry: '重试状态',
    marketState: '市场状态',
    quoteState: '行情状态',
    refreshPolicy: '刷新策略',
    valuationTime: '估值时间',
    noValuationTime: '暂无估值时间',
    cacheOnly: '仅缓存',
    cacheOnlyDetail: '当前刷新策略为仅缓存，估值可能使用已存行情。',
    cachedQuotes: '缓存行情',
    cachedQuotesDetail: '当前估值基于缓存市场数据。',
    valuationRequiresReview: '估值需要复核',
    valuationRequiresReviewDetail: (status: string) =>
      `行情状态为${status}。在数据刷新或对账前，请将估值和收益视为未确认。`,
    dataSource: '数据源',
    dataSourceStatus: '数据源状态',
    currentProvider: '当前数据源',
    providerConfigured: '配置状态',
    providerSupportsFunds: '基金支持',
    providerRequiresToken: '需要凭证',
    metadataConfigured: '资产元数据',
    persistentCache: '本地行情缓存',
    lastSuccessfulSync: '最近成功同步',
    providerNextAction: '下一步',
    providerAkshare: 'AKShare',
    providerTushare: 'Tushare',
    selectDataSource: '选择数据源',
    providerTimeoutNotice: '当前行情源请求超时。',
    operationsRegister: '运营登记',
    registerProvider: '行情源',
    registerPollInterval: '轮询间隔',
    registerTrackedAssets: '跟踪资产',
    registerStrategy: '策略',
    providerConfiguration: '行情源配置',
    providerConfigurationDetail:
      '只有保存后才会应用数据源变更；不会改变交易执行行为。',
    configurationEditor: '编辑账户与数据设置',
    configurationEditorDetail: '仅在修改账户成本默认值或已保存行情源时展开。',
    metadataReadiness: '元数据就绪',
    metadataReadinessDetail: '展示前必须能追溯资产名称与行情代码的来源。',
    dataSourceOperations: '数据源运营',
    dataSourceOperationsDetail:
      '按需查看数据源能力、权限缺口、备用行情路径和 TuShare 手工任务。',
    providerCapabilityMatrix: '行情源能力矩阵',
    capabilityStockRealtime: '股票实时',
    capabilityStockDaily: '股票日线',
    capabilityFundEstimate: '新浪基金盘中估值',
    capabilityPersistentCache: '本地行情缓存',
    tusharePermissions: 'TuShare 权限',
    fundFallback: '基金备用行情',
    eastmoneyFundEstimate: '新浪基金盘中估值',
    latestFallbackQuote: '最近备用行情',
    manualDailyTaskChecklist: '每日手工任务清单',
    taskTushareSignIn: 'TuShare 签到',
    taskGuessMarketDirection: '猜涨跌',
    taskCheckPoints: '查看积分和权限',
    openExternal: '打开',
    permissionBlocked: '权限不足',
    permissionUnknown: '权限未知',
    available: '可用',
    assetMetadataMissing: '尚未配置资产元数据',
    assetMetadataMissingDetail:
      '在本地保存的元数据中补齐缺少的资产名称与行情代码；私有运行配置继续留在本机。',
    assetMetadataDetail:
      '资产名称与行情代码以已保存元数据为准，不根据临时运行状态推断。',
    assetMetadataMissingCount: '缺失元数据',
    assetMetadataSource: '元数据来源',
    assetMetadataSourcePersisted: '已保存登记与关注列表',
    assetMetadataSourceLocal: '本地已保存配置',
    assetMetadataSourceProvided: '系统补充的元数据',
    assetMetadataMissingSymbols: '缺少元数据的资产',
    assetMetadataSnippet: '建议配置片段',
    assetMetadataSnippetDetail:
      '可将此内容作为元数据补齐或手工修复参考。不要提交私有运行配置。',
    assetMetadataComplete: '资产元数据已配置',
    assetMetadataCompleteDetail: '当前持仓的资产名称与行情代码均可追溯。',
    requiresRestart: '需要重启',
    hotSwitchAvailable:
      '行情刷新会立即使用所选数据源；更广泛的数据管理任务可能仍使用启动时配置。',
    yes: '是',
    no: '否',
    pollInterval: '轮询间隔',
    pollIntervalUnit: '秒',
    token: 'TuShare 凭证',
    credentialConfigured: '已通过运行环境配置',
    credentialMissing: '尚未配置；切换前请先配置运行环境凭证',
    credentialNotRequired: '当前行情源不需要凭证',
    credentialEnvironmentDetail:
      '本页不接收或展示凭证；请配置运行环境后重启 Karkinos。',
    accountCostProfile: '账户成本配置',
    accountCostProfileDetail:
      '仅用于手工录入股票/ETF 交易时预填费用，不改变回测假设，也不会提交订单。',
    stockCommissionRate: '股票佣金率',
    minimumCommission: '最低佣金',
    accountCostPreview: (rate: number, minimum: number) =>
      `手工交易默认：万${Number(rate * 10000).toFixed(2)}，最低 ¥${Number(
        minimum,
      ).toFixed(2)}`,
    saveAccountCosts: '保存账户成本',
    savingAccountCosts: '保存中',
    accountCostsSaved: '账户成本已保存',
    accountCostsSavedDetail: '新的手工交易会按该账户成本预填费用。',
    accountCostsFailed: '账户成本保存失败',
    saveDataSource: '保存数据设置',
    savingDataSource: '保存中',
    dataSourceSaved: '数据设置已保存',
    dataSourceFailed: '数据设置保存失败',
    scheduler: '调度器',
    schedulerRunning: '调度器运行中',
    schedulerUnavailable: '调度器不可用',
    brokerInterface: '交易接口',
    brokerReady: '接口状态可用',
    brokerDegraded: '接口未运行',
    runtimeBoundary: '运行边界',
    executionDefault: '执行默认值',
    manualConfirmation: '人工确认',
    manualConfirmationRequired: '必须人工确认',
    noAutoTrading: '不自动交易',
    safetyRegister: '安全登记',
    marketDataBoundary: '市场数据',
    timestampRequired: '必须检查时间戳',
    adviceBoundary: '建议边界',
    analysisOnly: '仅作分析',
    privateDataBoundary: '私有数据',
    keepPrivate: '保持私密',
    safetyManualConfirmation: '任何接近实盘执行的工作流默认都必须人工确认。',
    backendSettings: '已保存配置',
    persistedSettingsDetail:
      '账户与数据的非敏感默认值保存在这里；凭证仍由本地运行环境管理。',
    assetsTracked: (count: number) => `${count} 个跟踪资产`,
    initialCash: '初始现金',
    strategy: '策略',
    themeMocha: 'Mocha',
    themeLatte: 'Latte',
    themeSystem: '跟随系统',
    languageZh: '中文',
    languageEn: 'English',
    localOnly: '本地偏好',
    notificationType: '通知类型',
    notificationUnavailable: '未配置通知通道',
    notificationStatus: '通知就绪状态',
    notificationConfigured: '已通过运行环境配置',
    notificationMissingCredential: '缺少必需的环境变量',
    testNotification: '发送测试通知',
    testingNotification: '测试中',
    notificationOk: '测试通知已发送',
    notificationFailed: '测试通知失败',
    safetyCachedQuotes:
      '缓存行情表示最新已知价格来自本地存储，可能不等于当前市场价格。',
    safetyNoAdvice:
      'Karkinos 是个人量化投研与交易平台，不构成投资建议或成交保证。',
    safetyPrivateData: '券商凭证、账户导出和真实对账单不应进入公开仓库。',
    deferred: '暂缓项',
    deferredDetail:
      'AI 研究服务、证据采集规则、券商凭证和通知投递，在受控界面通过评审前仍在本页之外管理。',
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type SettingsCopy = (typeof settingsCopy)[Locale];

declare module '../../shared/i18n/context' {
  interface ApplicationCopy {
    settings: SettingsCopy;
  }
}
