import type { Locale } from '../../shared/locale';
import { formatPublicCode } from '../../shared/public-labels';

export const decisionCopy = {
  en: {
    kicker: 'Decision',
    title: 'Decision platform',
    subtitle:
      'Review daily and intraday candidates with risk gates, strategy evidence, quote health, and manual-confirmation readiness.',
    loading: 'Loading decision platform.',
    error: 'Failed to load decision platform.',
    intradayLoadingDetail:
      'Intraday evidence is still loading. Saved daily facts remain available.',
    intradayErrorDetail:
      'Intraday evidence is unavailable. The daily decision remains visible; do not infer an intraday conclusion.',
    simulationReviewRunFailed:
      'The simulation review could not run. Try again; if the problem persists, review the service logs.',
    commandRegister: 'Decision evidence register',
    commandRegisterTitle: 'Today operating posture',
    commandRegisterDetail:
      'Aggregates daily and intraday candidate pools before any manual approval path.',
    workflowKicker: 'Decision workflow',
    workflowTitle: 'Evidence-first review order',
    workflowDetail:
      'Check data and account facts first, then review strategy opportunities, simulation evidence, and manual confirmation.',
    workflowLaneKicker: 'Channel details',
    workflowLaneTitle: 'Daily and intraday gate details',
    workflowLaneDetail:
      'The primary matrix shows the daily review order. Expand only to compare daily and intraday task evidence.',
    workflowCollapsedTitle: (count: number) =>
      `${count} candidates: channel details collapsed`,
    workflowCollapsedDetail:
      'Expand only when auditing differences between daily and intraday tasks.',
    expandWorkflow: 'Expand channel details',
    tradingPlanKicker: 'Daily trading plan',
    tradingPlanTitle: 'Manual-confirmation plan',
    tradingPlanDetail:
      'Previews evidence-linked order intents with costs and cash impact before any manual confirmation.',
    tradingPlanLoading: 'Loading daily trading plan.',
    tradingPlanError: 'Daily trading plan is unavailable.',
    tradingPlanManualConfirmationReady: 'Manual confirmation ready',
    tradingPlanAccountTruthBlocked: 'Account truth blocked',
    tradingPlanRiskBlocked: 'Risk blocked',
    tradingPlanDataUnavailable: 'Market data unavailable',
    tradingPlanCashShortfall: 'Cash shortfall',
    tradingPlanPortfolioBlocked: 'Portfolio constraints blocked',
    tradingPlanMarketBlocked: 'Market constraints blocked',
    tradingPlanNoManualAction: 'No manual action required',
    tradingPlanCounts: (
      candidates: number,
      orderIntents: number,
      blockers: number,
    ) =>
      `${candidates} candidates · ${orderIntents} order intent previews · ${blockers} blockers`,
    tradingPlanDefaultManual: 'Default: manual confirmation',
    tradingPlanBrokerDisabled: 'Broker bridge disabled',
    tradingPlanOrderIntentPreviews: 'Order intent previews',
    tradingPlanQuantity: 'Quantity',
    tradingPlanFee: 'Estimated fee',
    tradingPlanNetCash: 'Net cash impact',
    tradingPlanCashShortfallAmount: 'Cash shortfall',
    tradingPlanConstraintChecks: 'Constraint checks',
    tradingPlanPositionAfter: 'Position after',
    tradingPlanCostBasis: 'Cost basis',
    tradingPlanDoesNotSubmit: 'Does not submit broker orders',
    tradingPlanNoOrderIntents: 'No manual-confirmation order intents.',
    candidateActions: 'Candidate pool',
    manualConfirmations: 'Manual confirmations',
    riskBlocks: 'Risk blocks',
    auditCoverage: 'Audit coverage',
    marketData: 'Market data',
    executionDefault: 'Execution default',
    manualConfirmationRequired: 'Manual confirmation required',
    accountTruthGate: 'Account truth gate',
    accountTruth: 'Account truth',
    accountTruthScore: 'Account truth score',
    strategyAttributionGate: 'Strategy attribution gate',
    strategyAttribution: 'Strategy attribution',
    strategyAuditId: 'Audit id',
    strategyAttributionStatus: 'Attribution status',
    strategyContributionStatus: 'Contribution status',
    accountTruthUnresolved: (count: number) =>
      `${count} unresolved differences`,
    gateRequirementLabel: (code: string) => formatPublicCode(code, 'en'),
    workflowTaskLabel: (code: string) => formatPublicCode(code, 'en'),
    workflowActionLabel: (code: string) => formatPublicCode(code, 'en'),
    workflowOpenMarket: 'Open Market data',
    workflowOpenBacktest: 'Open Strategy Lab',
    workflowOpenRisk: 'Open Risk center',
    workflowOpenTrading: 'Open trading review',
    workflowOpenSurfaceLabel: (surface: string, task: string) =>
      `${surface}: ${task}`,
    nextActionKicker: 'Next action',
    nextActionRiskTitle: 'Run pre-trade risk gate first',
    nextActionRiskDetail: (candidates: number, manualReady: number) =>
      `${candidates} candidates await risk checks; ${manualReady} are currently ready for manual confirmation. Only passed candidates can proceed to manual confirmation or simulation review.`,
    nextActionDefaultTitle: (task: string) => `Resolve ${task} first`,
    nextActionDefaultDetail: (action: string) =>
      `Complete this action before reviewing the candidate pool: ${action}.`,
    nextActionCandidatePoolNote: 'Candidate pool is not an order list',
    nextActionManualReadyNote: 'Manual confirmations are ready for review',
    readyCount: (count: number) => `${count} ready`,
    blockedCount: (count: number) => `${count} blocked`,
    dailyLane: 'Daily lane',
    intradayLane: 'Intraday lane',
    decision: 'Decision',
    generatedAt: 'Generated',
    candidateCount: (count: number) =>
      `${count} candidate${count === 1 ? '' : 's'} in pool`,
    summaryCollapsedKicker: 'Status summary',
    summaryCollapsedTitle: (count: number) =>
      `${count} candidates: status details collapsed`,
    summaryCollapsedDetail:
      'Account, quote, portfolio, and lane detail tiles stay collapsed while the page has a large candidate pool.',
    expandSummary: 'Expand status details',
    candidateEvidenceCollapsedTitle: (count: number) =>
      `${count} candidate${count === 1 ? '' : 's'} summarized`,
    candidateEvidenceCollapsedDetail:
      'Evidence cards stay collapsed until you need an audit drill-down.',
    expandCandidateEvidence: 'Expand evidence',
    collapseCandidateEvidence: 'Collapse evidence',
    marketHealth: 'Market health',
    portfolio: 'Portfolio',
    portfolioEquity: 'Portfolio equity',
    quotesDetail: (live: number, stale: number) =>
      `${live} live quotes · ${stale} stale quotes`,
    positionCount: (count: number) => `${count} positions`,
    riskBlocked: 'Risk blocked',
    manualReady: 'Manual ready',
    excludedDaily: 'Daily-only excluded',
    noActionReasons: 'No-action reasons',
    noActionUnavailable: 'No reason supplied',
    noDetail: 'No detail supplied.',
    candidateEvidenceChain: 'Candidate evidence chain',
    strategySource: 'Strategy source',
    marketDataStatus: 'Market data status',
    riskStatus: 'Risk status',
    researchEvidence: 'Research evidence',
    paperShadowEvidence: 'Simulation evidence',
    costImpact: 'Cost impact',
    certainty: 'Action certainty',
    certaintyPass: 'Ready for manual review',
    certaintyReviewRequired: 'Review data or account facts first',
    certaintyBlocked: 'Blocked until evidence is repaired',
    uncertainty: 'Uncertainty',
    noUncertainty: 'No additional uncertainty recorded',
    costImpactSummary: (commission: string, slippage: string) =>
      `Commission ${commission} · slippage ${slippage}`,
    riskGate: 'Risk gate',
    manual: 'Manual',
    afterCostOos: 'After-cost/OOS',
    dataFreshness: 'Data freshness',
    journal: 'Journal',
    strategy: 'Strategy',
    targetWeight: 'Target weight',
    price: 'Price',
    riskDecision: 'Risk decision',
    none: 'None',
    openTradingApprovals: 'Open trading review',
    openBacktestEvidence: 'Open Backtest evidence',
    openHoldingDetail: 'Open holding detail',
    openAttributionReview: 'Open attribution review',
    signalQueue: 'Signal action queue',
    signalQueueTitle: 'Signals, action tasks, and manual-order handoff',
    signalQueueDetail:
      'Review persisted signal actions and prepare manual orders only after risk gates mark an action ready for confirmation.',
    signalQueueCollapsedTitle: (count: number) =>
      `${count} signal actions summarized`,
    signalQueueCollapsedDetail:
      'Signal cards stay collapsed until the risk gate produces manual-ready items.',
    expandSignalQueue: 'Expand signal actions',
    signalJournal: 'Signal journal',
    noSignalActions: 'No pending signal actions are available.',
    noSignalJournal: 'No signal audit journal entries are available.',
    orderQuantity: 'Order quantity',
    prepareManualOrder: 'Prepare manual order',
  },
  zh: {
    kicker: '决策',
    title: '决策平台',
    subtitle:
      '查看日级与盘中候选动作、风控闸门、策略证据、行情健康和人工确认状态。',
    loading: '正在加载决策平台。',
    error: '决策平台加载失败。',
    intradayLoadingDetail: '盘中证据仍在加载；当前先展示已保存的日级事实。',
    intradayErrorDetail:
      '盘中证据暂不可用；日级决策继续展示，但不要据此推断盘中结论。',
    simulationReviewRunFailed:
      '模拟复核未能运行，请重试；若仍然失败，请检查服务日志。',
    commandRegister: '决策证据登记',
    commandRegisterTitle: '今日运行姿态',
    commandRegisterDetail: '汇总日级与盘中候选池，先于任何人工审批路径。',
    workflowKicker: '决策工作流',
    workflowTitle: '证据优先的复核顺序',
    workflowDetail:
      '先检查数据和账户事实，再查看策略机会、模拟证据与人工确认。',
    workflowLaneKicker: '通道明细',
    workflowLaneTitle: '日级与盘中闸门明细',
    workflowLaneDetail:
      '首屏矩阵给出日级复核顺序；仅在核对日级与盘中任务证据差异时展开。',
    workflowCollapsedTitle: (count: number) =>
      `${count} 个候选：通道明细已收起`,
    workflowCollapsedDetail: '仅在审计日级与盘中任务差异时展开。',
    expandWorkflow: '展开通道明细',
    tradingPlanKicker: '今日交易计划',
    tradingPlanTitle: '人工确认计划',
    tradingPlanDetail:
      '在任何人工确认前，预览带证据引用的订单意图、费用和现金影响。',
    tradingPlanLoading: '正在加载今日交易计划。',
    tradingPlanError: '今日交易计划暂不可用。',
    tradingPlanManualConfirmationReady: '待人工确认',
    tradingPlanAccountTruthBlocked: '账户事实阻断',
    tradingPlanRiskBlocked: '风控阻断',
    tradingPlanDataUnavailable: '行情数据不可用',
    tradingPlanCashShortfall: '现金不足',
    tradingPlanPortfolioBlocked: '组合约束阻断',
    tradingPlanMarketBlocked: '市场约束阻断',
    tradingPlanNoManualAction: '今日无需手动操作',
    tradingPlanCounts: (
      candidates: number,
      orderIntents: number,
      blockers: number,
    ) =>
      `${candidates} 个候选 · ${orderIntents} 个订单意图预览 · ${blockers} 个阻断`,
    tradingPlanDefaultManual: '默认：人工确认',
    tradingPlanBrokerDisabled: '券商桥接关闭',
    tradingPlanOrderIntentPreviews: '订单意图预览',
    tradingPlanQuantity: '数量',
    tradingPlanFee: '预计费用',
    tradingPlanNetCash: '现金影响',
    tradingPlanCashShortfallAmount: '现金缺口',
    tradingPlanConstraintChecks: '约束检查',
    tradingPlanPositionAfter: '计划后持仓',
    tradingPlanCostBasis: '成本口径',
    tradingPlanDoesNotSubmit: '不会提交券商订单',
    tradingPlanNoOrderIntents: '暂无可人工确认的订单意图。',
    candidateActions: '候选池',
    manualConfirmations: '人工确认',
    riskBlocks: '风控阻断',
    auditCoverage: '审计覆盖',
    marketData: '市场数据',
    executionDefault: '执行默认值',
    manualConfirmationRequired: '必须人工确认',
    accountTruthGate: '账户事实闸门',
    accountTruth: '账户事实',
    accountTruthScore: '账户事实分',
    strategyAttributionGate: '策略归因闸门',
    strategyAttribution: '策略归因',
    strategyAuditId: '审计 ID',
    strategyAttributionStatus: '归因状态',
    strategyContributionStatus: '贡献状态',
    accountTruthUnresolved: (count: number) => `${count} 个未解决差异`,
    gateRequirementLabel: (code: string) => formatPublicCode(code, 'zh'),
    workflowTaskLabel: (code: string) => formatPublicCode(code, 'zh'),
    workflowActionLabel: (code: string) => formatPublicCode(code, 'zh'),
    workflowOpenMarket: '打开行情中心',
    workflowOpenBacktest: '打开回测实验室',
    workflowOpenRisk: '打开风控中心',
    workflowOpenTrading: '打开交易复核',
    workflowOpenSurfaceLabel: (surface: string, task: string) =>
      `${surface}：${task}`,
    nextActionKicker: '下一步',
    nextActionRiskTitle: '先运行下单前风控',
    nextActionRiskDetail: (candidates: number, manualReady: number) =>
      `${candidates} 个候选等待风控检查，当前 ${manualReady} 个可人工确认。通过风控后才可进入人工确认或模拟复核。`,
    nextActionDefaultTitle: (task: string) => `先处理${task}`,
    nextActionDefaultDetail: (action: string) =>
      `先完成这个动作，再查看候选池：${action}。`,
    nextActionCandidatePoolNote: '候选池不是待下单清单',
    nextActionManualReadyNote: '人工确认已可复核',
    readyCount: (count: number) => `${count} 个就绪`,
    blockedCount: (count: number) => `${count} 个阻断`,
    dailyLane: '日级通道',
    intradayLane: '盘中通道',
    decision: '决策',
    generatedAt: '生成时间',
    candidateCount: (count: number) => `${count} 个候选`,
    summaryCollapsedKicker: '状态摘要',
    summaryCollapsedTitle: (count: number) => `${count} 个候选：状态明细已收起`,
    summaryCollapsedDetail:
      '账户、行情、组合和通道明细默认收起；候选池较大时优先处理下一步。',
    expandSummary: '展开状态明细',
    candidateEvidenceCollapsedTitle: (count: number) => `${count} 个候选已汇总`,
    candidateEvidenceCollapsedDetail:
      '候选证据默认收起；只有需要审计下钻时再展开。',
    expandCandidateEvidence: '展开证据明细',
    collapseCandidateEvidence: '收起证据明细',
    marketHealth: '行情健康',
    portfolio: '组合',
    portfolioEquity: '组合权益',
    quotesDetail: (live: number, stale: number) =>
      `${live} 条实时行情 · ${stale} 条陈旧行情`,
    positionCount: (count: number) => `${count} 个持仓`,
    riskBlocked: '风控拦截',
    manualReady: '待人工确认',
    excludedDaily: '排除日级动作',
    noActionReasons: '不行动原因',
    noActionUnavailable: '未提供原因',
    noDetail: '暂无详情。',
    candidateEvidenceChain: '候选动作证据链',
    strategySource: '策略来源',
    marketDataStatus: '行情状态',
    riskStatus: '风控状态',
    researchEvidence: '研究证据',
    paperShadowEvidence: '模拟证据',
    costImpact: '成本影响',
    certainty: '操作确定性',
    certaintyPass: '可进入人工复核',
    certaintyReviewRequired: '需要先复核数据或账户事实',
    certaintyBlocked: '证据修复前阻断',
    uncertainty: '不确定性',
    noUncertainty: '暂无额外不确定性记录',
    costImpactSummary: (commission: string, slippage: string) =>
      `佣金 ${commission} · 滑点 ${slippage}`,
    riskGate: '风控闸门',
    manual: '人工确认',
    afterCostOos: '扣除成本后/样本外',
    dataFreshness: '行情新鲜度',
    journal: '审计日志',
    strategy: '策略',
    targetWeight: '目标仓位',
    price: '价格',
    riskDecision: '风控决策',
    none: '无',
    openTradingApprovals: '打开交易复核',
    openBacktestEvidence: '打开回测证据',
    openHoldingDetail: '打开持仓明细',
    openAttributionReview: '打开归因复核',
    signalQueue: '信号动作队列',
    signalQueueTitle: '信号、动作任务与人工订单交接',
    signalQueueDetail:
      '查看已落库的信号动作；只有风控闸门标记为可人工确认后，才允许手动准备订单。',
    signalQueueCollapsedTitle: (count: number) => `${count} 个信号动作已汇总`,
    signalQueueCollapsedDetail:
      '信号卡默认收起；只有风控闸门产出可人工确认项后再展开。',
    expandSignalQueue: '展开信号动作',
    signalJournal: '信号审计日志',
    noSignalActions: '当前没有待处理的信号动作。',
    noSignalJournal: '当前没有信号审计日志。',
    orderQuantity: '订单数量',
    prepareManualOrder: '准备人工订单',
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type DecisionCopy = (typeof decisionCopy)[Locale];

declare module '../../shared/i18n/context' {
  interface ApplicationCopy {
    decision: DecisionCopy;
  }
}
