export type DailyResearchOperationPreview = {
  schema_version: 'karkinos.decision.research_operation_preview.v1';
  status: 'available' | 'no_formula_condition' | 'unavailable';
  market_date: string | null;
  target_market_date: string | null;
  market_calendar_evidence_refs: string[];
  run_id: string | null;
  selection_id: string | null;
  selection_fingerprint: string | null;
  backup_artifact_fingerprint: string | null;
  research_winner_candidate_id: string | null;
  source_preview_fingerprint: string | null;
  dataset_snapshot_id: string | null;
  formula_fingerprint: string | null;
  research_window_end_date: string | null;
  signal_observed_at: string | null;
  execution_timing: 'next_verified_market_session';
  allocation_slots: number | null;
  canonical_target_weight: number | null;
  operations: Array<{
    symbol: string;
    signal_date: string;
    signal_type: 'entry' | 'exit';
    operation: 'buy_candidate' | 'exit_if_held_candidate';
    target_weight: number;
    account_position_status: 'not_evaluated';
    next_session_only: true;
    research_only: true;
    executable: false;
  }>;
  blockers: string[];
  account_qualification_status: 'not_evaluated';
  account_positions_evaluated: false;
  provider_contacted: false;
  database_writes_performed: false;
  read_only: true;
  research_only: true;
  executable: false;
  authorizes_order_creation: false;
  authorizes_execution: false;
  authority_effect: 'none';
  evidence_fingerprint: string;
};
