import type { Locale } from '../../shared/locale';

export const portfolioCopy = {
  en: {
    kicker: 'Portfolio',
    title: 'Holdings & allocation',
    subtitle:
      'Review current holdings and evidence first, then allocation structure and strategy attribution.',
    positionsLoading: 'Loading positions.',
    positionsError: 'Failed to load positions.',
    positionsEmpty: 'No holdings yet. Add trades from Activity first.',
    filterEmpty: 'No holdings match the current filters.',
    currentHoldingsCount: (count: number) => `${count} open holdings`,
    filteredHoldingsCount: (count: number) => `${count} shown`,
    summary: {
      ariaLabel: 'Portfolio account summary',
      loading: 'Loading portfolio summary',
      loadingDetail:
        'Loading the latest saved account valuation and activity. Market data is not refreshed automatically.',
      error: 'Portfolio summary unavailable',
      errorDetail:
        'Current holdings may still load separately. Summary metrics remain unavailable until the saved account view can be read.',
      missing: 'Portfolio summary not available',
      missingDetail:
        'No account summary has been saved. The interface will not calculate account totals from the holdings table.',
      totalEquity: 'Total equity',
      totalEquityDetail: 'Latest saved account value',
      cash: 'Cash',
      cashDetail: 'Available account cash',
      openHoldings: 'Open holdings',
      openHoldingsDetail: 'Current non-zero holdings',
      realizedPnl: 'Realized PnL',
      realizedPnlDetail: 'Cumulative realized result',
    },
    currentHoldings: {
      title: 'Current holdings',
      detail:
        'Current account positions. Open a row for cost, quantity, quote source, and transaction evidence.',
    },
    analysis: {
      title: 'Allocation & attribution',
      detail:
        'Switch the analysis below without changing the current-holdings scope above.',
    },
    evidenceReview: {
      title: 'Evidence review — not current holdings',
      detail:
        'These facts are incomplete, pending settlement, or require reconciliation. They stay outside current holdings until reviewed.',
      count: (count: number) => `${count} to review`,
    },
    sidebarLoading: 'Loading allocation and performance breakdown.',
    sidebarError: 'Failed to load allocation or performance breakdown.',
    sidebarEmpty: 'No allocation view is available yet.',
    toolbar: {
      view: 'View',
      helper: 'Filter and sort current holdings.',
      search: 'Search',
      searchPlaceholder: 'Filter by symbol',
      assetClass: 'Asset Class',
      allAssetClasses: 'All asset classes',
      pnlFocus: 'PnL Focus',
      allHoldings: 'All holdings',
      winnersOnly: 'Winners only',
      losersOnly: 'Losers only',
      quoteFilter: 'Quote state',
      allQuoteStates: 'All quote states',
      healthyQuotes: 'Normal quotes',
      reviewQuotes: 'Stale or estimated',
      evidenceFilter: 'Reconciliation',
      allEvidenceStates: 'All evidence states',
      evidenceReviewOnly: 'Issues only',
      evidenceClearOnly: 'No issues',
      sortBy: 'Sort by',
      showMoreFilters: 'More filters',
      hideMoreFilters: 'Hide filters',
      activeFilters: (count: number) =>
        `${count} active filter${count === 1 ? '' : 's'}`,
      sortMarketValue: 'Market value',
      sortWeight: 'Portfolio weight',
      sortTodayPnl: 'Today PnL',
      sortUnrealizedPnl: 'Unrealized PnL',
      sortRealizedPnl: 'Realized PnL',
    },
    table: {
      symbol: 'Symbol',
      name: 'Name',
      assetClass: 'Asset Class',
      quantity: 'Quantity',
      availFrozen: 'Avail/Frozen',
      avgCost: 'Avg Cost',
      latestPrice: 'Quote Price',
      todayChange: 'Today PnL',
      cachedQuoteNotice: 'Cached quotes · positions valued from cached quotes',
      cachedQuoteAt: (time: string) => `Cached ${time}`,
      marketValue: 'Market Value',
      weight: 'Weight',
      unrealized: 'Unrealized',
      returnPct: 'Return',
      quoteState: 'Quote State',
      quoteAge: 'Quote Age',
      staleReason: 'Stale Reason',
      actions: 'Actions',
      refresh: 'Refresh',
      refreshing: 'Refreshing',
      trade: 'Trade',
      ledger: 'Ledger',
      realized: 'Realized PnL',
      closedOn: 'Closed on',
      detailsTitle: 'Holding Details',
    },
    detail: {
      kicker: 'Holding detail',
      title: (symbol: string) => `${symbol} Position`,
      subtitle:
        'Review cost, valuation, cached quote state, ledger trace, and related action paths for this holding.',
      backToPortfolio: 'Back to Portfolio',
      returnToPortfolio: 'Return to holdings list',
      notFoundTitle: 'Holding not found',
      notFoundDetail:
        'This symbol is not present in the current portfolio snapshot.',
      loading: 'Loading holding detail.',
      error: 'Failed to load holding detail.',
      summary: 'Summary',
      tabListLabel: 'Holding detail views',
      tabScrollHint: 'Scroll for more views →',
      tabPosition: 'Position',
      tabPnlCosts: 'P&L & Costs',
      tabTransactions: 'Transactions',
      tabEvidence: 'Evidence',
      tabReconciliation: 'Reconciliation',
      valuation: 'Valuation & Cost',
      resultsEvidence: 'Holding results & evidence',
      pnlCostsDetail:
        'Compare canonical local cost, labeled external or ledger-projected cost evidence, realized P&L, and fees without creating a second headline value.',
      closedHistoryOnly: 'Closed · history only',
      closedNoCurrentExposure:
        'This asset is closed and has no current portfolio exposure. Historical trades, fees, and realized PnL remain available for review.',
      evidenceIdentityMismatch:
        'The valuation snapshot or ledger scope changed during the request. Review the recorded basis before treating these figures as one result.',
      evidenceSummaryTitle: 'Holding evidence state',
      quoteStatus: 'Quote & Data State',
      marketEvidence: 'Market evidence',
      marketEvidenceDetail:
        'Persisted quote provenance and freshness for this instrument. Reading this view does not contact a provider.',
      ledgerTrace: 'Ledger Trace',
      productionLedgerOnly: 'Persisted account ledger only',
      riskExposure: 'Risk & Exposure',
      relatedActions: 'Related Actions',
      strategyAttributionBoundary: 'Strategy attribution boundary',
      strategyAttributionNoLinkedFills: 'No linked strategy fills yet',
      strategyAttributionDetail:
        'This holding does not yet have a complete strategy attribution evidence chain. Its P/L stays account-level until the missing signal, review, order, or fill reference is available.',
      strategyAttributionLinkedEvidence: 'Linked strategy evidence available',
      strategyAttributionLinkedDetail:
        'Strategy contribution remains review-only for this holding; manual trades and cash flows stay separate until attribution is reviewed.',
      strategyAttributionLinkedFills: (count: number) =>
        `${count} linked fills`,
      strategyAttributionLinkedFillsLabel: 'Linked fills',
      strategyAttributionStrategy: 'Strategy',
      strategyAttributionEvidenceRefs: 'Evidence refs',
      strategyAttributionEvidenceChain: 'Evidence chain',
      strategyAttributionEvidenceAuditRef: (value: string) =>
        `Audit ref ${value}`,
      strategyAttributionEvidenceTypeLabels: {
        signal: 'Signal evidence',
        action: 'Candidate action',
        risk: 'Risk check',
        review: 'Manual review',
        order: 'Order evidence',
        fill: 'Fill evidence',
        unknown: 'Evidence reference',
      },
      strategyAttributionEvidenceStatus: 'Evidence status',
      strategyAttributionContributionStatus: 'Contribution status',
      strategyAttributionReviewReadiness: 'Attribution review readiness',
      strategyAttributionReviewReady: 'Ready for review',
      strategyAttributionReviewIncomplete: 'Evidence still incomplete',
      strategyAttributionReviewBoundary:
        'Holding PnL is still not assigned to the strategy until review is complete.',
      strategyAttributionNextActionTitle: 'Next review step',
      strategyAttributionNextActionResearch:
        'Run or refresh the single-instrument strategy loop for this holding, then review signal, risk, simulation, and attribution evidence together.',
      strategyAttributionNextActionManualReview:
        'Review the strategy candidate in Decision before this holding can enter attribution review.',
      strategyAttributionNextActionExecution:
        'Check execution evidence before this holding can enter attribution review.',
      strategyAttributionNextActionGeneric:
        'Resolve the missing evidence before this holding can enter attribution review.',
      strategyAttributionOpenDecisionReview: 'Open Decision review',
      strategyAttributionOpenExecutionReview: 'Open execution review',
      strategyAttributionReadinessItems: {
        signalLinked: 'Strategy signal linked',
        signalMissing: 'Strategy signal missing',
        actionLinked: 'Candidate action linked',
        actionMissing: 'Candidate action missing',
        reviewLinked: 'Manual review linked',
        reviewMissing: 'Manual review missing',
        riskLinked: 'Risk check linked',
        riskMissing: 'Risk check missing',
        orderLinked: 'Order evidence linked',
        orderMissing: 'Order evidence missing',
        fillLinked: 'Fill evidence linked',
        fillMissing: 'Fill evidence missing',
        unknownLinked: 'Evidence linked',
        unknownMissing: 'Evidence missing',
      },
      displayName: 'Display Name',
      assetClass: 'Asset Class',
      quantity: 'Quantity',
      marketValue: 'Market Value',
      costBasis: 'Local cost basis',
      avgCost: 'Local moving average cost',
      brokerDisplayedCost: 'Broker displayed cost',
      brokerDisplayedCostBasis: 'Broker displayed cost basis',
      ledgerProjectedUnitCost: 'Ledger-projected unit cost',
      ledgerProjectedCostBasis: 'Ledger-projected remaining cost',
      costBasisDifference: 'Cost basis difference',
      costBasisMethod: 'Cost basis method',
      costBasisStatus: 'Cost basis evidence',
      costBasisReviewNeeded: 'Cost basis review needed',
      costBasisReviewDetail:
        'Broker displayed cost differs from Karkinos local moving average cost. Review Account Truth evidence before relying on cost-basis P/L.',
      costBasisMethods: {
        broker_remaining_cost: 'Broker remaining-position cost',
        moving_average_buy_cost: 'Local moving average buy cost',
        unavailable: 'No broker cost-basis evidence',
      },
      costBasisStatuses: {
        available: 'Broker-confirmed evidence',
        projected_from_ledger: 'Projected from local ledger',
        unavailable: 'No cost-basis evidence',
      },
      quotePrice: 'Quote Price',
      todayChange: 'Today PnL',
      todayChangePct: 'Today Return',
      baselinePrice: 'Daily Baseline',
      baselineSource: 'Baseline Source',
      baselineSources: {
        dailyClose: 'Local daily close',
        marketBarClose: 'Local OHLC close',
        previousClose: 'Reported previous close',
        previousQuote: 'Previous cached quote',
        intradayTradeCost: 'Intraday trade cost',
        fallbackClose: 'Fallback cached close',
        unavailable: 'Unavailable',
      },
      unrealizedPnl: 'Unrealized PnL',
      pnlPct: 'PnL %',
      realizedPnl: 'Realized PnL',
      commissionPaid: 'Commission Paid',
      availableFrozen: 'Available / Frozen',
      portfolioWeight: 'Portfolio Weight',
      lastTradeAt: 'Latest trade',
      valuationSnapshotId: 'Valuation snapshot',
      ledgerCutoffId: 'Ledger cutoff',
      evidenceState: 'Evidence state',
      nextManualStep: 'Next manual step',
      evidenceStates: {
        historicalClosed: 'Historical closed position',
        identityMismatch: 'Valuation scope mismatch',
        costBasisReview: 'Cost basis needs reconciliation',
        staleQuote: 'Quote is stale or estimated',
        complete: 'No current evidence issue',
      },
      evidenceNextSteps: {
        reviewHistory: 'Review the retained ledger and realized PnL.',
        reloadIdentity: 'Reload and confirm one snapshot and ledger cutoff.',
        reconcileCost: 'Review cost evidence in Account Truth.',
        reviewQuote: 'Review the recorded quote evidence on the Market page.',
        none: 'No additional manual action is required.',
      },
      chartBuyMarker: 'Buy',
      chartSellMarker: 'Sell',
      chartLocalCostLine: 'Local moving-average cost',
      chartEvidenceCostLine: 'Recorded evidence cost',
      positionFacts: 'Recorded position facts',
      positionFactsDetail:
        'Position quantity remains available from the account record even when saved price history is unavailable.',
      priceStructureMissing: 'Price evidence missing',
      priceStructureMissingDetail:
        'No saved price bars are available for this instrument. The position is still shown from the account record without inferring missing price history.',
      persistedPriceBoundary:
        'This read did not contact a provider or trigger a market-data refresh.',
      quoteTimestamp: 'Quote Timestamp',
      quoteSource: 'Quote Source',
      quoteAge: 'Quote Age',
      staleReason: 'Stale Reason',
      valuationTimestamp: 'Valuation Timestamp',
      refreshPolicy: 'Refresh Policy',
      marketOpen: 'Market Open',
      cacheOnly: 'Cache Only',
      marketClosed: 'Market Closed',
      cacheNotice: 'Cached quotes · valuation uses cached market data',
      quoteLive: 'Quote available',
      quoteStale: 'Cached quote',
      noLedger: 'No ledger trace is available for this symbol yet.',
      ledgerCount: (count: number) => `${count} matching entries`,
      entryType: 'Entry',
      amount: 'Amount',
      price: 'Price',
      note: 'Note',
      refreshQuote: 'Refresh this quote',
      quoteRefreshTitle: 'Refresh quote evidence',
      quoteRefreshDetail:
        'This controlled action may contact the configured market-data source and records an auditable result for this instrument.',
      quoteRefreshBoundary:
        'It does not rewrite the ledger, recalculate account facts in the UI, or grant trading authority',
      refreshingQuote: 'Refreshing quote…',
      refreshDone: 'Quote refresh request completed.',
      refreshFailed: 'Quote refresh failed. Check market data state.',
      actionStrategyResearch: 'Run strategy research for this holding',
      actionStrategyEvidence: 'Review strategy research evidence',
      actionMarket: 'Open Market research',
      actionTrading: 'Open trading review',
      actionActivity: 'Record activity',
      actionViewActivity: 'View historical activity',
      actionPortfolio: 'View all holdings',
      reconciliationTitle: 'Reconciliation evidence',
      reconciliationStateTitle: 'Valuation basis and cost alignment',
      reconciliationDetail:
        'Read-only alignment of the valuation snapshot, ledger cutoff, quote evidence, and cost-basis status. This view does not reconcile or mutate account facts.',
      actionAccountTruth: 'Open Account Truth review',
    },
    allocation: {
      title: 'Account composition',
      empty: 'No account assets match the current scope yet.',
      asset: 'Asset',
      valuationAmount: 'Valuation amount',
      navShare: 'Share of NAV',
      cashBalance: 'Cash balance',
    },
    allocationGroups: {
      title: 'Allocation Groups',
      empty: 'No grouped allocation available yet.',
    },
    liveBoard: {
      title: 'Holdings quote board',
      subtitle:
        'Track grouped holdings with quote price, intraday move, and since-buy return.',
      loading: 'Loading holdings quotes.',
      error: 'Failed to load holdings quotes.',
      empty:
        'No active holdings yet. Record the first trade to start tracking returns.',
      positionCount: (count: number) =>
        `${count} active holding${count === 1 ? '' : 's'}`,
      latestPrice: 'Quote price',
      todayMove: 'Today move',
      sinceBuyReturn: 'Since-buy return',
      updatedAt: 'Updated',
      baseline: 'Baseline',
      baselinePreviousClose: 'Previous close',
      baselineFallbackClose: 'Fallback close',
      baselineUnavailable: 'Daily baseline unavailable',
      quoteLive: 'Quote available',
      quoteStale: 'Cached quote',
      holdingDetailLink: (symbol: string) => `Holding Details: ${symbol}`,
      summaryOnly:
        'Instrument-level quote, cost, and K-line details are shown in the holdings list and detail pages below.',
    },
  },
  zh: {
    kicker: '组合',
    title: '持仓与配置',
    subtitle: '先核对当前持仓与证据，再查看配置结构和策略归因。',
    positionsLoading: '正在加载持仓明细。',
    positionsError: '持仓明细加载失败。',
    positionsEmpty: '当前还没有持仓，先去 Activity 录入交易。',
    filterEmpty: '当前筛选条件下没有匹配的持仓。',
    currentHoldingsCount: (count: number) => `当前持仓 ${count} 项`,
    filteredHoldingsCount: (count: number) => `筛选后展示 ${count} 项`,
    summary: {
      ariaLabel: '组合账户摘要',
      loading: '正在加载组合摘要',
      loadingDetail: '正在读取最近保存的账户估值与交易记录；不会自动刷新行情。',
      error: '组合摘要暂不可用',
      errorDetail:
        '当前持仓可能仍可单独读取；恢复已保存账户视图前，摘要指标保持不可用。',
      missing: '尚无组合摘要',
      missingDetail: '尚未保存账户汇总；页面不会用持仓表自行拼算总资产。',
      totalEquity: '总权益',
      totalEquityDetail: '最近保存的账户估值',
      cash: '现金',
      cashDetail: '可用账户现金',
      openHoldings: '当前持仓',
      openHoldingsDetail: '当前非零持仓',
      realizedPnl: '已实现盈亏',
      realizedPnlDetail: '累计已实现结果',
    },
    currentHoldings: {
      title: '当前持仓',
      detail: '当前账户持仓。打开任一标的查看成本、数量、行情来源和流水证据。',
    },
    analysis: {
      title: '配置与归因',
      detail: '切换下方分析视角，不改变上方当前持仓的筛选范围。',
    },
    evidenceReview: {
      title: '证据待复核（不属于当前持仓）',
      detail:
        '这些事实处于证据不完整、待交收或待对账状态；完成复核前不会冒充当前持仓。',
      count: (count: number) => `${count} 项待复核`,
    },
    sidebarLoading: '正在加载配置和收益拆解。',
    sidebarError: '配置或收益拆解加载失败。',
    sidebarEmpty: '还没有可用的配置视图。',
    toolbar: {
      view: '视角',
      helper: '筛选并排序当前持仓。',
      search: '搜索',
      searchPlaceholder: '按代码过滤',
      assetClass: '资产类别',
      allAssetClasses: '全部资产',
      pnlFocus: '收益筛选',
      allHoldings: '全部持仓',
      winnersOnly: '仅盈利',
      losersOnly: '仅亏损',
      quoteFilter: '行情状态',
      allQuoteStates: '全部行情状态',
      healthyQuotes: '行情正常',
      reviewQuotes: '陈旧或估算',
      evidenceFilter: '对账状态',
      allEvidenceStates: '全部证据状态',
      evidenceReviewOnly: '有对账问题',
      evidenceClearOnly: '无对账问题',
      sortBy: '排序',
      showMoreFilters: '更多筛选',
      hideMoreFilters: '收起筛选',
      activeFilters: (count: number) => `${count} 个筛选生效`,
      sortMarketValue: '按市值',
      sortWeight: '按当前权重',
      sortTodayPnl: '按今日盈亏',
      sortUnrealizedPnl: '按未实现盈亏',
      sortRealizedPnl: '按已实现盈亏',
    },
    table: {
      symbol: '代码',
      name: '名称',
      assetClass: '资产类别',
      quantity: '数量',
      availFrozen: '可用/冻结',
      avgCost: '成本价',
      latestPrice: '行情价',
      todayChange: '今日收益',
      cachedQuoteNotice: '行情缓存 · 持仓估值基于缓存行情',
      cachedQuoteAt: (time: string) => `缓存 ${time}`,
      marketValue: '市值',
      weight: '权重',
      unrealized: '浮盈亏',
      returnPct: '收益率',
      quoteState: '行情状态',
      quoteAge: '行情年龄',
      staleReason: '缓存原因',
      actions: '操作',
      refresh: '刷新',
      refreshing: '刷新中',
      trade: '交易',
      ledger: '流水',
      realized: '已实现盈亏',
      closedOn: '清仓日期',
      detailsTitle: '持仓明细',
    },
    detail: {
      kicker: '持仓详情',
      title: (symbol: string) => `${symbol} 持仓`,
      subtitle:
        '查看该标的的成本、估值、缓存行情状态、流水轨迹和相关操作入口。',
      backToPortfolio: '返回组合',
      returnToPortfolio: '返回持仓列表',
      notFoundTitle: '未找到持仓',
      notFoundDetail: '当前组合快照中没有这个标的。',
      loading: '正在加载持仓详情。',
      error: '持仓详情加载失败。',
      summary: '摘要',
      tabListLabel: '持仓详情视图',
      tabScrollHint: '横向滑动查看更多 →',
      tabPosition: '持仓',
      tabPnlCosts: '盈亏与成本',
      tabTransactions: '流水',
      tabEvidence: '证据',
      tabReconciliation: '对账',
      valuation: '估值与成本',
      resultsEvidence: '持仓结果与证据',
      pnlCostsDetail:
        '统一复核本地成本、明确标注的券商或流水推算成本、已实现盈亏与费用，不制造第二套权威结果。',
      closedHistoryOnly: '已清仓 · 仅历史',
      closedNoCurrentExposure:
        '该资产已经清仓，不再形成当前组合暴露；历史交易、费用和已实现盈亏仍完整保留以供复核。',
      evidenceIdentityMismatch:
        '请求期间估值快照或账本截止标识发生变化；复核前不得把这些数字视为同一份权威结果。',
      evidenceSummaryTitle: '持仓证据状态',
      quoteStatus: '行情与数据状态',
      marketEvidence: '市场证据',
      marketEvidenceDetail:
        '展示该标的已记录行情来源与新鲜度；打开本页不会联系数据源。',
      ledgerTrace: '流水轨迹',
      productionLedgerOnly: '仅账户账本记录',
      riskExposure: '风险暴露',
      relatedActions: '相关操作',
      strategyAttributionBoundary: '策略归因边界',
      strategyAttributionNoLinkedFills: '尚未关联策略成交',
      strategyAttributionDetail:
        '当前这只持仓暂无完整的策略归因证据链；缺少可追溯的信号、复核、订单或成交引用时，持仓收益仍按账户层级展示，不归因给某个策略。',
      strategyAttributionLinkedEvidence: '已有策略证据可复核',
      strategyAttributionLinkedDetail:
        '该持仓的策略贡献仍是复核证据；手工交易和现金流会保持拆分，等待归因复核后再使用。',
      strategyAttributionLinkedFills: (count: number) =>
        `${count} 条已关联成交`,
      strategyAttributionLinkedFillsLabel: '已关联成交',
      strategyAttributionStrategy: '策略',
      strategyAttributionEvidenceRefs: '证据引用',
      strategyAttributionEvidenceChain: '证据链',
      strategyAttributionEvidenceAuditRef: (value: string) =>
        `审计编号 ${value}`,
      strategyAttributionEvidenceTypeLabels: {
        signal: '信号证据',
        action: '候选动作',
        risk: '风控检查',
        review: '人工复核',
        order: '订单证据',
        fill: '成交证据',
        unknown: '证据引用',
      },
      strategyAttributionEvidenceStatus: '证据状态',
      strategyAttributionContributionStatus: '贡献状态',
      strategyAttributionReviewReadiness: '归因复核准备度',
      strategyAttributionReviewReady: '可进入复核',
      strategyAttributionReviewIncomplete: '证据仍未补齐',
      strategyAttributionReviewBoundary:
        '持仓收益在复核完成前仍不会归因到该策略。',
      strategyAttributionNextActionTitle: '下一步复核动作',
      strategyAttributionNextActionResearch:
        '先到回测页运行或刷新这只持仓的单标的策略闭环，再一起检查信号、风控、模拟复核和归因证据。',
      strategyAttributionNextActionManualReview:
        '先在决策页复核策略候选动作，再让该持仓进入归因复核。',
      strategyAttributionNextActionExecution:
        '先核对执行证据，再让该持仓进入归因复核。',
      strategyAttributionNextActionGeneric:
        '先补齐缺失证据，再让该持仓进入归因复核。',
      strategyAttributionOpenDecisionReview: '打开决策复核',
      strategyAttributionOpenExecutionReview: '打开执行复核',
      strategyAttributionReadinessItems: {
        signalLinked: '策略信号已关联',
        signalMissing: '缺少策略信号',
        actionLinked: '候选动作已关联',
        actionMissing: '缺少候选动作',
        reviewLinked: '人工复核已关联',
        reviewMissing: '缺少人工复核',
        riskLinked: '风控检查已关联',
        riskMissing: '缺少风控检查',
        orderLinked: '订单证据已关联',
        orderMissing: '缺少订单证据',
        fillLinked: '成交证据已关联',
        fillMissing: '缺少成交证据',
        unknownLinked: '证据已关联',
        unknownMissing: '缺少证据',
      },
      displayName: '名称',
      assetClass: '资产类别',
      quantity: '数量',
      marketValue: '市值',
      costBasis: '本地成本额',
      avgCost: '本地移动平均成本',
      brokerDisplayedCost: '券商展示成本',
      brokerDisplayedCostBasis: '券商展示成本额',
      ledgerProjectedUnitCost: '流水推算单位成本',
      ledgerProjectedCostBasis: '流水推算剩余持仓成本',
      costBasisDifference: '成本口径差异',
      costBasisMethod: '成本口径',
      costBasisStatus: '成本证据状态',
      costBasisReviewNeeded: '需要复核成本口径',
      costBasisReviewDetail:
        '券商展示成本与 Karkinos 本地移动平均成本不一致。依赖成本口径盈亏前，请先复核账户事实证据。',
      costBasisMethods: {
        broker_remaining_cost: '券商剩余持仓成本',
        moving_average_buy_cost: '本地移动平均买入成本',
        unavailable: '暂无券商成本证据',
      },
      costBasisStatuses: {
        available: '券商确认成本证据',
        projected_from_ledger: '本地流水推算',
        unavailable: '暂无成本证据',
      },
      quotePrice: '行情价',
      todayChange: '今日收益',
      todayChangePct: '今日涨跌幅',
      baselinePrice: '日内基准价',
      baselineSource: '基准来源',
      baselineSources: {
        dailyClose: '本地日线收盘价',
        marketBarClose: '本地 OHLC 收盘价',
        previousClose: '行情上报前收',
        previousQuote: '上一条缓存行情',
        intradayTradeCost: '当日买入成本',
        fallbackClose: '缓存收盘兜底',
        unavailable: '暂无基准',
      },
      unrealizedPnl: '浮动盈亏',
      pnlPct: '收益率',
      realizedPnl: '已实现盈亏',
      commissionPaid: '累计费用',
      availableFrozen: '可用 / 冻结',
      portfolioWeight: '组合占比',
      lastTradeAt: '最近交易时间',
      valuationSnapshotId: '估值快照',
      ledgerCutoffId: '账本截止',
      evidenceState: '证据状态',
      nextManualStep: '下一步人工操作',
      evidenceStates: {
        historicalClosed: '已清仓历史持仓',
        identityMismatch: '快照标识不一致',
        costBasisReview: '成本口径待对账',
        staleQuote: '行情陈旧或估算',
        complete: '当前无证据问题',
      },
      evidenceNextSteps: {
        reviewHistory: '复核保留的账本流水与已实现盈亏。',
        reloadIdentity: '重新读取并确认同一估值快照和账本截止。',
        reconcileCost: '到账户事实页复核成本证据。',
        reviewQuote: '前往市场页复核已记录的行情证据。',
        none: '当前无需额外人工操作。',
      },
      chartBuyMarker: '买入',
      chartSellMarker: '卖出',
      chartLocalCostLine: '本地移动平均成本',
      chartEvidenceCostLine: '证据成本',
      positionFacts: '持仓事实',
      positionFactsDetail:
        '即使没有价格历史，持仓数量仍来自账户记录并继续可见。',
      priceStructureMissing: '价格证据缺失',
      priceStructureMissingDetail:
        '当前标的没有已保存 K 线；页面仍展示账户持仓事实，不会推算缺失的价格历史。',
      persistedPriceBoundary:
        '本次读取没有联系数据提供方，也没有触发行情刷新。',
      quoteTimestamp: '行情时间',
      quoteSource: '行情来源',
      quoteAge: '行情年龄',
      staleReason: '缓存原因',
      valuationTimestamp: '估值时间',
      refreshPolicy: '刷新策略',
      marketOpen: '市场开盘',
      cacheOnly: '仅缓存',
      marketClosed: '市场休市',
      cacheNotice: '行情缓存 · 估值基于缓存行情',
      quoteLive: '行情可用',
      quoteStale: '缓存行情',
      noLedger: '当前还没有这个标的的流水轨迹。',
      ledgerCount: (count: number) => `${count} 条匹配流水`,
      entryType: '类型',
      amount: '金额',
      price: '价格',
      note: '备注',
      refreshQuote: '刷新该标的行情',
      quoteRefreshTitle: '刷新行情证据',
      quoteRefreshDetail:
        '这是受控操作，可能联系已配置的数据源，并记录一条可审计的刷新结果。',
      quoteRefreshBoundary: '不会改写账本、在 UI 重算账户事实或授予交易权限',
      refreshingQuote: '正在刷新行情…',
      refreshDone: '行情刷新请求已完成。',
      refreshFailed: '行情刷新失败，请检查市场数据状态。',
      actionStrategyResearch: '用该标的做策略研究',
      actionStrategyEvidence: '查看策略研究证据',
      actionMarket: '打开市场研究',
      actionTrading: '打开交易复核',
      actionActivity: '记录流水',
      actionViewActivity: '查看历史流水',
      actionPortfolio: '查看全部持仓',
      reconciliationTitle: '对账证据',
      reconciliationStateTitle: '估值依据与成本口径核对',
      reconciliationDetail:
        '只读核对估值快照、账本截止、行情证据与成本状态；本视图不会执行对账或修改账户事实。',
      actionAccountTruth: '打开账户事实复核',
    },
    allocation: {
      title: '账户资产构成',
      empty: '当前筛选范围下还没有可展示的账户资产。',
      asset: '资产',
      valuationAmount: '估值金额',
      navShare: '净值占比',
      cashBalance: '现金余额',
    },
    allocationGroups: {
      title: '分组配置',
      empty: '当前还没有分组配置可展示。',
    },
    liveBoard: {
      title: '持仓行情看板',
      subtitle: '按资产类别查看行情价格、今日涨跌和买入以来收益。',
      loading: '正在加载持仓行情。',
      error: '持仓行情加载失败。',
      empty: '当前还没有活跃持仓，先录入首笔交易再开始跟踪收益。',
      positionCount: (count: number) => `${count} 个活跃持仓`,
      latestPrice: '行情价格',
      todayMove: '今日涨跌',
      sinceBuyReturn: '买入以来收益',
      updatedAt: '更新时间',
      baseline: '对比基准',
      baselinePreviousClose: '昨收',
      baselineFallbackClose: '回补收盘点',
      baselineUnavailable: '暂无可用日内基准',
      quoteLive: '行情可用',
      quoteStale: '缓存行情',
      holdingDetailLink: (symbol: string) => `持仓明细：${symbol}`,
      summaryOnly: '单只标的行情、成本和 K 线在下方持仓明细与详情页中查看。',
    },
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type PortfolioCopy = (typeof portfolioCopy)[Locale];

declare module '../../shared/i18n/context' {
  interface ApplicationCopy {
    portfolio: PortfolioCopy;
  }
}
