export const portfolioEnCopy = {
  kicker: 'Portfolio',
  title: 'Holdings & allocation',
  subtitle:
    'Review current holdings and evidence first, then allocation structure and strategy attribution.',
  positionsLoading: 'Loading positions.',
  positionsError: 'Failed to load positions.',
  positionsEmpty: 'No holdings yet. Add trades from Activity first.',
  filterEmpty: 'No holdings match the current filters.',
  currentHoldingsCount: (count: number) => `${count} open holdings`,
  filteredHoldingsCount: (count: number) => `${count} shown`,
  summary: {
    ariaLabel: 'Portfolio account summary',
    loading: 'Loading portfolio summary',
    loadingDetail:
      'Loading the latest saved account valuation and activity. Market data is not refreshed automatically.',
    error: 'Portfolio summary unavailable',
    errorDetail:
      'Current holdings may still load separately. Summary metrics remain unavailable until the saved account view can be read.',
    missing: 'Portfolio summary not available',
    missingDetail:
      'No account summary has been saved. The interface will not calculate account totals from the holdings table.',
    totalEquity: 'Total equity',
    totalEquityDetail: 'Latest saved account value',
    cash: 'Cash',
    cashDetail: 'Available account cash',
    openHoldings: 'Open holdings',
    openHoldingsDetail: 'Current non-zero holdings',
    realizedPnl: 'Realized PnL',
    realizedPnlDetail: 'Cumulative realized result',
  },
  currentHoldings: {
    title: 'Current holdings',
    detail:
      'Current account positions. Open a row for cost, quantity, quote source, and transaction evidence.',
  },
  analysis: {
    title: 'Allocation & attribution',
    detail:
      'Switch the analysis below without changing the current-holdings scope above.',
  },
  evidenceReview: {
    title: 'Evidence review — not current holdings',
    detail:
      'These facts are incomplete, pending settlement, or require reconciliation. They stay outside current holdings until reviewed.',
    count: (count: number) => `${count} to review`,
  },
  sidebarLoading: 'Loading allocation and performance breakdown.',
  sidebarError: 'Failed to load allocation or performance breakdown.',
  sidebarEmpty: 'No allocation view is available yet.',
  toolbar: {
    view: 'View',
    helper: 'Filter and sort current holdings.',
    search: 'Search',
    searchPlaceholder: 'Filter by symbol',
    assetClass: 'Asset Class',
    allAssetClasses: 'All asset classes',
    pnlFocus: 'PnL Focus',
    allHoldings: 'All holdings',
    winnersOnly: 'Winners only',
    losersOnly: 'Losers only',
    quoteFilter: 'Quote state',
    allQuoteStates: 'All quote states',
    healthyQuotes: 'Normal quotes',
    reviewQuotes: 'Stale or estimated',
    evidenceFilter: 'Reconciliation',
    allEvidenceStates: 'All evidence states',
    evidenceReviewOnly: 'Issues only',
    evidenceClearOnly: 'No issues',
    sortBy: 'Sort by',
    showMoreFilters: 'More filters',
    hideMoreFilters: 'Hide filters',
    activeFilters: (count: number) =>
      `${count} active filter${count === 1 ? '' : 's'}`,
    sortMarketValue: 'Market value',
    sortWeight: 'Portfolio weight',
    sortTodayPnl: 'Today PnL',
    sortUnrealizedPnl: 'Unrealized PnL',
    sortRealizedPnl: 'Realized PnL',
  },
  table: {
    symbol: 'Symbol',
    name: 'Name',
    assetClass: 'Asset Class',
    quantity: 'Quantity',
    availFrozen: 'Avail/Frozen',
    avgCost: 'Avg Cost',
    latestPrice: 'Quote Price',
    todayChange: 'Today PnL',
    cachedQuoteNotice: 'Cached quotes · positions valued from cached quotes',
    cachedQuoteAt: (time: string) => `Cached ${time}`,
    marketValue: 'Market Value',
    weight: 'Weight',
    unrealized: 'Unrealized',
    returnPct: 'Return',
    quoteState: 'Quote State',
    quoteAge: 'Quote Age',
    staleReason: 'Stale Reason',
    actions: 'Actions',
    refresh: 'Refresh',
    refreshing: 'Refreshing',
    trade: 'Trade',
    ledger: 'Ledger',
    realized: 'Realized PnL',
    closedOn: 'Closed on',
    detailsTitle: 'Holding Details',
  },
  detail: {
    kicker: 'Holding detail',
    title: (symbol: string) => `${symbol} Position`,
    subtitle:
      'Review cost, valuation, cached quote state, ledger trace, and related action paths for this holding.',
    backToPortfolio: 'Back to Portfolio',
    returnToPortfolio: 'Return to holdings list',
    notFoundTitle: 'Holding not found',
    notFoundDetail:
      'This symbol is not present in the current portfolio snapshot.',
    loading: 'Loading holding detail.',
    error: 'Failed to load holding detail.',
    summary: 'Summary',
    tabListLabel: 'Holding detail views',
    tabScrollHint: 'Scroll for more views →',
    tabPosition: 'Position',
    tabPnlCosts: 'P&L & Costs',
    tabTransactions: 'Transactions',
    tabEvidence: 'Evidence',
    tabReconciliation: 'Reconciliation',
    valuation: 'Valuation & Cost',
    resultsEvidence: 'Holding results & evidence',
    pnlCostsDetail:
      'Compare canonical local cost, labeled external or ledger-projected cost evidence, realized P&L, and fees without creating a second headline value.',
    closedHistoryOnly: 'Closed · history only',
    closedNoCurrentExposure:
      'This asset is closed and has no current portfolio exposure. Historical trades, fees, and realized PnL remain available for review.',
    evidenceIdentityMismatch:
      'The valuation snapshot or ledger scope changed during the request. Review the recorded basis before treating these figures as one result.',
    evidenceSummaryTitle: 'Holding evidence state',
    quoteStatus: 'Quote & Data State',
    marketEvidence: 'Market evidence',
    marketEvidenceDetail:
      'Persisted quote provenance and freshness for this instrument. Reading this view does not contact a provider.',
    ledgerTrace: 'Ledger Trace',
    productionLedgerOnly: 'Persisted account ledger only',
    riskExposure: 'Risk & Exposure',
    relatedActions: 'Related Actions',
    strategyAttributionBoundary: 'Strategy attribution boundary',
    strategyAttributionNoLinkedFills: 'No linked strategy fills yet',
    strategyAttributionDetail:
      'This holding does not yet have a complete strategy attribution evidence chain. Its P/L stays account-level until the missing signal, review, order, or fill reference is available.',
    strategyAttributionLinkedEvidence: 'Linked strategy evidence available',
    strategyAttributionLinkedDetail:
      'Strategy contribution remains review-only for this holding; manual trades and cash flows stay separate until attribution is reviewed.',
    strategyAttributionLinkedFills: (count: number) => `${count} linked fills`,
    strategyAttributionLinkedFillsLabel: 'Linked fills',
    strategyAttributionStrategy: 'Strategy',
    strategyAttributionEvidenceRefs: 'Evidence refs',
    strategyAttributionEvidenceChain: 'Evidence chain',
    strategyAttributionEvidenceAuditRef: (value: string) =>
      `Audit ref ${value}`,
    strategyAttributionEvidenceTypeLabels: {
      signal: 'Signal evidence',
      action: 'Candidate action',
      risk: 'Risk check',
      review: 'Manual review',
      order: 'Order evidence',
      fill: 'Fill evidence',
      unknown: 'Evidence reference',
    },
    strategyAttributionEvidenceStatus: 'Evidence status',
    strategyAttributionContributionStatus: 'Contribution status',
    strategyAttributionReviewReadiness: 'Attribution review readiness',
    strategyAttributionReviewReady: 'Ready for review',
    strategyAttributionReviewIncomplete: 'Evidence still incomplete',
    strategyAttributionReviewBoundary:
      'Holding PnL is still not assigned to the strategy until review is complete.',
    strategyAttributionNextActionTitle: 'Next review step',
    strategyAttributionNextActionResearch:
      'Run or refresh the single-instrument strategy loop for this holding, then review signal, risk, simulation, and attribution evidence together.',
    strategyAttributionNextActionManualReview:
      'Review the strategy candidate in Decision before this holding can enter attribution review.',
    strategyAttributionNextActionExecution:
      'Check execution evidence before this holding can enter attribution review.',
    strategyAttributionNextActionGeneric:
      'Resolve the missing evidence before this holding can enter attribution review.',
    strategyAttributionOpenDecisionReview: 'Open Decision review',
    strategyAttributionOpenExecutionReview: 'Open execution review',
    strategyAttributionReadinessItems: {
      signalLinked: 'Strategy signal linked',
      signalMissing: 'Strategy signal missing',
      actionLinked: 'Candidate action linked',
      actionMissing: 'Candidate action missing',
      reviewLinked: 'Manual review linked',
      reviewMissing: 'Manual review missing',
      riskLinked: 'Risk check linked',
      riskMissing: 'Risk check missing',
      orderLinked: 'Order evidence linked',
      orderMissing: 'Order evidence missing',
      fillLinked: 'Fill evidence linked',
      fillMissing: 'Fill evidence missing',
      unknownLinked: 'Evidence linked',
      unknownMissing: 'Evidence missing',
    },
    displayName: 'Display Name',
    assetClass: 'Asset Class',
    quantity: 'Quantity',
    marketValue: 'Market Value',
    costBasis: 'Local cost basis',
    avgCost: 'Local moving average cost',
    brokerDisplayedCost: 'Broker displayed cost',
    brokerDisplayedCostBasis: 'Broker displayed cost basis',
    ledgerProjectedUnitCost: 'Ledger-projected unit cost',
    ledgerProjectedCostBasis: 'Ledger-projected remaining cost',
    costBasisDifference: 'Cost basis difference',
    costBasisMethod: 'Cost basis method',
    costBasisStatus: 'Cost basis evidence',
    costBasisReviewNeeded: 'Cost basis review needed',
    costBasisReviewDetail:
      'Broker displayed cost differs from Karkinos local moving average cost. Review Account Truth evidence before relying on cost-basis P/L.',
    costBasisMethods: {
      broker_remaining_cost: 'Broker remaining-position cost',
      moving_average_buy_cost: 'Local moving average buy cost',
      unavailable: 'No broker cost-basis evidence',
    },
    costBasisStatuses: {
      available: 'Broker-confirmed evidence',
      projected_from_ledger: 'Projected from local ledger',
      unavailable: 'No cost-basis evidence',
    },
    quotePrice: 'Quote Price',
    todayChange: 'Today PnL',
    todayChangePct: 'Today Return',
    baselinePrice: 'Daily Baseline',
    baselineSource: 'Baseline Source',
    baselineSources: {
      dailyClose: 'Local daily close',
      marketBarClose: 'Local OHLC close',
      previousClose: 'Reported previous close',
      previousQuote: 'Previous cached quote',
      intradayTradeCost: 'Intraday trade cost',
      fallbackClose: 'Fallback cached close',
      unavailable: 'Unavailable',
    },
    unrealizedPnl: 'Unrealized PnL',
    pnlPct: 'PnL %',
    realizedPnl: 'Realized PnL',
    commissionPaid: 'Commission Paid',
    availableFrozen: 'Available / Frozen',
    portfolioWeight: 'Portfolio Weight',
    lastTradeAt: 'Latest trade',
    valuationSnapshotId: 'Valuation snapshot',
    ledgerCutoffId: 'Ledger cutoff',
    evidenceState: 'Evidence state',
    nextManualStep: 'Next manual step',
    evidenceStates: {
      historicalClosed: 'Historical closed position',
      identityMismatch: 'Valuation scope mismatch',
      costBasisReview: 'Cost basis needs reconciliation',
      staleQuote: 'Quote is stale or estimated',
      complete: 'No current evidence issue',
    },
    evidenceNextSteps: {
      reviewHistory: 'Review the retained ledger and realized PnL.',
      reloadIdentity: 'Reload and confirm one snapshot and ledger cutoff.',
      reconcileCost: 'Review cost evidence in Account Truth.',
      reviewQuote: 'Review the recorded quote evidence on the Market page.',
      none: 'No additional manual action is required.',
    },
    chartBuyMarker: 'Buy',
    chartSellMarker: 'Sell',
    chartLocalCostLine: 'Local moving-average cost',
    chartEvidenceCostLine: 'Recorded evidence cost',
    positionFacts: 'Recorded position facts',
    positionFactsDetail:
      'Position quantity remains available from the account record even when saved price history is unavailable.',
    priceStructureMissing: 'Price evidence missing',
    priceStructureMissingDetail:
      'No saved price bars are available for this instrument. The position is still shown from the account record without inferring missing price history.',
    persistedPriceBoundary:
      'This read did not contact a provider or trigger a market-data refresh.',
    quoteTimestamp: 'Quote Timestamp',
    quoteSource: 'Quote Source',
    quoteAge: 'Quote Age',
    staleReason: 'Stale Reason',
    valuationTimestamp: 'Valuation Timestamp',
    refreshPolicy: 'Refresh Policy',
    marketOpen: 'Market Open',
    cacheOnly: 'Cache Only',
    marketClosed: 'Market Closed',
    cacheNotice: 'Cached quotes · valuation uses cached market data',
    quoteLive: 'Quote available',
    quoteStale: 'Cached quote',
    noLedger: 'No ledger trace is available for this symbol yet.',
    ledgerCount: (count: number) => `${count} matching entries`,
    entryType: 'Entry',
    amount: 'Amount',
    price: 'Price',
    note: 'Note',
    refreshQuote: 'Refresh this quote',
    quoteRefreshTitle: 'Refresh quote evidence',
    quoteRefreshDetail:
      'This controlled action may contact the configured market-data source and records an auditable result for this instrument.',
    quoteRefreshBoundary:
      'It does not rewrite the ledger, recalculate account facts in the UI, or grant trading authority',
    refreshingQuote: 'Refreshing quote…',
    refreshDone: 'Quote refresh request completed.',
    refreshFailed: 'Quote refresh failed. Check market data state.',
    actionStrategyResearch: 'Run strategy research for this holding',
    actionStrategyEvidence: 'Review strategy research evidence',
    actionMarket: 'Open Market research',
    actionTrading: 'Open trading review',
    actionActivity: 'Record activity',
    actionViewActivity: 'View historical activity',
    actionPortfolio: 'View all holdings',
    reconciliationTitle: 'Reconciliation evidence',
    reconciliationStateTitle: 'Valuation basis and cost alignment',
    reconciliationDetail:
      'Read-only alignment of the valuation snapshot, ledger cutoff, quote evidence, and cost-basis status. This view does not reconcile or mutate account facts.',
    actionAccountTruth: 'Open Account Truth review',
  },
  allocation: {
    title: 'Account composition',
    empty: 'No account assets match the current scope yet.',
    asset: 'Asset',
    valuationAmount: 'Valuation amount',
    navShare: 'Share of NAV',
    cashBalance: 'Cash balance',
  },
  allocationGroups: {
    title: 'Allocation Groups',
    empty: 'No grouped allocation available yet.',
  },
  liveBoard: {
    title: 'Holdings quote board',
    subtitle:
      'Track grouped holdings with quote price, intraday move, and since-buy return.',
    loading: 'Loading holdings quotes.',
    error: 'Failed to load holdings quotes.',
    empty:
      'No active holdings yet. Record the first trade to start tracking returns.',
    positionCount: (count: number) =>
      `${count} active holding${count === 1 ? '' : 's'}`,
    latestPrice: 'Quote price',
    todayMove: 'Today move',
    sinceBuyReturn: 'Since-buy return',
    updatedAt: 'Updated',
    baseline: 'Baseline',
    baselinePreviousClose: 'Previous close',
    baselineFallbackClose: 'Fallback close',
    baselineUnavailable: 'Daily baseline unavailable',
    quoteLive: 'Quote available',
    quoteStale: 'Cached quote',
    holdingDetailLink: (symbol: string) => `Holding Details: ${symbol}`,
    summaryOnly:
      'Instrument-level quote, cost, and K-line details are shown in the holdings list and detail pages below.',
  },
} satisfies Record<string, unknown>;
