export const SHADOW_RESEARCH_COPY = {
  en: {
    kicker: 'After-close DeepSeek research',
    title: 'Automated shadow strategy research',
    detail:
      'After the persisted market close, Karkinos refreshes the baseline locally and sends DeepSeek the saved backtest plus a sanitized account risk/allocation projection. Absolute account values and valuation/ledger identifiers stay redacted. Formula validation, after-cost backtest and rolling OOS remain local before the evidence critique.',
    disabled: 'Paused',
    enabled: 'Authorized',
    killSwitch: 'Kill switch',
    clear: 'Clear',
    calls: 'Provider calls',
    tokens: 'Token usage',
    tokenPolicy: 'Daily token policy',
    unboundedDailyTokens: 'No Karkinos daily aggregate limit',
    legacyBoundedDailyTokens:
      'Legacy bounded policy · blocked until reauthorized',
    providerLimitsRemain: 'Per-request provider and context limits still apply',
    tokenAccountingEstimate: 'accounting estimate',
    candidates: 'Sequential revisions',
    providerWindow: 'DeepSeek call window',
    offPeakEligible: 'Off-peak · batch eligible',
    offPeakDeferred: 'Deferred to off-peak',
    offPeakSchedule:
      'Weekdays 09:00–12:00 / 14:00–18:00 blocked · batch must finish before 09:00',
    nextEligible: 'Next eligible',
    dailyWinner: 'New candidate winner',
    noWinner: 'No new winner · current strategy unchanged',
    backup: 'Daily strategy backup',
    winnerBadge: 'New-candidate winner',
    iterationRound: 'Sequential round',
    backupVerified: 'Verified',
    fiveCandidateRule:
      'Five sequential rounds require ten provider calls: each round generates one revision, runs the canonical local backtest, records one critique, and binds that feedback into the next round. No new winner means no new promotion; the separate daily decision pipeline still decides trade or NO-ACTION.',
    fiveRoundPolicyBlocked:
      'Enabled research is blocked until the displayed policy authorizes exactly five sequential revisions, ten provider calls, and no Karkinos daily aggregate token limit.',
    notDailyWinner:
      'This candidate passed its own gate but is not the verified new-candidate winner, so public paper/shadow approval remains blocked.',
    closeTime: 'After-close time',
    question: 'Standing research question',
    operator: 'Owner identity',
    save: 'Save standing policy',
    saving: 'Saving…',
    confirmEnable:
      'I authorize five strictly sequential research rounds and ten provider calls per market date with no Karkinos daily aggregate token limit. Provider per-request limits and usage accounting remain; this has no strategy replacement or trading authority.',
    confirmPause: 'I confirm pausing recurring AI strategy research.',
    run: 'Check and run now',
    running: 'Checking evidence…',
    noCandidates:
      'No completed automated candidate is in the research pool yet.',
    baseline: 'Current baseline',
    candidate: 'New candidate',
    return: 'Total return',
    sharpe: 'Sharpe',
    drawdown: 'Max drawdown',
    costs: 'Total cost',
    oos: 'Mean / worst OOS',
    trades: 'Trades',
    risk: 'Risk impact',
    blockers: 'Promotion blockers',
    critique: 'DeepSeek evidence critique',
    approve: 'Approve for paper/shadow only',
    reapprove: 'Re-review for paper/shadow',
    approving: 'Recording approval…',
    approvalNote: 'Human review note',
    approvalConfirm:
      'I reviewed the baseline comparison, costs, rolling OOS, risks and critique. Approve this candidate for paper/shadow research only.',
    approved: 'Paper/shadow approved',
    paused: 'Paper/shadow paused / revoked',
    pause: 'Pause / revoke paper-shadow',
    pausing: 'Recording pause…',
    pauseNote: 'Pause / revocation reason',
    pauseConfirm:
      'I confirm pausing this exact candidate. Existing approval remains auditable, but new tickets must fail closed until a new explicit review.',
    noAuthority: 'No production replacement · no broker order',
    failure: 'The operation failed closed. No strategy or order was changed.',
  },
  zh: {
    kicker: 'DeepSeek 收盘后研究',
    title: '自动 shadow 策略研究池',
    detail:
      '持久化行情收盘后，Karkinos 在本地刷新基线，只向 DeepSeek 发送保存的回测证据与脱敏账户风险/配置投影；绝对账户金额及 valuation/ledger 标识不外发。Formula 校验、权威成本后回测和 rolling OOS 均留在本地，之后再发送证据做 critique。',
    disabled: '已暂停',
    enabled: '已授权',
    killSwitch: 'Kill Switch',
    clear: '未触发',
    calls: '模型调用',
    tokens: 'Token 用量',
    tokenPolicy: '每日 Token 策略',
    unboundedDailyTokens: 'Karkinos 不设每日累计上限',
    legacyBoundedDailyTokens: '旧版有界策略 · 重新授权前保持阻断',
    providerLimitsRemain: '仍受模型单次请求与上下文窗口的技术限制',
    tokenAccountingEstimate: '用量核算估计',
    candidates: '串行修订轮数',
    providerWindow: 'DeepSeek 调用窗口',
    offPeakEligible: '低谷期 · 可启动整批',
    offPeakDeferred: '已顺延至低谷期',
    offPeakSchedule:
      '工作日 09:00–12:00 / 14:00–18:00 禁止调用 · 整批须在次日 09:00 前完成',
    nextEligible: '下次可运行',
    dailyWinner: '新候选确定性优胜者',
    noWinner: '无新优胜者 · 当前策略不变',
    backup: '每日策略备份',
    winnerBadge: '新候选优胜者',
    iterationRound: '串行迭代轮次',
    backupVerified: '校验通过',
    fiveCandidateRule:
      '5 轮串行迭代需要 10 次模型调用：每轮生成 1 个修订版、本地权威回测并 critique，再把结果绑定给下一轮；无新优胜者只表示不发生新晋级，当天交易或 NO-ACTION 仍由独立日决策链判断。',
    fiveRoundPolicyBlocked:
      '启用状态下必须明确授权 5 轮严格串行修订、10 次模型调用且 Karkinos 不设每日累计 Token 上限，否则研究运行保持阻断。',
    notDailyWinner:
      '该候选虽通过自身门槛，但不是已校验的新候选优胜者，因此公开 paper/shadow 批准保持阻断。',
    closeTime: '收盘后时间',
    question: '长期研究问题',
    operator: '所有者身份',
    save: '保存站立授权',
    saving: '保存中…',
    confirmEnable:
      '我授权每个交易日进行 5 轮严格串行研究、最多 10 次模型调用，Karkinos 不设每日累计 Token 上限；仍记录用量并受模型单次请求和上下文窗口限制。该授权不包含策略替换权或交易权。',
    confirmPause: '我确认暂停周期性 AI 策略研究。',
    run: '立即检查并运行',
    running: '正在检查证据…',
    noCandidates: '研究池里还没有完成的自动候选。',
    baseline: '当前基线',
    candidate: '新候选',
    return: '总收益',
    sharpe: '夏普',
    drawdown: '最大回撤',
    costs: '总成本',
    oos: 'OOS 均值 / 最差',
    trades: '成交数',
    risk: '风险影响',
    blockers: '晋级阻断项',
    critique: 'DeepSeek 证据批判',
    approve: '仅批准进入 paper/shadow',
    reapprove: '重新复核进入 paper/shadow',
    approving: '正在记录批准…',
    approvalNote: '人工复核备注',
    approvalConfirm:
      '我已复核基线对比、成本、rolling OOS、风险与 critique；仅批准该候选进入 paper/shadow 研究。',
    approved: '已批准 paper/shadow',
    paused: 'paper/shadow 已暂停 / 撤销',
    pause: '暂停 / 撤销 paper-shadow',
    pausing: '正在记录暂停…',
    pauseNote: '暂停 / 撤销原因',
    pauseConfirm:
      '我确认暂停这一精确候选；原批准保留供审计，但重新明确复核前，新票据必须 fail closed。',
    noAuthority: '不会替换生产策略 · 不会创建 broker 订单',
    failure: '操作已 fail closed；没有修改策略或订单。',
  },
} as const;

export type ShadowResearchCopy =
  (typeof SHADOW_RESEARCH_COPY)[keyof typeof SHADOW_RESEARCH_COPY];
