export const SHADOW_RESEARCH_COPY = {
  en: {
    kicker: 'After-close DeepSeek research',
    title: 'Automated shadow strategy research',
    loading: 'Reading saved automated research…',
    loadFailed: 'Automated research status could not be loaded.',
    retry: 'Retry',
    detail:
      'After the persisted market close, Karkinos runs Formula discovery with normalized notional capital and canonical estimated costs. It does not require or export Account Truth, valuation or ledger facts. Formula validation, after-cost backtest and rolling OOS remain local before the evidence critique; account qualification remains a separate promotion and execution gate.',
    disabled: 'Paused',
    enabled: 'Authorized',
    killSwitch: 'Kill switch',
    clear: 'Clear',
    calls: 'Research-date provider calls',
    todayCalls: 'Today provider calls',
    noCallsToday: 'No provider call was recorded today',
    lastProviderCall: 'Last provider call',
    researchMarketDate: 'research market date',
    tokens: 'Token usage',
    tokenPolicy: 'Daily token policy',
    unboundedDailyTokens: 'No Karkinos daily aggregate limit',
    legacyBoundedDailyTokens:
      'Legacy bounded policy · blocked until reauthorized',
    providerLimitsRemain: 'Per-request provider and context limits still apply',
    tokenAccountingEstimate: 'accounting estimate',
    candidates: 'Sequential revisions',
    providerWindow: 'DeepSeek call window',
    offPeakEligible: 'Off-peak · batch eligible',
    offPeakDeferred: 'Deferred to off-peak',
    offPeakSchedule:
      'Weekdays 09:00–12:00 / 14:00–18:00 blocked · batch must finish before 09:00',
    nextEligible: 'Next eligible',
    dailyWinner: 'Daily research outcome',
    noWinner: 'No complete normalized research recommendation',
    researchNotQualified:
      'Best available for research · account qualification not evaluated',
    worstCostStressExcess: 'Worst modeled excess vs baseline at 10/25 bps',
    costStressUnavailable: 'Cost stress evidence missing or incomparable',
    costStressLegacy: 'Legacy ranking · cost stress comparison not recorded',
    backup: 'Daily strategy backup',
    winnerBadge: 'Account-qualified promotion winner',
    researchWinnerBadge: 'Formula research winner · non-executable',
    qualificationTitle: 'Account qualification review',
    qualificationDetail:
      'Provider-free replay evaluates the frozen Formula batch against current canonical account evidence. Only the exact qualified winner can be approved, and approval remains paper/shadow research only.',
    qualificationStatus: {
      running: 'Qualification running',
      completed: 'Qualified winner selected',
      passed: 'Qualification passed',
      blocked: 'Qualification blocked',
      failed: 'Qualification failed closed',
      not_evaluated: 'Not evaluated',
      not_applicable: 'Not applicable',
    },
    qualificationRun: 'Latest qualification run',
    qualificationAttempt: 'Latest qualification attempt',
    qualificationWinnerBinding: 'Winner → normalized source candidate',
    qualificationNotEvaluated: 'No qualification run is bound to the result.',
    qualificationNoWinner: 'No qualified winner',
    qualificationSourceBound: 'Exact normalized source candidate is bound.',
    qualificationSourceUnbound:
      'No exact normalized source binding; approval remains unavailable.',
    qualificationSourceLocked:
      'The normalized source candidate remains research-only and cannot use the original approval path.',
    qualificationBlockers: 'Qualification blockers',
    qualificationApprovalNote: 'Qualification approval note',
    qualificationApprovalConfirm:
      'I reviewed this exact account-qualified winner and approve it for paper/shadow research only. This grants no order, trade, or capital authority.',
    qualificationApprove: 'Approve qualified winner for paper/shadow only',
    qualificationApproving: 'Recording exact approval…',
    qualificationApproved: 'Exact paper/shadow approval recorded',
    observationTitle: 'Forward observation and paper results',
    observationBoundary:
      'Start an independent observation from this exact saved candidate and review its paper results here. These observations do not replace independent final evaluation or account qualification, and do not change approval eligibility.',
    observationUnavailable:
      'No exact normalized source candidate with a saved report is bound. Observation evidence is unavailable.',
    observationSource: 'Normalized source candidate / run',
    observationReport: 'Source report',
    observationReportLoading: 'Loading the exact source report…',
    observationReportFailed:
      'The exact source report is unavailable or does not match this candidate. Reload before starting an observation.',
    observationReportRefresh: 'Reload source report',
    iterationRound: 'Sequential round',
    backupVerified: 'Verified',
    fiveCandidateRule:
      'Five sequential rounds require ten provider calls: each round generates one revision, runs the canonical local backtest, records one critique, and binds that feedback into the next round. No new winner means no new promotion; the separate daily decision pipeline still decides trade or NO-ACTION.',
    fiveRoundPolicyBlocked:
      'Enabled research is blocked until the displayed policy authorizes exactly five sequential revisions, ten provider calls, and no Karkinos daily aggregate token limit.',
    normalizedMigrationRequired:
      'The persisted policy is legacy account-bound. Review the normalized-notional authorization above and save it before running.',
    notDailyWinner:
      'This candidate passed its own gate but is not the verified new-candidate winner, so public paper/shadow approval remains blocked.',
    closeTime: 'After-close time',
    researchEndDate: 'Research cutoff (optional)',
    sealedEndDate: 'Final holdout end (optional)',
    sealedDatesDetail:
      'Set both dates before the holdout starts. Research uses data through the cutoff; one champion must be frozen before midnight that day (Shanghai). The holdout must cover 5%–50% of the combined calendar interval and include verified trading days. Leave both blank for exploratory research, which cannot qualify for new account publication.',
    sealedDatesInvalid:
      'Set both dates, with the holdout end after the research cutoff, or leave both blank.',
    question: 'Standing research question',
    operator: 'Owner identity',
    save: 'Save research policy',
    saving: 'Saving…',
    savedPolicy: 'Saved policy',
    enableResearch: 'Enable recurring research',
    policyEditDetail: 'Changes take effect after confirmation and saving.',
    authorizationScope: 'Authorization scope',
    scopeRounds:
      'Per market date: five strictly sequential research rounds with normalized notional capital and at most ten provider calls.',
    scopeUsage:
      'No Karkinos daily aggregate token limit. Usage is recorded; per-request provider and context limits still apply.',
    scopeAuthority:
      'Discovery does not read Account Truth. This grants no promotion, strategy replacement, capital, or trading authority.',
    confirmEnable:
      'I have reviewed the scope above and authorize this research policy.',
    confirmPause: 'I confirm pausing recurring AI strategy research.',
    unsavedPolicy:
      'Unsaved changes. Confirm and save the policy before running.',
    runSavedPolicy: 'Run uses the saved policy and checks eligibility first.',
    policySaved: 'Research policy saved.',
    run: 'Check and schedule research',
    running: 'Checking eligibility…',
    runEnqueued: 'Research queued',
    runAlreadyEnqueued: 'Research is already queued. No duplicate was created.',
    runBlocked: 'Research was not started.',
    runScheduledFor: 'Scheduled for',
    runProviderPending: 'A queued receipt does not mean the model has run.',
    runBlockedReasons: {
      shadow_research_policy_disabled: 'Recurring research is paused.',
      research_worker_kill_switch_status_unavailable:
        'Pause controls are unavailable.',
      kill_switch_enabled: 'The global pause is active.',
      deepseek_provider_not_configured:
        'DeepSeek is not enabled or configured.',
    },
    noCandidates:
      'No completed automated candidate is in the research pool yet.',
    currentCandidates: 'Current research candidates',
    candidateRegistry: 'Candidate registry',
    candidateRegistryDetail:
      'Scan candidate state, then inspect one evidence package at a time.',
    selectedCandidate: 'Selected candidate evidence',
    candidateHistory: 'Historical research candidates',
    candidateHistoryDetail: (count: number) =>
      `${count} older candidates remain available for audit and replay.`,
    baseline: 'Current baseline',
    candidate: 'New candidate',
    return: 'Total return',
    sharpe: 'Sharpe',
    drawdown: 'Max drawdown',
    costs: 'Total cost',
    oos: 'Mean / worst OOS',
    trades: 'Trades',
    risk: 'Risk impact',
    blockers: 'Promotion blockers',
    critique: 'DeepSeek evidence critique',
    approve: 'Approve for paper/shadow only',
    reapprove: 'Re-review for paper/shadow',
    approving: 'Recording approval…',
    approvalNote: 'Human review note',
    approvalConfirm:
      'I reviewed the baseline comparison, costs, rolling OOS, risks and critique. Approve this candidate for paper/shadow research only.',
    approved: 'Paper/shadow approved',
    paused: 'Paper/shadow paused / revoked',
    pause: 'Pause / revoke paper-shadow',
    pausing: 'Recording pause…',
    pauseNote: 'Pause / revocation reason',
    pauseConfirm:
      'I confirm pausing this exact candidate. Existing approval remains auditable, but new tickets must fail closed until a new explicit review.',
    noAuthority:
      'Normalized-notional discovery · Account Truth remains required for promotion/execution · no broker order',
    failure: 'The operation failed closed. No strategy or order was changed.',
    openInStrategyLab: 'Open in Strategy Backtest',
    openInStrategyLabDetail:
      'Open this candidate in Strategy Backtest for parameter sweeps and backtesting',
    critiqueTrajectory: 'Critique self-healing & evolution timeline',
    selfHealingConverged: 'Self-healing converged',
    sequentialFeedbackBound: 'Sequential feedback bound',
    schemaValidationPass: 'Schema contract valid',
    metricEvolution: 'Metric evolution vs baseline',
    evolutionCorrectionNotice:
      'LLM generation passed bounded self-healing correction without schema violation escapes; structured into valid Formula and economic hypothesis.',
  },
  zh: {
    loading: '正在读取已保存自动研究…',
    loadFailed: '无法读取自动研究状态。',
    retry: '重试',
    kicker: 'DeepSeek 收盘后研究',
    title: '自动 shadow 策略研究池',
    detail:
      '持久化行情收盘后，Karkinos 使用归一化名义资金与 canonical 估算成本执行 Formula discovery，不要求也不外发 Account Truth、valuation 或 ledger 事实。Formula 校验、成本后回测和 rolling OOS 均留在本地；账户资格仍是后续晋级与执行的独立门禁。',
    disabled: '已暂停',
    enabled: '已授权',
    killSwitch: 'Kill Switch',
    clear: '未触发',
    calls: '研究交易日模型调用',
    todayCalls: '今日模型调用',
    noCallsToday: '今天尚未记录模型调用',
    lastProviderCall: '最近模型调用',
    researchMarketDate: '对应研究交易日',
    tokens: 'Token 用量',
    tokenPolicy: '每日 Token 策略',
    unboundedDailyTokens: 'Karkinos 不设每日累计上限',
    legacyBoundedDailyTokens: '旧版有界策略 · 重新授权前保持阻断',
    providerLimitsRemain: '仍受模型单次请求与上下文窗口的技术限制',
    tokenAccountingEstimate: '用量核算估计',
    candidates: '串行修订轮数',
    providerWindow: 'DeepSeek 调用窗口',
    offPeakEligible: '低谷期 · 可启动整批',
    offPeakDeferred: '已顺延至低谷期',
    offPeakSchedule:
      '工作日 09:00–12:00 / 14:00–18:00 禁止调用 · 整批须在次日 09:00 前完成',
    nextEligible: '下次可运行',
    dailyWinner: '每日研究结果',
    noWinner: '暂无完整的归一化研究推荐',
    researchNotQualified: '仅供继续研究 · 尚未评估账户资格',
    worstCostStressExcess: '10/25 bps 模拟压力下最差基准净超额',
    costStressUnavailable: '成本压力证据缺失或不可比',
    costStressLegacy: '旧版排序 · 未记录成本压力比较',
    backup: '每日策略备份',
    winnerBadge: '已通过账户资格的晋级优胜者',
    researchWinnerBadge: 'Formula 研究优胜者 · 不可执行',
    qualificationTitle: '账户资格复核',
    qualificationDetail:
      '系统不调用模型，使用同一冻结 Formula 批次和当前权威账户证据复跑。只有精确的资格优胜者可获人工批准，且批准仅限 paper/shadow 研究。',
    qualificationStatus: {
      running: '资格复核运行中',
      completed: '已选出资格优胜者',
      passed: '资格复核通过',
      blocked: '资格复核已阻断',
      failed: '资格复核已 fail closed',
      not_evaluated: '尚未复核',
      not_applicable: '不适用',
    },
    qualificationRun: '最新资格复核运行',
    qualificationAttempt: '最新资格复核尝试',
    qualificationWinnerBinding: '资格优胜者 → 归一化源候选',
    qualificationNotEvaluated: '当前研究结果尚未绑定资格复核运行。',
    qualificationNoWinner: '没有资格优胜者',
    qualificationSourceBound: '已绑定精确的归一化源候选。',
    qualificationSourceUnbound: '缺少精确源候选绑定，人工批准保持不可用。',
    qualificationSourceLocked:
      '归一化源候选仍仅供研究，不能使用原始候选批准入口。',
    qualificationBlockers: '资格复核阻断项',
    qualificationApprovalNote: '资格批准备注',
    qualificationApprovalConfirm:
      '我已复核这个精确的账户资格优胜者，仅批准其进入 paper/shadow 研究；该批准不授予下单、交易或资本权限。',
    qualificationApprove: '仅批准资格优胜者进入 paper/shadow',
    qualificationApproving: '正在记录精确批准…',
    qualificationApproved: '已记录精确的 paper/shadow 批准',
    observationTitle: '前向观察与模拟结果',
    observationBoundary:
      '从这个精确的已保存候选启动独立观察，并在此复核模拟结果。这些观察不能替代独立最终检验或账户资格复核，也不改变人工批准条件。',
    observationUnavailable:
      '尚未绑定具有已保存报告的精确归一化源候选，观察证据不可用。',
    observationSource: '归一化源候选 / 运行',
    observationReport: '源报告',
    observationReportLoading: '正在读取精确源报告…',
    observationReportFailed:
      '源报告不可用或与当前候选不匹配，请重新读取后再启动观察。',
    observationReportRefresh: '重新读取源报告',
    iterationRound: '串行迭代轮次',
    backupVerified: '校验通过',
    fiveCandidateRule:
      '5 轮串行迭代需要 10 次模型调用：每轮生成 1 个修订版、本地权威回测并 critique，再把结果绑定给下一轮；无新优胜者只表示不发生新晋级，当天交易或 NO-ACTION 仍由独立日决策链判断。',
    fiveRoundPolicyBlocked:
      '启用状态下必须明确授权 5 轮严格串行修订、10 次模型调用且 Karkinos 不设每日累计 Token 上限，否则研究运行保持阻断。',
    normalizedMigrationRequired:
      '当前持久化策略仍是旧版账户绑定模式；请复核上方归一化名义本金授权并保存后再运行。',
    notDailyWinner:
      '该候选虽通过自身门槛，但不是已校验的新候选优胜者，因此公开 paper/shadow 批准保持阻断。',
    closeTime: '收盘后时间',
    researchEndDate: '研究截止日（可选）',
    sealedEndDate: '最终检验结束日（可选）',
    sealedDatesDetail:
      '在检验区间开始前同时设置两项日期。研究只使用截止日及之前的数据，并须在截止日当晚北京时间零点前冻结一个优胜候选。检验区间须占研究与检验总日历天数的 5%～50%，且包含已验证交易日。两项留空时可继续探索研究，但不能据此取得新的账户发布资格。',
    sealedDatesInvalid:
      '请同时设置两项日期，且检验结束日须晚于研究截止日；或将两项同时留空。',
    question: '长期研究问题',
    operator: '所有者身份',
    save: '保存研究策略',
    saving: '保存中…',
    savedPolicy: '已保存策略',
    enableResearch: '启用自动研究',
    policyEditDetail: '修改须经确认并保存后生效。',
    authorizationScope: '授权范围',
    scopeRounds:
      '每个交易日使用归一化名义资金，进行 5 轮严格串行研究、最多 10 次模型调用。',
    scopeUsage:
      'Karkinos 不设每日累计 Token 上限；记录用量，仍受模型单次请求及上下文窗口限制。',
    scopeAuthority:
      '研究不读取 Account Truth 账户事实；不授予晋级、策略替换、资本或交易权限。',
    confirmEnable: '我已了解以上范围，确认授权此研究策略。',
    confirmPause: '我确认暂停周期性 AI 策略研究。',
    unsavedPolicy: '有未保存的修改，请先确认并保存后运行。',
    runSavedPolicy: '运行使用已保存策略，并先检查运行条件。',
    policySaved: '研究策略已保存。',
    run: '检查并安排研究',
    running: '正在检查运行条件…',
    runEnqueued: '研究已排入队列',
    runAlreadyEnqueued: '研究已在队列中，未重复创建任务。',
    runBlocked: '研究未启动。',
    runScheduledFor: '计划运行时间',
    runProviderPending: '排队确认不代表模型已运行。',
    runBlockedReasons: {
      shadow_research_policy_disabled: '自动研究已暂停。',
      research_worker_kill_switch_status_unavailable: '无法读取全局暂停状态。',
      kill_switch_enabled: '全局暂停已生效。',
      deepseek_provider_not_configured: 'DeepSeek 尚未启用或配置。',
    },
    noCandidates: '研究池里还没有完成的自动候选。',
    currentCandidates: '当前研究候选',
    candidateRegistry: '候选登记',
    candidateRegistryDetail: '先扫描候选状态，再一次复核一个完整证据包。',
    selectedCandidate: '当前候选证据',
    candidateHistory: '历史研究候选',
    candidateHistoryDetail: (count: number) =>
      `${count} 个较早候选保留用于审计与重放。`,
    baseline: '当前基线',
    candidate: '新候选',
    return: '总收益',
    sharpe: '夏普',
    drawdown: '最大回撤',
    costs: '总成本',
    oos: 'OOS 均值 / 最差',
    trades: '成交数',
    risk: '风险影响',
    blockers: '晋级阻断项',
    critique: 'DeepSeek 证据批判',
    approve: '仅批准进入 paper/shadow',
    reapprove: '重新复核进入 paper/shadow',
    approving: '正在记录批准…',
    approvalNote: '人工复核备注',
    approvalConfirm:
      '我已复核基线对比、成本、rolling OOS、风险与 critique；仅批准该候选进入 paper/shadow 研究。',
    approved: '已批准 paper/shadow',
    paused: 'paper/shadow 已暂停 / 撤销',
    pause: '暂停 / 撤销 paper-shadow',
    pausing: '正在记录暂停…',
    pauseNote: '暂停 / 撤销原因',
    pauseConfirm:
      '我确认暂停这一精确候选；原批准保留供审计，但重新明确复核前，新票据必须 fail closed。',
    noAuthority:
      '归一化名义资金研究 · Account Truth 仅用于后续晋级/执行 · 不会创建 broker 订单',
    failure: '操作已 fail closed；没有修改策略或订单。',
    openInStrategyLab: '在策略回测中打开',
    openInStrategyLabDetail: '克隆该候选策略至策略回测进行人工调参及回测',
    critiqueTrajectory: 'Critique 自愈轨迹与演化时间线',
    selfHealingConverged: '自愈纠偏收敛',
    sequentialFeedbackBound: '已绑定前序轮次反馈',
    schemaValidationPass: '输出契约与Schema校验通过',
    metricEvolution: '回测指标演变（对比基线）',
    evolutionCorrectionNotice:
      '大模型输出经过有界自愈纠偏，无 Schema 异常逃逸，输出已转换为结构化 Formula 与回测假说。',
  },
} as const;

export type ShadowResearchCopy =
  (typeof SHADOW_RESEARCH_COPY)[keyof typeof SHADOW_RESEARCH_COPY];
