import type { PublicLedgerEntry } from './ledger-format-contracts';

// Synthetic paired records; no account data.
export const correctionFixture = {
  id: 103,
  entry_type: 'legacy_fund_trade_duplicate_projection_correction',
  timestamp: '2026-02-10T09:00:01+08:00',
  created_at: '2026-02-20T17:00:00+08:00',
  symbol: 'FIXTURE-FUND',
  display_name: '示例基金',
  asset_class: 'fund',
  amount: 20,
  quantity: -10,
  price: null,
  direction: null,
  commission: 0,
  source: 'legacy_fund_trade_duplicate_repair',
  source_ref: 'repair:fixture:group:fixture',
  note: 'Append-only replay correction for a fingerprint-bound legacy fund trade duplicate group.',
  entry_fingerprint: 'fixture-entry',
  correction_payload: {
    schema_version: 'karkinos.legacy_fund_trade_duplicate_correction_plan.v1',
    authorization_fingerprint: 'fixture-authorization',
    original_ledger_entry_ids: [101],
    canonical_ledger_entry_ids: [102],
    cash_before: '60',
    cash_after: '80',
    position_before: { quantity: '20', avg_cost: '2', realized_pnl: '0' },
    position_after: { quantity: '10', avg_cost: '2', realized_pnl: '0' },
  },
  correction_evidence: {
    status: 'verified',
    entry_fingerprint: 'fixture-entry',
    blockers: [],
    related_entries: [
      {
        role: 'original',
        id: 101,
        entry_type: 'trade_buy',
        timestamp: '2026-02-05T09:00:00+08:00',
        symbol: 'FIXTURE-FUND',
        amount: 20,
        quantity: 10,
        price: 2,
        source: 'manual',
      },
      {
        role: 'retained',
        id: 102,
        entry_type: 'trade_buy',
        timestamp: '2026-02-05T09:00:00+08:00',
        symbol: 'FIXTURE-FUND',
        amount: 20,
        quantity: 10,
        price: 2,
        source: 'portfolio_trade',
      },
    ],
  },
} satisfies PublicLedgerEntry;
