import type { Locale } from '../../shared/locale';

export const tradingCopy = {
  en: {
    page: {
      kicker: 'Manual review',
      title: 'Trading review',
      subtitle:
        'Review the recorded manual-order evidence and capture the operator decision. This page does not submit broker orders.',
      statusCheck: 'Status check',
      operatingMode: 'Operating mode',
      manualDefault: 'Manual confirmation default',
      brokerBridgeDisabled: 'Broker bridge disabled',
      pending: 'Pending review',
      confirmed: 'Confirmed',
      rejected: 'Rejected',
      canceled: 'Canceled',
      lastUpdated: 'Last order update',
      filterTitle: 'Order filters',
      moreFilters: 'More filters',
      moreFiltersDetail: 'Symbol and side',
      statusFilter: 'Status',
      allStatuses: 'All statuses',
      symbolFilter: 'Symbol',
      symbolPlaceholder: 'Filter symbol…',
      sideFilter: 'Side',
      allSides: 'All sides',
      buy: 'Buy',
      sell: 'Sell',
      filteredCount: (count: number) => `${count} visible`,
      ordersTitle: 'Order queue',
      historyKicker: 'Decision log',
      historyTitle: 'Audit trail',
      historyDetail:
        'Confirmed and rejected rows come from the existing manual-order endpoint.',
      noHistory: 'No completed order decisions are available yet.',
      noPublicAuditNote: 'No public note recorded.',
      statusPendingConfirm: 'Pending review',
      brokerBoundaryEvidence: 'Broker boundary evidence',
      brokerBoundaryEvidenceDetail:
        'Adapter readiness, signed release, controlled write, and per-order evidence are audit drill-downs.',
      expandOnDemand: 'Expand on demand',
      statusConfirmed: 'Confirmed',
      statusRejected: 'Rejected',
      statusCanceled: 'Canceled',
      rejectConfirm: 'Reject with reason',
      manualReviewDecision: 'Operator review decision',
      manualReviewDecisionDetail:
        'Records confirmation or rejection only. It does not submit a broker order.',
      manualTicketHandoff: 'Manual ticket handoff',
      executionAudit: 'Execution audit',
      executionAuditTitle: 'Order facts, fills, and simulation review',
      executionAuditDetail:
        'Review normalized order/fill evidence and manually trigger a simulated review without sending broker orders.',
      simulationReviewAction: 'Paper/shadow review action',
      simulationReviewActionDetail:
        'Creates or records simulation evidence only. It does not submit a broker order or mutate the production ledger.',
      auditLoading: 'Loading execution evidence.',
      auditLoadFailed: 'Execution evidence is unavailable.',
      orderFacts: 'Order facts',
      fills: 'Fill facts',
      noOrderFacts: 'No normalized order facts yet.',
      noFills: 'No fill facts have been recorded yet.',
      commission: 'Commission',
      runShadowReview: 'Run daily simulation review',
      runningShadowReview: 'Running simulation review',
      shadowRunResult: (processed: number, reused: number) =>
        `Simulation review prepared ${processed} orders and reused ${reused}.`,
      simulationReviewNeedsAttention: 'Simulation review needs attention',
      simulationReviewNeedsAttentionDetail:
        'Review the latest simulated order/fill evidence before manual confirmation.',
      recordSimulationReview: 'Record simulation review',
      recordingSimulationReview: 'Recording simulation review',
      simulationReviewAccepted:
        'Simulation review accepted; continue with manual confirmation.',
      simulationReviewFailed: 'Simulation review could not be recorded.',
      manualTicketExportTitle: 'Manual ticket export',
      manualTicketExportDetail:
        'Copy this payload into the broker client manually. Karkinos does not submit it.',
      manualTicketExportCopyText: 'Broker copy text',
      manualTicketExportPayload: 'JSON payload',
      manualTicketExportSafety: 'submitted_to_broker=false',
      manualTicketAccountAlias: 'Account alias',
      manualTicketEstimatedTotalFee: 'Estimated total fee',
      manualTicketTradingSession: 'Trading session',
      manualTicketNetCashImpact: 'Net cash impact',
      manualTicketPositionAfter: 'Position after',
      manualTicketCostBasisMethod: 'Cost basis method',
      manualExecutionPreviewTitle: 'Manual execution preview',
      manualExecutionPreviewDetail:
        'Preview the operator-entered fill economics and ledger draft without saving production records.',
      previewManualExecution: 'Preview manual execution',
      previewingManualExecution: 'Previewing manual execution',
      manualExecutionFillPrice: 'Fill price',
      manualExecutionQuantity: 'Quantity',
      manualExecutionFee: 'Fee',
      manualExecutionTax: 'Tax',
      manualExecutionTransferFee: 'Transfer fee',
      manualExecutionGrossAmount: 'Gross amount',
      manualExecutionFeeTax: 'Fee / tax',
      manualExecutionNetCashImpact: 'Net cash impact',
      manualExecutionPositionPreview: 'Execution position preview',
      manualExecutionCurrentQuantity: 'Current quantity',
      manualExecutionCurrentAvgCost: 'Current average cost',
      manualExecutionCurrentMarketValue: 'Current market value',
      manualExecutionPositionAfter: 'Quantity after execution',
      manualExecutionAvgCostAfter: 'Average cost after execution',
      manualExecutionPositionPreviewSource: 'Position preview source',
      manualExecutionLedgerDraft: 'Ledger draft',
      manualExecutionPreviewFingerprint: 'Preview fingerprint',
      manualExecutionFingerprintScope: 'Fingerprint scope',
      manualExecutionSafety: 'Preview safety',
      manualExecutionGateSummary: 'Controlled bridge gate summary',
      manualExecutionLimitations: 'Manual execution limitations',
      recordManualExecution: 'Record manual execution evidence',
      recordingManualExecution: 'Recording manual execution evidence',
      manualExecutionRecordTitle: 'Manual execution evidence recorded',
      manualExecutionRecordDetail:
        'Gateway evidence was recorded for audit only; ledger save and broker submission remain separate.',
      manualExecutionGatewayEvent: 'Gateway event',
      manualExecutionRecordSafety: 'Record safety',
    },
    killSwitch: {
      kicker: 'Trading controls',
      title: 'Global kill switch',
      subtitle:
        'Block new buy orders before they reach broker execution. Sell-side risk reduction and cancel flows remain available.',
      loading: 'Checking',
      enabled: 'Kill switch active',
      disabled: 'Trading allowed',
      enable: 'Enable kill switch',
      disable: 'Disable kill switch',
      submitting: 'Updating...',
      reason: 'Operator reason',
      reasonPlaceholder: 'Required before blocking new buy orders',
      currentReasonPlaceholder: 'Current reason',
      reasonRequired: 'Enter a reason before enabling the kill switch.',
      updatedAt: 'Updated',
      neverUpdated: 'Never',
      loadFailed: 'Failed to load kill switch state.',
    },
    orders: {
      kicker: 'Manual execution',
      title: 'Pending order approvals',
      subtitle:
        'Orders that passed pre-trade risk checks wait here until an operator confirms or rejects them.',
      loading: 'Loading pending orders.',
      loadFailed: 'Failed to load pending orders.',
      empty: 'No orders are waiting for manual confirmation.',
      pendingCount: (count: number) => `${count} awaiting approval`,
      symbol: 'Symbol',
      side: 'Side',
      buy: 'Buy',
      sell: 'Sell',
      quantity: 'Quantity',
      price: 'Price',
      riskHint: 'Risk audit',
      rejectReason: 'Reject reason',
      rejectReasonPlaceholder: 'Required to reject…',
      rejectReasonRequired: 'Enter a reject reason before rejecting an order.',
      actions: 'Actions',
      confirm: 'Confirm',
      reject: 'Reject',
      exportTicket: 'Export ticket',
      exportingTicket: 'Exporting',
      riskApproved: 'Pre-trade check passed',
      decisionId: 'Decision',
      intentId: 'Intent',
    },
  },
  zh: {
    page: {
      kicker: '人工复核',
      title: '交易复核',
      subtitle:
        '复核已记录的人工订单证据并登记操作决定；本页不会向券商提交订单。',
      statusCheck: '状态检查',
      operatingMode: '运行模式',
      manualDefault: '默认人工确认',
      brokerBridgeDisabled: '券商桥接未启用',
      pending: '待复核',
      confirmed: '已确认',
      rejected: '已拒绝',
      canceled: '已取消',
      lastUpdated: '最近订单更新',
      filterTitle: '订单筛选',
      moreFilters: '更多筛选',
      moreFiltersDetail: '标的与方向',
      statusFilter: '状态',
      allStatuses: '全部状态',
      symbolFilter: '标的',
      symbolPlaceholder: '筛选代码…',
      sideFilter: '方向',
      allSides: '全部方向',
      buy: '买入',
      sell: '卖出',
      filteredCount: (count: number) => `${count} 条可见`,
      ordersTitle: '订单队列',
      historyKicker: '决策日志',
      historyTitle: '审计记录',
      historyDetail: '已确认与已拒绝记录来自现有人工订单接口。',
      noHistory: '当前还没有已完成的订单决策。',
      noPublicAuditNote: '暂无公开备注。',
      statusPendingConfirm: '待复核',
      brokerBoundaryEvidence: '券商边界证据',
      brokerBoundaryEvidenceDetail:
        '适配器就绪、签名放行、受控写入和逐单证据属于审计下钻。',
      expandOnDemand: '按需展开',
      statusConfirmed: '已确认',
      statusRejected: '已拒绝',
      statusCanceled: '已取消',
      rejectConfirm: '填写原因并拒绝',
      manualReviewDecision: '操作员复核决定',
      manualReviewDecisionDetail: '仅记录确认或拒绝；不会提交券商订单。',
      manualTicketHandoff: '手工票据交接',
      executionAudit: '执行审计',
      executionAuditTitle: '订单事实、成交事实与模拟复核',
      executionAuditDetail:
        '查看归一化订单/成交证据，并手动触发模拟复核；不会提交券商订单。',
      simulationReviewAction: '模拟复核操作',
      simulationReviewActionDetail:
        '仅创建或记录模拟证据；不会提交券商订单，也不会修改生产账本。',
      auditLoading: '正在加载执行证据。',
      auditLoadFailed: '执行证据暂不可用。',
      orderFacts: '订单事实',
      fills: '成交事实',
      noOrderFacts: '当前还没有归一化订单事实。',
      noFills: '当前还没有成交事实。',
      commission: '手续费',
      runShadowReview: '运行当日模拟复核',
      runningShadowReview: '模拟复核中',
      shadowRunResult: (processed: number, reused: number) =>
        `模拟复核准备 ${processed} 笔订单，复用 ${reused} 笔。`,
      simulationReviewNeedsAttention: '模拟复核需要处理',
      simulationReviewNeedsAttentionDetail:
        '人工确认前先复核最新模拟订单/成交证据。',
      recordSimulationReview: '记录模拟复核',
      recordingSimulationReview: '正在记录模拟复核',
      simulationReviewAccepted: '模拟复核已接受，可继续人工确认。',
      simulationReviewFailed: '模拟复核记录失败。',
      manualTicketExportTitle: '手工票据导出',
      manualTicketExportDetail:
        '将这份载荷手动录入券商客户端；Karkinos 不会提交券商订单。',
      manualTicketExportCopyText: '券商录入文本',
      manualTicketExportPayload: 'JSON 载荷',
      manualTicketExportSafety: 'submitted_to_broker=false',
      manualTicketAccountAlias: '账户别名',
      manualTicketEstimatedTotalFee: '预估总费用',
      manualTicketTradingSession: '交易时段',
      manualTicketNetCashImpact: '现金影响',
      manualTicketPositionAfter: '计划后持仓',
      manualTicketCostBasisMethod: '成本口径',
      manualExecutionPreviewTitle: '手工成交预览',
      manualExecutionPreviewDetail:
        '预览操作员录入的成交经济性和账本草稿，不写入生产账本。',
      previewManualExecution: '预览手工成交',
      previewingManualExecution: '正在预览手工成交',
      manualExecutionFillPrice: '成交价',
      manualExecutionQuantity: '数量',
      manualExecutionFee: '费用',
      manualExecutionTax: '税费',
      manualExecutionTransferFee: '过户费',
      manualExecutionGrossAmount: '成交金额',
      manualExecutionFeeTax: '费用 / 税费',
      manualExecutionNetCashImpact: '现金影响',
      manualExecutionPositionPreview: '成交后持仓预览',
      manualExecutionCurrentQuantity: '当前数量',
      manualExecutionCurrentAvgCost: '当前均价',
      manualExecutionCurrentMarketValue: '当前市值',
      manualExecutionPositionAfter: '成交后数量',
      manualExecutionAvgCostAfter: '成交后均价',
      manualExecutionPositionPreviewSource: '持仓预览来源',
      manualExecutionLedgerDraft: '账本草稿',
      manualExecutionPreviewFingerprint: '预览指纹',
      manualExecutionFingerprintScope: '指纹范围',
      manualExecutionSafety: '预览边界',
      manualExecutionGateSummary: '受控桥接门禁摘要',
      manualExecutionLimitations: '手工成交限制',
      recordManualExecution: '记录手工成交证据',
      recordingManualExecution: '正在记录手工成交证据',
      manualExecutionRecordTitle: '手工成交证据已记录',
      manualExecutionRecordDetail:
        'Gateway 证据仅用于审计；账本保存和券商提交仍是独立流程。',
      manualExecutionGatewayEvent: 'Gateway 事件',
      manualExecutionRecordSafety: '记录边界',
    },
    killSwitch: {
      kicker: '交易控制',
      title: '全局熔断开关',
      subtitle:
        '在订单触达券商前拦截新的买入委托。卖出减仓和撤单类流程仍可继续执行。',
      loading: '检查中',
      enabled: '熔断已开启',
      disabled: '允许交易',
      enable: '开启熔断',
      disable: '解除熔断',
      submitting: '更新中...',
      reason: '操作原因',
      reasonPlaceholder: '开启买单熔断前必须填写原因',
      currentReasonPlaceholder: '当前熔断原因',
      reasonRequired: '开启熔断前必须填写原因。',
      updatedAt: '更新时间',
      neverUpdated: '从未更新',
      loadFailed: '熔断状态读取失败。',
    },
    orders: {
      kicker: '人工执行',
      title: '待确认订单审批',
      subtitle:
        '已通过事前风控的订单会停在这里，等待人工确认或拒绝后才进入下游执行。',
      loading: '正在加载待确认订单。',
      loadFailed: '待确认订单加载失败。',
      empty: '当前没有等待人工确认的订单。',
      pendingCount: (count: number) => `${count} 等待审批`,
      symbol: '标的',
      side: '方向',
      buy: '买入',
      sell: '卖出',
      quantity: '数量',
      price: '价格',
      riskHint: '风控审计',
      rejectReason: '拒绝原因',
      rejectReasonPlaceholder: '拒绝时必填…',
      rejectReasonRequired: '拒绝订单前必须填写原因。',
      actions: '操作',
      confirm: '确认通过',
      reject: '拒绝/撤销',
      exportTicket: '导出票据',
      exportingTicket: '导出中',
      riskApproved: '事前风控已通过',
      decisionId: '决策',
      intentId: '意图',
    },
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type TradingCopy = (typeof tradingCopy)[Locale];

declare module '../../shared/i18n/context' {
  interface ApplicationCopy {
    trading: TradingCopy;
  }
}
