export const overviewCopyZh = {
  kicker: '总览',
  title: '今日投资工作台',
  subtitle: '先确认账户事实，再处理异常与当前持仓，最后进入分析与历史。',
  modeHelper: '账户视角看资本结构，策略视角看收益质量和执行结果。',
  loading: '正在读取账户事实和当前持仓。',
  error: '账户总览或当前持仓读取失败。',
  curveLoading: '正在加载净值曲线。',
  curveError: '净值曲线读取失败。',
  curveSnapshotPending:
    '估值输入已变化，但新的不可变快照尚未发布完成；未绑定的财务读取仍被阻断，请稍后重试。',
  curveRefreshError:
    '刷新失败；当前继续展示上一次已发布且已绑定身份的净值曲线，可手动重试。',
  empty: '还没有可展示的账户数据。',
  cards: {
    totalAssets: '总资产',
    availableCash: '可用现金',
    todayPnl: '今日盈亏',
    latestTradingDayPnl: '最近交易日盈亏',
    marketClosedPnlContext: '今日休市，展示最近可用估值的盈亏。',
    todayStocks: '股票',
    todayFunds: '基金',
    todayTotal: '合计',
    todayContributors: '今日贡献',
    exposureSummary: '组合暴露摘要',
    stockExposure: '股票市值占比',
    fundExposure: '基金市值占比',
    cashExposure: '现金占比',
    largestHolding: '最大单一持仓',
    largestHoldingUnavailable: '当前没有未平仓资产暴露。',
    exposureUnavailable: '总权益为零或缺失，组合暴露暂不可用。',
    exposurePartial: '部分估值',
    cumulativeReturn: '累计收益',
    netDeposits: '净投入',
    unrealizedPnl: '浮动盈亏',
    cashRatio: '现金占比',
    currentDrawdown: '当前回撤',
    drawdownPeak: '峰值',
    positionsCount: '活跃持仓',
    cachedValuation: '行情缓存 · 估值时间',
    valuationStatus: (status: string) => `估值状态：${status}`,
    evidenceReady: '证据完整',
    supportingMetrics: '账户辅助指标',
    evidenceIdentity: (asOf: string) => `估值截至 ${asOf}`,
  },
  dashboard: {
    equityPanel: '资金曲线',
    opsPanel: '复核队列',
    dailyWorkbench: '今日待办',
    todayToReview: '今天需要处理',
    additionalReviewItems: (count: number) => `${count} 个其他待复核项`,
    noActionItems: '当前没有紧急事项。',
    noActionItemsDetail: '行情、审批和策略证据暂时不需要立即处理。',
    operationsTower: '执行状态',
    operationsConclusion: '今日状态',
    operationsNoManualAction: '今日无需手动交易',
    operationsPendingManual: (count: number) => `${count} 项待人工确认`,
    operationsPlanIntentsReady: (count: number) =>
      `${count} 个交易计划意图待复核`,
    operationsRiskBlocked: (count: number) => `${count} 项风控阻断需要复核`,
    operationsAccountTruthBlocked: '账户事实未通过，暂停执行复核',
    operationsDataUnavailable: '行情数据不可用，暂停候选复核',
    operationsExecutionException: (count: number) =>
      `${count} 项执行异常需要复核`,
    operationsCandidatePool: '候选池',
    operationsEvidencePassed: '证据通过',
    operationsRiskPassed: '风控通过',
    operationsManualReady: '计划意图待复核',
    operationsPendingOrders: '待确认订单意图',
    operationsExecutionRecords: '执行记录',
    operationsLedgerReview: '账本待复核',
    operationsDefaultMode: '默认模式',
    operationsBrokerBridge: '券商桥接',
    operationsManualConfirmation: '人工确认',
    operationsBrokerDisabled: '未启用',
    operationsViewCandidates: '复核交易计划',
    operationsViewRisk: '查看风控原因',
    operationsViewTrading: '进入人工确认',
    operationsViewLedger: '核对账本',
    operationsViewAccountTruth: '复核账户事实',
    operationsViewMarket: '复核行情数据',
    operationsViewPaperShadow: '复核模拟证据',
    queuePriorityFirst: '先处理',
    queuePriorityWatch: '今日关注',
    queuePriorityNormal: '正常状态',
    resolutionCondition: (condition: string) =>
      `解除条件：${condition}。仅查看或确认不会清除此状态。`,
    dataResolutionCondition:
      '更新且已确认的行情或净值覆盖全部当前持仓，并绑定同一估值与流水范围；仅查看不会清除。',
    strategyNoLinkedFillsResolution:
      '无需处理：只有完成对账的成交被明确关联到策略证据后，系统才会展示策略贡献。',
    strategyEvidenceResolution:
      '信号、复核、订单、成交、流水记录与估值引用形成同一条可审计证据链。',
    dataUsable: '行情与净值可用于解读。',
    dataNeedsReview: '行情或净值需要复核。',
    dataReviewLoading: '正在读取当前持仓证据。',
    dataReviewUnavailable: '当前持仓证据暂不可用；账户解读继续阻断。',
    dataReviewIdentityBlocked: '账户估值或流水范围不完整；需要先恢复证据关联。',
    dataReviewConfirmedCount: (count: number) => `${count} 个当前持仓已确认`,
    dataReviewSummary: (
      fundNav: number,
      stale: number,
      missing: number,
      estimated: number,
      unknown: number,
    ) =>
      [
        fundNav > 0 ? `${fundNav} 基金净值` : null,
        stale > 0 ? `${stale} 陈旧/缓存` : null,
        missing > 0 ? `${missing} 缺失/错误` : null,
        estimated > 0 ? `${estimated} 估算` : null,
        unknown > 0 ? `${unknown} 未知状态` : null,
      ]
        .filter(Boolean)
        .join(' · '),
    pendingOrdersReady: '订单等待人工确认',
    pendingOrdersClear: '暂无待确认订单',
    strategyCandidateAction: '策略候选信号',
    strategyCandidateClear: '暂无策略候选信号',
    strategyCandidateLoading: '正在加载策略候选信号',
    strategyDecisionUnavailable: '策略候选信号暂不可用',
    strategyCandidateEmptyDetail:
      '当前没有买入、卖出、持有或再平衡信号进入队列。',
    tradingPlanUnavailable: '今日交易计划暂不可用',
    tradingPlanLoading: '正在加载今日交易计划',
    tradingPlanNeedsReview: '今日交易计划需要复核',
    tradingPlanCashShortfall: '买入预览因现金不足阻断',
    tradingPlanManualReady: (count: number) => `${count} 个交易计划意图待复核`,
    tradingPlanManualReadyDetail: (count: number) =>
      `先复核 ${count} 个带证据引用的订单意图，再准备手工订单。`,
    tradingPlanManualIntentDetail: (
      side: string,
      symbol: string,
      quantity: number,
    ) => `${side} · ${symbol} · ${quantity}`,
    tradingPlanBlockedDetail: (count: number) =>
      `${count} 个阻断需要先清除，才能进入人工确认。`,
    tradingPlanCashShortfallDetail: (amount: string) =>
      `确认前先复核现金分配。现金缺口：${amount}。`,
    tradingPlanMeta: (
      manualReady: number,
      candidates: number,
      blockers: number | string,
    ) =>
      typeof blockers === 'number'
        ? `${manualReady} 意图待复核 · ${candidates} 候选池 · ${blockers} 阻断`
        : `${manualReady} 意图待复核 · ${candidates} 候选池 · ${blockers}`,
    strategyEvidenceLinked: '策略贡献已连接证据',
    strategyNoLinkedFills: '策略尚无可归属成交',
    strategyEvidenceRequired: '策略贡献需要补充证据',
    strategyUnavailable: '策略贡献暂不可用',
    viewData: '查看数据状态',
    viewDecision: '查看决策证据',
    viewOperations: '查看运行证据',
    viewTrading: '复核交易队列',
    viewStrategy: '查看策略证据',
    candidateCount: (count: number) => `${count} 个候选信号`,
    decisionActionLabels: {
      buy: '买入候选',
      sell: '卖出候选',
      hold: '持有候选',
      rebalance: '再平衡候选',
      no_action: '不操作',
      review_required: '需要复核',
    },
    marketPulse: '市场脉搏',
    marketPulseDetail:
      '查看今日大盘行情背景。这里只展示市场环境，不给出交易指令。',
    marketPulseMissing:
      '暂时没有可用的大盘指数行情。可以前往市场页补充或刷新指数数据。',
    marketPulsePositive: '大盘偏强',
    marketPulseNegative: '大盘偏弱',
    marketPulseMixed: '大盘分化',
    marketPulsePending: '指数待补齐',
    marketPulseNoSignal: '趋势待确认',
    marketPulseDisclosure: '仅作市场背景',
    marketPulseMoveMissing: '涨跌缺失',
    marketPulseMissingChanges: (count: number) => `${count} 个指数涨跌缺失`,
    marketPulseChangeCoverage: (available: number, total: number) =>
      `涨跌覆盖 ${available}/${total}`,
    marketHeatmapUnavailable: '市场热力图待证据',
    marketHeatmapUnavailableDetail:
      '当前数据仅覆盖指数点位，尚无可核对的全市场或行业广度数据，因此不显示热力图。',
    viewMarket: '打开市场页',
    viewHoldingDetail: '查看持仓详情',
    todayMove: '今日变化',
    sinceBuyMove: '持有以来',
    quoteStatusLabel: '行情状态',
    pendingApprovals: '待审批订单',
    pendingEmpty: '当前没有需要审批的订单。',
    pendingEmptyDetail: '通过风控后的订单会先进入这里，确认后才继续执行。',
    pendingCount: (count: number) => `${count} 笔待审批`,
    ledgerPanel: '最新流水',
    ledgerCount: (count: number) => `${count} 条流水`,
    ledgerEmpty: '还没有账本流水。',
    positionsPanel: '当前持仓',
    positionsDetail: '行情价格、成本、市值与浮动盈亏均来自当前账户视图。',
    quickActions: '快捷操作',
    refreshQuotes: '刷新行情',
    refreshingQuotes: '刷新中',
    addLedger: '添加流水',
    tradingDesk: '交易审批',
    dataSettings: '数据源设置',
    dataStatus: '数据状态',
    valuationTime: '估值时间',
    quoteAge: '行情年龄',
    staleReason: '缓存原因',
    refreshPolicy: '刷新策略',
    quoteSource: '行情来源',
    affectedHoldings: '影响标的',
    affectedCount: (count: number) => `${count} 个标的需要确认`,
    usingEstimate: '使用估算',
    waitingConfirmedNav: '等待确认净值',
    checkDataSource: '检查数据源',
    refreshFailed: '行情刷新失败',
    refreshDone: '行情刷新完成',
    tradeBuy: '买入',
    tradeSell: '卖出',
    cashDeposit: '入金',
    cashWithdrawal: '出金',
    dividend: '分红',
    adjustment: '调整',
    unknownActivity: '账本事件',
  },
  equityCurve: {
    title: '净值分析',
    range: '区间',
    total: '总计',
    stocks: '股票',
    funds: '基金',
    others: '其他',
    cash: '现金',
    allSeries: '全选',
    oneDay: '1D',
    fiveDays: '5D',
    oneMonth: '1M',
    sixMonths: '6M',
    oneYear: '1年',
    all: 'ALL',
    empty: '还没有净值历史。',
    emptyTitle: '尚无净值历史',
    emptyPeriod: '当前区间暂无可用数据。',
    insufficientData: '该区间数据不足。',
    emptyDetail: '先录入首笔资金流水或交易，系统才会开始生成净值曲线。',
    emptyHint: '账户形成连续历史记录后，净值曲线会出现在这里。',
    currentPoint: '当前估值点',
    categoryDailyChange: (label: string) => `${label}截至此时变化`,
    unconfirmedCategoryDailyChange: (label: string) => `${label}变化待确认`,
    portfolioTotal: '组合总计',
    rangeHigh: '区间最高',
    quoteStatus: '行情状态',
    realtimeUnrealizedPnl: '组合浮动盈亏',
    cachedValuation: '估值基于缓存行情',
    valuationStatus: (status: string) => `估值状态：${status}`,
  },
  livePulse: {
    title: '资产脉冲',
    subtitle: '按资产类别快速查看持仓市值、行情涨跌和买入以来收益。',
    loading: '正在加载分组持仓。',
    error: '分组持仓加载失败。',
    empty: '当前还没有活跃持仓。',
    marketValue: '持仓市值',
    todayMove: '今日涨跌',
    sinceBuyReturn: '买入以来收益',
  },
  risk: {
    registerKicker: '风险边界',
    title: '风险边界登记',
    subtitle: '只读查看集中度、流动性、仓位利用与执行默认边界。',
    concentration: '最大持仓权重',
    concentrationBoundary: '单标的集中度复核',
    cashBuffer: '现金缓冲',
    cashBoundary: '新增暴露前的流动性底线',
    deployment: '资金利用率',
    deploymentBoundary: '在场资金压力',
    positions: '活跃持仓',
    positionsBoundary: '当前风险敞口数量',
    positionsHint: (count: number) => `${count} 个持仓在场`,
    boundary: '边界',
    current: '当前值',
    cashHealthy: '现金缓冲健康',
    cashWatch: '现金缓冲偏薄',
    deploymentBalanced: '仓位节奏平衡',
    deploymentHigh: '当前仓位偏热',
    executionBoundary: '执行边界',
    executionBoundaryDetail:
      '类实盘流程默认保持闸门控制，必须由操作人复核订单并手动确认。',
    manualConfirmationRequired: '需要人工确认',
  },
  breakdown: {
    accountKicker: '账户拆解',
    strategyKicker: '策略拆解',
    accountTitle: '资金结构与配置节奏',
    strategyTitle: '收益质量与执行结果',
    marketValue: '持仓市值',
    activePositions: (count: number) => `${count} 个活跃持仓`,
    cashReserve: '现金储备',
    netDeposits: '净投入',
    capitalBase: '净投入本金',
    deployment: '仓位利用率',
    capitalAtWork: '已投入仓位',
    unrealizedPnl: '浮动盈亏',
    openPositions: '来自当前持仓',
    realizedPnl: '已实现盈亏',
    closedActivity: '来自已落袋交易',
    totalPnl: '总收益',
    totalPnlHint: '已实现 + 浮动',
    payoutBuffer: '再配置缓冲',
    payoutBufferHint: '可用于继续配置的现金',
  },
} as const;
