import { usePreferences, type Locale } from "./preferences";

export const copy = {
  en: {
    shell: {
      title: "Portfolio OS",
      description:
        "Portfolio workspace for holdings, cash, activity, and valuation.",
      language: "Language",
      theme: "Theme",
      navigation: "Navigation",
      openNavigation: "Open navigation",
      closeNavigation: "Close navigation",
      toolbarTitle: "Workspace toolbar",
      toolbarSubtitle:
        "Keep preferences and portfolio status in one consistent global toolbar.",
      accountStatus: "Account Status",
      apiStatus: "API",
      navStatus: "NAV",
      themeStatus: "Theme",
      ledgerMode: "Ledger synced",
      valuationMode: "Valuation active",
      brokerMode: "Broker API ready",
      light: "Light",
      dark: "Dark",
      system: "System",
      systemThemeLabel: "System theme",
      lightThemeLabel: "Light theme",
      darkThemeLabel: "Dark theme",
      nav: {
        overview: "Overview",
        portfolio: "Portfolio",
        activity: "Activity",
        risk: "Risk",
        market: "Market",
        settings: "Settings",
      },
    },
    states: {
      loading: "Loading",
      error: "Request failed",
      empty: "No data yet",
      retry: "Retry",
    },
    common: {
      required: "This field is required.",
      mustBePositive: "Enter a value greater than zero.",
      genericSubmitError: "Request failed. Check your payload and server logs.",
      assetClassStock: "Stock",
      assetClassEtf: "ETF",
      assetClassFund: "Fund",
      assetClassGold: "Gold",
      assetClassBond: "Bond",
    },
    mode: {
      account: "Account view",
      strategy: "Strategy view",
      accountShort: "Account",
      strategyShort: "Strategy",
    },
    overview: {
      kicker: "Overview",
      title: "Portfolio workspace",
      subtitle:
        "Track capital structure, return breakdown, and equity movement in one place.",
      modeHelper:
        "Account view focuses on capital structure. Strategy view focuses on return quality.",
      loading: "Loading account overview and portfolio snapshot.",
      error: "Failed to load account overview or snapshot.",
      curveLoading: "Loading equity curve.",
      curveError: "Failed to load equity curve.",
      empty: "No account data available yet.",
      cards: {
        totalAssets: "Total Assets",
        availableCash: "Available Cash",
        unrealizedPnl: "Unrealized PnL",
        cashRatio: "Cash Ratio",
      },
      equityCurve: {
        title: "Equity Curve",
        range: "Range",
        oneMonth: "1M",
        threeMonths: "3M",
        oneYear: "1Y",
        all: "All",
        empty: "No equity history yet.",
        emptyTitle: "No Equity History Yet",
        emptyDetail:
          "Record the first cash flow or trade to start building the equity curve.",
        emptyHint: "The curve appears after the portfolio has time-series ledger points.",
      },
      livePulse: {
        title: "Live asset pulse",
        subtitle:
          "Review grouped holdings by asset class with intraday move and since-buy return.",
        loading: "Loading live grouped holdings.",
        error: "Failed to load live grouped holdings.",
        empty: "No active holdings yet.",
        marketValue: "Market value",
        todayMove: "Today move",
        sinceBuyReturn: "Since-buy return",
      },
      risk: {
        title: "Risk Summary",
        concentration: "Top Holding Weight",
        cashBuffer: "Cash Buffer",
        deployment: "Capital Deployment",
        positions: "Active Positions",
        positionsHint: (count: number) => `${count} open positions`,
        cashHealthy: "Healthy reserve",
        cashWatch: "Cash reserve is getting thin",
        deploymentBalanced: "Deployment is balanced",
        deploymentHigh: "Portfolio is running hot",
      },
      breakdown: {
        accountKicker: "Account breakdown",
        strategyKicker: "Strategy breakdown",
        accountTitle: "Capital structure and deployment",
        strategyTitle: "Returns and execution outcome",
        marketValue: "Market Value",
        activePositions: (count: number) => `${count} active positions`,
        cashReserve: "Cash Reserve",
        netDeposits: "Net Deposits",
        capitalBase: "Capital base",
        deployment: "Deployment",
        capitalAtWork: "Capital at work",
        unrealizedPnl: "Unrealized PnL",
        openPositions: "Open positions",
        realizedPnl: "Realized PnL",
        closedActivity: "Closed activity",
        totalPnl: "Total PnL",
        totalPnlHint: "Realized + unrealized",
        payoutBuffer: "Payout Buffer",
        payoutBufferHint: "Cash available for redeploy",
      },
    },
    portfolio: {
      kicker: "Portfolio",
      title: "Holdings and allocation workspace",
      subtitle:
        "Filter holdings by symbol, asset class, and PnL focus while keeping allocation and return structure in view.",
      positionsLoading: "Loading positions.",
      positionsError: "Failed to load positions.",
      positionsEmpty: "No holdings yet. Add trades from Activity first.",
      filterEmpty: "No holdings match the current filters.",
      sidebarLoading: "Loading allocation and performance breakdown.",
      sidebarError: "Failed to load allocation or performance breakdown.",
      sidebarEmpty: "No allocation view is available yet.",
      toolbar: {
        view: "View",
        helper:
          "Account emphasizes capital structure. Strategy emphasizes return quality.",
        search: "Search",
        searchPlaceholder: "Filter by symbol",
        assetClass: "Asset Class",
        allAssetClasses: "All asset classes",
        pnlFocus: "PnL Focus",
        allHoldings: "All holdings",
        winnersOnly: "Winners only",
        losersOnly: "Losers only",
      },
      table: {
        symbol: "Symbol",
        assetClass: "Asset Class",
        quantity: "Quantity",
        availFrozen: "Avail/Frozen",
        avgCost: "Avg Cost",
        marketValue: "Market Value",
        unrealized: "Unrealized",
        realized: "Realized",
        detailsTitle: "Holding Details",
      },
      allocation: {
        title: "Allocation",
        empty: "No allocation matches the current scope yet.",
      },
      allocationGroups: {
        title: "Allocation Groups",
        empty: "No grouped allocation available yet.",
      },
      liveBoard: {
        title: "Live holdings board",
        subtitle:
          "Track grouped holdings with latest price, intraday move, and since-buy return.",
        loading: "Loading live holdings.",
        error: "Failed to load live holdings.",
        empty: "No active holdings yet. Record the first trade to start tracking live returns.",
        latestPrice: "Latest price",
        todayMove: "Today move",
        sinceBuyReturn: "Since-buy return",
        updatedAt: "Updated",
        baseline: "Baseline",
        baselinePreviousClose: "Previous close",
        baselineFallbackClose: "Fallback close",
        baselineUnavailable: "Daily baseline unavailable",
        quoteLive: "Live quote",
        quoteStale: "Stale quote",
      },
    },
    riskPage: {
      kicker: "Risk",
      title: "Risk workspace",
      subtitle:
        "Review current alerts, capital pressure, and equity attribution in one place.",
      loading: "Loading risk workspace.",
      error: "Failed to load risk workspace.",
      alerts: "Active alerts",
      nextStep: "Suggested next step",
      equityBridge: "Equity bridge",
      recentDrivers: "Recent drivers",
      positionDrivers: "Position drivers",
      emptyDrivers: "No explainability drivers available yet.",
      metrics: "Risk metrics",
      currentDrawdown: "Current drawdown",
      currentDrawdownDetail:
        "Distance between current equity and the latest portfolio peak.",
      maxDrawdown: "Max drawdown",
      maxDrawdownDetail:
        "Largest observed peak-to-trough loss across the equity curve.",
      grossExposure: "Gross exposure",
      grossExposureDetail: "Capital currently deployed in non-cash positions.",
      cashRatio: "Cash ratio",
      cashRatioDetail: "Immediate liquidity buffer for rebalance or defense.",
      largestPosition: "Largest position",
      largestPositionDetail: "Single-name concentration of the biggest live holding.",
      top3Concentration: "Top 3 concentration",
      top3ConcentrationDetail:
        "Aggregate concentration across the three largest holdings.",
      drawdown: "Drawdown path",
      exposure: "Exposure buckets",
      bucketHeavy: "Heavy conviction",
      bucketCore: "Core",
      bucketStarter: "Starter",
      bucketSmall: "Small / tracking",
      bucketCash: "Cash reserve",
      concentration: "Concentration drill-down",
      noConcentration: "No live positions available for concentration analysis.",
    },
    market: {
      kicker: "Market",
      title: "Research workspace",
      subtitle:
        "Track coverage, quote health, price structure, and research records for each symbol.",
      loading: "Loading research board.",
      error: "Failed to load research board.",
      watchlist: "Research board",
      health: "Data health",
      chart: "Price structure",
      addSymbol: "Add symbol",
      symbolPlaceholder: "Symbol",
      assetClass: "Asset class",
      add: "Add",
      remove: "Remove",
      marketOpen: "Market open",
      marketClosed: "Market closed",
      refreshPolicy: "Refresh policy",
      selectedSymbol: "Selected symbol",
      symbolLabel: "Symbol",
      priceLabel: "Price",
      snapshotLabel: "Snapshot time",
      holdingsContext: "Holding context",
      noSelection: "Select or add a symbol to start research.",
      noChart: "No price structure available for the selected symbol.",
      promptsTitle: "Research checklist",
      notesTitle: "Research notes",
      notesEmpty: "No notes yet. Capture the current thesis before the market moves.",
      noteType: "Record type",
      noteTitle: "Title",
      noteContent: "Content",
      notePriority: "Priority",
      noteDate: "Catalyst date",
      noteDateFrom: "From date",
      noteDateTo: "To date",
      editNote: "Edit note",
      updateNote: "Update note",
      saveNote: "Save note",
      savingNote: "Saving...",
      noteSaved: "Research note saved",
      noteFailed: "Failed to save research note",
      noteDeleted: "Research note removed",
      noteDeleteFailed: "Failed to remove research note",
      noteTitlePlaceholder: "What changed or needs to be watched?",
      noteContentPlaceholder: "Capture the thesis, risk, or trigger in a reusable way.",
      note: "Note",
      thesis: "Thesis",
      catalyst: "Catalyst",
      highPriority: "High",
      normalPriority: "Normal",
      lowPriority: "Low",
      researchCount: "Research records",
      lastResearch: "Last updated",
      allTypes: "All types",
      allPriorities: "All priorities",
      prompts: [
        "Review price structure against the current cost basis.",
        "Confirm whether position size still fits conviction and cash buffer.",
        "Check whether the symbol adds opportunity or concentration risk.",
      ],
    },
    explainability: {
      title: "Explainability snapshot",
      empty: "No explainability data available yet.",
      timeline: "Timeline attribution",
      returnCalendar: "Return calendar",
      heatmapView: "Heatmap",
      tableView: "Table",
      curveView: "Curve",
      bucketLabel: "Bucket",
      day: "Day",
      week: "Week",
      month: "Month",
      year: "Year",
      amountMetric: "Amount",
      percentMetric: "Percent",
      timelineEmpty: "No daily attribution available yet.",
      timelineRange: "Date range",
      timelineEventKind: "Event type",
      allEvents: "All events",
      deposits: "Deposits",
      withdrawals: "Withdrawals",
      dividends: "Dividends",
      buys: "Buys",
      sells: "Sells",
      adjustments: "Adjustments",
      category: "Category",
      impactSource: "Impact source",
      categoryCapital: "Capital",
      categoryIncome: "Income",
      categoryOverride: "Override",
      categoryTrade: "Trade",
      sourceExternal: "External",
      sourceCash: "Cash",
      sourceManual: "Manual",
      sourcePositioning: "Positioning",
      equity: "Equity",
      netChange: "Net change",
      externalFlow: "External flow",
      marketPnl: "Market move",
      quantity: "Quantity",
      latestPrice: "Latest price",
      snapshotAt: "Snapshot time",
    },
    activity: {
      kicker: "Activity",
      title: "Ledger activity",
      subtitle:
        "Record trades, dividends, cash flows, and manual adjustments with immediate portfolio refresh.",
      loading: "Loading ledger activity.",
      error: "Failed to load ledger activity.",
      tradeSaved: "Trade saved",
      tradeFailed: "Trade failed",
      cashFlowSaved: "Cash flow saved",
      cashFlowFailed: "Cash flow failed",
      dividendSaved: "Dividend saved",
      dividendFailed: "Dividend failed",
      adjustmentSaved: "Adjustment saved",
      adjustmentFailed: "Adjustment failed",
      feedRefreshed: "Portfolio projections are refreshing now.",
      feed: {
        title: "Recent ledger entries",
        empty:
          "No ledger activity yet. Submit a trade, cash flow, dividend, or adjustment to build the timeline.",
      },
      forms: {
        trade: {
          title: "Manual trade",
          symbolPlaceholder: "Symbol",
          notePlaceholder: "Note",
          buy: "Buy",
          sell: "Sell",
          submit: "Save Trade",
          saving: "Saving...",
          genericSubmitError: "Unable to save the trade.",
        },
        cashFlow: {
          title: "Cash flow",
          notePlaceholder: "Note",
          deposit: "Deposit",
          withdrawal: "Withdrawal",
          submit: "Save Cash Flow",
          saving: "Saving...",
          genericSubmitError: "Unable to save the cash flow.",
        },
        dividend: {
          title: "Dividend",
          symbolPlaceholder: "Symbol",
          notePlaceholder: "Note",
          submit: "Save Dividend",
          saving: "Saving...",
          genericSubmitError: "Unable to save the dividend.",
        },
        adjustment: {
          title: "Manual adjustment",
          symbolPlaceholder: "Symbol",
          notePlaceholder: "Note",
          submit: "Save Adjustment",
          saving: "Saving...",
          genericSubmitError: "Unable to save the adjustment.",
        },
      },
    },
    placeholder: "This page is still under construction.",
  },
  zh: {
    shell: {
      title: "组合工作台",
      description: "覆盖持仓、现金、活动与估值的组合工作台。",
      language: "语言",
      theme: "主题",
      navigation: "导航",
      openNavigation: "打开导航",
      closeNavigation: "关闭导航",
      toolbarTitle: "全局工具栏",
      toolbarSubtitle: "把偏好设置与组合状态统一收口，避免页面级分散控制。",
      accountStatus: "账户状态",
      apiStatus: "接口",
      navStatus: "净值",
      themeStatus: "主题",
      ledgerMode: "账本已同步",
      valuationMode: "估值已启用",
      brokerMode: "券商接口就绪",
      light: "浅色",
      dark: "深色",
      system: "跟随系统",
      systemThemeLabel: "跟随系统主题",
      lightThemeLabel: "浅色主题",
      darkThemeLabel: "深色主题",
      nav: {
        overview: "总览",
        portfolio: "组合",
        activity: "流水",
        risk: "风险",
        market: "市场",
        settings: "设置",
      },
    },
    states: {
      loading: "加载中",
      error: "加载失败",
      empty: "暂无数据",
      retry: "重试",
    },
    common: {
      required: "该字段不能为空。",
      mustBePositive: "请输入大于零的数值。",
      genericSubmitError: "请求失败，请检查录入内容或服务日志。",
      assetClassStock: "股票",
      assetClassEtf: "ETF",
      assetClassFund: "基金",
      assetClassGold: "黄金",
      assetClassBond: "债券",
    },
    mode: {
      account: "账户视角",
      strategy: "策略视角",
      accountShort: "账户",
      strategyShort: "策略",
    },
    overview: {
      kicker: "总览",
      title: "资产工作台",
      subtitle: "同时查看资金结构、收益拆解和净值走势，快速判断组合当前状态。",
      modeHelper: "账户视角看资本结构，策略视角看收益质量和执行结果。",
      loading: "正在加载账户总览和组合快照。",
      error: "账户总览或组合快照读取失败。",
      curveLoading: "正在加载净值曲线。",
      curveError: "净值曲线读取失败。",
      empty: "还没有可展示的账户数据。",
      cards: {
        totalAssets: "总资产",
        availableCash: "可用现金",
        unrealizedPnl: "浮动盈亏",
        cashRatio: "现金占比",
      },
      equityCurve: {
        title: "净值曲线",
        range: "区间",
        oneMonth: "1个月",
        threeMonths: "3个月",
        oneYear: "1年",
        all: "全部",
        empty: "还没有净值历史。",
        emptyTitle: "尚无净值历史",
        emptyDetail: "先录入首笔资金流水或交易，系统才会开始生成净值曲线。",
        emptyHint: "净值曲线依赖按时间累计的账本历史点。",
      },
      livePulse: {
        title: "实时资产脉冲",
        subtitle: "按资产类别快速查看持仓市值、今日涨跌和买入以来收益。",
        loading: "正在加载分组实时持仓。",
        error: "分组实时持仓加载失败。",
        empty: "当前还没有活跃持仓。",
        marketValue: "持仓市值",
        todayMove: "今日涨跌",
        sinceBuyReturn: "买入以来收益",
      },
      risk: {
        title: "风险摘要",
        concentration: "最大持仓权重",
        cashBuffer: "现金缓冲",
        deployment: "资金利用率",
        positions: "活跃持仓",
        positionsHint: (count: number) => `${count} 个持仓在场`,
        cashHealthy: "现金缓冲健康",
        cashWatch: "现金缓冲偏薄",
        deploymentBalanced: "仓位节奏平衡",
        deploymentHigh: "当前仓位偏热",
      },
      breakdown: {
        accountKicker: "账户拆解",
        strategyKicker: "策略拆解",
        accountTitle: "资金结构与配置节奏",
        strategyTitle: "收益质量与执行结果",
        marketValue: "持仓市值",
        activePositions: (count: number) => `${count} 个活跃持仓`,
        cashReserve: "现金储备",
        netDeposits: "净投入",
        capitalBase: "净投入本金",
        deployment: "仓位利用率",
        capitalAtWork: "已投入仓位",
        unrealizedPnl: "浮动盈亏",
        openPositions: "来自当前持仓",
        realizedPnl: "已实现盈亏",
        closedActivity: "来自已落袋交易",
        totalPnl: "总收益",
        totalPnlHint: "已实现 + 浮动",
        payoutBuffer: "再配置缓冲",
        payoutBufferHint: "可用于继续配置的现金",
      },
    },
    portfolio: {
      kicker: "组合",
      title: "持仓与配置工作台",
      subtitle: "支持按标的检索、收益筛选和资产类别过滤，右侧持续给出配置和收益拆解。",
      positionsLoading: "正在加载持仓明细。",
      positionsError: "持仓明细加载失败。",
      positionsEmpty: "当前还没有持仓，先去 Activity 录入交易。",
      filterEmpty: "当前筛选条件下没有匹配的持仓。",
      sidebarLoading: "正在加载配置和收益拆解。",
      sidebarError: "配置或收益拆解加载失败。",
      sidebarEmpty: "还没有可用的配置视图。",
      toolbar: {
        view: "视角",
        helper: "账户视角偏重资产结构，策略视角偏重收益质量。",
        search: "搜索",
        searchPlaceholder: "按代码过滤",
        assetClass: "资产类别",
        allAssetClasses: "全部资产",
        pnlFocus: "收益筛选",
        allHoldings: "全部持仓",
        winnersOnly: "仅盈利",
        losersOnly: "仅亏损",
      },
      table: {
        symbol: "代码",
        assetClass: "资产类别",
        quantity: "数量",
        availFrozen: "可用/冻结",
        avgCost: "成本价",
        marketValue: "市值",
        unrealized: "浮盈亏",
        realized: "已实现",
        detailsTitle: "持仓明细",
      },
      allocation: {
        title: "配置明细",
        empty: "当前筛选范围下还没有可展示的配置。",
      },
      allocationGroups: {
        title: "分组配置",
        empty: "当前还没有分组配置可展示。",
      },
      liveBoard: {
        title: "实时持仓看板",
        subtitle: "按资产类别查看最新价格、今日涨跌和买入以来收益。",
        loading: "正在加载实时持仓。",
        error: "实时持仓加载失败。",
        empty: "当前还没有活跃持仓，先录入首笔交易再开始跟踪实时收益。",
        latestPrice: "最新价格",
        todayMove: "今日涨跌",
        sinceBuyReturn: "买入以来收益",
        updatedAt: "更新时间",
        baseline: "对比基准",
        baselinePreviousClose: "昨收",
        baselineFallbackClose: "回补收盘点",
        baselineUnavailable: "暂无可用日内基准",
        quoteLive: "实时行情",
        quoteStale: "快照行情",
      },
    },
    riskPage: {
      kicker: "风险",
      title: "风险工作台",
      subtitle: "统一查看风险提示、资金压力与净值归因。",
      loading: "正在加载风险工作台。",
      error: "风险工作台加载失败。",
      alerts: "当前风险提示",
      nextStep: "建议动作",
      equityBridge: "净值桥",
      recentDrivers: "最近驱动事件",
      positionDrivers: "持仓驱动",
      emptyDrivers: "当前还没有可解释的驱动数据。",
      metrics: "风险指标",
      currentDrawdown: "当前回撤",
      currentDrawdownDetail: "当前净值距离最近峰值的回撤幅度。",
      maxDrawdown: "最大回撤",
      maxDrawdownDetail: "净值曲线历史上最大的峰谷回撤。",
      grossExposure: "总暴露",
      grossExposureDetail: "当前配置在非现金资产中的资金比例。",
      cashRatio: "现金占比",
      cashRatioDetail: "用于再平衡或防守的即时流动性缓冲。",
      largestPosition: "最大单一持仓",
      largestPositionDetail: "当前最大活跃持仓带来的单标的集中度。",
      top3Concentration: "前三集中度",
      top3ConcentrationDetail: "前三大持仓合计带来的集中度。",
      drawdown: "回撤路径",
      exposure: "暴露分桶",
      bucketHeavy: "高信念仓位",
      bucketCore: "核心仓位",
      bucketStarter: "起始仓位",
      bucketSmall: "小仓位 / 跟踪仓",
      bucketCash: "现金储备",
      concentration: "集中度拆解",
      noConcentration: "当前暂无活跃持仓，无法拆解集中度。",
    },
    market: {
      kicker: "市场",
      title: "研究工作台",
      subtitle: "围绕关注列表、行情健康度、价格结构与研究记录组织研究输入。",
      loading: "正在加载研究工作台。",
      error: "研究工作台加载失败。",
      watchlist: "研究看板",
      health: "数据健康度",
      chart: "价格结构",
      addSymbol: "新增标的",
      symbolPlaceholder: "代码",
      assetClass: "资产类别",
      add: "添加",
      remove: "移除",
      marketOpen: "市场开盘",
      marketClosed: "市场收盘",
      refreshPolicy: "刷新策略",
      selectedSymbol: "当前标的",
      symbolLabel: "代码",
      priceLabel: "价格",
      snapshotLabel: "快照时间",
      holdingsContext: "持仓上下文",
      noSelection: "先选择或新增一个标的，再开始研究。",
      noChart: "当前标的没有可用的价格结构数据。",
      promptsTitle: "研究清单",
      notesTitle: "研究记录",
      notesEmpty: "还没有研究记录，先把当前逻辑或催化剂写下来。",
      noteType: "记录类型",
      noteTitle: "标题",
      noteContent: "内容",
      notePriority: "优先级",
      noteDate: "催化日期",
      noteDateFrom: "开始日期",
      noteDateTo: "结束日期",
      editNote: "编辑记录",
      updateNote: "更新记录",
      saveNote: "保存记录",
      savingNote: "保存中...",
      noteSaved: "研究记录已保存",
      noteFailed: "研究记录保存失败",
      noteDeleted: "研究记录已删除",
      noteDeleteFailed: "研究记录删除失败",
      noteTitlePlaceholder: "这次变化是什么，接下来要盯什么？",
      noteContentPlaceholder: "把逻辑、风险点和催化条件写成可复用记录。",
      note: "笔记",
      thesis: "逻辑",
      catalyst: "催化剂",
      highPriority: "高",
      normalPriority: "中",
      lowPriority: "低",
      researchCount: "研究条目",
      lastResearch: "最近更新",
      allTypes: "全部类型",
      allPriorities: "全部优先级",
      prompts: [
        "检查当前价格结构相对持仓成本的变化。",
        "确认当前仓位是否仍匹配判断与现金缓冲。",
        "判断该标的是新增机会还是集中度来源。",
      ],
    },
    explainability: {
      title: "解释层快照",
      empty: "当前还没有可用的解释层数据。",
      timeline: "时间序列归因",
      returnCalendar: "收益日历",
      heatmapView: "热力图",
      tableView: "表格",
      curveView: "曲线",
      bucketLabel: "周期",
      day: "日",
      week: "周",
      month: "月",
      year: "年",
      amountMetric: "金额",
      percentMetric: "涨跌幅",
      timelineEmpty: "暂无按日归因数据。",
      timelineRange: "日期区间",
      timelineEventKind: "事件类型",
      allEvents: "全部事件",
      deposits: "入金",
      withdrawals: "出金",
      dividends: "分红",
      buys: "买入",
      sells: "卖出",
      adjustments: "手工调整",
      category: "分类",
      impactSource: "影响来源",
      categoryCapital: "资金事件",
      categoryIncome: "收益事件",
      categoryOverride: "手工覆盖",
      categoryTrade: "交易事件",
      sourceExternal: "外部资金",
      sourceCash: "现金",
      sourceManual: "手工录入",
      sourcePositioning: "持仓变化",
      equity: "净值",
      netChange: "当日变化",
      externalFlow: "事件流入/流出",
      marketPnl: "市场变动",
      quantity: "数量",
      latestPrice: "最新价格",
      snapshotAt: "快照时间",
    },
    activity: {
      kicker: "流水",
      title: "账本活动台",
      subtitle: "手工录入交易、分红、现金流和调整，并即时回刷资产、收益和持仓。",
      loading: "正在加载账本流水。",
      error: "账本流水加载失败。",
      tradeSaved: "交易已保存",
      tradeFailed: "交易保存失败",
      cashFlowSaved: "现金流已保存",
      cashFlowFailed: "现金流保存失败",
      dividendSaved: "分红已保存",
      dividendFailed: "分红保存失败",
      adjustmentSaved: "调整已保存",
      adjustmentFailed: "调整保存失败",
      feedRefreshed: "组合快照和流水已经开始刷新。",
      feed: {
        title: "最近账本流水",
        empty: "还没有账本流水。先录入交易、现金流、分红或手工调整，时间线就会开始累计。",
      },
      forms: {
        trade: {
          title: "手工交易",
          symbolPlaceholder: "证券代码",
          notePlaceholder: "备注",
          buy: "买入",
          sell: "卖出",
          submit: "保存交易",
          saving: "保存中...",
          genericSubmitError: "交易保存失败。",
        },
        cashFlow: {
          title: "现金流水",
          notePlaceholder: "备注",
          deposit: "入金",
          withdrawal: "出金",
          submit: "保存现金流",
          saving: "保存中...",
          genericSubmitError: "现金流保存失败。",
        },
        dividend: {
          title: "分红",
          symbolPlaceholder: "证券代码",
          notePlaceholder: "备注",
          submit: "保存分红",
          saving: "保存中...",
          genericSubmitError: "分红保存失败。",
        },
        adjustment: {
          title: "手工调整",
          symbolPlaceholder: "证券代码",
          notePlaceholder: "备注",
          submit: "保存调整",
          saving: "保存中...",
          genericSubmitError: "调整保存失败。",
        },
      },
    },
    placeholder: "这个页面还在继续建设中。",
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type AppCopy = (typeof copy)[Locale];

export function useCopy() {
  const { locale } = usePreferences();
  return copy[locale];
}

export function getCopy(locale: Locale) {
  return copy[locale];
}
