import { usePreferences, type Locale } from './preferences';

export const copy = {
  en: {
    shell: {
      title: 'Portfolio OS',
      description:
        'Portfolio workspace for holdings, cash, activity, and valuation.',
      language: 'Language',
      theme: 'Theme',
      navigation: 'Navigation',
      openNavigation: 'Open navigation',
      closeNavigation: 'Close navigation',
      toolbarTitle: 'Workspace toolbar',
      toolbarSubtitle:
        'Keep preferences and portfolio status in one consistent global toolbar.',
      accountStatus: 'Account Status',
      apiStatus: 'API',
      navStatus: 'NAV',
      marketStatus: 'Market',
      resync: 'Re-sync ledger',
      syncing: 'Checking',
      checking: 'Checking',
      syncedJustNow: 'Checked just now',
      lastSync: 'Last status check',
      latency: 'Latency',
      details: 'Details',
      statusUnknown: 'Status unknown',
      ledgerUnavailable: 'Ledger unavailable',
      brokerStopped: 'Interface stopped',
      brokerError: 'Interface error',
      valuationStale: 'Cached quotes',
      valuationError: 'Valuation error',
      valuationAt: (time: string) => `Valuation ${time}`,
      quoteStatus: 'Quote status',
      cachedQuotes: 'Cached quotes',
      marketLive: 'Market data available',
      marketClosed: 'Market closed',
      marketCacheOnly: 'Cache only',
      marketError: 'Market error',
      refreshPolicy: 'Refresh policy',
      marketSession: 'Market session',
      marketOpen: 'Market open',
      valuationUpdated: 'Last valuation refresh',
      clickToResync: 'Click to resync ledger',
      viewLatencyDetails: 'View latency details',
      viewValuationDetails: 'View valuation details',
      viewStatusDetails: 'View status details',
      themeStatus: 'Theme',
      ledgerMode: 'Ledger available',
      valuationMode: 'Valuation available',
      brokerMode: 'Broker API available',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      systemThemeLabel: 'System theme',
      lightThemeLabel: 'Light theme',
      darkThemeLabel: 'Dark theme',
      nav: {
        overview: 'Overview',
        portfolio: 'Portfolio',
        activity: 'Activity',
        risk: 'Risk',
        market: 'Market',
        settings: 'Settings',
      },
    },
    states: {
      loading: 'Loading',
      error: 'Request failed',
      empty: 'No data yet',
      retry: 'Retry',
    },
    common: {
      required: 'This field is required.',
      mustBePositive: 'Enter a value greater than zero.',
      genericSubmitError: 'Request failed. Check your payload and server logs.',
      assetClassStock: 'Stock',
      assetClassEtf: 'ETF',
      assetClassFund: 'Fund',
      assetClassGold: 'Gold',
      assetClassBond: 'Bond',
    },
    mode: {
      account: 'Account Perspective',
      strategy: 'Strategy Perspective',
      accountShort: 'Account',
      strategyShort: 'Strategy',
    },
    overview: {
      kicker: 'Overview',
      title: 'Portfolio workspace',
      subtitle:
        'Track capital structure, return breakdown, and equity movement in one place.',
      modeHelper:
        'Account view focuses on capital structure. Strategy view focuses on return quality.',
      loading: 'Loading account overview and portfolio snapshot.',
      error: 'Failed to load account overview or snapshot.',
      curveLoading: 'Loading equity curve.',
      curveError: 'Failed to load equity curve.',
      empty: 'No account data available yet.',
      cards: {
        totalAssets: 'Total Assets',
        availableCash: 'Available Cash',
        todayPnl: 'Today PnL',
        unrealizedPnl: 'Unrealized PnL',
        cashRatio: 'Cash Ratio',
        currentDrawdown: 'Current Drawdown',
        cachedValuation: 'Cached quotes · valuation time',
      },
      dashboard: {
        equityPanel: 'Equity curve',
        opsPanel: 'Execution queue',
        pendingApprovals: 'Pending approvals',
        pendingEmpty: 'No orders require approval.',
        pendingEmptyDetail:
          'Approved orders will appear here before execution.',
        pendingCount: (count: number) => `${count} pending`,
        ledgerPanel: 'Latest ledger',
        ledgerEmpty: 'No ledger entries yet.',
        positionsPanel: 'Current positions',
        positionsDetail:
          'Quote price, cost basis, market value, and floating PnL from backend projections.',
        tradeBuy: 'Buy',
        tradeSell: 'Sell',
        cashDeposit: 'Deposit',
        cashWithdrawal: 'Withdrawal',
        dividend: 'Dividend',
        adjustment: 'Adjustment',
        unknownActivity: 'Ledger entry',
      },
      equityCurve: {
        title: 'Performance Analysis',
        range: 'Range',
        total: 'Total',
        stocks: 'Stocks',
        funds: 'Funds',
        others: 'Others',
        cash: 'Cash',
        oneDay: '1D',
        fiveDays: '5D',
        oneMonth: '1M',
        sixMonths: '6M',
        oneYear: '1Y',
        all: 'ALL',
        empty: 'No equity history yet.',
        emptyTitle: 'No Equity History Yet',
        emptyPeriod: 'No data available for this period.',
        emptyDetail:
          'Record the first cash flow or trade to start building the equity curve.',
        emptyHint:
          'The curve appears after the portfolio has time-series ledger points.',
        realtimeUnrealizedPnl: 'Unrealized P/L',
        cachedValuation: 'Valuation uses cached quotes',
      },
      livePulse: {
        title: 'Asset pulse',
        subtitle:
          'Review grouped holdings by asset class with quote move and since-buy return.',
        loading: 'Loading grouped holdings.',
        error: 'Failed to load grouped holdings.',
        empty: 'No active holdings yet.',
        marketValue: 'Market value',
        todayMove: 'Today move',
        sinceBuyReturn: 'Since-buy return',
      },
      risk: {
        title: 'Risk Summary',
        concentration: 'Top Holding Weight',
        cashBuffer: 'Cash Buffer',
        deployment: 'Capital Deployment',
        positions: 'Active Positions',
        positionsHint: (count: number) => `${count} open positions`,
        cashHealthy: 'Healthy reserve',
        cashWatch: 'Cash reserve is getting thin',
        deploymentBalanced: 'Deployment is balanced',
        deploymentHigh: 'Portfolio is running hot',
      },
      breakdown: {
        accountKicker: 'Account breakdown',
        strategyKicker: 'Strategy breakdown',
        accountTitle: 'Capital structure and deployment',
        strategyTitle: 'Returns and execution outcome',
        marketValue: 'Market Value',
        activePositions: (count: number) => `${count} active positions`,
        cashReserve: 'Cash Reserve',
        netDeposits: 'Net Deposits',
        capitalBase: 'Capital base',
        deployment: 'Deployment',
        capitalAtWork: 'Capital at work',
        unrealizedPnl: 'Unrealized PnL',
        openPositions: 'Open positions',
        realizedPnl: 'Realized PnL',
        closedActivity: 'Closed activity',
        totalPnl: 'Total PnL',
        totalPnlHint: 'Realized + unrealized',
        payoutBuffer: 'Payout Buffer',
        payoutBufferHint: 'Cash available for redeploy',
      },
    },
    portfolio: {
      kicker: 'Portfolio',
      title: 'Holdings and allocation workspace',
      subtitle:
        'Filter holdings by symbol, asset class, and PnL focus while keeping allocation and return structure in view.',
      positionsLoading: 'Loading positions.',
      positionsError: 'Failed to load positions.',
      positionsEmpty: 'No holdings yet. Add trades from Activity first.',
      filterEmpty: 'No holdings match the current filters.',
      sidebarLoading: 'Loading allocation and performance breakdown.',
      sidebarError: 'Failed to load allocation or performance breakdown.',
      sidebarEmpty: 'No allocation view is available yet.',
      toolbar: {
        view: 'View',
        helper:
          'Account emphasizes capital structure. Strategy emphasizes return quality.',
        search: 'Search',
        searchPlaceholder: 'Filter by symbol',
        assetClass: 'Asset Class',
        allAssetClasses: 'All asset classes',
        pnlFocus: 'PnL Focus',
        allHoldings: 'All holdings',
        winnersOnly: 'Winners only',
        losersOnly: 'Losers only',
      },
      table: {
        symbol: 'Symbol',
        assetClass: 'Asset Class',
        quantity: 'Quantity',
        availFrozen: 'Avail/Frozen',
        avgCost: 'Avg Cost',
        latestPrice: 'Quote Price',
        cachedQuoteNotice:
          'Cached quotes · positions valued from cached quotes',
        cachedQuoteAt: (time: string) => `Cached ${time}`,
        marketValue: 'Market Value',
        unrealized: 'Unrealized',
        realized: 'Realized',
        detailsTitle: 'Holding Details',
      },
      allocation: {
        title: 'Allocation',
        empty: 'No allocation matches the current scope yet.',
      },
      allocationGroups: {
        title: 'Allocation Groups',
        empty: 'No grouped allocation available yet.',
      },
      liveBoard: {
        title: 'Holdings quote board',
        subtitle:
          'Track grouped holdings with quote price, intraday move, and since-buy return.',
        loading: 'Loading holdings quotes.',
        error: 'Failed to load holdings quotes.',
        empty:
          'No active holdings yet. Record the first trade to start tracking returns.',
        latestPrice: 'Quote price',
        todayMove: 'Today move',
        sinceBuyReturn: 'Since-buy return',
        updatedAt: 'Updated',
        baseline: 'Baseline',
        baselinePreviousClose: 'Previous close',
        baselineFallbackClose: 'Fallback close',
        baselineUnavailable: 'Daily baseline unavailable',
        quoteLive: 'Quote available',
        quoteStale: 'Cached quote',
      },
    },
    riskPage: {
      kicker: 'Risk',
      title: 'Risk workspace',
      subtitle:
        'Review current alerts, capital pressure, and equity attribution in one place.',
      loading: 'Loading risk workspace.',
      error: 'Failed to load risk workspace.',
      alerts: 'Active alerts',
      nextStep: 'Suggested next step',
      equityBridge: 'Equity bridge',
      recentDrivers: 'Recent drivers',
      positionDrivers: 'Position drivers',
      emptyDrivers: 'No explainability drivers available yet.',
      metrics: 'Risk metrics',
      currentDrawdown: 'Current drawdown',
      currentDrawdownDetail:
        'Distance between current equity and the latest portfolio peak.',
      maxDrawdown: 'Max drawdown',
      maxDrawdownDetail:
        'Largest observed peak-to-trough loss across the equity curve.',
      grossExposure: 'Gross exposure',
      grossExposureDetail: 'Capital currently deployed in non-cash positions.',
      cashRatio: 'Cash ratio',
      cashRatioDetail: 'Immediate liquidity buffer for rebalance or defense.',
      largestPosition: 'Largest position',
      largestPositionDetail:
        'Single-name concentration of the biggest active holding.',
      top3Concentration: 'Top 3 concentration',
      top3ConcentrationDetail:
        'Aggregate concentration across the three largest holdings.',
      drawdown: 'Drawdown path',
      exposure: 'Exposure buckets',
      bucketHeavy: 'Heavy conviction',
      bucketCore: 'Core',
      bucketStarter: 'Starter',
      bucketSmall: 'Small / tracking',
      bucketCash: 'Cash reserve',
      concentration: 'Concentration drill-down',
      noConcentration:
        'No active positions available for concentration analysis.',
    },
    trading: {
      killSwitch: {
        kicker: 'Trading controls',
        title: 'Global kill switch',
        subtitle:
          'Block new buy orders before they reach broker execution. Sell-side risk reduction and cancel flows remain available.',
        loading: 'Checking',
        enabled: 'Kill switch active',
        disabled: 'Trading allowed',
        enable: 'Enable kill switch',
        disable: 'Disable kill switch',
        submitting: 'Updating...',
        reason: 'Operator reason',
        reasonPlaceholder: 'Required before blocking new buy orders',
        currentReasonPlaceholder: 'Current reason',
        reasonRequired: 'Enter a reason before enabling the kill switch.',
        updatedAt: 'Updated',
        neverUpdated: 'Never',
        loadFailed: 'Failed to load kill switch state.',
      },
      orders: {
        kicker: 'Manual execution',
        title: 'Pending order approvals',
        subtitle:
          'Orders that passed pre-trade risk checks wait here until an operator confirms or rejects them.',
        loading: 'Loading pending orders.',
        loadFailed: 'Failed to load pending orders.',
        empty: 'No orders are waiting for manual confirmation.',
        pendingCount: (count: number) => `${count} pending`,
        symbol: 'Symbol',
        side: 'Side',
        buy: 'Buy',
        sell: 'Sell',
        quantity: 'Quantity',
        price: 'Price',
        riskHint: 'Risk audit',
        rejectReason: 'Reject reason',
        rejectReasonPlaceholder: 'Required to reject',
        rejectReasonRequired:
          'Enter a reject reason before rejecting an order.',
        actions: 'Actions',
        confirm: 'Confirm',
        reject: 'Reject',
        riskApproved: 'Pre-trade check passed',
        decisionId: 'Decision',
        intentId: 'Intent',
      },
    },
    backtest: {
      selection: {
        kicker: 'Backtest history',
        title: 'Report selection',
        ariaLabel: 'Select backtest report',
        loading: 'Loading backtest results.',
        loadFailed: 'Failed to load backtest history.',
        empty:
          'No backtest reports have been saved yet. Run a backtest first to inspect metrics, costs, equity curve, and fills.',
        selectedLoading: 'Loading selected report.',
        selectedFailed: 'Failed to load selected backtest report.',
      },
      summary: {
        return: 'Summary return',
        sharpe: 'Summary Sharpe',
        maxDrawdown: 'Summary max drawdown',
      },
      metrics: {
        totalReturn: 'Total return',
        sharpe: 'Sharpe',
        sortino: 'Sortino',
        maxDrawdown: 'Max drawdown',
        calmar: 'Calmar',
        winRate: 'Win rate',
        durationDays: (days: number) => `${days} trading days`,
        volatility: 'Volatility',
        annualReturn: 'Annual return',
        grossTurnover: 'Gross turnover',
        fills: (count: number) => `${count} fills`,
        totalCommission: 'Total commission',
        commissionDetail: 'Brokerage and exchange fees',
        totalSlippage: 'Total slippage',
        slippageDetail: 'Execution drift from reference price',
      },
      chart: {
        kicker: 'Backtest curve',
        title: 'Equity and drawdown',
        empty: 'No equity curve is available for this backtest result.',
        points: (count: number) => `${count} points`,
        drawdown: 'Drawdown',
      },
      fills: {
        kicker: 'Execution ledger',
        title: 'Fills',
        rows: (count: number) => `${count} rows`,
        empty:
          'No fill details are available for this saved result. New runs expose per-fill cost records when the backtest engine returns them.',
        time: 'Time',
        symbol: 'Symbol',
        side: 'Side',
        fillPrice: 'Fill price',
        quantity: 'Quantity',
        commission: 'Commission',
        slippage: 'Slippage',
      },
    },
    market: {
      kicker: 'Market',
      title: 'Research workspace',
      subtitle:
        'Track coverage, quote health, price structure, and research records for each symbol.',
      loading: 'Loading research board.',
      error: 'Failed to load research board.',
      watchlist: 'Research board',
      health: 'Data health',
      chart: 'Price structure',
      addSymbol: 'Add symbol',
      symbolPlaceholder: 'Symbol',
      assetClass: 'Asset class',
      add: 'Add',
      remove: 'Remove',
      marketOpen: 'Market open',
      marketClosed: 'Market closed',
      refreshPolicy: 'Refresh policy',
      refreshQuotes: 'Refresh quotes',
      refreshingQuotes: 'Refreshing quotes',
      quoteRefreshComplete: 'Quote refresh completed',
      quoteRefreshPartial: 'Partial quote refresh completed',
      quoteRefreshStale: 'Quote source returned cached quotes',
      quoteRefreshFailed: 'Quote refresh failed',
      selectedSymbol: 'Selected symbol',
      symbolLabel: 'Symbol',
      priceLabel: 'Price',
      snapshotLabel: 'Snapshot time',
      holdingsContext: 'Holding context',
      noSelection: 'Select or add a symbol to start research.',
      noChart: 'No price structure available for the selected symbol.',
      promptsTitle: 'Research checklist',
      notesTitle: 'Research notes',
      notesEmpty:
        'No notes yet. Capture the current thesis before the market moves.',
      noteType: 'Record type',
      noteTitle: 'Title',
      noteContent: 'Content',
      notePriority: 'Priority',
      noteDate: 'Catalyst date',
      noteDateFrom: 'From date',
      noteDateTo: 'To date',
      editNote: 'Edit note',
      updateNote: 'Update note',
      saveNote: 'Save note',
      savingNote: 'Saving...',
      noteSaved: 'Research note saved',
      noteFailed: 'Failed to save research note',
      noteDeleted: 'Research note removed',
      noteDeleteFailed: 'Failed to remove research note',
      noteTitlePlaceholder: 'What changed or needs to be watched?',
      noteContentPlaceholder:
        'Capture the thesis, risk, or trigger in a reusable way.',
      note: 'Note',
      thesis: 'Thesis',
      catalyst: 'Catalyst',
      highPriority: 'High',
      normalPriority: 'Normal',
      lowPriority: 'Low',
      researchCount: 'Research records',
      lastResearch: 'Last updated',
      allTypes: 'All types',
      allPriorities: 'All priorities',
      prompts: [
        'Review price structure against the current cost basis.',
        'Confirm whether position size still fits conviction and cash buffer.',
        'Check whether the symbol adds opportunity or concentration risk.',
      ],
    },
    explainability: {
      title: 'Explainability snapshot',
      empty: 'No explainability data available yet.',
      timeline: 'Timeline attribution',
      returnCalendar: 'Return calendar',
      heatmapView: 'Heatmap',
      tableView: 'Table',
      curveView: 'Curve',
      bucketLabel: 'Bucket',
      day: 'Day',
      week: 'Week',
      month: 'Month',
      year: 'Year',
      amountMetric: 'Amount',
      percentMetric: 'Percent',
      timelineEmpty: 'No daily attribution available yet.',
      timelineRange: 'Date range',
      timelineEventKind: 'Event type',
      allEvents: 'All events',
      deposits: 'Deposits',
      withdrawals: 'Withdrawals',
      dividends: 'Dividends',
      buys: 'Buys',
      sells: 'Sells',
      adjustments: 'Adjustments',
      category: 'Category',
      impactSource: 'Impact source',
      categoryCapital: 'Capital',
      categoryIncome: 'Income',
      categoryOverride: 'Override',
      categoryTrade: 'Trade',
      sourceExternal: 'External',
      sourceCash: 'Cash',
      sourceManual: 'Manual',
      sourcePositioning: 'Positioning',
      equity: 'Equity',
      netChange: 'Net change',
      externalFlow: 'External flow',
      marketPnl: 'Market move',
      equityBridgeLabels: {
        deposits: 'Net Deposits',
        realized: 'Realized PnL',
        unrealized: 'Unrealized PnL',
        cash: 'Cash',
        market_value: 'Market Value',
        equity: 'Total Equity',
      },
      equityBridgeDetails: {
        deposits: 'External capital recorded through deposits and withdrawals.',
        realized: 'Closed trade outcome already locked in.',
        unrealized: 'Mark-to-market move on current positions.',
        cash: 'Immediate buffer available for redeployment.',
        market_value: 'Current marked value of open positions.',
        equity: (totalPnl: string) => `Deposits plus total PnL (${totalPnl}).`,
      },
      quantity: 'Quantity',
      latestPrice: 'Quote price',
      snapshotAt: 'Snapshot time',
    },
    activity: {
      kicker: 'Activity',
      title: 'Ledger activity',
      subtitle:
        'Record trades, dividends, cash flows, and manual adjustments with immediate portfolio refresh.',
      loading: 'Loading ledger activity.',
      error: 'Failed to load ledger activity.',
      tradeSaved: 'Trade saved',
      tradeFailed: 'Trade failed',
      cashFlowSaved: 'Cash flow saved',
      cashFlowFailed: 'Cash flow failed',
      dividendSaved: 'Dividend saved',
      dividendFailed: 'Dividend failed',
      adjustmentSaved: 'Adjustment saved',
      adjustmentFailed: 'Adjustment failed',
      feedRefreshed: 'Portfolio projections are refreshing now.',
      feed: {
        title: 'Recent ledger entries',
        empty:
          'No ledger activity yet. Submit a trade, cash flow, dividend, or adjustment to build the timeline.',
      },
      pending: {
        kicker: 'Pending',
        title: 'Pending fund subscriptions',
        loading: 'Loading pending fund subscriptions.',
        error: 'Failed to load pending fund subscriptions.',
        submittedAt: 'submitted',
        waitingFor: 'Waiting for NAV confirmation on',
      },
      forms: {
        trade: {
          title: 'Manual trade',
          occurredAtLabel: 'Occurred At',
          symbolLabel: 'Symbol',
          directionLabel: 'Direction',
          assetClassLabel: 'Asset Class',
          subscriptionAmountLabel: 'Subscription Amount',
          quantityLabel: 'Quantity',
          priceLabel: 'Unit Price',
          feeLabel: 'Fee',
          noteLabel: 'Trade Note',
          symbolPlaceholder: 'Symbol',
          amountPlaceholder: 'Subscription amount',
          quantityPlaceholder: 'Quantity',
          pricePlaceholder: 'Unit price',
          notePlaceholder: 'Note',
          buy: 'Buy',
          sell: 'Sell',
          amountRequired: 'Enter the subscription amount for a fund buy.',
          fundAmountHelp:
            'Fund buys can be recorded by amount. The system confirms quantity and cost from the published NAV.',
          submit: 'Save Trade',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the trade.',
        },
        fundBatch: {
          title: 'Batch fund add',
          helper:
            'Record one top-up operation across your held funds. Positive rows are submitted as fund buys by amount.',
          occurredAtLabel: 'Batch Occurred At',
          amountLabel: (symbol: string) => `${symbol} Amount`,
          noteLabel: 'Batch Fund Note',
          amountPlaceholder: 'Amount',
          notePlaceholder: 'Batch note',
          emptyError: 'Enter at least one fund amount.',
          submit: 'Save Batch',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the batch fund order.',
        },
        cashFlow: {
          title: 'Cash flow',
          occurredAtLabel: 'Cash Flow Occurred At',
          amountLabel: 'Amount',
          flowTypeLabel: 'Flow Type',
          noteLabel: 'Cash Flow Note',
          notePlaceholder: 'Note',
          deposit: 'Deposit',
          withdrawal: 'Withdrawal',
          submit: 'Save Cash Flow',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the cash flow.',
        },
        dividend: {
          title: 'Dividend',
          occurredAtLabel: 'Dividend Occurred At',
          symbolLabel: 'Dividend Symbol',
          assetClassLabel: 'Dividend Asset Class',
          amountLabel: 'Dividend Amount',
          noteLabel: 'Dividend Note',
          symbolPlaceholder: 'Symbol',
          notePlaceholder: 'Note',
          submit: 'Save Dividend',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the dividend.',
        },
        adjustment: {
          title: 'Manual adjustment',
          occurredAtLabel: 'Adjustment Occurred At',
          symbolLabel: 'Adjustment Symbol',
          assetClassLabel: 'Adjustment Asset Class',
          amountLabel: 'Adjustment Amount',
          quantityLabel: 'Adjustment Quantity',
          priceLabel: 'Adjustment Price',
          noteLabel: 'Adjustment Note',
          symbolPlaceholder: 'Symbol',
          notePlaceholder: 'Note',
          submit: 'Save Adjustment',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the adjustment.',
        },
      },
    },
    settings: {
      kicker: 'Settings',
      title: 'Control center',
      subtitle:
        'Review data freshness, service state, local preferences, and safety notes without changing trading semantics.',
      dataStatus: 'Data status',
      dataStatusDetail:
        'Portfolio valuation uses backend quote status and market refresh policy.',
      liveServices: 'Live services',
      liveServicesDetail:
        'Scheduler and interface state come from the backend live status endpoint.',
      preferences: 'Preferences',
      preferencesDetail:
        'Theme and language are local browser preferences for this workspace.',
      notifications: 'Notifications',
      notificationsDetail:
        'Current notification configuration is read from backend settings.',
      dataSafety: 'Data safety',
      dataSafetyDetail:
        'Cached quotes can lag market prices. Use timestamps before acting.',
      loading: 'Loading settings state.',
      error: 'Failed to load settings state.',
      retry: 'Retry status',
      marketState: 'Market state',
      quoteState: 'Quote state',
      refreshPolicy: 'Refresh policy',
      valuationTime: 'Valuation time',
      noValuationTime: 'No valuation timestamp',
      cacheOnly: 'Cache only',
      cacheOnlyDetail:
        'Market refresh policy is cache-only. Valuation may use stored quotes.',
      cachedQuotes: 'Cached quotes',
      cachedQuotesDetail: 'Current valuation is based on cached market data.',
      dataSource: 'Data source',
      pollInterval: 'Poll interval',
      pollIntervalUnit: 'seconds',
      token: 'Provider token',
      maskedToken: 'Masked token retained',
      saveDataSource: 'Save data settings',
      savingDataSource: 'Saving data settings',
      dataSourceSaved: 'Data settings saved',
      dataSourceFailed: 'Failed to save data settings',
      scheduler: 'Scheduler',
      schedulerRunning: 'Scheduler running',
      schedulerStopped: 'Scheduler stopped',
      brokerInterface: 'Broker interface',
      brokerReady: 'Interface status available',
      brokerDegraded: 'Interface not running',
      startScheduler: 'Start scheduler',
      stopScheduler: 'Stop scheduler',
      updatingScheduler: 'Updating scheduler',
      schedulerUpdateFailed: 'Failed to update scheduler state',
      backendSettings: 'Backend settings',
      assetsTracked: (count: number) => `${count} tracked assets`,
      initialCash: 'Initial cash',
      strategy: 'Strategy',
      themeMocha: 'Mocha',
      themeLatte: 'Latte',
      themeSystem: 'System',
      languageZh: '中文',
      languageEn: 'English',
      localOnly: 'Local preference',
      notificationType: 'Notification type',
      notificationUnavailable: 'No notification channel configured',
      testNotification: 'Send test notification',
      testingNotification: 'Testing notification',
      notificationOk: 'Notification test sent',
      notificationFailed: 'Notification test failed',
      safetyCachedQuotes:
        'Cached quote labels mean the latest known price is stored locally and may not match the current market.',
      safetyNoAdvice:
        'Karkinos is an analysis workspace, not investment advice or execution guarantee.',
      safetyPrivateData:
        'Keep broker tokens, account exports, and real statements out of public repositories.',
      deferred: 'Deferred',
      deferredDetail:
        'Full broker credentials, notification channel editing, and advanced data-source health are intentionally deferred.',
    },
    placeholder: 'This page is still under construction.',
  },
  zh: {
    shell: {
      title: '组合工作台',
      description: '覆盖持仓、现金、活动与估值的组合工作台。',
      language: '语言',
      theme: '主题',
      navigation: '导航',
      openNavigation: '打开导航',
      closeNavigation: '关闭导航',
      toolbarTitle: '全局工具栏',
      toolbarSubtitle: '把偏好设置与组合状态统一收口，避免页面级分散控制。',
      accountStatus: '账户状态',
      apiStatus: '接口',
      navStatus: '净值',
      marketStatus: '行情',
      resync: '重新同步账本',
      syncing: '检查中',
      checking: '检查中',
      syncedJustNow: '刚刚检查',
      lastSync: '上次状态检查',
      latency: '延迟',
      details: '详情',
      statusUnknown: '状态未知',
      ledgerUnavailable: '账本异常',
      brokerStopped: '接口未启动',
      brokerError: '接口异常',
      valuationStale: '缓存行情',
      valuationError: '估值异常',
      valuationAt: (time: string) => `估值 ${time}`,
      quoteStatus: '行情状态',
      cachedQuotes: '缓存行情',
      marketLive: '行情可用',
      marketClosed: '市场休市',
      marketCacheOnly: '缓存行情',
      marketError: '行情异常',
      refreshPolicy: '刷新策略',
      marketSession: '市场状态',
      marketOpen: '市场开盘',
      valuationUpdated: '上次估值刷新',
      clickToResync: '点击重新同步账本',
      viewLatencyDetails: '查看延迟详情',
      viewValuationDetails: '查看估值详情',
      viewStatusDetails: '查看状态详情',
      themeStatus: '主题',
      ledgerMode: '账本可用',
      valuationMode: '估值可用',
      brokerMode: '券商接口可用',
      light: '浅色',
      dark: '深色',
      system: '跟随系统',
      systemThemeLabel: '跟随系统主题',
      lightThemeLabel: '浅色主题',
      darkThemeLabel: '深色主题',
      nav: {
        overview: '总览',
        portfolio: '组合',
        activity: '流水',
        risk: '风险',
        market: '市场',
        settings: '设置',
      },
    },
    states: {
      loading: '加载中',
      error: '加载失败',
      empty: '暂无数据',
      retry: '重试',
    },
    common: {
      required: '该字段不能为空。',
      mustBePositive: '请输入大于零的数值。',
      genericSubmitError: '请求失败，请检查录入内容或服务日志。',
      assetClassStock: '股票',
      assetClassEtf: 'ETF',
      assetClassFund: '基金',
      assetClassGold: '黄金',
      assetClassBond: '债券',
    },
    mode: {
      account: '账户视角',
      strategy: '策略视角',
      accountShort: '账户',
      strategyShort: '策略',
    },
    overview: {
      kicker: '总览',
      title: '资产工作台',
      subtitle: '同时查看资金结构、收益拆解和净值走势，快速判断组合当前状态。',
      modeHelper: '账户视角看资本结构，策略视角看收益质量和执行结果。',
      loading: '正在加载账户总览和组合快照。',
      error: '账户总览或组合快照读取失败。',
      curveLoading: '正在加载净值曲线。',
      curveError: '净值曲线读取失败。',
      empty: '还没有可展示的账户数据。',
      cards: {
        totalAssets: '总资产',
        availableCash: '可用现金',
        todayPnl: '今日盈亏',
        unrealizedPnl: '浮动盈亏',
        cashRatio: '现金占比',
        currentDrawdown: '当前回撤',
        cachedValuation: '行情缓存 · 估值时间',
      },
      dashboard: {
        equityPanel: '资金曲线',
        opsPanel: '执行队列',
        pendingApprovals: '待审批订单',
        pendingEmpty: '当前没有需要审批的订单。',
        pendingEmptyDetail: '通过风控后的订单会先进入这里，确认后才继续执行。',
        pendingCount: (count: number) => `${count} 笔待审批`,
        ledgerPanel: '最新流水',
        ledgerEmpty: '还没有账本流水。',
        positionsPanel: '当前持仓',
        positionsDetail: '来自后端投影的行情价格、成本、市值与浮动盈亏。',
        tradeBuy: '买入',
        tradeSell: '卖出',
        cashDeposit: '入金',
        cashWithdrawal: '出金',
        dividend: '分红',
        adjustment: '调整',
        unknownActivity: '账本事件',
      },
      equityCurve: {
        title: '净值分析',
        range: '区间',
        total: '总计',
        stocks: '股票',
        funds: '基金',
        others: '其他',
        cash: '现金',
        oneDay: '1D',
        fiveDays: '5D',
        oneMonth: '1M',
        sixMonths: '6M',
        oneYear: '1年',
        all: 'ALL',
        empty: '还没有净值历史。',
        emptyTitle: '尚无净值历史',
        emptyPeriod: '当前区间暂无可用数据。',
        emptyDetail: '先录入首笔资金流水或交易，系统才会开始生成净值曲线。',
        emptyHint: '净值曲线依赖按时间累计的账本历史点。',
        realtimeUnrealizedPnl: '浮动盈亏',
        cachedValuation: '估值基于缓存行情',
      },
      livePulse: {
        title: '资产脉冲',
        subtitle: '按资产类别快速查看持仓市值、行情涨跌和买入以来收益。',
        loading: '正在加载分组持仓。',
        error: '分组持仓加载失败。',
        empty: '当前还没有活跃持仓。',
        marketValue: '持仓市值',
        todayMove: '今日涨跌',
        sinceBuyReturn: '买入以来收益',
      },
      risk: {
        title: '风险摘要',
        concentration: '最大持仓权重',
        cashBuffer: '现金缓冲',
        deployment: '资金利用率',
        positions: '活跃持仓',
        positionsHint: (count: number) => `${count} 个持仓在场`,
        cashHealthy: '现金缓冲健康',
        cashWatch: '现金缓冲偏薄',
        deploymentBalanced: '仓位节奏平衡',
        deploymentHigh: '当前仓位偏热',
      },
      breakdown: {
        accountKicker: '账户拆解',
        strategyKicker: '策略拆解',
        accountTitle: '资金结构与配置节奏',
        strategyTitle: '收益质量与执行结果',
        marketValue: '持仓市值',
        activePositions: (count: number) => `${count} 个活跃持仓`,
        cashReserve: '现金储备',
        netDeposits: '净投入',
        capitalBase: '净投入本金',
        deployment: '仓位利用率',
        capitalAtWork: '已投入仓位',
        unrealizedPnl: '浮动盈亏',
        openPositions: '来自当前持仓',
        realizedPnl: '已实现盈亏',
        closedActivity: '来自已落袋交易',
        totalPnl: '总收益',
        totalPnlHint: '已实现 + 浮动',
        payoutBuffer: '再配置缓冲',
        payoutBufferHint: '可用于继续配置的现金',
      },
    },
    portfolio: {
      kicker: '组合',
      title: '持仓与配置工作台',
      subtitle:
        '支持按标的检索、收益筛选和资产类别过滤，右侧持续给出配置和收益拆解。',
      positionsLoading: '正在加载持仓明细。',
      positionsError: '持仓明细加载失败。',
      positionsEmpty: '当前还没有持仓，先去 Activity 录入交易。',
      filterEmpty: '当前筛选条件下没有匹配的持仓。',
      sidebarLoading: '正在加载配置和收益拆解。',
      sidebarError: '配置或收益拆解加载失败。',
      sidebarEmpty: '还没有可用的配置视图。',
      toolbar: {
        view: '视角',
        helper: '账户视角偏重资产结构，策略视角偏重收益质量。',
        search: '搜索',
        searchPlaceholder: '按代码过滤',
        assetClass: '资产类别',
        allAssetClasses: '全部资产',
        pnlFocus: '收益筛选',
        allHoldings: '全部持仓',
        winnersOnly: '仅盈利',
        losersOnly: '仅亏损',
      },
      table: {
        symbol: '代码',
        assetClass: '资产类别',
        quantity: '数量',
        availFrozen: '可用/冻结',
        avgCost: '成本价',
        latestPrice: '行情价',
        cachedQuoteNotice: '行情缓存 · 持仓估值基于缓存行情',
        cachedQuoteAt: (time: string) => `缓存 ${time}`,
        marketValue: '市值',
        unrealized: '浮盈亏',
        realized: '已实现',
        detailsTitle: '持仓明细',
      },
      allocation: {
        title: '配置明细',
        empty: '当前筛选范围下还没有可展示的配置。',
      },
      allocationGroups: {
        title: '分组配置',
        empty: '当前还没有分组配置可展示。',
      },
      liveBoard: {
        title: '持仓行情看板',
        subtitle: '按资产类别查看行情价格、今日涨跌和买入以来收益。',
        loading: '正在加载持仓行情。',
        error: '持仓行情加载失败。',
        empty: '当前还没有活跃持仓，先录入首笔交易再开始跟踪收益。',
        latestPrice: '行情价格',
        todayMove: '今日涨跌',
        sinceBuyReturn: '买入以来收益',
        updatedAt: '更新时间',
        baseline: '对比基准',
        baselinePreviousClose: '昨收',
        baselineFallbackClose: '回补收盘点',
        baselineUnavailable: '暂无可用日内基准',
        quoteLive: '行情可用',
        quoteStale: '缓存行情',
      },
    },
    riskPage: {
      kicker: '风险',
      title: '风险工作台',
      subtitle: '统一查看风险提示、资金压力与净值归因。',
      loading: '正在加载风险工作台。',
      error: '风险工作台加载失败。',
      alerts: '当前风险提示',
      nextStep: '建议动作',
      equityBridge: '净值桥',
      recentDrivers: '最近驱动事件',
      positionDrivers: '持仓驱动',
      emptyDrivers: '当前还没有可解释的驱动数据。',
      metrics: '风险指标',
      currentDrawdown: '当前回撤',
      currentDrawdownDetail: '当前净值距离最近峰值的回撤幅度。',
      maxDrawdown: '最大回撤',
      maxDrawdownDetail: '净值曲线历史上最大的峰谷回撤。',
      grossExposure: '总暴露',
      grossExposureDetail: '当前配置在非现金资产中的资金比例。',
      cashRatio: '现金占比',
      cashRatioDetail: '用于再平衡或防守的可用流动性缓冲。',
      largestPosition: '最大单一持仓',
      largestPositionDetail: '当前最大活跃持仓带来的单标的集中度。',
      top3Concentration: '前三集中度',
      top3ConcentrationDetail: '前三大持仓合计带来的集中度。',
      drawdown: '回撤路径',
      exposure: '暴露分桶',
      bucketHeavy: '高信念仓位',
      bucketCore: '核心仓位',
      bucketStarter: '起始仓位',
      bucketSmall: '小仓位 / 跟踪仓',
      bucketCash: '现金储备',
      concentration: '集中度拆解',
      noConcentration: '当前暂无活跃持仓，无法拆解集中度。',
    },
    trading: {
      killSwitch: {
        kicker: '交易控制',
        title: '全局熔断开关',
        subtitle:
          '在订单触达券商前拦截新的买入委托。卖出减仓和撤单类流程仍可继续执行。',
        loading: '检查中',
        enabled: '熔断已开启',
        disabled: '允许交易',
        enable: '开启熔断',
        disable: '解除熔断',
        submitting: '更新中...',
        reason: '操作原因',
        reasonPlaceholder: '开启买单熔断前必须填写原因',
        currentReasonPlaceholder: '当前熔断原因',
        reasonRequired: '开启熔断前必须填写原因。',
        updatedAt: '更新时间',
        neverUpdated: '从未更新',
        loadFailed: '熔断状态读取失败。',
      },
      orders: {
        kicker: '人工执行',
        title: '待确认订单审批',
        subtitle:
          '已通过事前风控的订单会停在这里，等待人工确认或拒绝后才进入下游执行。',
        loading: '正在加载待确认订单。',
        loadFailed: '待确认订单加载失败。',
        empty: '当前没有等待人工确认的订单。',
        pendingCount: (count: number) => `${count} 笔待审批`,
        symbol: '标的',
        side: '方向',
        buy: '买入',
        sell: '卖出',
        quantity: '数量',
        price: '价格',
        riskHint: '风控审计',
        rejectReason: '拒绝原因',
        rejectReasonPlaceholder: '拒绝时必填',
        rejectReasonRequired: '拒绝订单前必须填写原因。',
        actions: '操作',
        confirm: '确认通过',
        reject: '拒绝/撤销',
        riskApproved: '事前风控已通过',
        decisionId: '决策',
        intentId: '意图',
      },
    },
    backtest: {
      selection: {
        kicker: '回测历史',
        title: '报告选择',
        ariaLabel: '选择回测报告',
        loading: '正在加载回测结果。',
        loadFailed: '回测历史加载失败。',
        empty:
          '还没有保存的回测报告。先运行一次回测，再查看指标、成本、净值曲线和成交流水。',
        selectedLoading: '正在加载所选报告。',
        selectedFailed: '所选回测报告加载失败。',
      },
      summary: {
        return: '摘要收益',
        sharpe: '摘要夏普',
        maxDrawdown: '摘要最大回撤',
      },
      metrics: {
        totalReturn: '总收益率',
        sharpe: '夏普',
        sortino: '索提诺',
        maxDrawdown: '最大回撤',
        calmar: 'Calmar',
        winRate: '胜率',
        durationDays: (days: number) => `${days} 个交易日`,
        volatility: '波动率',
        annualReturn: '年化收益',
        grossTurnover: '总成交额',
        fills: (count: number) => `${count} 笔成交`,
        totalCommission: '总手续费',
        commissionDetail: '券商与交易所费用',
        totalSlippage: '总滑点',
        slippageDetail: '成交相对参考价的偏移成本',
      },
      chart: {
        kicker: '回测曲线',
        title: '净值与回撤',
        empty: '当前回测结果没有可用的净值曲线。',
        points: (count: number) => `${count} 个点`,
        drawdown: '回撤',
      },
      fills: {
        kicker: '执行流水',
        title: '成交明细',
        rows: (count: number) => `${count} 行`,
        empty:
          '当前保存结果没有成交明细。新的回测运行会在引擎返回成本流水后展示逐笔记录。',
        time: '时间',
        symbol: '标的',
        side: '方向',
        fillPrice: '成交价',
        quantity: '数量',
        commission: '手续费',
        slippage: '滑点',
      },
    },
    market: {
      kicker: '市场',
      title: '研究工作台',
      subtitle: '围绕关注列表、行情健康度、价格结构与研究记录组织研究输入。',
      loading: '正在加载研究工作台。',
      error: '研究工作台加载失败。',
      watchlist: '研究看板',
      health: '数据健康度',
      chart: '价格结构',
      addSymbol: '新增标的',
      symbolPlaceholder: '代码',
      assetClass: '资产类别',
      add: '添加',
      remove: '移除',
      marketOpen: '市场开盘',
      marketClosed: '市场收盘',
      refreshPolicy: '刷新策略',
      refreshQuotes: '刷新行情',
      refreshingQuotes: '刷新中',
      quoteRefreshComplete: '行情刷新完成',
      quoteRefreshPartial: '部分行情刷新完成',
      quoteRefreshStale: '行情源返回缓存行情',
      quoteRefreshFailed: '行情刷新失败',
      selectedSymbol: '当前标的',
      symbolLabel: '代码',
      priceLabel: '价格',
      snapshotLabel: '快照时间',
      holdingsContext: '持仓上下文',
      noSelection: '先选择或新增一个标的，再开始研究。',
      noChart: '当前标的没有可用的价格结构数据。',
      promptsTitle: '研究清单',
      notesTitle: '研究记录',
      notesEmpty: '还没有研究记录，先把当前逻辑或催化剂写下来。',
      noteType: '记录类型',
      noteTitle: '标题',
      noteContent: '内容',
      notePriority: '优先级',
      noteDate: '催化日期',
      noteDateFrom: '开始日期',
      noteDateTo: '结束日期',
      editNote: '编辑记录',
      updateNote: '更新记录',
      saveNote: '保存记录',
      savingNote: '保存中...',
      noteSaved: '研究记录已保存',
      noteFailed: '研究记录保存失败',
      noteDeleted: '研究记录已删除',
      noteDeleteFailed: '研究记录删除失败',
      noteTitlePlaceholder: '这次变化是什么，接下来要盯什么？',
      noteContentPlaceholder: '把逻辑、风险点和催化条件写成可复用记录。',
      note: '笔记',
      thesis: '逻辑',
      catalyst: '催化剂',
      highPriority: '高',
      normalPriority: '中',
      lowPriority: '低',
      researchCount: '研究条目',
      lastResearch: '最近更新',
      allTypes: '全部类型',
      allPriorities: '全部优先级',
      prompts: [
        '检查当前价格结构相对持仓成本的变化。',
        '确认当前仓位是否仍匹配判断与现金缓冲。',
        '判断该标的是新增机会还是集中度来源。',
      ],
    },
    explainability: {
      title: '解释层快照',
      empty: '当前还没有可用的解释层数据。',
      timeline: '时间序列归因',
      returnCalendar: '收益日历',
      heatmapView: '热力图',
      tableView: '表格',
      curveView: '曲线',
      bucketLabel: '周期',
      day: '日',
      week: '周',
      month: '月',
      year: '年',
      amountMetric: '金额',
      percentMetric: '涨跌幅',
      timelineEmpty: '暂无按日归因数据。',
      timelineRange: '日期区间',
      timelineEventKind: '事件类型',
      allEvents: '全部事件',
      deposits: '入金',
      withdrawals: '出金',
      dividends: '分红',
      buys: '买入',
      sells: '卖出',
      adjustments: '手工调整',
      category: '分类',
      impactSource: '影响来源',
      categoryCapital: '资金事件',
      categoryIncome: '收益事件',
      categoryOverride: '手工覆盖',
      categoryTrade: '交易事件',
      sourceExternal: '外部资金',
      sourceCash: '现金',
      sourceManual: '手工录入',
      sourcePositioning: '持仓变化',
      equity: '净值',
      netChange: '当日变化',
      externalFlow: '事件流入/流出',
      marketPnl: '市场变动',
      equityBridgeLabels: {
        deposits: '净投入',
        realized: '已实现盈亏',
        unrealized: '浮动盈亏',
        cash: '现金',
        market_value: '持仓市值',
        equity: '总资产',
      },
      equityBridgeDetails: {
        deposits: '入金与出金累计后的外部资金净额。',
        realized: '已平仓或已确认交易带来的锁定收益。',
        unrealized: '当前持仓按市价重估产生的浮动变化。',
        cash: '可用于再平衡、防守或下一笔交易的可用缓冲。',
        market_value: '当前持仓按行情价格估算的总市值。',
        equity: (totalPnl: string) => `净投入加累计盈亏（${totalPnl}）。`,
      },
      quantity: '数量',
      latestPrice: '行情价格',
      snapshotAt: '快照时间',
    },
    activity: {
      kicker: '流水',
      title: '账本活动台',
      subtitle: '手工录入交易、分红、现金流和调整，并刷新资产、收益和持仓。',
      loading: '正在加载账本流水。',
      error: '账本流水加载失败。',
      tradeSaved: '交易已保存',
      tradeFailed: '交易保存失败',
      cashFlowSaved: '现金流已保存',
      cashFlowFailed: '现金流保存失败',
      dividendSaved: '分红已保存',
      dividendFailed: '分红保存失败',
      adjustmentSaved: '调整已保存',
      adjustmentFailed: '调整保存失败',
      feedRefreshed: '组合快照和流水已经开始刷新。',
      feed: {
        title: '最近账本流水',
        empty:
          '还没有账本流水。先录入交易、现金流、分红或手工调整，时间线就会开始累计。',
      },
      pending: {
        kicker: '待确认',
        title: '待确认基金申购',
        loading: '正在加载待确认基金申购。',
        error: '待确认基金申购加载失败。',
        submittedAt: '提交于',
        waitingFor: '等待净值确认日',
      },
      forms: {
        trade: {
          title: '手工交易',
          occurredAtLabel: '发生时间',
          symbolLabel: '证券代码',
          directionLabel: '买卖方向',
          assetClassLabel: '资产类别',
          subscriptionAmountLabel: '申购金额',
          quantityLabel: '数量',
          priceLabel: '成交价',
          feeLabel: '费用',
          noteLabel: '交易备注',
          symbolPlaceholder: '证券代码',
          amountPlaceholder: '申购金额',
          quantityPlaceholder: '数量',
          pricePlaceholder: '成交价',
          notePlaceholder: '备注',
          buy: '买入',
          sell: '卖出',
          amountRequired: '基金买入需要填写申购金额。',
          fundAmountHelp:
            '基金买入可只记录金额，系统会在净值披露后确认份额和成本。',
          submit: '保存交易',
          saving: '保存中...',
          genericSubmitError: '交易保存失败。',
        },
        fundBatch: {
          title: '批量基金加仓',
          helper:
            '一次录入持有基金的加仓金额，系统会按金额申购并等待净值确认。',
          occurredAtLabel: '批量发生时间',
          amountLabel: (symbol: string) => `${symbol} 申购金额`,
          noteLabel: '批量基金备注',
          amountPlaceholder: '金额',
          notePlaceholder: '批量备注',
          emptyError: '至少填写一只基金的申购金额。',
          submit: '保存批量加仓',
          saving: '保存中...',
          genericSubmitError: '批量基金加仓保存失败。',
        },
        cashFlow: {
          title: '现金流水',
          occurredAtLabel: '现金流发生时间',
          amountLabel: '金额',
          flowTypeLabel: '流水类型',
          noteLabel: '现金流备注',
          notePlaceholder: '备注',
          deposit: '入金',
          withdrawal: '出金',
          submit: '保存现金流',
          saving: '保存中...',
          genericSubmitError: '现金流保存失败。',
        },
        dividend: {
          title: '分红',
          occurredAtLabel: '分红发生时间',
          symbolLabel: '分红证券代码',
          assetClassLabel: '分红资产类别',
          amountLabel: '分红金额',
          noteLabel: '分红备注',
          symbolPlaceholder: '证券代码',
          notePlaceholder: '备注',
          submit: '保存分红',
          saving: '保存中...',
          genericSubmitError: '分红保存失败。',
        },
        adjustment: {
          title: '手工调整',
          occurredAtLabel: '调整发生时间',
          symbolLabel: '调整证券代码',
          assetClassLabel: '调整资产类别',
          amountLabel: '调整金额',
          quantityLabel: '调整数量',
          priceLabel: '调整价格',
          noteLabel: '调整备注',
          symbolPlaceholder: '证券代码',
          notePlaceholder: '备注',
          submit: '保存调整',
          saving: '保存中...',
          genericSubmitError: '调整保存失败。',
        },
      },
    },
    settings: {
      kicker: '设置',
      title: '控制中心',
      subtitle:
        '集中查看数据新鲜度、服务状态、本地偏好与安全提示，不改变交易语义。',
      dataStatus: '数据状态',
      dataStatusDetail: '组合估值读取后端行情状态与市场刷新策略。',
      liveServices: '服务状态',
      liveServicesDetail: '调度器与接口状态来自后端 live status 接口。',
      preferences: '偏好设置',
      preferencesDetail: '主题和语言是当前浏览器的本地偏好。',
      notifications: '通知',
      notificationsDetail: '当前通知配置来自后端设置。',
      dataSafety: '数据安全',
      dataSafetyDetail: '缓存行情可能滞后市场价格，操作前请确认时间戳。',
      loading: '正在加载设置状态。',
      error: '设置状态加载失败。',
      retry: '重试状态',
      marketState: '市场状态',
      quoteState: '行情状态',
      refreshPolicy: '刷新策略',
      valuationTime: '估值时间',
      noValuationTime: '暂无估值时间',
      cacheOnly: '仅缓存',
      cacheOnlyDetail: '当前刷新策略为仅缓存，估值可能使用已存行情。',
      cachedQuotes: '缓存行情',
      cachedQuotesDetail: '当前估值基于缓存市场数据。',
      dataSource: '数据源',
      pollInterval: '轮询间隔',
      pollIntervalUnit: '秒',
      token: '供应商 token',
      maskedToken: '保留已脱敏 token',
      saveDataSource: '保存数据设置',
      savingDataSource: '保存中',
      dataSourceSaved: '数据设置已保存',
      dataSourceFailed: '数据设置保存失败',
      scheduler: '调度器',
      schedulerRunning: '调度器运行中',
      schedulerStopped: '调度器已停止',
      brokerInterface: '交易接口',
      brokerReady: '接口状态可用',
      brokerDegraded: '接口未运行',
      startScheduler: '启动调度器',
      stopScheduler: '停止调度器',
      updatingScheduler: '更新调度器',
      schedulerUpdateFailed: '调度器状态更新失败',
      backendSettings: '后端设置',
      assetsTracked: (count: number) => `${count} 个跟踪资产`,
      initialCash: '初始现金',
      strategy: '策略',
      themeMocha: 'Mocha',
      themeLatte: 'Latte',
      themeSystem: '跟随系统',
      languageZh: '中文',
      languageEn: 'English',
      localOnly: '本地偏好',
      notificationType: '通知类型',
      notificationUnavailable: '未配置通知通道',
      testNotification: '发送测试通知',
      testingNotification: '测试中',
      notificationOk: '测试通知已发送',
      notificationFailed: '测试通知失败',
      safetyCachedQuotes:
        '缓存行情表示最新已知价格来自本地存储，可能不等于当前市场价格。',
      safetyNoAdvice: 'Karkinos 是分析工作台，不构成投资建议或成交保证。',
      safetyPrivateData: '券商 token、账户导出和真实对账单不应进入公开仓库。',
      deferred: '暂缓项',
      deferredDetail:
        '完整券商凭证管理、通知通道编辑和高级数据源健康页暂不在第一版落地。',
    },
    placeholder: '这个页面还在继续建设中。',
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type AppCopy = (typeof copy)[Locale];

export function useCopy() {
  const { locale } = usePreferences();
  return copy[locale];
}

export function getCopy(locale: Locale) {
  return copy[locale];
}
