import { usePreferences, type Locale } from './preferences';

export const copy = {
  en: {
    shell: {
      title: 'Portfolio OS',
      description:
        'Portfolio workspace for holdings, cash, activity, and valuation.',
      language: 'Language',
      theme: 'Theme',
      navigation: 'Navigation',
      openNavigation: 'Open navigation',
      closeNavigation: 'Close navigation',
      toolbarTitle: 'Workspace toolbar',
      toolbarSubtitle:
        'Keep preferences and portfolio status in one consistent global toolbar.',
      accountStatus: 'Account Status',
      apiStatus: 'API',
      navStatus: 'NAV',
      marketStatus: 'Market',
      resync: 'Re-sync ledger',
      syncing: 'Checking',
      checking: 'Checking',
      syncedJustNow: 'Checked just now',
      lastSync: 'Last status check',
      latency: 'Latency',
      details: 'Details',
      statusUnknown: 'Status unknown',
      ledgerUnavailable: 'Ledger unavailable',
      brokerStopped: 'Interface stopped',
      brokerError: 'Interface error',
      valuationStale: 'Cached quotes',
      valuationError: 'Valuation error',
      valuationAt: (time: string) => `Valuation ${time}`,
      quoteStatus: 'Quote status',
      cachedQuotes: 'Cached quotes',
      marketLive: 'Market data available',
      marketClosed: 'Market closed',
      marketCacheOnly: 'Cache only',
      marketError: 'Market error',
      refreshPolicy: 'Refresh policy',
      marketSession: 'Market session',
      marketOpen: 'Market open',
      valuationUpdated: 'Last valuation refresh',
      clickToResync: 'Click to resync ledger',
      viewLatencyDetails: 'View latency details',
      viewValuationDetails: 'View valuation details',
      viewStatusDetails: 'View status details',
      themeStatus: 'Theme',
      ledgerMode: 'Ledger available',
      valuationMode: 'Valuation available',
      brokerMode: 'Broker API available',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      systemThemeLabel: 'System theme',
      lightThemeLabel: 'Light theme',
      darkThemeLabel: 'Dark theme',
      nav: {
        overview: 'Overview',
        portfolio: 'Portfolio',
        activity: 'Activity',
        risk: 'Risk',
        decision: 'Decision',
        market: 'Market',
        trading: 'Trading',
        backtest: 'Backtest',
        settings: 'Settings',
      },
    },
    states: {
      loading: 'Loading',
      error: 'Request failed',
      empty: 'No data yet',
      retry: 'Retry',
    },
    common: {
      required: 'This field is required.',
      mustBePositive: 'Enter a value greater than zero.',
      genericSubmitError: 'Request failed. Check your payload and server logs.',
      assetClassStock: 'Stock',
      assetClassEtf: 'ETF',
      assetClassFund: 'Fund',
      assetClassGold: 'Gold',
      assetClassBond: 'Bond',
      assetClassCash: 'Cash',
      staleReasons: {
        noRealDataAvailable: 'No real quote available',
        quoteTimestampMissing: 'Quote timestamp missing',
        marketClosedCacheOnly: 'Market closed; using cached quote',
        refreshPolicyCacheOnly: 'Refresh policy uses cache only',
        quoteOlderThanExpectedSession:
          'Quote older than expected trading session',
        providerTimeout: 'Data source timed out; using cached quote',
        providerUnavailable: 'Data source unavailable; using cached quote',
        sourceUnavailable: 'Data source unavailable; using cached quote',
        tushareFundNavPermissionDenied:
          'TuShare fund_nav permission denied; using Eastmoney fund estimate',
      },
    },
    mode: {
      account: 'Account Perspective',
      strategy: 'Strategy Perspective',
      accountShort: 'Account',
      strategyShort: 'Strategy',
    },
    overview: {
      kicker: 'Overview',
      title: 'Portfolio workspace',
      subtitle:
        'Track capital structure, return breakdown, and equity movement in one place.',
      modeHelper:
        'Account view focuses on capital structure. Strategy view focuses on return quality.',
      loading: 'Loading account overview and portfolio snapshot.',
      error: 'Failed to load account overview or snapshot.',
      curveLoading: 'Loading equity curve.',
      curveError: 'Failed to load equity curve.',
      empty: 'No account data available yet.',
      cards: {
        totalAssets: 'Total Assets',
        availableCash: 'Available Cash',
        todayPnl: 'Today PnL',
        unrealizedPnl: 'Unrealized PnL',
        cashRatio: 'Cash Ratio',
        currentDrawdown: 'Current Drawdown',
        cachedValuation: 'Cached quotes · valuation time',
      },
      dashboard: {
        equityPanel: 'Equity curve',
        opsPanel: 'Execution queue',
        pendingApprovals: 'Pending approvals',
        pendingEmpty: 'No orders require approval.',
        pendingEmptyDetail:
          'Approved orders will appear here before execution.',
        pendingCount: (count: number) => `${count} pending`,
        ledgerPanel: 'Latest ledger',
        ledgerEmpty: 'No ledger entries yet.',
        positionsPanel: 'Current positions',
        positionsDetail:
          'Quote price, cost basis, market value, and floating PnL from backend projections.',
        quickActions: 'Quick actions',
        refreshQuotes: 'Refresh quotes',
        refreshingQuotes: 'Refreshing',
        addLedger: 'Add ledger entry',
        tradingDesk: 'Trading desk',
        dataSettings: 'Data settings',
        dataStatus: 'Data status',
        valuationTime: 'Valuation time',
        quoteAge: 'Quote age',
        staleReason: 'Stale reason',
        refreshPolicy: 'Refresh policy',
        quoteSource: 'Quote source',
        checkDataSource: 'Check data source',
        refreshFailed: 'Quote refresh failed',
        refreshDone: 'Quote refresh completed',
        tradeBuy: 'Buy',
        tradeSell: 'Sell',
        cashDeposit: 'Deposit',
        cashWithdrawal: 'Withdrawal',
        dividend: 'Dividend',
        adjustment: 'Adjustment',
        unknownActivity: 'Ledger entry',
      },
      equityCurve: {
        title: 'Performance Analysis',
        range: 'Range',
        total: 'Total',
        stocks: 'Stocks',
        funds: 'Funds',
        others: 'Others',
        cash: 'Cash',
        allSeries: 'All series',
        oneDay: '1D',
        fiveDays: '5D',
        oneMonth: '1M',
        sixMonths: '6M',
        oneYear: '1Y',
        all: 'ALL',
        empty: 'No equity history yet.',
        emptyTitle: 'No Equity History Yet',
        emptyPeriod: 'No data available for this period.',
        insufficientData: 'Insufficient data for this range.',
        emptyDetail:
          'Record the first cash flow or trade to start building the equity curve.',
        emptyHint:
          'The curve appears after the portfolio has time-series ledger points.',
        currentPoint: 'Current valuation point',
        quoteStatus: 'Quote status',
        realtimeUnrealizedPnl: 'Unrealized P/L',
        cachedValuation: 'Valuation uses cached quotes',
      },
      livePulse: {
        title: 'Asset pulse',
        subtitle:
          'Review grouped holdings by asset class with quote move and since-buy return.',
        loading: 'Loading grouped holdings.',
        error: 'Failed to load grouped holdings.',
        empty: 'No active holdings yet.',
        marketValue: 'Market value',
        todayMove: 'Today move',
        sinceBuyReturn: 'Since-buy return',
      },
      risk: {
        registerKicker: 'Risk boundary',
        title: 'Risk boundary register',
        subtitle:
          'Read-only operating boundaries for concentration, liquidity, deployment, and execution posture.',
        concentration: 'Top Holding Weight',
        concentrationBoundary: 'Single-name concentration review',
        cashBuffer: 'Cash Buffer',
        cashBoundary: 'Liquidity floor before new exposure',
        deployment: 'Capital Deployment',
        deploymentBoundary: 'Capital-at-work pressure',
        positions: 'Active Positions',
        positionsBoundary: 'Open risk surface',
        positionsHint: (count: number) => `${count} open positions`,
        boundary: 'Boundary',
        current: 'Current',
        cashHealthy: 'Healthy reserve',
        cashWatch: 'Cash reserve is getting thin',
        deploymentBalanced: 'Deployment is balanced',
        deploymentHigh: 'Portfolio is running hot',
        executionBoundary: 'Execution boundary',
        executionBoundaryDetail:
          'Live-like workflows stay gated until an operator reviews the order and confirms it manually.',
        manualConfirmationRequired: 'Manual confirmation required',
      },
      breakdown: {
        accountKicker: 'Account breakdown',
        strategyKicker: 'Strategy breakdown',
        accountTitle: 'Capital structure and deployment',
        strategyTitle: 'Returns and execution outcome',
        marketValue: 'Market Value',
        activePositions: (count: number) => `${count} active positions`,
        cashReserve: 'Cash Reserve',
        netDeposits: 'Net Deposits',
        capitalBase: 'Capital base',
        deployment: 'Deployment',
        capitalAtWork: 'Capital at work',
        unrealizedPnl: 'Unrealized PnL',
        openPositions: 'Open positions',
        realizedPnl: 'Realized PnL',
        closedActivity: 'Closed activity',
        totalPnl: 'Total PnL',
        totalPnlHint: 'Realized + unrealized',
        payoutBuffer: 'Payout Buffer',
        payoutBufferHint: 'Cash available for redeploy',
      },
    },
    portfolio: {
      kicker: 'Portfolio',
      title: 'Holdings and allocation workspace',
      subtitle:
        'Filter holdings by symbol, asset class, and PnL focus while keeping allocation and return structure in view.',
      positionsLoading: 'Loading positions.',
      positionsError: 'Failed to load positions.',
      positionsEmpty: 'No holdings yet. Add trades from Activity first.',
      filterEmpty: 'No holdings match the current filters.',
      sidebarLoading: 'Loading allocation and performance breakdown.',
      sidebarError: 'Failed to load allocation or performance breakdown.',
      sidebarEmpty: 'No allocation view is available yet.',
      toolbar: {
        view: 'View',
        helper:
          'Account emphasizes capital structure. Strategy emphasizes return quality.',
        search: 'Search',
        searchPlaceholder: 'Filter by symbol',
        assetClass: 'Asset Class',
        allAssetClasses: 'All asset classes',
        pnlFocus: 'PnL Focus',
        allHoldings: 'All holdings',
        winnersOnly: 'Winners only',
        losersOnly: 'Losers only',
      },
      table: {
        symbol: 'Symbol',
        name: 'Name',
        assetClass: 'Asset Class',
        quantity: 'Quantity',
        availFrozen: 'Avail/Frozen',
        avgCost: 'Avg Cost',
        latestPrice: 'Quote Price',
        cachedQuoteNotice:
          'Cached quotes · positions valued from cached quotes',
        cachedQuoteAt: (time: string) => `Cached ${time}`,
        marketValue: 'Market Value',
        unrealized: 'Unrealized',
        returnPct: 'Return',
        quoteState: 'Quote State',
        quoteAge: 'Quote Age',
        staleReason: 'Stale Reason',
        actions: 'Actions',
        refresh: 'Refresh',
        refreshing: 'Refreshing',
        trade: 'Trade',
        ledger: 'Ledger',
        realized: 'Realized',
        detailsTitle: 'Holding Details',
      },
      detail: {
        kicker: 'Holding detail',
        title: (symbol: string) => `${symbol} Position`,
        subtitle:
          'Review cost, valuation, cached quote state, ledger trace, and related action paths for this holding.',
        backToPortfolio: 'Back to Portfolio',
        returnToPortfolio: 'Return to holdings list',
        notFoundTitle: 'Holding not found',
        notFoundDetail:
          'This symbol is not present in the current portfolio snapshot.',
        loading: 'Loading holding detail.',
        error: 'Failed to load holding detail.',
        summary: 'Summary',
        valuation: 'Valuation & Cost',
        quoteStatus: 'Quote & Data State',
        ledgerTrace: 'Ledger Trace',
        riskExposure: 'Risk & Exposure',
        relatedActions: 'Related Actions',
        displayName: 'Display Name',
        assetClass: 'Asset Class',
        quantity: 'Quantity',
        marketValue: 'Market Value',
        costBasis: 'Cost Basis',
        avgCost: 'Average Cost',
        quotePrice: 'Quote Price',
        unrealizedPnl: 'Unrealized PnL',
        pnlPct: 'PnL %',
        realizedPnl: 'Realized PnL',
        commissionPaid: 'Commission Paid',
        availableFrozen: 'Available / Frozen',
        portfolioWeight: 'Portfolio Weight',
        quoteTimestamp: 'Quote Timestamp',
        quoteSource: 'Quote Source',
        quoteAge: 'Quote Age',
        staleReason: 'Stale Reason',
        valuationTimestamp: 'Valuation Timestamp',
        refreshPolicy: 'Refresh Policy',
        marketOpen: 'Market Open',
        cacheOnly: 'Cache Only',
        marketClosed: 'Market Closed',
        cacheNotice: 'Cached quotes · valuation uses cached market data',
        quoteLive: 'Quote available',
        quoteStale: 'Cached quote',
        noLedger: 'No ledger trace is available for this symbol yet.',
        ledgerCount: (count: number) => `${count} matching entries`,
        entryType: 'Entry',
        amount: 'Amount',
        price: 'Price',
        note: 'Note',
        refreshQuote: 'Refresh this quote',
        refreshingQuote: 'Refreshing quote…',
        refreshDone: 'Quote refresh request completed.',
        refreshFailed: 'Quote refresh failed. Check market data state.',
        actionMarket: 'Open Market workspace',
        actionTrading: 'Open Trading approvals',
        actionActivity: 'Record activity',
        actionPortfolio: 'View all holdings',
      },
      allocation: {
        title: 'Allocation',
        empty: 'No allocation matches the current scope yet.',
      },
      allocationGroups: {
        title: 'Allocation Groups',
        empty: 'No grouped allocation available yet.',
      },
      liveBoard: {
        title: 'Holdings quote board',
        subtitle:
          'Track grouped holdings with quote price, intraday move, and since-buy return.',
        loading: 'Loading holdings quotes.',
        error: 'Failed to load holdings quotes.',
        empty:
          'No active holdings yet. Record the first trade to start tracking returns.',
        positionCount: (count: number) =>
          `${count} active holding${count === 1 ? '' : 's'}`,
        latestPrice: 'Quote price',
        todayMove: 'Today move',
        sinceBuyReturn: 'Since-buy return',
        updatedAt: 'Updated',
        baseline: 'Baseline',
        baselinePreviousClose: 'Previous close',
        baselineFallbackClose: 'Fallback close',
        baselineUnavailable: 'Daily baseline unavailable',
        quoteLive: 'Quote available',
        quoteStale: 'Cached quote',
        holdingDetailLink: (symbol: string) => `Holding Details: ${symbol}`,
        summaryOnly:
          'Instrument-level quote, cost, and K-line details are shown in the holdings list and detail pages below.',
      },
    },
    riskPage: {
      kicker: 'Risk',
      title: 'Risk workspace',
      subtitle:
        'Review current alerts, capital pressure, and equity attribution in one place.',
      loading: 'Loading risk workspace.',
      error: 'Failed to load risk workspace.',
      alerts: 'Active alerts',
      blockingRegister: 'Blocking register',
      blockingRegisterDetail:
        'Risk alerts that should be reviewed before new buy-side exposure reaches manual order approval.',
      noBlockingItems: 'No active blocking items from the risk summary.',
      nextStep: 'Suggested next step',
      equityBridge: 'Equity bridge',
      recentDrivers: 'Recent drivers',
      positionDrivers: 'Position drivers',
      emptyDrivers: 'No explainability drivers available yet.',
      metrics: 'Risk metrics',
      currentDrawdown: 'Current drawdown',
      currentDrawdownDetail:
        'Distance between current equity and the latest portfolio peak.',
      maxDrawdown: 'Max drawdown',
      maxDrawdownDetail:
        'Largest observed peak-to-trough loss across the equity curve.',
      grossExposure: 'Gross exposure',
      grossExposureDetail: 'Capital currently deployed in non-cash positions.',
      cashRatio: 'Cash ratio',
      cashRatioDetail: 'Immediate liquidity buffer for rebalance or defense.',
      largestPosition: 'Largest position',
      largestPositionDetail:
        'Single-name concentration of the biggest active holding.',
      top3Concentration: 'Top 3 concentration',
      top3ConcentrationDetail:
        'Aggregate concentration across the three largest holdings.',
      drawdown: 'Drawdown path',
      exposure: 'Exposure buckets',
      bucketHeavy: 'Heavy conviction',
      bucketCore: 'Core',
      bucketStarter: 'Starter',
      bucketSmall: 'Small / tracking',
      bucketCash: 'Cash reserve',
      concentration: 'Concentration drill-down',
      noConcentration:
        'No active positions available for concentration analysis.',
    },
    decision: {
      kicker: 'Decision',
      title: 'Decision cockpit',
      subtitle:
        'Review daily and intraday candidates with risk gates, strategy evidence, quote health, and manual-confirmation readiness.',
      loading: 'Loading decision cockpit.',
      error: 'Failed to load decision cockpit.',
      commandRegister: 'Decision command register',
      commandRegisterTitle: 'Today operating posture',
      commandRegisterDetail:
        'Aggregates daily and intraday candidates before any manual approval path.',
      candidateActions: 'Candidate actions',
      manualConfirmations: 'Manual confirmations',
      riskBlocks: 'Risk blocks',
      auditCoverage: 'Audit coverage',
      marketData: 'Market data',
      executionDefault: 'Execution default',
      manualConfirmationRequired: 'Manual confirmation required',
      readyCount: (count: number) => `${count} ready`,
      blockedCount: (count: number) => `${count} blocked`,
      dailyLane: 'Daily lane',
      intradayLane: 'Intraday lane',
      decision: 'Decision',
      generatedAt: 'Generated',
      candidateCount: (count: number) => `${count} candidates`,
      marketHealth: 'Market health',
      portfolio: 'Portfolio',
      portfolioEquity: 'Portfolio equity',
      quotesDetail: (live: number, stale: number) =>
        `${live} live quotes · ${stale} stale quotes`,
      positionCount: (count: number) => `${count} positions`,
      riskBlocked: 'Risk blocked',
      manualReady: 'Manual ready',
      excludedDaily: 'Daily-only excluded',
      noActionReasons: 'No-action reasons',
      noActionUnavailable: 'No reason supplied',
      noDetail: 'No detail supplied.',
      riskGate: 'Risk gate',
      manual: 'Manual',
      afterCostOos: 'After-cost/OOS',
      dataFreshness: 'Data freshness',
      journal: 'Journal',
      strategy: 'Strategy',
      targetWeight: 'Target weight',
      price: 'Price',
      riskDecision: 'Risk decision',
      openTradingApprovals: 'Open Trading approvals',
    },
    trading: {
      page: {
        kicker: 'Order control',
        title: 'Trading approvals',
        subtitle:
          'Inspect manual orders, confirm approved execution, reject blocked items, and keep an audit view of operator decisions.',
        statusCheck: 'Status check',
        pending: 'Pending approval',
        confirmed: 'Confirmed',
        rejected: 'Rejected',
        canceled: 'Canceled',
        lastUpdated: 'Last order update',
        filterTitle: 'Order filters',
        statusFilter: 'Status',
        allStatuses: 'All statuses',
        symbolFilter: 'Symbol',
        symbolPlaceholder: 'Filter symbol…',
        sideFilter: 'Side',
        allSides: 'All sides',
        buy: 'Buy',
        sell: 'Sell',
        filteredCount: (count: number) => `${count} visible`,
        ordersTitle: 'Order queue',
        historyKicker: 'Decision log',
        historyTitle: 'Audit trail',
        historyDetail:
          'Confirmed and rejected rows come from the existing manual-order endpoint.',
        noHistory: 'No completed order decisions are available yet.',
        statusPendingConfirm: 'Pending approval',
        statusConfirmed: 'Confirmed',
        statusRejected: 'Rejected',
        statusCanceled: 'Canceled',
        rejectConfirm: 'Reject with reason',
      },
      killSwitch: {
        kicker: 'Trading controls',
        title: 'Global kill switch',
        subtitle:
          'Block new buy orders before they reach broker execution. Sell-side risk reduction and cancel flows remain available.',
        loading: 'Checking',
        enabled: 'Kill switch active',
        disabled: 'Trading allowed',
        enable: 'Enable kill switch',
        disable: 'Disable kill switch',
        submitting: 'Updating...',
        reason: 'Operator reason',
        reasonPlaceholder: 'Required before blocking new buy orders',
        currentReasonPlaceholder: 'Current reason',
        reasonRequired: 'Enter a reason before enabling the kill switch.',
        updatedAt: 'Updated',
        neverUpdated: 'Never',
        loadFailed: 'Failed to load kill switch state.',
      },
      orders: {
        kicker: 'Manual execution',
        title: 'Pending order approvals',
        subtitle:
          'Orders that passed pre-trade risk checks wait here until an operator confirms or rejects them.',
        loading: 'Loading pending orders.',
        loadFailed: 'Failed to load pending orders.',
        empty: 'No orders are waiting for manual confirmation.',
        pendingCount: (count: number) => `${count} pending`,
        symbol: 'Symbol',
        side: 'Side',
        buy: 'Buy',
        sell: 'Sell',
        quantity: 'Quantity',
        price: 'Price',
        riskHint: 'Risk audit',
        rejectReason: 'Reject reason',
        rejectReasonPlaceholder: 'Required to reject…',
        rejectReasonRequired:
          'Enter a reject reason before rejecting an order.',
        actions: 'Actions',
        confirm: 'Confirm',
        reject: 'Reject',
        riskApproved: 'Pre-trade check passed',
        decisionId: 'Decision',
        intentId: 'Intent',
      },
    },
    backtest: {
      page: {
        kicker: 'Backtest lab',
        title: 'Strategy replay',
        subtitle:
          'Run a controlled historical simulation, then inspect risk, costs, equity path, and fill coverage.',
        formKicker: 'Run setup',
        formTitle: 'Backtest configuration',
        formDetail:
          'Uses the backend backtest contract. Leave assets empty to use configured coverage.',
        startDate: 'Start date',
        endDate: 'End date',
        initialCash: 'Initial cash',
        strategy: 'Strategy',
        strategyNames: {
          dual_ma: 'Dual Moving Average',
          monthly_rebalance: 'Monthly Rebalance',
          bollinger: 'Bollinger Mean Reversion',
          rsi: 'RSI Momentum / Reversion',
        },
        parameterLabels: {
          short_period: 'Short moving-average window',
          long_period: 'Long moving-average window',
          bb_period: 'Bollinger lookback window',
          num_std: 'Standard-deviation multiplier',
        },
        parameterDescriptions: {
          short_period: 'Fast-average lookback, counted in trading bars.',
          long_period: 'Slow-average lookback, counted in trading bars.',
          bb_period: 'Lookback window used to calculate Bollinger bands.',
          num_std:
            'Number of standard deviations used to place the upper and lower bands.',
        },
        parameterCode: (name: string) => `API field: ${name}`,
        strategyRegistryLoading: 'Loading strategy registry.',
        strategyRegistryFailed:
          'Strategy registry unavailable; using the default baseline.',
        shortPeriod: 'Short period',
        longPeriod: 'Long period',
        symbol: 'Symbol',
        symbolPlaceholder: '603659',
        assetClass: 'Asset class',
        singleSymbolHint:
          'Leave symbol empty to use the backend configured universe. Single-symbol runs are research evidence only.',
        assets: 'Assets',
        assetsPlaceholder: 'SYMBOL stock\nSYMBOL fund',
        assetsHint: 'One asset per line: symbol asset_class.',
        run: 'Run backtest',
        running: 'Running backtest',
        currentKicker: 'Current run',
        currentTitle: 'Run output',
        emptyCurrent:
          'Run a backtest to inspect the current result. Saved reports remain available below.',
        totalReturn: 'Total return',
        maxDrawdown: 'Max drawdown',
        totalCost: 'Total cost',
        fillsCount: 'Fills',
      },
      selection: {
        kicker: 'Backtest history',
        title: 'Report selection',
        ariaLabel: 'Select backtest report',
        loading: 'Loading backtest results.',
        loadFailed: 'Failed to load backtest history.',
        empty:
          'No backtest reports have been saved yet. Run a backtest first to inspect metrics, costs, equity curve, and fills.',
        selectedLoading: 'Loading selected report.',
        selectedFailed: 'Failed to load selected backtest report.',
      },
      summary: {
        return: 'Summary return',
        sharpe: 'Summary Sharpe',
        maxDrawdown: 'Summary max drawdown',
      },
      metrics: {
        totalReturn: 'Total return',
        sharpe: 'Sharpe',
        sortino: 'Sortino',
        maxDrawdown: 'Max drawdown',
        calmar: 'Calmar',
        winRate: 'Win rate',
        durationDays: (days: number) => `${days} trading days`,
        volatility: 'Volatility',
        annualReturn: 'Annual return',
        grossTurnover: 'Gross turnover',
        fills: (count: number) => `${count} fills`,
        totalCommission: 'Total commission',
        commissionDetail: 'Brokerage and exchange fees',
        totalSlippage: 'Total slippage',
        slippageDetail: 'Execution drift from reference price',
      },
      datasetSnapshot: {
        kicker: 'Data audit',
        title: 'Dataset snapshot',
        subtitle:
          'Frozen data identity for this research result. Use it to compare runs without silently changing inputs.',
        snapshotId: 'Snapshot id',
        dataSource: 'Data source',
        dateRange: 'Date range',
        rows: 'Rows',
        rowsValue: (count: number) => `${count} rows`,
        quality: 'Quality',
        qualityValue: (status: string) =>
          status === 'ok' ? 'OK' : status.toUpperCase(),
        cacheStore: 'Cache store',
        cacheMetadata: 'Cache metadata',
        adjustmentMode: 'Adjustment',
        symbol: 'Symbol',
        assetClass: 'Asset class',
        frequency: 'Frequency',
        providerName: 'Provider',
        coverage: 'Coverage',
        yes: 'Yes',
        no: 'No',
        unknown: 'Unknown',
        notAvailable: 'N/A',
      },
      validationEvidence: {
        kicker: 'Research evidence',
        title: 'Validation evidence',
        subtitle:
          'After-cost and out-of-sample evidence for this run. Use it for research review, not as an execution approval.',
        afterCostTitle: 'After-cost evidence',
        oosTitle: 'Out-of-sample split',
        netReturn: 'Net return',
        grossReturn: 'Gross before costs',
        totalCost: 'Total cost',
        costDrag: 'Cost drag',
        fills: 'Fills',
        turnover: 'Turnover',
        strategy: 'Strategy',
        benchmarkRole: 'Benchmark role',
        split: 'Split',
        status: 'Status',
        oosReturn: 'OOS return',
        excessReturn: 'Excess return',
        benchmarkReturn: 'Benchmark return',
        oosFills: 'OOS fills',
        assumptions: 'Assumptions',
        limitations: 'Limitations',
        unknown: 'Unknown',
        fillCount: (count: number) => `${count} fills`,
        statusValue: (status?: string, passed?: boolean | null) => {
          if (status === 'benchmark_passed' || passed === true) {
            return 'Benchmark passed';
          }
          if (status === 'benchmark_failed' || passed === false) {
            return 'Benchmark failed';
          }
          if (status === 'benchmark_not_supplied') {
            return 'Benchmark not supplied';
          }
          return status ?? 'Unknown';
        },
      },
      chart: {
        kicker: 'Backtest curve',
        title: 'Equity and drawdown',
        empty: 'No equity curve is available for this backtest result.',
        points: (count: number) => `${count} points`,
        drawdown: 'Drawdown',
      },
      fills: {
        kicker: 'Execution ledger',
        title: 'Fills',
        rows: (count: number) => `${count} rows`,
        empty:
          'No fill details are available for this saved result. New runs expose per-fill cost records when the backtest engine returns them.',
        time: 'Time',
        symbol: 'Symbol',
        side: 'Side',
        fillPrice: 'Fill price',
        quantity: 'Quantity',
        commission: 'Commission',
        slippage: 'Slippage',
      },
    },
    market: {
      kicker: 'Market',
      title: 'Research workspace',
      subtitle:
        'Track coverage, quote health, price structure, and research records for each symbol.',
      loading: 'Loading research board.',
      error: 'Failed to load research board.',
      watchlist: 'Research board',
      health: 'Data health',
      chart: 'Price structure',
      priceRangeKline: 'Price range / K-line',
      addSymbol: 'Add symbol',
      symbolPlaceholder: 'Symbol',
      assetClass: 'Asset class',
      add: 'Add',
      remove: 'Remove',
      marketOpen: 'Market open',
      marketClosed: 'Market closed',
      refreshPolicy: 'Refresh policy',
      sourceHealth: 'Source health',
      provider: 'Provider',
      providerStatus: 'Provider status',
      providerConfigured: 'Provider configured',
      providerSupportsFunds: 'Fund support',
      providerTimeout: 'Provider timeout',
      providerNextAction: 'Next action',
      metadataConfiguredCount: 'Configured metadata',
      latestQuote: 'Latest quote timestamp',
      cacheAge: 'Cache age',
      staleSymbols: 'Stale symbols',
      lastRefreshAttempt: 'Last refresh attempt',
      lastRefreshError: 'Last refresh error',
      quoteSource: 'Quote source',
      staleReason: 'Stale reason',
      quoteAge: 'Quote age',
      configured: 'Configured',
      notConfigured: 'Not configured',
      fundSupported: 'Fund-capable',
      fundUnsupported: 'Not fund-capable',
      unknown: 'Unknown',
      refreshQuotes: 'Refresh quotes',
      refreshingQuotes: 'Refreshing quotes',
      quoteRefreshComplete: 'Quote refresh completed',
      quoteRefreshPartial: 'Partial quote refresh completed',
      quoteRefreshStale: 'Quote source returned cached quotes',
      quoteRefreshFailed: 'Quote refresh failed',
      refreshResult: 'Refresh result',
      providerActions: {
        configure_data_source_token: 'Configure data source token',
        switch_to_fund_supported_provider: 'Switch to a fund-capable source',
        check_provider_network_or_use_cache:
          'Check provider network or continue with cached quotes',
        check_data_source_settings: 'Check data source settings',
        refresh_quotes_or_check_source: 'Refresh quotes or check source',
        configure_real_provider: 'Configure a real market data provider',
        configure_asset_metadata: 'Configure asset metadata',
        use_cached_data: 'Continue with local cached market data',
        run_first_sync: 'Configure a data source or run the first sync',
      },
      selectedSymbol: 'Selected symbol',
      symbolLabel: 'Symbol',
      priceLabel: 'Price',
      klineRanges: {
        oneMonth: '1M',
        threeMonths: '3M',
        sixMonths: '6M',
        oneYear: '1Y',
        all: 'All',
      },
      klineAxes: {
        price: 'Price axis',
        date: 'Date axis',
      },
      showKlineRange: (label: string) => `Show ${label} K-line range`,
      snapshotLabel: 'Snapshot time',
      holdingsContext: 'Holding context',
      noSelection: 'Select or add a symbol to start research.',
      noChart: 'No price structure available for the selected symbol.',
      promptsTitle: 'Research checklist',
      notesTitle: 'Research notes',
      notesEmpty:
        'No notes yet. Capture the current thesis before the market moves.',
      noteType: 'Record type',
      noteTitle: 'Title',
      noteContent: 'Content',
      notePriority: 'Priority',
      noteDate: 'Catalyst date',
      noteDateFrom: 'From date',
      noteDateTo: 'To date',
      editNote: 'Edit note',
      updateNote: 'Update note',
      saveNote: 'Save note',
      savingNote: 'Saving...',
      noteSaved: 'Research note saved',
      noteFailed: 'Failed to save research note',
      noteDeleted: 'Research note removed',
      noteDeleteFailed: 'Failed to remove research note',
      noteTitlePlaceholder: 'What changed or needs to be watched?',
      noteContentPlaceholder:
        'Capture the thesis, risk, or trigger in a reusable way.',
      note: 'Note',
      thesis: 'Thesis',
      catalyst: 'Catalyst',
      highPriority: 'High',
      normalPriority: 'Normal',
      lowPriority: 'Low',
      researchCount: 'Research records',
      lastResearch: 'Last updated',
      allTypes: 'All types',
      allPriorities: 'All priorities',
      prompts: [
        'Review price structure against the current cost basis.',
        'Confirm whether position size still fits conviction and cash buffer.',
        'Check whether the symbol adds opportunity or concentration risk.',
      ],
    },
    explainability: {
      title: 'Explainability snapshot',
      empty: 'No explainability data available yet.',
      timeline: 'Timeline attribution',
      returnCalendar: 'Return calendar',
      returnCalendarDetail:
        'Review daily, monthly, and annual return distribution next to the net-value curve.',
      calendarView: 'Calendar',
      heatmapView: 'Heatmap',
      tableView: 'Table',
      curveView: 'Curve',
      calendarPeriod: 'Calendar period',
      bucketLabel: 'Bucket',
      day: 'Day',
      week: 'Week',
      month: 'Month',
      year: 'Year',
      monthDays: 'Monthly days',
      yearMonths: 'Yearly months',
      years: 'Years',
      selectedPeriod: 'Selected period',
      weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      amountMetric: 'Amount',
      percentMetric: 'Percent',
      valuationCoverage: 'Valuation coverage',
      missingValuationShort: 'Price gap',
      missingHistoricalPrices: 'Missing historical prices',
      timelineEmpty: 'No daily attribution available yet.',
      currentPositionPnl: 'Current position PnL',
      returnCalendarWarmingUp: 'Return calendar is warming up',
      returnCalendarEmptyDetail:
        'Once Karkinos has continuous valuations and activity history, this area will switch to daily, monthly, and annual return views. For now it shows current holding PnL.',
      addActivity: 'Add activity',
      checkDataSource: 'Check data source',
      marketValue: 'Market value',
      unrealizedPnl: 'Unrealized PnL',
      timelineRange: 'Date range',
      timelineEventKind: 'Event type',
      allEvents: 'All events',
      deposits: 'Deposits',
      withdrawals: 'Withdrawals',
      dividends: 'Dividends',
      buys: 'Buys',
      sells: 'Sells',
      adjustments: 'Adjustments',
      category: 'Category',
      impactSource: 'Impact source',
      categoryCapital: 'Capital',
      categoryIncome: 'Income',
      categoryOverride: 'Override',
      categoryTrade: 'Trade',
      sourceExternal: 'External',
      sourceCash: 'Cash',
      sourceManual: 'Manual',
      sourcePositioning: 'Positioning',
      equity: 'Equity',
      netChange: 'Net change',
      netChangeDaily: 'Daily change',
      netChangeMonthly: 'Monthly change',
      netChangeAnnual: 'Annual change',
      externalFlow: 'External flow',
      marketPnl: 'Market move',
      marketBreakdownLabels: {
        stock: 'Stocks',
        fund: 'Funds',
        etf: 'ETFs',
        other: 'Other assets',
      },
      externalFlowBreakdownLabels: {
        cash_deposit: 'Deposits',
        cash_withdrawal: 'Withdrawals',
        dividend: 'Dividends',
        manual_adjustment: 'Manual adjustments',
      },
      equityBridgeLabels: {
        deposits: 'Net Deposits',
        realized: 'Realized PnL',
        unrealized: 'Unrealized PnL',
        cash: 'Cash',
        market_value: 'Market Value',
        equity: 'Total Equity',
      },
      equityBridgeDetails: {
        deposits: 'External capital recorded through deposits and withdrawals.',
        realized: 'Closed trade outcome already locked in.',
        unrealized: 'Mark-to-market move on current positions.',
        cash: 'Immediate buffer available for redeployment.',
        market_value: 'Current marked value of open positions.',
        equity: (totalPnl: string) => `Deposits plus total PnL (${totalPnl}).`,
      },
      quantity: 'Quantity',
      latestPrice: 'Quote price',
      snapshotAt: 'Snapshot time',
    },
    activity: {
      kicker: 'Activity',
      title: 'Ledger activity',
      subtitle:
        'Record trades, dividends, cash flows, and manual adjustments with immediate portfolio refresh.',
      loading: 'Loading ledger activity.',
      error: 'Failed to load ledger activity.',
      tradeSaved: 'Trade saved',
      tradeFailed: 'Trade failed',
      cashFlowSaved: 'Cash flow saved',
      cashFlowFailed: 'Cash flow failed',
      dividendSaved: 'Dividend saved',
      dividendFailed: 'Dividend failed',
      adjustmentSaved: 'Adjustment saved',
      adjustmentFailed: 'Adjustment failed',
      feedRefreshed: 'Portfolio projections are refreshing now.',
      summary: {
        pendingOrders: 'Pending fund orders',
        pendingOrdersDetail: 'Subscriptions waiting for NAV confirmation.',
        recentEntries: 'Recent entries',
        recentEntriesDetail: 'Visible audit rows in the current timeline.',
        netCashImpact: 'Net cash impact',
        netCashImpactDetail: 'Signed view of recent ledger movements.',
        latestActivity: 'Latest activity',
        latestActivityDetail: 'Most recent audited ledger timestamp.',
      },
      feed: {
        kicker: 'Audit trail',
        title: 'Recent ledger entries',
        count: (count: number) => `${count} entries`,
        empty:
          'No ledger activity yet. Submit a trade, cash flow, dividend, or adjustment to build the timeline.',
        noDetail: 'No public note',
        columns: {
          time: 'Time',
          activity: 'Activity',
          instrument: 'Instrument',
          amount: 'Cash impact',
          detail: 'Public note',
        },
        detailFields: {
          amount: 'Amount',
          quantity: 'Quantity',
          price: 'Price',
          fee: 'Fee',
        },
        entryTypes: {
          tradeBuy: 'Security buy',
          tradeSell: 'Security sell',
          cashDeposit: 'Cash deposit',
          cashWithdrawal: 'Cash withdrawal',
          dividend: 'Dividend received',
          adjustment: 'Manual adjustment',
          other: 'Ledger entry',
        },
        shortTypes: {
          buy: 'B',
          sell: 'S',
          cashIn: '+',
          cashOut: '-',
          dividend: 'D',
          adjustment: 'A',
          other: 'L',
        },
        cashImpact: {
          credit: 'Adds cash or realized proceeds',
          debit: 'Consumes cash',
          adjustment: 'Operator adjustment',
          neutral: 'Reference ledger movement',
        },
        sources: {
          manual: 'Manual entry',
          system: 'System entry',
          unknown: 'Source unknown',
        },
      },
      pending: {
        kicker: 'Pending',
        title: 'Pending fund subscriptions',
        loading: 'Loading pending fund subscriptions.',
        error: 'Failed to load pending fund subscriptions.',
        submittedAt: 'submitted',
        waitingFor: 'Waiting for NAV confirmation on',
        status: {
          pending: 'Pending NAV',
          confirmed: 'Confirmed',
          rejected: 'Rejected',
        },
      },
      forms: {
        trade: {
          title: 'Manual trade',
          occurredAtLabel: 'Occurred At',
          symbolLabel: 'Symbol',
          directionLabel: 'Direction',
          assetClassLabel: 'Asset Class',
          subscriptionAmountLabel: 'Subscription Amount',
          quantityLabel: 'Quantity',
          priceLabel: 'Unit Price',
          feeLabel: 'Fee',
          noteLabel: 'Trade Note',
          symbolPlaceholder: 'Symbol',
          amountPlaceholder: 'Subscription amount',
          quantityPlaceholder: 'Quantity',
          pricePlaceholder: 'Unit price',
          notePlaceholder: 'Note',
          buy: 'Buy',
          sell: 'Sell',
          amountRequired: 'Enter the subscription amount for a fund buy.',
          fundAmountHelp:
            'Fund buys can be recorded by amount. The system confirms quantity and cost from the published NAV.',
          commissionHelp: (rateBp: number, minimum: string) =>
            `Commission rate ${Number(rateBp).toFixed(1)} bp, minimum ${minimum}`,
          submit: 'Save Trade',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the trade.',
        },
        fundBatch: {
          title: 'Batch fund add',
          helper:
            'Record one top-up operation across your held funds. Positive rows are submitted as fund buys by amount.',
          occurredAtLabel: 'Batch Occurred At',
          amountLabel: (symbol: string) => `${symbol} Amount`,
          noteLabel: 'Batch Fund Note',
          amountPlaceholder: 'Amount',
          notePlaceholder: 'Batch note',
          loadingCandidates: 'Loading held funds.',
          noCandidates: 'No held funds available for batch add.',
          emptyError: 'Enter at least one fund amount.',
          submit: 'Save Batch',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the batch fund order.',
        },
        cashFlow: {
          title: 'Cash flow',
          occurredAtLabel: 'Cash Flow Occurred At',
          amountLabel: 'Amount',
          flowTypeLabel: 'Flow Type',
          noteLabel: 'Cash Flow Note',
          notePlaceholder: 'Note',
          deposit: 'Deposit',
          withdrawal: 'Withdrawal',
          submit: 'Save Cash Flow',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the cash flow.',
        },
        dividend: {
          title: 'Dividend',
          occurredAtLabel: 'Dividend Occurred At',
          symbolLabel: 'Dividend Symbol',
          assetClassLabel: 'Dividend Asset Class',
          amountLabel: 'Dividend Amount',
          noteLabel: 'Dividend Note',
          symbolPlaceholder: 'Symbol',
          notePlaceholder: 'Note',
          submit: 'Save Dividend',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the dividend.',
        },
        adjustment: {
          title: 'Manual adjustment',
          occurredAtLabel: 'Adjustment Occurred At',
          symbolLabel: 'Adjustment Symbol',
          assetClassLabel: 'Adjustment Asset Class',
          amountLabel: 'Adjustment Amount',
          quantityLabel: 'Adjustment Quantity',
          priceLabel: 'Adjustment Price',
          noteLabel: 'Adjustment Note',
          symbolPlaceholder: 'Symbol',
          notePlaceholder: 'Note',
          submit: 'Save Adjustment',
          saving: 'Saving...',
          genericSubmitError: 'Unable to save the adjustment.',
        },
      },
    },
    settings: {
      kicker: 'Settings',
      title: 'Control center',
      subtitle:
        'Review data freshness, service state, local preferences, and safety notes without changing trading semantics.',
      dataStatus: 'Data status',
      dataStatusDetail:
        'Portfolio valuation uses backend quote status and market refresh policy.',
      liveServices: 'Live services',
      liveServicesDetail:
        'Scheduler and interface state come from the backend live status endpoint.',
      preferences: 'Preferences',
      preferencesDetail:
        'Theme and language are local browser preferences for this workspace.',
      notifications: 'Notifications',
      notificationsDetail:
        'Current notification configuration is read from backend settings.',
      dataSafety: 'Data safety',
      dataSafetyDetail:
        'Cached quotes can lag market prices. Use timestamps before acting.',
      loading: 'Loading settings state.',
      error: 'Failed to load settings state.',
      retry: 'Retry status',
      marketState: 'Market state',
      quoteState: 'Quote state',
      refreshPolicy: 'Refresh policy',
      valuationTime: 'Valuation time',
      noValuationTime: 'No valuation timestamp',
      cacheOnly: 'Cache only',
      cacheOnlyDetail:
        'Market refresh policy is cache-only. Valuation may use stored quotes.',
      cachedQuotes: 'Cached quotes',
      cachedQuotesDetail: 'Current valuation is based on cached market data.',
      dataSource: 'Data source',
      dataSourceStatus: 'Data source status',
      currentProvider: 'Current provider',
      providerConfigured: 'Provider configured',
      providerSupportsFunds: 'Fund support',
      providerRequiresToken: 'Token required',
      metadataConfigured: 'Asset metadata',
      persistentCache: 'Persistent cache',
      lastSuccessfulSync: 'Last successful sync',
      providerNextAction: 'Next action',
      providerAkshare: 'AKShare',
      providerTushare: 'Tushare',
      selectDataSource: 'Select data source',
      providerTimeoutNotice: 'The configured quote source is timing out.',
      operationsRegister: 'Operations register',
      registerProvider: 'Provider',
      registerPollInterval: 'Poll interval',
      registerTrackedAssets: 'Tracked assets',
      registerStrategy: 'Strategy',
      providerConfiguration: 'Provider configuration',
      providerConfigurationDetail:
        'Data-source changes stay explicit and do not alter execution behavior.',
      metadataReadiness: 'Metadata readiness',
      metadataReadinessDetail:
        'Instrument names and provider symbols are checked before dashboard display.',
      dataSourceOperations: 'Data source operations',
      dataSourceOperationsDetail:
        'Review provider capability, permission gaps, fallback routing, and manual TuShare tasks.',
      providerCapabilityMatrix: 'Provider capability matrix',
      capabilityStockRealtime: 'Stock realtime',
      capabilityStockDaily: 'Stock daily',
      capabilityFundEstimate: 'Eastmoney fund estimate',
      capabilityPersistentCache: 'Persistent cache',
      tusharePermissions: 'TuShare permissions',
      fundFallback: 'Fund fallback',
      eastmoneyFundEstimate: 'Eastmoney fund estimate',
      latestFallbackQuote: 'Latest fallback quote',
      manualDailyTaskChecklist: 'Manual daily task checklist',
      taskTushareSignIn: 'TuShare sign-in',
      taskGuessMarketDirection: 'Guess market direction',
      taskCheckPoints: 'Check points and permissions',
      openExternal: 'Open',
      permissionBlocked: 'Permission blocked',
      permissionUnknown: 'Permission unknown',
      available: 'Available',
      assetMetadataMissing: 'Asset metadata is not configured',
      assetMetadataMissingDetail:
        'Backfill asset names and provider symbols into the local instrument metadata table. Keep config.json for runtime settings and watchlist symbols only.',
      assetMetadataDetail:
        'Asset identities should come from local instrument_metadata records, not runtime config.',
      assetMetadataMissingCount: 'Missing metadata',
      assetMetadataSource: 'Metadata source',
      assetMetadataMissingSymbols: 'Assets missing metadata',
      assetMetadataSnippet: 'Suggested config snippet',
      assetMetadataSnippetDetail:
        'Use this payload as a reference for metadata backfill or manual metadata repair. Do not commit private runtime config.',
      assetMetadataComplete: 'Asset metadata configured',
      assetMetadataCompleteDetail:
        'Current holdings have configured asset identities or safe fallbacks.',
      requiresRestart: 'Restart required',
      hotSwitchAvailable:
        'Quote refresh uses the selected source immediately. Broader data-manager tasks may still use startup configuration.',
      yes: 'Yes',
      no: 'No',
      pollInterval: 'Poll interval',
      pollIntervalUnit: 'seconds',
      token: 'Provider token',
      maskedToken: 'Masked token retained',
      accountCostProfile: 'Account cost profile',
      accountCostProfileDetail:
        'Used only to prefill manual stock/ETF trade fees. It does not change backtest assumptions or submit orders.',
      stockCommissionRate: 'Stock commission rate',
      minimumCommission: 'Minimum commission',
      accountCostPreview: (rate: number, minimum: number) =>
        `Manual trade default: ${Number(rate * 10000).toFixed(2)} bp, minimum CN¥${Number(
          minimum,
        ).toFixed(2)}`,
      saveAccountCosts: 'Save account costs',
      savingAccountCosts: 'Saving account costs',
      accountCostsSaved: 'Account costs saved',
      accountCostsSavedDetail:
        'New manual trades will prefill fees from this account profile.',
      accountCostsFailed: 'Failed to save account costs',
      saveDataSource: 'Save data settings',
      savingDataSource: 'Saving data settings',
      dataSourceSaved: 'Data settings saved',
      dataSourceFailed: 'Failed to save data settings',
      scheduler: 'Scheduler',
      schedulerRunning: 'Scheduler running',
      schedulerStopped: 'Scheduler stopped',
      brokerInterface: 'Broker interface',
      brokerReady: 'Interface status available',
      brokerDegraded: 'Interface not running',
      runtimeBoundary: 'Runtime boundary',
      schedulerBoundaryDetail:
        'Background polling refreshes market and live status; it does not submit orders.',
      executionDefault: 'Execution default',
      manualConfirmation: 'Manual confirmation',
      manualConfirmationRequired: 'Manual confirmation required',
      noAutoTrading: 'No automatic trading',
      safetyRegister: 'Safety register',
      marketDataBoundary: 'Market data',
      timestampRequired: 'Timestamp required',
      adviceBoundary: 'Advice boundary',
      analysisOnly: 'Analysis only',
      privateDataBoundary: 'Private data',
      keepPrivate: 'Keep private',
      safetyManualConfirmation:
        'Live-like workflows remain manually confirmed by default.',
      startScheduler: 'Start scheduler',
      stopScheduler: 'Stop scheduler',
      updatingScheduler: 'Updating scheduler',
      schedulerUpdateFailed: 'Failed to update scheduler state',
      backendSettings: 'Backend settings',
      assetsTracked: (count: number) => `${count} tracked assets`,
      initialCash: 'Initial cash',
      strategy: 'Strategy',
      themeMocha: 'Mocha',
      themeLatte: 'Latte',
      themeSystem: 'System',
      languageZh: '中文',
      languageEn: 'English',
      localOnly: 'Local preference',
      notificationType: 'Notification type',
      notificationUnavailable: 'No notification channel configured',
      testNotification: 'Send test notification',
      testingNotification: 'Testing notification',
      notificationOk: 'Notification test sent',
      notificationFailed: 'Notification test failed',
      safetyCachedQuotes:
        'Cached quote labels mean the latest known price is stored locally and may not match the current market.',
      safetyNoAdvice:
        'Karkinos is an analysis workspace, not investment advice or execution guarantee.',
      safetyPrivateData:
        'Keep broker tokens, account exports, and real statements out of public repositories.',
      deferred: 'Deferred',
      deferredDetail:
        'Full broker credentials, notification channel editing, and advanced data-source health are intentionally deferred.',
    },
    placeholder: 'This page is still under construction.',
  },
  zh: {
    shell: {
      title: '组合工作台',
      description: '覆盖持仓、现金、活动与估值的组合工作台。',
      language: '语言',
      theme: '主题',
      navigation: '导航',
      openNavigation: '打开导航',
      closeNavigation: '关闭导航',
      toolbarTitle: '全局工具栏',
      toolbarSubtitle: '把偏好设置与组合状态统一收口，避免页面级分散控制。',
      accountStatus: '账户状态',
      apiStatus: '接口',
      navStatus: '净值',
      marketStatus: '行情',
      resync: '重新同步账本',
      syncing: '检查中',
      checking: '检查中',
      syncedJustNow: '刚刚检查',
      lastSync: '上次状态检查',
      latency: '延迟',
      details: '详情',
      statusUnknown: '状态未知',
      ledgerUnavailable: '账本异常',
      brokerStopped: '接口未启动',
      brokerError: '接口异常',
      valuationStale: '缓存行情',
      valuationError: '估值异常',
      valuationAt: (time: string) => `估值 ${time}`,
      quoteStatus: '行情状态',
      cachedQuotes: '缓存行情',
      marketLive: '行情可用',
      marketClosed: '市场休市',
      marketCacheOnly: '缓存行情',
      marketError: '行情异常',
      refreshPolicy: '刷新策略',
      marketSession: '市场状态',
      marketOpen: '市场开盘',
      valuationUpdated: '上次估值刷新',
      clickToResync: '点击重新同步账本',
      viewLatencyDetails: '查看延迟详情',
      viewValuationDetails: '查看估值详情',
      viewStatusDetails: '查看状态详情',
      themeStatus: '主题',
      ledgerMode: '账本可用',
      valuationMode: '估值可用',
      brokerMode: '券商接口可用',
      light: '浅色',
      dark: '深色',
      system: '跟随系统',
      systemThemeLabel: '跟随系统主题',
      lightThemeLabel: '浅色主题',
      darkThemeLabel: '深色主题',
      nav: {
        overview: '总览',
        portfolio: '组合',
        activity: '流水',
        risk: '风险',
        decision: '决策',
        market: '市场',
        trading: '交易',
        backtest: '回测',
        settings: '设置',
      },
    },
    states: {
      loading: '加载中',
      error: '加载失败',
      empty: '暂无数据',
      retry: '重试',
    },
    common: {
      required: '该字段不能为空。',
      mustBePositive: '请输入大于零的数值。',
      genericSubmitError: '请求失败，请检查录入内容或服务日志。',
      assetClassStock: '股票',
      assetClassEtf: 'ETF',
      assetClassFund: '基金',
      assetClassGold: '黄金',
      assetClassBond: '债券',
      assetClassCash: '现金',
      staleReasons: {
        noRealDataAvailable: '暂无可用真实行情',
        quoteTimestampMissing: '缺少行情时间戳',
        marketClosedCacheOnly: '休市中，使用缓存行情',
        refreshPolicyCacheOnly: '当前刷新策略仅使用缓存',
        quoteOlderThanExpectedSession: '行情未及时更新（早于当前交易时段）',
        providerTimeout: '数据源超时，使用缓存行情',
        providerUnavailable: '数据源不可用，使用缓存行情',
        sourceUnavailable: '数据源不可用，使用缓存行情',
        tushareFundNavPermissionDenied:
          'TuShare fund_nav 权限不足，已切换 Eastmoney 基金估算源',
      },
    },
    mode: {
      account: '账户视角',
      strategy: '策略视角',
      accountShort: '账户',
      strategyShort: '策略',
    },
    overview: {
      kicker: '总览',
      title: '资产工作台',
      subtitle: '同时查看资金结构、收益拆解和净值走势，快速判断组合当前状态。',
      modeHelper: '账户视角看资本结构，策略视角看收益质量和执行结果。',
      loading: '正在加载账户总览和组合快照。',
      error: '账户总览或组合快照读取失败。',
      curveLoading: '正在加载净值曲线。',
      curveError: '净值曲线读取失败。',
      empty: '还没有可展示的账户数据。',
      cards: {
        totalAssets: '总资产',
        availableCash: '可用现金',
        todayPnl: '今日盈亏',
        unrealizedPnl: '浮动盈亏',
        cashRatio: '现金占比',
        currentDrawdown: '当前回撤',
        cachedValuation: '行情缓存 · 估值时间',
      },
      dashboard: {
        equityPanel: '资金曲线',
        opsPanel: '执行队列',
        pendingApprovals: '待审批订单',
        pendingEmpty: '当前没有需要审批的订单。',
        pendingEmptyDetail: '通过风控后的订单会先进入这里，确认后才继续执行。',
        pendingCount: (count: number) => `${count} 笔待审批`,
        ledgerPanel: '最新流水',
        ledgerEmpty: '还没有账本流水。',
        positionsPanel: '当前持仓',
        positionsDetail: '来自后端投影的行情价格、成本、市值与浮动盈亏。',
        quickActions: '快捷操作',
        refreshQuotes: '刷新行情',
        refreshingQuotes: '刷新中',
        addLedger: '添加流水',
        tradingDesk: '交易审批',
        dataSettings: '数据源设置',
        dataStatus: '数据状态',
        valuationTime: '估值时间',
        quoteAge: '行情年龄',
        staleReason: '缓存原因',
        refreshPolicy: '刷新策略',
        quoteSource: '行情来源',
        checkDataSource: '检查数据源',
        refreshFailed: '行情刷新失败',
        refreshDone: '行情刷新完成',
        tradeBuy: '买入',
        tradeSell: '卖出',
        cashDeposit: '入金',
        cashWithdrawal: '出金',
        dividend: '分红',
        adjustment: '调整',
        unknownActivity: '账本事件',
      },
      equityCurve: {
        title: '净值分析',
        range: '区间',
        total: '总计',
        stocks: '股票',
        funds: '基金',
        others: '其他',
        cash: '现金',
        allSeries: '全选',
        oneDay: '1D',
        fiveDays: '5D',
        oneMonth: '1M',
        sixMonths: '6M',
        oneYear: '1年',
        all: 'ALL',
        empty: '还没有净值历史。',
        emptyTitle: '尚无净值历史',
        emptyPeriod: '当前区间暂无可用数据。',
        insufficientData: '该区间数据不足。',
        emptyDetail: '先录入首笔资金流水或交易，系统才会开始生成净值曲线。',
        emptyHint: '净值曲线依赖按时间累计的账本历史点。',
        currentPoint: '当前估值点',
        quoteStatus: '行情状态',
        realtimeUnrealizedPnl: '浮动盈亏',
        cachedValuation: '估值基于缓存行情',
      },
      livePulse: {
        title: '资产脉冲',
        subtitle: '按资产类别快速查看持仓市值、行情涨跌和买入以来收益。',
        loading: '正在加载分组持仓。',
        error: '分组持仓加载失败。',
        empty: '当前还没有活跃持仓。',
        marketValue: '持仓市值',
        todayMove: '今日涨跌',
        sinceBuyReturn: '买入以来收益',
      },
      risk: {
        registerKicker: '风险边界',
        title: '风险边界登记',
        subtitle: '只读查看集中度、流动性、仓位利用与执行默认边界。',
        concentration: '最大持仓权重',
        concentrationBoundary: '单标的集中度复核',
        cashBuffer: '现金缓冲',
        cashBoundary: '新增暴露前的流动性底线',
        deployment: '资金利用率',
        deploymentBoundary: '在场资金压力',
        positions: '活跃持仓',
        positionsBoundary: '当前风险敞口数量',
        positionsHint: (count: number) => `${count} 个持仓在场`,
        boundary: '边界',
        current: '当前值',
        cashHealthy: '现金缓冲健康',
        cashWatch: '现金缓冲偏薄',
        deploymentBalanced: '仓位节奏平衡',
        deploymentHigh: '当前仓位偏热',
        executionBoundary: '执行边界',
        executionBoundaryDetail:
          '类实盘流程默认保持闸门控制，必须由操作人复核订单并手动确认。',
        manualConfirmationRequired: '需要人工确认',
      },
      breakdown: {
        accountKicker: '账户拆解',
        strategyKicker: '策略拆解',
        accountTitle: '资金结构与配置节奏',
        strategyTitle: '收益质量与执行结果',
        marketValue: '持仓市值',
        activePositions: (count: number) => `${count} 个活跃持仓`,
        cashReserve: '现金储备',
        netDeposits: '净投入',
        capitalBase: '净投入本金',
        deployment: '仓位利用率',
        capitalAtWork: '已投入仓位',
        unrealizedPnl: '浮动盈亏',
        openPositions: '来自当前持仓',
        realizedPnl: '已实现盈亏',
        closedActivity: '来自已落袋交易',
        totalPnl: '总收益',
        totalPnlHint: '已实现 + 浮动',
        payoutBuffer: '再配置缓冲',
        payoutBufferHint: '可用于继续配置的现金',
      },
    },
    portfolio: {
      kicker: '组合',
      title: '持仓与配置工作台',
      subtitle:
        '支持按标的检索、收益筛选和资产类别过滤，右侧持续给出配置和收益拆解。',
      positionsLoading: '正在加载持仓明细。',
      positionsError: '持仓明细加载失败。',
      positionsEmpty: '当前还没有持仓，先去 Activity 录入交易。',
      filterEmpty: '当前筛选条件下没有匹配的持仓。',
      sidebarLoading: '正在加载配置和收益拆解。',
      sidebarError: '配置或收益拆解加载失败。',
      sidebarEmpty: '还没有可用的配置视图。',
      toolbar: {
        view: '视角',
        helper: '账户视角偏重资产结构，策略视角偏重收益质量。',
        search: '搜索',
        searchPlaceholder: '按代码过滤',
        assetClass: '资产类别',
        allAssetClasses: '全部资产',
        pnlFocus: '收益筛选',
        allHoldings: '全部持仓',
        winnersOnly: '仅盈利',
        losersOnly: '仅亏损',
      },
      table: {
        symbol: '代码',
        name: '名称',
        assetClass: '资产类别',
        quantity: '数量',
        availFrozen: '可用/冻结',
        avgCost: '成本价',
        latestPrice: '行情价',
        cachedQuoteNotice: '行情缓存 · 持仓估值基于缓存行情',
        cachedQuoteAt: (time: string) => `缓存 ${time}`,
        marketValue: '市值',
        unrealized: '浮盈亏',
        returnPct: '收益率',
        quoteState: '行情状态',
        quoteAge: '行情年龄',
        staleReason: '缓存原因',
        actions: '操作',
        refresh: '刷新',
        refreshing: '刷新中',
        trade: '交易',
        ledger: '流水',
        realized: '已实现',
        detailsTitle: '持仓明细',
      },
      detail: {
        kicker: '持仓详情',
        title: (symbol: string) => `${symbol} 持仓`,
        subtitle:
          '查看该标的的成本、估值、缓存行情状态、流水轨迹和相关操作入口。',
        backToPortfolio: '返回组合',
        returnToPortfolio: '返回持仓列表',
        notFoundTitle: '未找到持仓',
        notFoundDetail: '当前组合快照中没有这个标的。',
        loading: '正在加载持仓详情。',
        error: '持仓详情加载失败。',
        summary: '摘要',
        valuation: '估值与成本',
        quoteStatus: '行情与数据状态',
        ledgerTrace: '流水轨迹',
        riskExposure: '风险暴露',
        relatedActions: '相关操作',
        displayName: '名称',
        assetClass: '资产类别',
        quantity: '数量',
        marketValue: '市值',
        costBasis: '成本额',
        avgCost: '平均成本',
        quotePrice: '行情价',
        unrealizedPnl: '浮动盈亏',
        pnlPct: '收益率',
        realizedPnl: '已实现盈亏',
        commissionPaid: '累计费用',
        availableFrozen: '可用 / 冻结',
        portfolioWeight: '组合占比',
        quoteTimestamp: '行情时间',
        quoteSource: '行情来源',
        quoteAge: '行情年龄',
        staleReason: '缓存原因',
        valuationTimestamp: '估值时间',
        refreshPolicy: '刷新策略',
        marketOpen: '市场开盘',
        cacheOnly: '仅缓存',
        marketClosed: '市场休市',
        cacheNotice: '行情缓存 · 估值基于缓存行情',
        quoteLive: '行情可用',
        quoteStale: '缓存行情',
        noLedger: '当前还没有这个标的的流水轨迹。',
        ledgerCount: (count: number) => `${count} 条匹配流水`,
        entryType: '类型',
        amount: '金额',
        price: '价格',
        note: '备注',
        refreshQuote: '刷新该标的行情',
        refreshingQuote: '正在刷新行情…',
        refreshDone: '行情刷新请求已完成。',
        refreshFailed: '行情刷新失败，请检查市场数据状态。',
        actionMarket: '打开市场工作台',
        actionTrading: '打开交易审批',
        actionActivity: '记录流水',
        actionPortfolio: '查看全部持仓',
      },
      allocation: {
        title: '配置明细',
        empty: '当前筛选范围下还没有可展示的配置。',
      },
      allocationGroups: {
        title: '分组配置',
        empty: '当前还没有分组配置可展示。',
      },
      liveBoard: {
        title: '持仓行情看板',
        subtitle: '按资产类别查看行情价格、今日涨跌和买入以来收益。',
        loading: '正在加载持仓行情。',
        error: '持仓行情加载失败。',
        empty: '当前还没有活跃持仓，先录入首笔交易再开始跟踪收益。',
        positionCount: (count: number) => `${count} 个活跃持仓`,
        latestPrice: '行情价格',
        todayMove: '今日涨跌',
        sinceBuyReturn: '买入以来收益',
        updatedAt: '更新时间',
        baseline: '对比基准',
        baselinePreviousClose: '昨收',
        baselineFallbackClose: '回补收盘点',
        baselineUnavailable: '暂无可用日内基准',
        quoteLive: '行情可用',
        quoteStale: '缓存行情',
        holdingDetailLink: (symbol: string) => `持仓明细：${symbol}`,
        summaryOnly: '单只标的行情、成本和 K 线在下方持仓明细与详情页中查看。',
      },
    },
    riskPage: {
      kicker: '风险',
      title: '风险工作台',
      subtitle: '统一查看风险提示、资金压力与净值归因。',
      loading: '正在加载风险工作台。',
      error: '风险工作台加载失败。',
      alerts: '当前风险提示',
      blockingRegister: '阻断登记',
      blockingRegisterDetail:
        '这些风险提示需要在新增买入暴露进入人工审批前完成复核。',
      noBlockingItems: '当前风险摘要没有活跃阻断项。',
      nextStep: '建议动作',
      equityBridge: '净值桥',
      recentDrivers: '最近驱动事件',
      positionDrivers: '持仓驱动',
      emptyDrivers: '当前还没有可解释的驱动数据。',
      metrics: '风险指标',
      currentDrawdown: '当前回撤',
      currentDrawdownDetail: '当前净值距离最近峰值的回撤幅度。',
      maxDrawdown: '最大回撤',
      maxDrawdownDetail: '净值曲线历史上最大的峰谷回撤。',
      grossExposure: '总暴露',
      grossExposureDetail: '当前配置在非现金资产中的资金比例。',
      cashRatio: '现金占比',
      cashRatioDetail: '用于再平衡或防守的可用流动性缓冲。',
      largestPosition: '最大单一持仓',
      largestPositionDetail: '当前最大活跃持仓带来的单标的集中度。',
      top3Concentration: '前三集中度',
      top3ConcentrationDetail: '前三大持仓合计带来的集中度。',
      drawdown: '回撤路径',
      exposure: '暴露分桶',
      bucketHeavy: '高信念仓位',
      bucketCore: '核心仓位',
      bucketStarter: '起始仓位',
      bucketSmall: '小仓位 / 跟踪仓',
      bucketCash: '现金储备',
      concentration: '集中度拆解',
      noConcentration: '当前暂无活跃持仓，无法拆解集中度。',
    },
    decision: {
      kicker: '决策',
      title: '决策驾驶舱',
      subtitle:
        '查看日级与盘中候选动作、风控闸门、策略证据、行情健康和人工确认状态。',
      loading: '正在加载决策驾驶舱。',
      error: '决策驾驶舱加载失败。',
      commandRegister: '决策指令登记',
      commandRegisterTitle: '今日运行姿态',
      commandRegisterDetail: '汇总日级与盘中候选动作，先于任何人工审批路径。',
      candidateActions: '候选动作',
      manualConfirmations: '人工确认',
      riskBlocks: '风控阻断',
      auditCoverage: '审计覆盖',
      marketData: '市场数据',
      executionDefault: '执行默认值',
      manualConfirmationRequired: '必须人工确认',
      readyCount: (count: number) => `${count} 个就绪`,
      blockedCount: (count: number) => `${count} 个阻断`,
      dailyLane: '日级通道',
      intradayLane: '盘中通道',
      decision: '决策',
      generatedAt: '生成时间',
      candidateCount: (count: number) => `${count} 个候选`,
      marketHealth: '行情健康',
      portfolio: '组合',
      portfolioEquity: '组合权益',
      quotesDetail: (live: number, stale: number) =>
        `${live} 条实时行情 · ${stale} 条陈旧行情`,
      positionCount: (count: number) => `${count} 个持仓`,
      riskBlocked: '风控拦截',
      manualReady: '待人工确认',
      excludedDaily: '排除日级动作',
      noActionReasons: '不行动原因',
      noActionUnavailable: '未提供原因',
      noDetail: '暂无详情。',
      riskGate: '风控闸门',
      manual: '人工确认',
      afterCostOos: '成本后/OOS',
      dataFreshness: '行情新鲜度',
      journal: '审计日志',
      strategy: '策略',
      targetWeight: '目标仓位',
      price: '价格',
      riskDecision: '风控决策',
      openTradingApprovals: '打开交易审批',
    },
    trading: {
      page: {
        kicker: '订单控制',
        title: '交易审批',
        subtitle:
          '集中查看人工订单、确认已通过执行、拒绝阻断项，并保留操作审计视图。',
        statusCheck: '状态检查',
        pending: '待审批',
        confirmed: '已确认',
        rejected: '已拒绝',
        canceled: '已取消',
        lastUpdated: '最近订单更新',
        filterTitle: '订单筛选',
        statusFilter: '状态',
        allStatuses: '全部状态',
        symbolFilter: '标的',
        symbolPlaceholder: '筛选代码…',
        sideFilter: '方向',
        allSides: '全部方向',
        buy: '买入',
        sell: '卖出',
        filteredCount: (count: number) => `${count} 条可见`,
        ordersTitle: '订单队列',
        historyKicker: '决策日志',
        historyTitle: '审计记录',
        historyDetail: '已确认与已拒绝记录来自现有人工订单接口。',
        noHistory: '当前还没有已完成的订单决策。',
        statusPendingConfirm: '待审批',
        statusConfirmed: '已确认',
        statusRejected: '已拒绝',
        statusCanceled: '已取消',
        rejectConfirm: '填写原因并拒绝',
      },
      killSwitch: {
        kicker: '交易控制',
        title: '全局熔断开关',
        subtitle:
          '在订单触达券商前拦截新的买入委托。卖出减仓和撤单类流程仍可继续执行。',
        loading: '检查中',
        enabled: '熔断已开启',
        disabled: '允许交易',
        enable: '开启熔断',
        disable: '解除熔断',
        submitting: '更新中...',
        reason: '操作原因',
        reasonPlaceholder: '开启买单熔断前必须填写原因',
        currentReasonPlaceholder: '当前熔断原因',
        reasonRequired: '开启熔断前必须填写原因。',
        updatedAt: '更新时间',
        neverUpdated: '从未更新',
        loadFailed: '熔断状态读取失败。',
      },
      orders: {
        kicker: '人工执行',
        title: '待确认订单审批',
        subtitle:
          '已通过事前风控的订单会停在这里，等待人工确认或拒绝后才进入下游执行。',
        loading: '正在加载待确认订单。',
        loadFailed: '待确认订单加载失败。',
        empty: '当前没有等待人工确认的订单。',
        pendingCount: (count: number) => `${count} 笔待审批`,
        symbol: '标的',
        side: '方向',
        buy: '买入',
        sell: '卖出',
        quantity: '数量',
        price: '价格',
        riskHint: '风控审计',
        rejectReason: '拒绝原因',
        rejectReasonPlaceholder: '拒绝时必填…',
        rejectReasonRequired: '拒绝订单前必须填写原因。',
        actions: '操作',
        confirm: '确认通过',
        reject: '拒绝/撤销',
        riskApproved: '事前风控已通过',
        decisionId: '决策',
        intentId: '意图',
      },
    },
    backtest: {
      page: {
        kicker: '回测实验室',
        title: '策略回放',
        subtitle: '运行受控历史模拟，并查看风险、成本、净值路径与成交覆盖。',
        formKicker: '运行设置',
        formTitle: '回测配置',
        formDetail: '使用后端回测 contract。资产留空时使用后端配置资产池。',
        startDate: '开始日期',
        endDate: '结束日期',
        initialCash: '初始现金',
        strategy: '策略',
        strategyNames: {
          dual_ma: '双均线策略',
          monthly_rebalance: '月度再平衡',
          bollinger: '布林带均值回归',
          rsi: 'RSI 动量/反转',
        },
        parameterLabels: {
          short_period: '短期均线周期',
          long_period: '长期均线周期',
          bb_period: '布林带回看周期',
          num_std: '标准差倍数',
        },
        parameterDescriptions: {
          short_period:
            '用于计算短期移动平均线的 K 线/交易周期数，例如 5 表示最近 5 根日线或分钟线。',
          long_period:
            '用于计算长期移动平均线的 K 线/交易周期数，必须大于短期周期。',
          bb_period: '用于计算布林带上下轨的回看窗口。',
          num_std: '上下轨距离均线的标准差倍数。',
        },
        parameterCode: (name: string) => `参数键：${name}`,
        strategyRegistryLoading: '正在加载策略注册表。',
        strategyRegistryFailed: '策略注册表不可用；暂用默认基准策略。',
        shortPeriod: '短周期',
        longPeriod: '长周期',
        symbol: '标的代码',
        symbolPlaceholder: '603659',
        assetClass: '资产类别',
        singleSymbolHint:
          '标的留空时使用后端配置资产池；单标的回测仅作为研究证据。',
        assets: '资产',
        assetsPlaceholder: '标的代码 stock\n标的代码 fund',
        assetsHint: '每行一个资产：代码 asset_class。',
        run: '运行回测',
        running: '回测运行中',
        currentKicker: '当前运行',
        currentTitle: '运行结果',
        emptyCurrent: '运行一次回测后可查看当前结果；已保存报告仍在下方可选。',
        totalReturn: '总收益率',
        maxDrawdown: '最大回撤',
        totalCost: '总成本',
        fillsCount: '成交数',
      },
      selection: {
        kicker: '回测历史',
        title: '报告选择',
        ariaLabel: '选择回测报告',
        loading: '正在加载回测结果。',
        loadFailed: '回测历史加载失败。',
        empty:
          '还没有保存的回测报告。先运行一次回测，再查看指标、成本、净值曲线和成交流水。',
        selectedLoading: '正在加载所选报告。',
        selectedFailed: '所选回测报告加载失败。',
      },
      summary: {
        return: '摘要收益',
        sharpe: '摘要夏普',
        maxDrawdown: '摘要最大回撤',
      },
      metrics: {
        totalReturn: '总收益率',
        sharpe: '夏普',
        sortino: '索提诺',
        maxDrawdown: '最大回撤',
        calmar: 'Calmar',
        winRate: '胜率',
        durationDays: (days: number) => `${days} 个交易日`,
        volatility: '波动率',
        annualReturn: '年化收益',
        grossTurnover: '总成交额',
        fills: (count: number) => `${count} 笔成交`,
        totalCommission: '总手续费',
        commissionDetail: '券商与交易所费用',
        totalSlippage: '总滑点',
        slippageDetail: '成交相对参考价的偏移成本',
      },
      datasetSnapshot: {
        kicker: '数据审计',
        title: '数据快照',
        subtitle:
          '本次研究结果使用的数据身份。用于比较运行结果，避免静默更换输入数据。',
        snapshotId: '快照 ID',
        dataSource: '数据源',
        dateRange: '日期范围',
        rows: '行数',
        rowsValue: (count: number) => `${count} 行`,
        quality: '质量',
        qualityValue: (status: string) => (status === 'ok' ? '正常' : status),
        cacheStore: '缓存存储',
        cacheMetadata: '缓存元数据',
        adjustmentMode: '复权',
        symbol: '标的',
        assetClass: '资产类别',
        frequency: '频率',
        providerName: '来源',
        coverage: '覆盖范围',
        yes: '是',
        no: '否',
        unknown: '未知',
        notAvailable: '不可用',
      },
      validationEvidence: {
        kicker: '研究证据',
        title: '验证证据',
        subtitle:
          '本次运行的 after-cost 与样本外证据。用于研究复核，不代表执行审批。',
        afterCostTitle: '扣成本后证据',
        oosTitle: '样本外切分',
        netReturn: '净收益率',
        grossReturn: '扣成本前收益',
        totalCost: '总成本',
        costDrag: '成本拖累',
        fills: '成交',
        turnover: '成交额',
        strategy: '策略',
        benchmarkRole: '基准角色',
        split: '切分点',
        status: '状态',
        oosReturn: '样本外收益',
        excessReturn: '超额收益',
        benchmarkReturn: '基准收益',
        oosFills: '样本外成交',
        assumptions: '假设',
        limitations: '限制',
        unknown: '未知',
        fillCount: (count: number) => `${count} 笔成交`,
        statusValue: (status?: string, passed?: boolean | null) => {
          if (status === 'benchmark_passed' || passed === true) {
            return '基准通过';
          }
          if (status === 'benchmark_failed' || passed === false) {
            return '基准未通过';
          }
          if (status === 'benchmark_not_supplied') {
            return '未提供基准';
          }
          return status ?? '未知';
        },
      },
      chart: {
        kicker: '回测曲线',
        title: '净值与回撤',
        empty: '当前回测结果没有可用的净值曲线。',
        points: (count: number) => `${count} 个点`,
        drawdown: '回撤',
      },
      fills: {
        kicker: '执行流水',
        title: '成交明细',
        rows: (count: number) => `${count} 行`,
        empty:
          '当前保存结果没有成交明细。新的回测运行会在引擎返回成本流水后展示逐笔记录。',
        time: '时间',
        symbol: '标的',
        side: '方向',
        fillPrice: '成交价',
        quantity: '数量',
        commission: '手续费',
        slippage: '滑点',
      },
    },
    market: {
      kicker: '市场',
      title: '研究工作台',
      subtitle: '围绕关注列表、行情健康度、价格结构与研究记录组织研究输入。',
      loading: '正在加载研究工作台。',
      error: '研究工作台加载失败。',
      watchlist: '研究看板',
      health: '数据健康度',
      chart: '价格结构',
      priceRangeKline: '区间波动 / K 线',
      klineRanges: {
        oneMonth: '1月',
        threeMonths: '3月',
        sixMonths: '6月',
        oneYear: '1年',
        all: '全部',
      },
      klineAxes: {
        price: '价格轴',
        date: '日期轴',
      },
      showKlineRange: (label: string) => `显示 ${label} K 线区间`,
      addSymbol: '新增标的',
      symbolPlaceholder: '代码',
      assetClass: '资产类别',
      add: '添加',
      remove: '移除',
      marketOpen: '市场开盘',
      marketClosed: '市场收盘',
      refreshPolicy: '刷新策略',
      sourceHealth: '来源健康度',
      provider: '行情源',
      providerStatus: '行情源状态',
      providerConfigured: '配置状态',
      providerSupportsFunds: '基金支持',
      providerTimeout: '超时保护',
      providerNextAction: '下一步',
      metadataConfiguredCount: '已配置元数据',
      latestQuote: '最近行情时间',
      cacheAge: '缓存年龄',
      staleSymbols: '缓存标的',
      lastRefreshAttempt: '最近刷新尝试',
      lastRefreshError: '最近刷新错误',
      quoteSource: '行情来源',
      staleReason: '缓存原因',
      quoteAge: '行情年龄',
      configured: '已配置',
      notConfigured: '未配置',
      fundSupported: '支持基金',
      fundUnsupported: '不支持基金',
      unknown: '未知',
      refreshQuotes: '刷新行情',
      refreshingQuotes: '刷新中',
      quoteRefreshComplete: '行情刷新完成',
      quoteRefreshPartial: '部分行情刷新完成',
      quoteRefreshStale: '行情源返回缓存行情',
      quoteRefreshFailed: '行情刷新失败',
      refreshResult: '刷新结果',
      providerActions: {
        configure_data_source_token: '配置数据源 token',
        switch_to_fund_supported_provider: '切换到支持基金的数据源',
        check_provider_network_or_use_cache:
          '检查行情源网络，或继续使用缓存行情',
        check_data_source_settings: '检查数据源设置',
        refresh_quotes_or_check_source: '刷新行情或检查数据源',
        configure_real_provider: '配置真实行情源',
        configure_asset_metadata: '配置资产元数据',
        use_cached_data: '继续使用本地缓存行情',
        run_first_sync: '配置数据源或执行首次同步',
      },
      selectedSymbol: '当前标的',
      symbolLabel: '代码',
      priceLabel: '价格',
      snapshotLabel: '快照时间',
      holdingsContext: '持仓上下文',
      noSelection: '先选择或新增一个标的，再开始研究。',
      noChart: '当前标的没有可用的价格结构数据。',
      promptsTitle: '研究清单',
      notesTitle: '研究记录',
      notesEmpty: '还没有研究记录，先把当前逻辑或催化剂写下来。',
      noteType: '记录类型',
      noteTitle: '标题',
      noteContent: '内容',
      notePriority: '优先级',
      noteDate: '催化日期',
      noteDateFrom: '开始日期',
      noteDateTo: '结束日期',
      editNote: '编辑记录',
      updateNote: '更新记录',
      saveNote: '保存记录',
      savingNote: '保存中...',
      noteSaved: '研究记录已保存',
      noteFailed: '研究记录保存失败',
      noteDeleted: '研究记录已删除',
      noteDeleteFailed: '研究记录删除失败',
      noteTitlePlaceholder: '这次变化是什么，接下来要盯什么？',
      noteContentPlaceholder: '把逻辑、风险点和催化条件写成可复用记录。',
      note: '笔记',
      thesis: '逻辑',
      catalyst: '催化剂',
      highPriority: '高',
      normalPriority: '中',
      lowPriority: '低',
      researchCount: '研究条目',
      lastResearch: '最近更新',
      allTypes: '全部类型',
      allPriorities: '全部优先级',
      prompts: [
        '检查当前价格结构相对持仓成本的变化。',
        '确认当前仓位是否仍匹配判断与现金缓冲。',
        '判断该标的是新增机会还是集中度来源。',
      ],
    },
    explainability: {
      title: '解释层快照',
      empty: '当前还没有可用的解释层数据。',
      timeline: '时间序列归因',
      returnCalendar: '收益日历',
      returnCalendarDetail: '结合净值曲线查看每日、每月与年度收益分布。',
      calendarView: '日历',
      heatmapView: '热力图',
      tableView: '表格',
      curveView: '曲线',
      calendarPeriod: '日历周期',
      bucketLabel: '周期',
      day: '日',
      week: '周',
      month: '月',
      year: '年',
      monthDays: '月内每日',
      yearMonths: '年内每月',
      years: '每年',
      selectedPeriod: '选中周期',
      weekdays: ['日', '一', '二', '三', '四', '五', '六'],
      amountMetric: '金额',
      percentMetric: '涨跌幅',
      valuationCoverage: '估值覆盖',
      missingValuationShort: '缺价',
      missingHistoricalPrices: '缺少历史价格',
      timelineEmpty: '暂无按日归因数据。',
      currentPositionPnl: '当前持仓收益',
      returnCalendarWarmingUp: '收益日历正在积累数据',
      returnCalendarEmptyDetail:
        '当 Karkinos 积累到连续估值和流水记录后，这里会切换为日、月、年的收益日历。现在先展示当前持仓收益。',
      addActivity: '补充流水',
      checkDataSource: '检查数据源',
      marketValue: '持仓市值',
      unrealizedPnl: '浮动盈亏',
      timelineRange: '日期区间',
      timelineEventKind: '事件类型',
      allEvents: '全部事件',
      deposits: '入金',
      withdrawals: '出金',
      dividends: '分红',
      buys: '买入',
      sells: '卖出',
      adjustments: '手工调整',
      category: '分类',
      impactSource: '影响来源',
      categoryCapital: '资金事件',
      categoryIncome: '收益事件',
      categoryOverride: '手工覆盖',
      categoryTrade: '交易事件',
      sourceExternal: '外部资金',
      sourceCash: '现金',
      sourceManual: '手工录入',
      sourcePositioning: '持仓变化',
      equity: '净值',
      netChange: '当日变化',
      netChangeDaily: '当日变化',
      netChangeMonthly: '当月变化',
      netChangeAnnual: '当年变化',
      externalFlow: '事件流入/流出',
      marketPnl: '市场变动',
      marketBreakdownLabels: {
        stock: '股票变化',
        fund: '基金变化',
        etf: 'ETF变化',
        other: '其他资产变化',
      },
      externalFlowBreakdownLabels: {
        cash_deposit: '入金',
        cash_withdrawal: '出金',
        dividend: '分红',
        manual_adjustment: '手工调整',
      },
      equityBridgeLabels: {
        deposits: '净投入',
        realized: '已实现盈亏',
        unrealized: '浮动盈亏',
        cash: '现金',
        market_value: '持仓市值',
        equity: '总资产',
      },
      equityBridgeDetails: {
        deposits: '入金与出金累计后的外部资金净额。',
        realized: '已平仓或已确认交易带来的锁定收益。',
        unrealized: '当前持仓按市价重估产生的浮动变化。',
        cash: '可用于再平衡、防守或下一笔交易的可用缓冲。',
        market_value: '当前持仓按行情价格估算的总市值。',
        equity: (totalPnl: string) => `净投入加累计盈亏（${totalPnl}）。`,
      },
      quantity: '数量',
      latestPrice: '行情价格',
      snapshotAt: '快照时间',
    },
    activity: {
      kicker: '流水',
      title: '账本活动台',
      subtitle: '手工录入交易、分红、现金流和调整，并刷新资产、收益和持仓。',
      loading: '正在加载账本流水。',
      error: '账本流水加载失败。',
      tradeSaved: '交易已保存',
      tradeFailed: '交易保存失败',
      cashFlowSaved: '现金流已保存',
      cashFlowFailed: '现金流保存失败',
      dividendSaved: '分红已保存',
      dividendFailed: '分红保存失败',
      adjustmentSaved: '调整已保存',
      adjustmentFailed: '调整保存失败',
      feedRefreshed: '组合快照和流水已经开始刷新。',
      summary: {
        pendingOrders: '待确认申购',
        pendingOrdersDetail: '等待净值确认的基金申购。',
        recentEntries: '近期流水',
        recentEntriesDetail: '当前时间线可见的审计记录。',
        netCashImpact: '净现金影响',
        netCashImpactDetail: '按业务方向折算的近期现金变化。',
        latestActivity: '最新活动',
        latestActivityDetail: '最近一条账本审计时间。',
      },
      feed: {
        kicker: '审计流水',
        title: '最近账本流水',
        count: (count: number) => `${count} 条`,
        empty:
          '还没有账本流水。先录入交易、现金流、分红或手工调整，时间线就会开始累计。',
        noDetail: '无公开备注',
        columns: {
          time: '时间',
          activity: '业务类型',
          instrument: '标的',
          amount: '资金影响',
          detail: '业务备注',
        },
        detailFields: {
          amount: '金额',
          quantity: '份额/数量',
          price: '价格',
          fee: '手续费',
        },
        entryTypes: {
          tradeBuy: '证券买入',
          tradeSell: '证券卖出',
          cashDeposit: '现金入金',
          cashWithdrawal: '现金出金',
          dividend: '分红入账',
          adjustment: '手工调整',
          other: '账本流水',
        },
        shortTypes: {
          buy: '买',
          sell: '卖',
          cashIn: '入',
          cashOut: '出',
          dividend: '息',
          adjustment: '调',
          other: '流',
        },
        cashImpact: {
          credit: '增加现金或确认回款',
          debit: '占用现金',
          adjustment: '人工校正',
          neutral: '参考流水',
        },
        sources: {
          manual: '手工录入',
          system: '系统生成',
          unknown: '来源未知',
        },
      },
      pending: {
        kicker: '待确认',
        title: '待确认基金申购',
        loading: '正在加载待确认基金申购。',
        error: '待确认基金申购加载失败。',
        submittedAt: '提交于',
        waitingFor: '等待净值确认日',
        status: {
          pending: '待确认净值',
          confirmed: '已确认',
          rejected: '已拒绝',
        },
      },
      forms: {
        trade: {
          title: '手工交易',
          occurredAtLabel: '发生时间',
          symbolLabel: '证券代码',
          directionLabel: '买卖方向',
          assetClassLabel: '资产类别',
          subscriptionAmountLabel: '申购金额',
          quantityLabel: '数量',
          priceLabel: '成交价',
          feeLabel: '费用',
          noteLabel: '交易备注',
          symbolPlaceholder: '证券代码',
          amountPlaceholder: '申购金额',
          quantityPlaceholder: '数量',
          pricePlaceholder: '成交价',
          notePlaceholder: '备注',
          buy: '买入',
          sell: '卖出',
          amountRequired: '基金买入需要填写申购金额。',
          fundAmountHelp:
            '基金买入可只记录金额，系统会在净值披露后确认份额和成本。',
          commissionHelp: (rateBp: number, minimum: string) =>
            `佣金率万${Number(rateBp).toFixed(1)}，最低 ${minimum}`,
          submit: '保存交易',
          saving: '保存中...',
          genericSubmitError: '交易保存失败。',
        },
        fundBatch: {
          title: '批量基金加仓',
          helper:
            '一次录入持有基金的加仓金额，系统会按金额申购并等待净值确认。',
          occurredAtLabel: '批量发生时间',
          amountLabel: (symbol: string) => `${symbol} 申购金额`,
          noteLabel: '批量基金备注',
          amountPlaceholder: '金额',
          notePlaceholder: '批量备注',
          loadingCandidates: '正在读取已持有基金。',
          noCandidates: '当前没有可批量加仓的已持有基金。',
          emptyError: '至少填写一只基金的申购金额。',
          submit: '保存批量加仓',
          saving: '保存中...',
          genericSubmitError: '批量基金加仓保存失败。',
        },
        cashFlow: {
          title: '现金流水',
          occurredAtLabel: '现金流发生时间',
          amountLabel: '金额',
          flowTypeLabel: '流水类型',
          noteLabel: '现金流备注',
          notePlaceholder: '备注',
          deposit: '入金',
          withdrawal: '出金',
          submit: '保存现金流',
          saving: '保存中...',
          genericSubmitError: '现金流保存失败。',
        },
        dividend: {
          title: '分红',
          occurredAtLabel: '分红发生时间',
          symbolLabel: '分红证券代码',
          assetClassLabel: '分红资产类别',
          amountLabel: '分红金额',
          noteLabel: '分红备注',
          symbolPlaceholder: '证券代码',
          notePlaceholder: '备注',
          submit: '保存分红',
          saving: '保存中...',
          genericSubmitError: '分红保存失败。',
        },
        adjustment: {
          title: '手工调整',
          occurredAtLabel: '调整发生时间',
          symbolLabel: '调整证券代码',
          assetClassLabel: '调整资产类别',
          amountLabel: '调整金额',
          quantityLabel: '调整数量',
          priceLabel: '调整价格',
          noteLabel: '调整备注',
          symbolPlaceholder: '证券代码',
          notePlaceholder: '备注',
          submit: '保存调整',
          saving: '保存中...',
          genericSubmitError: '调整保存失败。',
        },
      },
    },
    settings: {
      kicker: '设置',
      title: '控制中心',
      subtitle:
        '集中查看数据新鲜度、服务状态、本地偏好与安全提示，不改变交易语义。',
      dataStatus: '数据状态',
      dataStatusDetail: '组合估值读取后端行情状态与市场刷新策略。',
      liveServices: '服务状态',
      liveServicesDetail: '调度器与接口状态来自后端 live status 接口。',
      preferences: '偏好设置',
      preferencesDetail: '主题和语言是当前浏览器的本地偏好。',
      notifications: '通知',
      notificationsDetail: '当前通知配置来自后端设置。',
      dataSafety: '数据安全',
      dataSafetyDetail: '缓存行情可能滞后市场价格，操作前请确认时间戳。',
      loading: '正在加载设置状态。',
      error: '设置状态加载失败。',
      retry: '重试状态',
      marketState: '市场状态',
      quoteState: '行情状态',
      refreshPolicy: '刷新策略',
      valuationTime: '估值时间',
      noValuationTime: '暂无估值时间',
      cacheOnly: '仅缓存',
      cacheOnlyDetail: '当前刷新策略为仅缓存，估值可能使用已存行情。',
      cachedQuotes: '缓存行情',
      cachedQuotesDetail: '当前估值基于缓存市场数据。',
      dataSource: '数据源',
      dataSourceStatus: '数据源状态',
      currentProvider: '当前数据源',
      providerConfigured: '配置状态',
      providerSupportsFunds: '基金支持',
      providerRequiresToken: '需要 token',
      metadataConfigured: '资产元数据',
      persistentCache: '持久化缓存',
      lastSuccessfulSync: '最近成功同步',
      providerNextAction: '下一步',
      providerAkshare: 'AKShare',
      providerTushare: 'Tushare',
      selectDataSource: '选择数据源',
      providerTimeoutNotice: '当前行情源请求超时。',
      operationsRegister: '运营登记',
      registerProvider: '供应商',
      registerPollInterval: '轮询间隔',
      registerTrackedAssets: '跟踪资产',
      registerStrategy: '策略',
      providerConfiguration: '供应商配置',
      providerConfigurationDetail: '数据源变更保持显式，不改变交易执行行为。',
      metadataReadiness: '元数据就绪',
      metadataReadinessDetail:
        '资产名称和 provider_symbol 在进入驾驶舱展示前需要可追溯。',
      dataSourceOperations: '数据源运营',
      dataSourceOperationsDetail:
        '集中查看供应商能力、权限缺口、fallback 路由和 TuShare 手工任务。',
      providerCapabilityMatrix: '供应商能力矩阵',
      capabilityStockRealtime: '股票实时',
      capabilityStockDaily: '股票日线',
      capabilityFundEstimate: 'Eastmoney 基金估算',
      capabilityPersistentCache: '持久化缓存',
      tusharePermissions: 'TuShare 权限',
      fundFallback: '基金 fallback',
      eastmoneyFundEstimate: 'Eastmoney 基金估算',
      latestFallbackQuote: '最近 fallback 行情',
      manualDailyTaskChecklist: '每日手工任务清单',
      taskTushareSignIn: 'TuShare 签到',
      taskGuessMarketDirection: '猜涨跌',
      taskCheckPoints: '查看积分和权限',
      openExternal: '打开',
      permissionBlocked: '权限不足',
      permissionUnknown: '权限未知',
      available: '可用',
      assetMetadataMissing: '尚未配置资产元数据',
      assetMetadataMissingDetail:
        '请将资产名称和 provider_symbol 补齐到本地 instrument_metadata 表。config.json 只保留运行配置和 watchlist 代码。',
      assetMetadataDetail:
        '资产身份应来自本地 instrument_metadata 记录，而不是运行配置。',
      assetMetadataMissingCount: '缺失元数据',
      assetMetadataSource: '元数据来源',
      assetMetadataMissingSymbols: '缺少元数据的资产',
      assetMetadataSnippet: '建议配置片段',
      assetMetadataSnippetDetail:
        '可将此内容作为元数据补齐或手工修复参考。不要提交私有运行配置。',
      assetMetadataComplete: '资产元数据已配置',
      assetMetadataCompleteDetail: '当前持仓已有资产身份配置或安全 fallback。',
      requiresRestart: '需要重启',
      hotSwitchAvailable:
        '行情刷新会立即使用所选数据源；更广泛的数据管理任务可能仍使用启动时配置。',
      yes: '是',
      no: '否',
      pollInterval: '轮询间隔',
      pollIntervalUnit: '秒',
      token: '供应商 token',
      maskedToken: '保留已脱敏 token',
      accountCostProfile: '账户成本配置',
      accountCostProfileDetail:
        '仅用于手工录入股票/ETF 交易时预填费用，不改变回测假设，也不会提交订单。',
      stockCommissionRate: '股票佣金率',
      minimumCommission: '最低佣金',
      accountCostPreview: (rate: number, minimum: number) =>
        `手工交易默认：万${Number(rate * 10000).toFixed(2)}，最低 ¥${Number(
          minimum,
        ).toFixed(2)}`,
      saveAccountCosts: '保存账户成本',
      savingAccountCosts: '保存中',
      accountCostsSaved: '账户成本已保存',
      accountCostsSavedDetail: '新的手工交易会按该账户成本预填费用。',
      accountCostsFailed: '账户成本保存失败',
      saveDataSource: '保存数据设置',
      savingDataSource: '保存中',
      dataSourceSaved: '数据设置已保存',
      dataSourceFailed: '数据设置保存失败',
      scheduler: '调度器',
      schedulerRunning: '调度器运行中',
      schedulerStopped: '调度器已停止',
      brokerInterface: '交易接口',
      brokerReady: '接口状态可用',
      brokerDegraded: '接口未运行',
      runtimeBoundary: '运行边界',
      schedulerBoundaryDetail: '后台轮询刷新行情和 live 状态；它不会提交订单。',
      executionDefault: '执行默认值',
      manualConfirmation: '人工确认',
      manualConfirmationRequired: '必须人工确认',
      noAutoTrading: '不自动交易',
      safetyRegister: '安全登记',
      marketDataBoundary: '市场数据',
      timestampRequired: '必须检查时间戳',
      adviceBoundary: '建议边界',
      analysisOnly: '仅作分析',
      privateDataBoundary: '私有数据',
      keepPrivate: '保持私密',
      safetyManualConfirmation: '类 live 工作流默认保持人工确认。',
      startScheduler: '启动调度器',
      stopScheduler: '停止调度器',
      updatingScheduler: '更新调度器',
      schedulerUpdateFailed: '调度器状态更新失败',
      backendSettings: '后端设置',
      assetsTracked: (count: number) => `${count} 个跟踪资产`,
      initialCash: '初始现金',
      strategy: '策略',
      themeMocha: 'Mocha',
      themeLatte: 'Latte',
      themeSystem: '跟随系统',
      languageZh: '中文',
      languageEn: 'English',
      localOnly: '本地偏好',
      notificationType: '通知类型',
      notificationUnavailable: '未配置通知通道',
      testNotification: '发送测试通知',
      testingNotification: '测试中',
      notificationOk: '测试通知已发送',
      notificationFailed: '测试通知失败',
      safetyCachedQuotes:
        '缓存行情表示最新已知价格来自本地存储，可能不等于当前市场价格。',
      safetyNoAdvice: 'Karkinos 是分析工作台，不构成投资建议或成交保证。',
      safetyPrivateData: '券商 token、账户导出和真实对账单不应进入公开仓库。',
      deferred: '暂缓项',
      deferredDetail:
        '完整券商凭证管理、通知通道编辑和高级数据源健康页暂不在第一版落地。',
    },
    placeholder: '这个页面还在继续建设中。',
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type AppCopy = (typeof copy)[Locale];

export function useCopy() {
  const { locale } = usePreferences();
  return copy[locale];
}

export function getCopy(locale: Locale) {
  return copy[locale];
}
