import type { Locale } from '../shared/locale';

export const shellCopy = {
  en: {
    shell: {
      title: 'Quant platform',
      description:
        'Personal finance app for holdings, cash, activity, and valuation.',
      language: 'Language',
      theme: 'Theme',
      navigation: 'Navigation',
      primaryNavigation: 'Primary navigation',
      moreNavigation: 'More',
      openNavigation: 'Open navigation',
      closeNavigation: 'Close navigation',
      currentWorkspace: 'Current workspace',
      publicHome: 'Public home',
      workspaceLabel: 'Quant workbench',
      accountMode: 'Mode',
      paperShadowMode: 'Paper / shadow',
      manualConfirmationMode: 'Manual confirmation',
      evidenceStatus: 'Evidence',
      dataStatus: 'Data',
      commandTrigger: 'Go to a workspace route',
      commandTitle: 'Go to workspace',
      commandPlaceholder: 'Search routes',
      commandResults: 'Workspace routes',
      commandEmpty: 'No matching route.',
      closeCommand: 'Close command menu',
      persistedEvidence: 'Recorded evidence',
      toolbarTitle: 'Workspace toolbar',
      toolbarSubtitle:
        'Keep preferences and portfolio status in one consistent global toolbar.',
      accountStatus: 'Account Status',
      apiStatus: 'API',
      navStatus: 'NAV',
      marketStatus: 'Market',
      resync: 'Re-sync ledger',
      syncing: 'Checking',
      checking: 'Checking',
      syncedJustNow: 'Checked just now',
      lastSync: 'Last status check',
      latency: 'Latency',
      details: 'Details',
      statusUnknown: 'Status unknown',
      ledgerUnavailable: 'Ledger unavailable',
      brokerStopped: 'Interface stopped',
      brokerError: 'Interface error',
      valuationStale: 'Cached quotes',
      valuationError: 'Valuation error',
      valuationAt: (time: string) => `Valuation ${time}`,
      quoteStatus: 'Quote status',
      cachedQuotes: 'Cached quotes',
      marketLive: 'Market data available',
      marketClosed: 'Market closed',
      marketCacheOnly: 'Cache only',
      marketError: 'Market error',
      refreshPolicy: 'Refresh policy',
      marketSession: 'Market session',
      marketOpen: 'Market open',
      valuationUpdated: 'Last valuation refresh',
      clickToResync: 'Click to resync ledger',
      viewLatencyDetails: 'View latency details',
      viewValuationDetails: 'View valuation details',
      viewStatusDetails: 'View status details',
      themeStatus: 'Theme',
      ledgerMode: 'Ledger available',
      valuationMode: 'Valuation available',
      brokerMode: 'Broker API available',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      systemThemeLabel: 'System theme',
      lightThemeLabel: 'Light theme',
      darkThemeLabel: 'Dark theme',
      nav: {
        overview: 'Overview',
        portfolio: 'Portfolio',
        activity: 'Ledger',
        risk: 'Risk',
        decision: 'Decision',
        operations: 'Operations',
        market: 'Market',
        trading: 'Execution',
        backtest: 'Strategy Lab',
        aiResearch: 'AI Research',
        settings: 'Settings',
      },
    },
    placeholder: 'This page is still under construction.',
  },
  zh: {
    shell: {
      title: '量化投研平台',
      description: '覆盖持仓、现金、活动与估值的个人金融应用。',
      language: '语言',
      theme: '主题',
      navigation: '导航',
      primaryNavigation: '主导航',
      moreNavigation: '更多',
      openNavigation: '打开导航',
      closeNavigation: '关闭导航',
      currentWorkspace: '当前工作区',
      publicHome: '公开首页',
      workspaceLabel: '个人量化工作台',
      accountMode: '模式',
      paperShadowMode: '模拟 / 影子',
      manualConfirmationMode: '人工确认',
      evidenceStatus: '证据',
      dataStatus: '数据',
      commandTrigger: '跳转到工作台页面',
      commandTitle: '前往工作台',
      commandPlaceholder: '搜索页面',
      commandResults: '工作台页面',
      commandEmpty: '没有匹配的页面。',
      closeCommand: '关闭命令菜单',
      persistedEvidence: '已记录证据',
      toolbarTitle: '全局工具栏',
      toolbarSubtitle: '把偏好设置与组合状态统一收口，避免页面级分散控制。',
      accountStatus: '账户状态',
      apiStatus: '接口',
      navStatus: '净值',
      marketStatus: '行情',
      resync: '重新同步账本',
      syncing: '检查中',
      checking: '检查中',
      syncedJustNow: '刚刚检查',
      lastSync: '上次状态检查',
      latency: '延迟',
      details: '详情',
      statusUnknown: '状态未知',
      ledgerUnavailable: '账本异常',
      brokerStopped: '接口未启动',
      brokerError: '接口异常',
      valuationStale: '缓存行情',
      valuationError: '估值异常',
      valuationAt: (time: string) => `估值 ${time}`,
      quoteStatus: '行情状态',
      cachedQuotes: '缓存行情',
      marketLive: '行情可用',
      marketClosed: '市场休市',
      marketCacheOnly: '缓存行情',
      marketError: '行情异常',
      refreshPolicy: '刷新策略',
      marketSession: '市场状态',
      marketOpen: '市场开盘',
      valuationUpdated: '上次估值刷新',
      clickToResync: '点击重新同步账本',
      viewLatencyDetails: '查看延迟详情',
      viewValuationDetails: '查看估值详情',
      viewStatusDetails: '查看状态详情',
      themeStatus: '主题',
      ledgerMode: '账本可用',
      valuationMode: '估值可用',
      brokerMode: '券商接口可用',
      light: '浅色',
      dark: '深色',
      system: '跟随系统',
      systemThemeLabel: '跟随系统主题',
      lightThemeLabel: '浅色主题',
      darkThemeLabel: '深色主题',
      nav: {
        overview: '总览',
        portfolio: '组合',
        activity: '账本',
        risk: '风控',
        decision: '决策',
        operations: '运营',
        market: '行情',
        trading: '执行',
        backtest: '策略实验',
        aiResearch: 'AI 研究',
        settings: '设置',
      },
    },
    placeholder: '这个页面还在继续建设中。',
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type ShellCopy = (typeof shellCopy)[Locale];

declare module '../shared/i18n/context' {
  interface ApplicationCopy {
    shell: ShellCopy['shell'];
    placeholder: ShellCopy['placeholder'];
  }
}
