import type { Locale } from '../../shared/locale';

export const activityCopy = {
  en: {
    kicker: 'Ledger',
    title: 'Ledger history',
    subtitle:
      'Review the account ledger first. New trades, cash movements, dividends, and adjustments are added only through explicit, controlled actions.',
    loading: 'Loading ledger activity.',
    error: 'Failed to load ledger activity.',
    tradeSaved: 'Trade saved',
    tradeFailed: 'Trade failed',
    cashFlowSaved: 'Cash flow saved',
    cashFlowFailed: 'Cash flow failed',
    dividendSaved: 'Dividend saved',
    dividendFailed: 'Dividend failed',
    adjustmentSaved: 'Adjustment saved',
    adjustmentFailed: 'Adjustment failed',
    feedRefreshed: 'Portfolio projections are refreshing now.',
    summary: {
      pendingOrders: 'Pending fund orders',
      pendingOrdersDetail: 'Subscriptions waiting for NAV confirmation.',
      netCashImpact: 'Net cash impact',
      netCashImpactUnavailable: 'Not available',
      netCashImpactDetail:
        'Recent entries are not a complete account history, so no total is shown.',
    },
    entryTools: {
      kicker: 'Entry tools',
      title: 'New entry',
      openAction: 'New entry',
      closeAction: 'Close entry tools',
      boundaryTitle: 'Ledger write boundary',
      detail:
        'Preview public ledger impact before writing to the local ledger, then refresh the portfolio path.',
      boundary:
        'Submitting writes the reviewed entry to the account ledger. It never places a broker order or grants trading authority.',
      ariaLabel: 'Ledger entry tool selector',
    },
    feed: {
      kicker: 'Audit trail',
      title: 'Recent entries',
      count: (count: number) => `${count} entries`,
      showing: (visible: number, total: number) =>
        `Showing ${visible} of ${total} entries`,
      showMore: (count: number) => `Show ${count} more entries`,
      tableScrollLabel: 'Ledger entries table',
      empty:
        'No entries yet. Submit a trade, cash flow, dividend, or adjustment to build the timeline.',
      filteredEmpty: 'No matching entries.',
      categoryFilter: 'Ledger category filter',
      subcategoryFilter: 'Ledger detail filter',
      searchLabel: 'Search instrument name or symbol',
      searchPlaceholder: 'Search name / symbol',
      openHoldingDetail: (symbol: string) =>
        `Open holding history for ${symbol}`,
      categoryLabels: {
        all: 'All',
        trade: 'Trades',
        cash: 'Cash',
        dividend: 'Dividends',
        adjustment: 'Adjustments',
        other: 'Other',
      },
      subcategoryAllLabels: {
        trade: 'All trades',
        cash: 'All cash',
        dividend: 'All dividends',
        adjustment: 'All adjustments',
        other: 'All other',
      },
      subcategoryLabels: {
        stock: 'Stocks',
        fund: 'Funds',
        cashAccount: 'Cash account',
        otherAsset: 'Other assets',
        cashDeposit: 'Deposits',
        cashWithdrawal: 'Withdrawals',
        cashInterest: 'Interest',
        otherCash: 'Other cash',
      },
      noDetail: '--',
      columns: {
        time: 'Time',
        activity: 'Activity',
        instrument: 'Instrument',
        amount: 'Cash impact',
        detail: 'Public note',
      },
      detailFields: {
        amount: 'Amount',
        grossAmount: 'Gross amount',
        netCashImpact: 'Net cash impact',
        quantity: 'Quantity',
        price: 'Price',
        fee: 'Fee',
        commission: 'Commission',
        stampTax: 'Stamp tax',
        transferFee: 'Transfer fee',
        otherFees: 'Other fees',
        costBasis: 'Cost basis',
      },
      entryTypes: {
        tradeBuy: 'Security buy',
        tradeSell: 'Security sell',
        cashDeposit: 'Cash transfer in',
        cashWithdrawal: 'Cash withdrawal',
        dividend: 'Dividend received',
        adjustment: 'Manual adjustment',
        other: 'Ledger entry',
      },
      shortTypes: {
        buy: 'B',
        sell: 'S',
        cashIn: '+',
        cashOut: '-',
        dividend: 'D',
        adjustment: 'A',
        other: 'L',
      },
      cashImpact: {
        credit: 'Adds cash or realized proceeds',
        debit: 'Consumes cash',
        adjustment: 'Operator adjustment',
        neutral: 'Reference ledger movement',
      },
      sources: {
        manual: 'Manual entry',
        system: 'System entry',
        unknown: 'Source unknown',
      },
    },
    pending: {
      kicker: 'Pending',
      title: 'Pending fund subscriptions',
      loading: 'Loading pending fund subscriptions.',
      error: 'Failed to load pending fund subscriptions.',
      submittedAt: 'submitted',
      waitingFor: 'Waiting for NAV confirmation on',
      status: {
        pending: 'Pending NAV',
        confirmed: 'Confirmed',
        rejected: 'Rejected',
      },
    },
    forms: {
      trade: {
        title: 'Manual trade',
        occurredAtLabel: 'Occurred At',
        symbolLabel: 'Symbol',
        directionLabel: 'Direction',
        assetClassLabel: 'Asset Class',
        subscriptionAmountLabel: 'Subscription Amount',
        quantityLabel: 'Quantity',
        priceLabel: 'Unit Price',
        feeLabel: 'Fee',
        noteLabel: 'Trade Note',
        symbolPlaceholder: 'Symbol',
        amountPlaceholder: 'Subscription amount',
        quantityPlaceholder: 'Quantity',
        pricePlaceholder: 'Unit price',
        notePlaceholder: 'Note',
        buy: 'Buy',
        sell: 'Sell',
        amountRequired: 'Enter the subscription amount for a fund buy.',
        fundAmountHelp:
          'Fund buys can be recorded by amount. The system confirms quantity and cost from the published NAV.',
        commissionHelp: (rateBp: number, minimum: string) =>
          `Commission rate ${Number(rateBp).toFixed(1)} bp, minimum ${minimum}`,
        previewTitle: 'Trade preview',
        previewLoading: 'Calculating fee and cash impact.',
        previewUnavailable: 'Preview unavailable for the current inputs.',
        previewGrossAmount: 'Gross amount',
        previewCommission: 'Commission',
        previewStampTax: 'Stamp tax',
        previewTransferFee: 'Transfer fee',
        previewOtherFees: 'Other fees',
        previewTotalFee: 'Total fee',
        previewNetCashImpact: 'Net cash impact',
        previewFeeRule: 'Fee rule',
        previewConfiguredFeeRule: 'Configured account fee rule',
        previewManualFeeRule: 'Manual fee override',
        previewCostBasisMethod: 'Cost basis method',
        previewMovingAverageCost: 'Moving average buy cost',
        submit: 'Save Trade',
        saving: 'Saving...',
        genericSubmitError: 'Unable to save the trade.',
      },
      fundBatch: {
        title: 'Batch fund add',
        helper:
          'Record one top-up operation across your held funds. Positive rows are submitted as fund buys by amount.',
        occurredAtLabel: 'Batch Occurred At',
        amountLabel: (symbol: string) => `${symbol} Amount`,
        noteLabel: 'Batch Fund Note',
        amountPlaceholder: 'Amount',
        notePlaceholder: 'Batch note',
        loadingCandidates: 'Loading held funds.',
        noCandidates: 'No held funds available for batch add.',
        emptyError: 'Enter at least one fund amount.',
        submit: 'Save Batch',
        saving: 'Saving...',
        genericSubmitError: 'Unable to save the batch fund order.',
      },
      cashFlow: {
        title: 'Cash flow',
        occurredAtLabel: 'Cash Flow Occurred At',
        amountLabel: 'Amount',
        flowTypeLabel: 'Flow Type',
        noteLabel: 'Cash Flow Note',
        notePlaceholder: 'Note',
        deposit: 'Deposit',
        withdrawal: 'Withdrawal',
        submit: 'Save Cash Flow',
        saving: 'Saving...',
        genericSubmitError: 'Unable to save the cash flow.',
      },
      dividend: {
        title: 'Dividend',
        occurredAtLabel: 'Dividend Occurred At',
        symbolLabel: 'Dividend Symbol',
        assetClassLabel: 'Dividend Asset Class',
        amountLabel: 'Dividend Amount',
        noteLabel: 'Dividend Note',
        symbolPlaceholder: 'Symbol',
        notePlaceholder: 'Note',
        submit: 'Save Dividend',
        saving: 'Saving...',
        genericSubmitError: 'Unable to save the dividend.',
      },
      adjustment: {
        title: 'Manual adjustment',
        occurredAtLabel: 'Adjustment Occurred At',
        symbolLabel: 'Adjustment Symbol',
        assetClassLabel: 'Adjustment Asset Class',
        amountLabel: 'Adjustment Amount',
        quantityLabel: 'Adjustment Quantity',
        priceLabel: 'Adjustment Price',
        noteLabel: 'Adjustment Note',
        symbolPlaceholder: 'Symbol',
        notePlaceholder: 'Note',
        submit: 'Save Adjustment',
        saving: 'Saving...',
        genericSubmitError: 'Unable to save the adjustment.',
      },
    },
  },
  zh: {
    kicker: '账本',
    title: '账本流水',
    subtitle:
      '先核对账户账本；交易、资金流水、分红和调整只能通过明确受控的入口新增。',
    loading: '正在加载账本流水。',
    error: '账本流水加载失败。',
    tradeSaved: '交易已保存',
    tradeFailed: '交易保存失败',
    cashFlowSaved: '资金流水已保存',
    cashFlowFailed: '资金流水保存失败',
    dividendSaved: '分红已保存',
    dividendFailed: '分红保存失败',
    adjustmentSaved: '调整已保存',
    adjustmentFailed: '调整保存失败',
    feedRefreshed: '组合快照和流水已经开始刷新。',
    summary: {
      pendingOrders: '待确认申购',
      pendingOrdersDetail: '等待净值确认的基金申购。',
      netCashImpact: '净现金影响',
      netCashImpactUnavailable: '暂无完整汇总',
      netCashImpactDetail: '下方仅展示最近流水，不能代表完整历史的现金净变动。',
    },
    entryTools: {
      kicker: '录入工具',
      title: '新增流水',
      openAction: '新增流水',
      closeAction: '关闭流水录入',
      boundaryTitle: '账本写入边界',
      detail: '写入本地账本前，先预览公开账本影响，再刷新组合路径。',
      boundary:
        '确认提交后才会写入账户账本；不会向券商下单，也不会授予交易权限。',
      ariaLabel: '流水录入工具选择',
    },
    feed: {
      kicker: '审计流水',
      title: '最近流水',
      count: (count: number) => `${count} 条`,
      showing: (visible: number, total: number) =>
        `已显示 ${visible} / ${total} 条`,
      showMore: (count: number) => `再显示 ${count} 条`,
      tableScrollLabel: '账本流水表格',
      empty:
        '还没有流水。先录入交易、资金流水、分红或手工调整，时间线就会开始累计。',
      filteredEmpty: '没有匹配的流水。',
      categoryFilter: '流水分类筛选',
      subcategoryFilter: '流水二级筛选',
      searchLabel: '搜索标的名称 / 代码',
      searchPlaceholder: '搜索名称 / 代码',
      openHoldingDetail: (symbol: string) => `查看 ${symbol} 的持仓历史`,
      categoryLabels: {
        all: '全部',
        trade: '交易',
        cash: '现金',
        dividend: '分红',
        adjustment: '调整',
        other: '其他',
      },
      subcategoryAllLabels: {
        trade: '全部交易',
        cash: '全部现金',
        dividend: '全部分红',
        adjustment: '全部调整',
        other: '全部其他',
      },
      subcategoryLabels: {
        stock: '股票',
        fund: '基金',
        cashAccount: '现金账户',
        otherAsset: '其他资产',
        cashDeposit: '资金转入',
        cashWithdrawal: '资金转出',
        cashInterest: '结息',
        otherCash: '其他现金',
      },
      noDetail: '--',
      columns: {
        time: '时间',
        activity: '业务类型',
        instrument: '标的',
        amount: '资金影响',
        detail: '业务备注',
      },
      detailFields: {
        amount: '金额',
        grossAmount: '成交总额',
        netCashImpact: '净现金影响',
        quantity: '份额/数量',
        price: '价格',
        fee: '手续费',
        commission: '佣金',
        stampTax: '印花税',
        transferFee: '过户费',
        otherFees: '其他费用',
        costBasis: '成本口径',
      },
      entryTypes: {
        tradeBuy: '证券买入',
        tradeSell: '证券卖出',
        cashDeposit: '资金转入',
        cashWithdrawal: '资金转出',
        dividend: '分红入账',
        adjustment: '手工调整',
        other: '账本流水',
      },
      shortTypes: {
        buy: '买',
        sell: '卖',
        cashIn: '入',
        cashOut: '出',
        dividend: '息',
        adjustment: '调',
        other: '流',
      },
      cashImpact: {
        credit: '现金增加',
        debit: '占用现金',
        adjustment: '人工校正',
        neutral: '参考流水',
      },
      sources: {
        manual: '手工录入',
        system: '系统生成',
        unknown: '来源未知',
      },
    },
    pending: {
      kicker: '待确认',
      title: '待确认基金申购',
      loading: '正在加载待确认基金申购。',
      error: '待确认基金申购加载失败。',
      submittedAt: '提交于',
      waitingFor: '等待净值确认日',
      status: {
        pending: '待确认净值',
        confirmed: '已确认',
        rejected: '已拒绝',
      },
    },
    forms: {
      trade: {
        title: '手工交易',
        occurredAtLabel: '发生时间',
        symbolLabel: '证券代码',
        directionLabel: '买卖方向',
        assetClassLabel: '资产类别',
        subscriptionAmountLabel: '申购金额',
        quantityLabel: '数量',
        priceLabel: '成交价',
        feeLabel: '费用',
        noteLabel: '交易备注',
        symbolPlaceholder: '证券代码',
        amountPlaceholder: '申购金额',
        quantityPlaceholder: '数量',
        pricePlaceholder: '成交价',
        notePlaceholder: '备注',
        buy: '买入',
        sell: '卖出',
        amountRequired: '基金买入需要填写申购金额。',
        fundAmountHelp:
          '基金买入可只记录金额，系统会在净值披露后确认份额和成本。',
        commissionHelp: (rateBp: number, minimum: string) =>
          `佣金率万${Number(rateBp).toFixed(1)}，最低 ${minimum}`,
        previewTitle: '交易预览',
        previewLoading: '正在计算费用与现金影响。',
        previewUnavailable: '当前输入暂不能生成预览。',
        previewGrossAmount: '成交金额',
        previewCommission: '佣金',
        previewStampTax: '印花税',
        previewTransferFee: '过户费',
        previewOtherFees: '其他费用',
        previewTotalFee: '总费用',
        previewNetCashImpact: '净现金影响',
        previewFeeRule: '费用规则',
        previewConfiguredFeeRule: '账户配置费用规则',
        previewManualFeeRule: '手工费用覆盖',
        previewCostBasisMethod: '成本口径',
        previewMovingAverageCost: '移动平均买入成本',
        submit: '保存交易',
        saving: '保存中...',
        genericSubmitError: '交易保存失败。',
      },
      fundBatch: {
        title: '批量基金加仓',
        helper: '一次录入持有基金的加仓金额，系统会按金额申购并等待净值确认。',
        occurredAtLabel: '批量发生时间',
        amountLabel: (symbol: string) => `${symbol} 申购金额`,
        noteLabel: '批量基金备注',
        amountPlaceholder: '金额',
        notePlaceholder: '批量备注',
        loadingCandidates: '正在读取已持有基金。',
        noCandidates: '当前没有可批量加仓的已持有基金。',
        emptyError: '至少填写一只基金的申购金额。',
        submit: '保存批量加仓',
        saving: '保存中...',
        genericSubmitError: '批量基金加仓保存失败。',
      },
      cashFlow: {
        title: '资金流水',
        occurredAtLabel: '资金流水发生时间',
        amountLabel: '金额',
        flowTypeLabel: '资金方向',
        noteLabel: '资金流水备注',
        notePlaceholder: '备注',
        deposit: '入金',
        withdrawal: '出金',
        submit: '保存资金流水',
        saving: '保存中...',
        genericSubmitError: '资金流水保存失败。',
      },
      dividend: {
        title: '分红',
        occurredAtLabel: '分红发生时间',
        symbolLabel: '分红证券代码',
        assetClassLabel: '分红资产类别',
        amountLabel: '分红金额',
        noteLabel: '分红备注',
        symbolPlaceholder: '证券代码',
        notePlaceholder: '备注',
        submit: '保存分红',
        saving: '保存中...',
        genericSubmitError: '分红保存失败。',
      },
      adjustment: {
        title: '手工调整',
        occurredAtLabel: '调整发生时间',
        symbolLabel: '调整证券代码',
        assetClassLabel: '调整资产类别',
        amountLabel: '调整金额',
        quantityLabel: '调整数量',
        priceLabel: '调整价格',
        noteLabel: '调整备注',
        symbolPlaceholder: '证券代码',
        notePlaceholder: '备注',
        submit: '保存调整',
        saving: '保存中...',
        genericSubmitError: '调整保存失败。',
      },
    },
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type ActivityCopy = (typeof activityCopy)[Locale];

declare module '../../shared/i18n/context' {
  interface ApplicationCopy {
    activity: ActivityCopy;
  }
}
